### ISSUE TITLE
Test files absent

### ISSUE THREAD

**Issue by sarvex** [NVIDIA/nccl#10]
The documentation specifies

"Test binaries are located in the subdirectories nccl/build/test and nccl/build/mpitest." 
and 
"./build/test/all_reduce_test"

Whereas when I build the library; mpitest library was absent and all_reduce_test was present in ./build/test/single/ directory. 

Am I missing something here

**Comment by sjeaugey** [comment]
What you describe seems indeed normal. all_reduce_test is not an MPI test, hence it is located in test/single.

To build mpitest, you need to do ```make mpitest``` instead of ```make test```.

**Comment by cliffwoolley** [comment]
We did move the single-node tests down into the "single/" subdirectory,
however.  This issue correctly points out that we should update the
documentation to reflect that.

**Comment by sjeaugey** [comment]
Indeed, I missed the documentation issue after the test reorganization.
Fixed by commit ddd3f20
