### ISSUE TITLE
Questions about NVLS

### ISSUE THREAD

**Issue by ziannchen** [NVIDIA/nccl#1006]
Hi nccl‘s developers, I have some questions about nvls.
1. How does MC/UC mean? This is a bit like the memory mapping in the normal p2p connection, but more complicated. 
2. How nccl selects NVSwitch for each channel? 
3. Also, I don't seem to find the memory mapping between GPU and NVSwitch, do we need to do this explicitly or is it hidden under some cuda api?

**Comment by sjeaugey** [comment]
1. MC means Multi-cast. Load/stores to MC buffers are amplified by the switch. UC means Unicast, that's just the access to the local buffer.
2. All channels do the exact same thing, so they're all using the same buffer, except at different offsets.
3. This is done using a CUDA API which maps all UC buffers together to return the address of the MC buffer.

**Comment by ziannchen** [comment]
I can understand your answers about my question 2/3.
But there are 4 NVSwitches on a H100/800 node. For each channel, if some GPUs send data to NVSwitch0, other GPUs send data to NVSwitch1, in this case no NVSwitch can received all data to do reduce. I think there must be a mechanism to ensure that different GPUs use the same NVSwitch, or there's a shared memory or communication mechanism between different NVSwitches?
So, I want to know how does nccl control which NVSwitch to use for every ld/store on MC buffer？

**Comment by sjeaugey** [comment]
The different NVSwitches are not visible to NCCL. Not for NVLink communication, not for NVLink SHARP. Traffic is spread on all switches transparently.

**Comment by ziannchen** [comment]
So can a channel use different nvswitches?

**Comment by sjeaugey** [comment]
Yes it can and it will.

**Comment by ziannchen** [comment]
many thanks
