### ISSUE TITLE
Install problem on CentOS 6.9

### ISSUE THREAD

**Issue by HandsomeHans** [NVIDIA/nccl#101]
when i run make test or make install 
i meet a problem as below

`[xuegengjian@localhost nccl-master]$ gcc --version
gcc (GCC) 4.7.0 20120507 (Red Hat 4.7.0-5)
Copyright (C) 2012 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

[xuegengjian@localhost nccl-master]$ make CUDA_HOME=/usr/local/cuda-8.0 test
Compiling src/libwrap.cu                      > /home/xuegengjian/caffe/nccl/nccl-master/build/obj/libwrap.o
src/core.h:35:16: error: expected unqualified-id before ‘long’
src/core.h:35:16: error: expected ‘)’ before ‘long’
src/core.h:99:1: error: ‘DevRing’ does not name a type
make: *** [/home/xuegengjian/caffe/nccl/nccl-master/build/obj/libwrap.o] Error 1
`

I cannot find any information related to this problem on the internet.
any one can help me ?
Thanks a lot!

**Comment by sjeaugey** [comment]
If I remember correctly, you need at least GCC 4.8 to compile NCCL.

**Comment by HandsomeHans** [comment]
@sjeaugey you are right brother! I update my gcc to 4.8, and this time all things go right. Thank you very much!
