### ISSUE TITLE
Does PXN support all-reduce for Rail-optimized network topology？

### ISSUE THREAD

**Issue by xuchenhui-5** [NVIDIA/nccl#1014]
In [nccl 2.12Blog](https://developer.nvidia.com/blog/doubling-all2all-performance-with-nvidia-collective-communication-library-2-12/), using PXN can improve all2all Performance for Rail-optimized network topology. Does it can apply to all-reduce for same rail topology?

To my understanding, ring for inter node maybe cannot build normally.

assume: 8 nodes, 8 GPUS for per node, 8 NIC for per node, Rail-optimized network topology

reason:
If channel ring is NET0 0 1 2 3 4 5 6 7 NET0 for Node 0, and next Node's recv rank is 10(rank 2 and rank 10 in same rail switch), as output nic NET0, it can't build net connect between rank 7 and rank 10 even though using PXN, because they are not in same rail.

In NCCL 2.18.5-1 source code [net.cc](http://net.cc/), the sendSetup function will find req.netDev(NET0) and proxyRank(rank 0) for rank 7 by using PXN. However, rank 0 is not in same rail with rank 10 (peer rank). so I have doubt how using PXN build inter ring in different rail.

I have two guesses:
1. using PXN can't build this inter ring, must modify nccl source code and retry find new NET when connecting rank 10. eg. find NET 2 in node 0 for connect peer rank 10.
2. If inter NIC is NET0, It never create ring 0 1 2 3 4 5 6 7 10 ....., must be creat ring 0 1 2 3 4 5 6 7 8 ....., rank 0 and rank 8 exists same rail. But I have't find logic process in nccl 2.18 source code.

I think there was a misunderstanding at some point for me. Please correct me.

thanks

**Comment by sjeaugey** [comment]
Indeed, NCCL builds rings which enter and exit the node using the same NIC to avoid crossing rails; but that assumes that nodes are identical, and the communicator contains the same GPUs on each node. If on the next node we only have GPU 2, or if GPUs are reordered, then we will end up crossing rails.

This is not something NCCL can do anything about, unless we have some network topology detection API.

**Comment by xuchenhui-5** [comment]
> Indeed, NCCL builds rings which enter and exit the node using the same NIC to avoid crossing rails; but that assumes that nodes are identical, and the communicator contains the same GPUs on each node. If on the next node we only have GPU 2, or if GPUs are reordered, then we will end up crossing rails.
> 
> This is not something NCCL can do anything about, unless we have some network topology detection API.

thank you for your reply.  If I user 2 Node,  and every node has 8 GPUS and 8 NICs for rail topology. 

can nccl create ring NET0 0 1 2 3 4 5 6 7 NET0  NET2 10 11 8  9 12 13 14 15 NET2 in function ncclTopoPostset ？

I think it will,  because when creating ring NET0 0 1 2 3 4 5 6 7 NET0  in node0, it doesn't known who is next node receive rank. I haven't see source code  to check whether in same rail with next node receive rank. If it create ring successfully for rank 7's  next node receive rank 10, it won't communication as they are not in same rail.   so I have doubt in this point, please correct me. 

thanks

**Comment by sjeaugey** [comment]
NCCL will connect the first ring of the first node with the first ring of the second node.
If nodes are identical, then the first ring of the second node should be NET 0 8 9 10 11 12 13 14 15 NET 0.

**Comment by xuchenhui-5** [comment]
Make sense

Even though nccl creates many rings  in  inter-nodes, it also can guarantee connected for the x ring of the first node with the x ring of the second node when nodes are identical. 

greatly appreciate!
