### ISSUE TITLE
error: parameter packs not expanded with ‘...’

### ISSUE THREAD

**Issue by orlovk** [NVIDIA/nccl#102]
Hi. I'm trying to build xgboost that contains nccl package.

gcc 6.4.0
ubunut 17.04

But the comiler craches with the following error message:
```
[ 64%] Building NVCC (Device) object nccl/CMakeFiles/cuda_compile_1.dir/src/cuda_compile_1_generated_reduce_scatter.cu.o
/usr/include/c++/6/tuple:605:4: error: parameter packs not expanded with ‘...’:
                bool>::type=true>
    ^
/usr/include/c++/6/tuple:605:4: note:         ‘_Elements’
...... <more 20 lines of the same error>
```

Any ideas?

**Comment by nluehr** [comment]
Looks like your gcc version is not supported by CUDA. https://devtalk.nvidia.com/default/topic/949770/cuda-8-0rc-supporting-gcc6-/

**Comment by intractabilis** [comment]
> Looks like your gcc version is not supported by CUDA. https://devtalk.nvidia.com/default/topic/949770/cuda-8-0rc-supporting-gcc6-/

I have the same issue with CUDA 11.5 and GCC 11, which a supported compiler according to https://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html.

**Comment by intractabilis** [comment]
The voice of one crying in the wilderness... De profundis ad te clamavi, NVIDIAAAAAAAA....

**Comment by jbachan** [comment]
Is it the exact same compiler message as originally posted? If not, perhaps I can find a way to workaround nvcc's issue. But if nvcc is choking on standard library headers like `<tuple>` then there may not be much I can do. This isn't a NCCL bug after all.

**Comment by intractabilis** [comment]
Since 4 years has passed, and the version of the compiler was incremented 5 times, the error message is not *exactly* the same.
```
/home/user/gcc-env/include/c++/11/bits/std_function.h:435:145: error: parameter packs not expanded with ‘...’:
  435 |         function(_Functor&& __f)
      |                                                                                                                                                 ^
/home/user/gcc-env/include/c++/11/bits/std_function.h:435:145: note:         ‘_ArgTypes’
/home/user/gcc-env/include/c++/11/bits/std_function.h:530:146: error: parameter packs not expanded with ‘...’:
  530 |         operator=(_Functor&& __f)
      |                                                                                                                                                  ^
```
The error happens while compiling a generated file with extension `.compute_86.cudafe1.cpp`. So, whatever the problem is, it is in that file and has nothing to do with system headers.

It seems like NVCC is sensitive to the minor version of the compiler. The workaround was to have a second compiler with version 11.1 and specify `-ccbin /path/to/gcc11.1` in `CUDA_NVCC_FLAGS`.

**Comment by Medoalmasry** [comment]
If someone is facing the same issue, I checked the difference between gcc 11.2 and 11.1
you can just hide both templates
```
 /**
      template<typename _Functor,
               typename _Constraints = _Requires<_Callable<_Functor>>>
        function(_Functor&& __f)
        noexcept(_Handler<_Functor>::template _S_nothrow_init<_Functor>())
        : _Function_base()
        {
          static_assert(is_copy_constructible<__decay_t<_Functor>>::value,
              "std::function target must be copy-constructible");
          static_assert(is_constructible<__decay_t<_Functor>, _Functor>::value,
              "std::function target must be constructible from the "
              "constructor argument");

          using _My_handler = _Handler<_Functor>;

          if (_My_handler::_M_not_empty_function(__f))
            {
              _My_handler::_M_init_functor(_M_functor,
                                           std::forward<_Functor>(__f));
              _M_invoker = &_My_handler::_M_invoke;
              _M_manager = &_My_handler::_M_manager;
            }
        }
        **/

```

**Comment by intractabilis** [comment]
I know why NVIDIA is the best place to work at according to Glassdoor. You don't have to fix bugs. You got paid for 5-star reviews on Glassdoor.

**Comment by geoeo** [comment]
This has reappeared on ubuntu jammy. Default (Aptitude) gcc is 11.2 and cuda version is 11.6.

**Comment by gpecke** [comment]
Taking std_function.h from a different gcc version fixed this for me for the time being.

**Comment by geoeo** [comment]
For me I had to manually install the 11.6 toolkit. The aptitude version is 11.5 !

**Comment by kekegg** [comment]
Taking std_function.h from gcc 11.1 fixed this for me for the time being. I'm compiling gromacs with gpu support in ubuntu 22.04 with gcc 11.2.

**Comment by intractabilis** [comment]
The problem is in CUDAFE. FE stands for front-end, it's a C++ front-end based on EDG front-end. As far as I understand, it heavily modifies your code, and, obviously, introduces bugs on the way. I think probably NVIDIA doesn't have money to update the EDG version, and, thus, simply ignores this bug.

**Comment by nachovizzo** [comment]
For CMake based projects I managed to sort this problem out by installing an older compiler and telling nvcc which is the host compiler
```
 cmake -DCMAKE_CUDA_HOST_COMPILER=/usr/bin/g++-10 ..
```
