### ISSUE TITLE
D2H and NCCL communication overlap

### ISSUE THREAD

**Issue by ForFishes** [NVIDIA/nccl#1023]
Hi, Here we overlap D2H with calculation and communication respectively. We found that when D2H and GPU kernel calculations overlap, the calculation performance will not slow down because D2H uses the DMA engine; however, D2H and NCCL communicate together, which will cause the communication to slow down.  Is this reasonable?

**result：**

allreduce_offload_time  > allreduce_time > offload_time

<img width="844" alt="image" src="https://github.com/NVIDIA/nccl/assets/19485646/d2376df7-2f82-4b01-aa2c-4d0912f14a11">

**2 machines  code：**

[my_program.txt](https://github.com/NVIDIA/nccl/files/12881981/my_program.txt)

**Comment by sjeaugey** [comment]
It depends on your system. If NCCL communication uses NVLink, then I don't see why D2H/H2D would interfere. But if you're on a system without NVLink or you're doing inter-node communication with NCCL through the NIC (hence PCI), then everything is using the PCI link of the GPU, so it's normal we the two interfere with each other.

**Comment by ForFishes** [comment]
OK，i understand it, thanks.
