### ISSUE TITLE
example on single GPU

### ISSUE THREAD

**Issue by fastalgo** [NVIDIA/nccl#103]
Can I use NCCL on a single GPU?
If so, can you give me an example?

**Comment by nluehr** [comment]
I'm not sure what you have in mind. NCCL is intended for communication between GPUs. Within a single GPU, you'd be better off with simple CUDA kernels and cudaMemcpy calls.

**Comment by fastalgo** [comment]
Just want to do a test without considering the performance.
Is it possible to use NCCL on a single GPU?

**Comment by nluehr** [comment]
In principle it may be possible. You'll need to control all NCCL ranks from within a single process. Then just repeat your device index in the device list passed to ncclCommInitAll(), and then use different cudaStreams for each rank.
But this is not recommended due to the possibility of creating deadlocks in cases where all kernels do not get scheduled simultaneously on the GPU.

**Comment by AddyLaddy** [comment]
All the NCCL collectives do support being called with a single rank communicator, in which case they simply call the cudaMemcpyAsync() function with the Device to Device flag.

**Comment by fastalgo** [comment]
Thanks so much!

**Comment by ice-tong** [comment]
> All the NCCL collectives do support being called with a single rank communicator, in which case they simply call the cudaMemcpyAsync() function with the Device to Device flag.

How about multiple processes in single GPU? ^_^

**Comment by sjeaugey** [comment]
> How about multiple processes in single GPU? ^_^
It is no longer possible to have multiple ranks use the same GPU since NCCL 2.5. It will return an error.

**Comment by ice-tong** [comment]
Hi @sjeaugey , I have an all-gather test using NCCL on the same GPU:

```python
import torch
import torch.distributed as torch_dist
import torch.multiprocessing as mp


def _torch_dist_fn(rank, world_size):
    torch_dist.init_process_group(
        backend='gloo',
        init_method=f'tcp://127.0.0.1:2345',
        world_size=world_size,
        rank=rank)
    torch.cuda.set_device(rank % torch.cuda.device_count())
    tensor = torch.Tensor([rank]).cuda()
    tensor_list = [torch.Tensor([0]).cuda() for _ in range(world_size)]
    torch_dist.all_gather(tensor_list, tensor)
    print(f'[rank {rank}]: tensor: {tensor}, tensor_list: {tensor_list}')


def launch_torch_distributed(process_num):
    mp.spawn(_torch_dist_fn, nprocs=process_num, args=(process_num, ))


if __name__=="__main__":
    print('CUDA DEIVCE COUNT:', torch.cuda.device_count())
    print('PYTORCH VERSION:', torch.__version__)
    print('NCCL VERSION:', torch.cuda.nccl.version())
    launch_torch_distributed(2)
```
Got:
```
CUDA DEIVCE COUNT: 1
PYTORCH VERSION: 1.9.0+cu111
NCCL VERSION: 2708
[rank 1]: tensor: tensor([1.], device='cuda:0'), tensor_list: [tensor([0.], device='cuda:0'), tensor([1.], device='cuda:0')]
[rank 0]: tensor: tensor([0.], device='cuda:0'), tensor_list: [tensor([0.], device='cuda:0'), tensor([1.], device='cuda:0')]
```

Is that mean multiple ranks in the same GPU work?

**Comment by sjeaugey** [comment]
If you set NCCL_DEBUG=WARN NCCL should print something like:
```
NCCL WARN Duplicate GPU detected : rank 0 and rank 0 both on CUDA device XX
```

**Comment by ice-tong** [comment]
Thanks for the reply!

**Comment by christopherhesse** [comment]
@sjeaugey I am running into that warning `[0] init.cc:545 NCCL WARN Duplicate GPU detected : rank 0 and rank 1 both on CUDA device 100000`, but it would be very handy to run our multi-gpu tests on a smaller number of GPUs.

Is there some configuration which might work where we could have two processes per GPU?

**Comment by sjeaugey** [comment]
Unfortunately not. A large part of the optimization of rings and trees is based on designating the order in which we go through the GPUs and those are identified by their GPU index. 

So, on top of being prone do deadlocks, running two ranks on the same GPU is not supported.

**Comment by christopherhesse** [comment]
Got it, thanks!

**Comment by christopherhesse** [comment]
It's my understanding there is some way to split an nvidia GPU such that each VM could see a different "slice" of the GPU, would such a thing potentially work with NCCL?

**Comment by sjeaugey** [comment]
I guess you are referring to MIG (Multi instance GPU). Unfortunately in MIG mode we do not define new GPU indexes so NCCL cannot differentiate the sub GPUs using cudaGetDevice (or some other call).
Maybe if you were to split the GPU and run a different VM on each slice so that nccl considers each slice as a different node (with a single GPU), it would work. You'd be using the network for all communication but I don't see a reason for it not to work.

**Comment by jiangxiaobin96** [comment]
> I guess you are referring to MIG (Multi instance GPU). Unfortunately in MIG mode we do not define new GPU indexes so NCCL cannot differentiate the sub GPUs using cudaGetDevice (or some other call). Maybe if you were to split the GPU and run a different VM on each slice so that nccl considers each slice as a different node (with a single GPU), it would work. You'd be using the network for all communication but I don't see a reason for it not to work. NCCL+MIG is not supported though so no guarantees.

if two VMs(two gpu pass through two vm) in one host, how NCCL communicate between VMs, p2p or shm or net? Is any solution to accelerate this communication.

**Comment by sjeaugey** [comment]
It will probably be NET, as we don't see other GPUs, and we currently have no way to know they're on the same physical node and accessible through SHM/P2P.

**Comment by zxgx** [comment]
Hi, @sjeaugey , thank you for your comprehensive explaination. Is there any plan for NCCL supporting MIG or MPS in the near future?

**Comment by christopherhesse** [comment]
@sjeaugey I got a chance to try MIG and I think it actually does work on a multi-GPU machine.  E.g. if you set `NCCL_DISABLE_P2P=1` (no NVLink support) and run NCCL across 1 MIG slice from each GPU it seems to be fine.

**Comment by wlgusgit** [comment]
Hi, @christopherhesse, If possible, could you share the experimental setup you used? I’m particularly interested in using MIG with multi-GPU settings. However, from what I understand, it seems that specifying different GPUs using cudaSetDevice() isn't supported, as discussed in [NVIDIA forum](https://forums.developer.nvidia.com/t/how-to-use-cudasetdevice-to-select-devices-while-using-mig-on-a100/190283) [pytorch forum](https://discuss.pytorch.org/t/set-cuda-visible-device-multiple-migs-single-job/172366).

**Comment by wlgusgit** [comment]
Hi, @christopherhesse, If possible, could you share the experimental setup you used? I’m particularly interested in using MIG with multi-GPU settings. However, from what I understand, it seems that specifying different GPUs using cudaSetDevice() isn't supported, as discussed in [NVIDIA forum](https://forums.developer.nvidia.com/t/how-to-use-cudasetdevice-to-select-devices-while-using-mig-on-a100/190283) and [pytorch forum](https://discuss.pytorch.org/t/set-cuda-visible-device-multiple-migs-single-job/172366).

**Comment by sjeaugey** [comment]
Hum, interesting. Indeed I could see how disabling P2P (and probably SHM as well) could make NCCL work with multiple MIG instances. It's not designed for that though, so there could be other issues.
