### ISSUE TITLE
Question about tuning plugin

### ISSUE THREAD

**Issue by wanglei837** [NVIDIA/nccl#1036]
I noticed that the latest commit in the branch 2.19.1-1 mentions the addition of **tuning plugin support**, is it open source and is there any documentation on this feature?[https://github.com/NVIDIA/nccl/commit/f9c3dc251e0fd3144341b4f43336c53dd913c110](url)

**Comment by sjeaugey** [comment]
There is no documentation, but there is an empty example in `ext-tuner/example`. Starting from that example, you can write any code which would select the algo/protocol based on the input.

**Comment by wanglei837** [comment]
Got it, thanks!
