### ISSUE TITLE
M40 24GB AllReduce on cuda 8.0?

### ISSUE THREAD

**Issue by StillKeepTry** [NVIDIA/nccl#104]
When i use nccl test on 8xM40 GPU, it will be stalled.

> Using devices
   Rank  0 uses device  0 [0x05] Tesla M40 24GB
   Rank  1 uses device  1 [0x08] Tesla M40 24GB
   Rank  2 uses device  2 [0x0d] Tesla M40 24GB
   Rank  3 uses device  3 [0x13] Tesla M40 24GB
   Rank  4 uses device  4 [0x83] Tesla M40 24GB
   Rank  5 uses device  5 [0x89] Tesla M40 24GB
   Rank  6 uses device  6 [0x8e] Tesla M40 24GB
   Rank  7 uses device  7 [0x91] Tesla M40 24GB
>
>                                                 out-of-place                    in-place
>      bytes             N    type      op     time  algbw  busbw      res     time  algbw  busbw      res

I have find the same problem on [issues36](https://github.com/NVIDIA/nccl/issues/36). But the issues provide the driver on cuda7.5. I have update the driver to 375.66, but this problem still exists. Can some provide some advices.

**Comment by nluehr** [comment]
Have you checked `sudo lspci -vvv | grep -i acsctl` to make sure ACS is disabled (all entries marked with "-")?

**Comment by StillKeepTry** [comment]
This problem fixed, Thank you.
