### ISSUE TITLE
[question] libibverbs: Warning: couldn't load driver 'libipathverbs-rdmav25.so': libipathverbs-rdmav25.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by gouchangjiang** [NVIDIA/nccl#1044]
Bonjour. Do you know which package or software stack this warning raises? Does NCCL raise it? The network used to train DNNs is RoCE. This warning can be removed if I delete /etc/libibverbs.d/ipath.driver. Google tells me that ipath.driver is a Intel implementation of ibverbs. Please give some background info about how NCCL selects the ibverbs implementation here? Merci. I am afraid that this warning may influence the throughput of training.

**Comment by KaimingOuyang** [comment]
I don't see this is raised by NCCL. It is raised by libibverbs when you try to load it and its dependent libs. 

NCCL will search all possible paths where libibverbs.so locates and uses the first one it finds. Basically, you can use LD_LIBRARY_PATH to tell where NCCL should search.

Indeed, if you cannot find correct libibverbs, NCCL might not use IB to communicate which can harm performance.

**Comment by gouchangjiang** [comment]
thank you, kaiming.
