### ISSUE TITLE
error when install caffe with USE_NCCL on

### ISSUE THREAD

**Issue by moumouyou** [NVIDIA/nccl#105]
CXX/LD -o .build_release/tools/finetune_net.bin
CXX/LD -o .build_release/examples/siamese/convert_mnist_siamese_data.bin
CXX/LD -o .build_release/examples/cpp_classification/classification.bin
CXX/LD -o .build_release/examples/mnist/convert_mnist_data.bin
.build_release/tools/caffe.o：在函数‘train()’中：
caffe.cpp:(.text+0x2845)：对‘caffe::NCCL<float>::NCCL(boost::shared_ptr<caffe::Solver<float> >)’未定义的引用
caffe.cpp:(.text+0x2888)：对‘caffe::NCCL<float>::Run(std::vector<int, std::allocator<int> > const&, char const*)’未定义的引用
caffe.cpp:(.text+0x2890)：对‘caffe::NCCL<float>::~NCCL()’未定义的引用
caffe.cpp:(.text+0x3232)：对‘caffe::NCCL<float>::~NCCL()’未定义的引用
caffe.cpp:(.text+0x335b)：对‘caffe::NCCL<float>::~NCCL()’未定义的引用
collect2: error: ld returned 1 exit status
Makefile:627: recipe for target '.build_release/tools/caffe.bin' failed
make: *** [.build_release/tools/caffe.bin] Error 1
make: *** 正在等待未完成的任务....

My environment:
Ubunutu 16.04
caffe 1.0.0rc5, everything is OK without nccl
cuda 8.0
cudnn 5.1
nccl 1.3.4 or 1.2.3, build from source or installed from deb pkg without error message
gpu: nvidia gtx1080 x2    
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 375.39                 Driver Version: 375.39                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 1080    Off  | 0000:02:00.0     Off |                  N/A |
|  3%   48C    P8     8W / 200W |      1MiB /  8114MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce GTX 1080    Off  | 0000:03:00.0      On |                  N/A |
|  0%   48C    P8     8W / 200W |    183MiB /  8110MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

Any advice will be appreciate!

**Comment by sjeaugey** [comment]
I think this is a question for the Caffe project.
