### ISSUE TITLE
[QUESTION] question about aggregation mode

### ISSUE THREAD

**Issue by PhdShi** [NVIDIA/nccl#1058]
Can different collective communication operations such as allreduce and allgather be aggregated into a single group? If so, do the algorithms and protocols need to be consistent with each other?

**Comment by sjeaugey** [comment]
Yes, you can group operations of different kind, and they don't need to use the same algorithms internally (but that's an implementation detail).

**Comment by PhdShi** [comment]
> Yes, you can group operations of different kind, and they don't need to use the same algorithms internally (but that's an implementation detail).

Thanks very much!
