### ISSUE TITLE
all-to-all collective in NCCL 2?

### ISSUE THREAD

**Issue by sleeepyjack** [NVIDIA/nccl#106]
I'm currently working on a project which requires an all-to-all collective.
Will it be included in NCCL 2?

Thanks in advance!

**Comment by aurotripathy** [comment]
Hello @sleeepyjack, I do not see a response, but do you know the answer to the question you posed. Thank you

**Comment by sjeaugey** [comment]
We just posted a preview for point-to-point. See the p2p branch and PR #316 .
