### ISSUE TITLE
maxconn in topo dump file

### ISSUE THREAD

**Issue by tks2004** [NVIDIA/nccl#1089]
Hi,
Could you let us know what maxconn value mean in the following line which was generated using the topo dump file:
<net name="mlx5_3" dev="3" speed="100000" port="1" latency="0.000000" guid="0xa49942ffffa4e988" maxconn="131072" gdr="1"/>

**Comment by PhdShi** [comment]
Maximum number of comms we can create

**Comment by tks2004** [comment]
Can we change this value If so which variable can we use

**Comment by sjeaugey** [comment]
No, this was added in case we'd need it but it's always been ignored so far.

**Comment by tks2004** [comment]
Thanks!
