### ISSUE TITLE
How to install NCCL2 on CentOS

### ISSUE THREAD

**Issue by hujie-frank** [NVIDIA/nccl#109]
I try to download NCCL2 from the official website, but there are only  install packs on Ubuntu.  Are you going to support other linux system, such as CentOS?

**Comment by fmana** [comment]
Hi, I'm joining the thread since I have the same trouble.
I would like to evaluate NCCL2 in my tool. but I need CentOS release.

**Comment by sjeaugey** [comment]
Please note that issues concerning NCCL2 should be posted on developer.nvidia.com (my account -> my bugs). You may as well post your questions on devtalk.nvidia.com as Franco did.

Also note that deb packages are simple archives which you may extract using the "ar' command. The following script illustrate that :
```
#!/bin/bash
# Extract debs into a directory
if [ "$2" == "" ]; then echo "Usage : $0 <dir> <debs>" ; exit 1; fi

DIR=`realpath $1`; shift
DEBS=""
while [ "$1" != "" ]; do DEBS=`realpath $1` ; shift; done

mkdir temp && cd temp
for deb in $DEBS; do
  ar x $deb && tar xf data.tar.xz
  rm data.tar.xz control.tar.gz debian-binary
done

mkdir -p $DIR
mv usr/include usr/share $DIR
mv usr/lib/x86_64-linux-gnu $DIR/lib

cd .. && rm -Rf temp
```

**Comment by hujie-frank** [comment]
Many thanks! It works well.
