### ISSUE TITLE
the number of threads used by send/recv

### ISSUE THREAD

**Issue by wangxicoding** [NVIDIA/nccl#1098]
I found that even if ncclSend/ncclRecv only send/recv 1 byte, it will use 640 threads, but ncclAllreduce only uses 96 threads. Is there a way to control the minimum number of threads used by send/recv,  while without affecting other communications?

**Comment by sjeaugey** [comment]
We've moved away from optimizing threads as it seems to make no difference. The NCCL kernels won't execute on the same SM as another kernel anyway, so reducing the number of threads makes little sense.

**Comment by wangxicoding** [comment]
thank you for your reply
