### ISSUE TITLE
Package libnccl_static.a into .deb

### ISSUE THREAD

**Issue by deepali-c** [NVIDIA/nccl#110]
I think `libnccl_static.a `can be packaged into libnccl-dev package.

**Comment by deepali-c** [comment]
@peterhj , I observed that the` libnccl_static.a` is not currently packaged into the .deb. Do you think we can add this to the deb just like the CUDA packages. Please suggest.

**Comment by cliffwoolley** [comment]
The static library build is in the -dev deb package.

Thanks,
Cliff

**Comment by deepali-c** [comment]
Thanks @cliffwoolley. 

I am not sure if I am mistaken, but I do not see it in the deb though

```
dpkg -c libnccl-dev_1.3.4-1.cuda8.0_amd64.deb
drwxr-xr-x root/root         0 2017-03-24 19:08 ./
drwxr-xr-x root/root         0 2017-03-24 19:08 ./usr/
drwxr-xr-x root/root         0 2017-03-24 19:08 ./usr/share/
drwxr-xr-x root/root         0 2017-03-24 19:08 ./usr/share/doc/
drwxr-xr-x root/root         0 2017-03-24 19:08 ./usr/share/doc/libnccl-dev/
-rw-r--r-- root/root       154 2017-03-24 19:05 ./usr/share/doc/libnccl-dev/changelog.Debian.gz
-rw-r--r-- root/root      1735 2017-03-24 19:05 ./usr/share/doc/libnccl-dev/copyright
drwxr-xr-x root/root         0 2017-03-24 19:08 ./usr/share/man/
drwxr-xr-x root/root         0 2017-03-24 19:08 ./usr/share/man/man7/
-rw-r--r-- root/root      2253 2017-03-24 19:08 ./usr/share/man/man7/nccl.7.gz
drwxr-xr-x root/root         0 2017-03-24 19:08 ./usr/include/
-rw-r--r-- root/root      9616 2017-03-24 19:02 ./usr/include/nccl.h
drwxr-xr-x root/root         0 2017-03-24 19:08 ./usr/lib/
drwxr-xr-x root/root         0 2017-03-24 19:08 ./usr/lib/x86_64-linux-gnu/
lrwxrwxrwx root/root         0 2017-03-24 19:08 ./usr/lib/x86_64-linux-gnu/libnccl.so -> libnccl.so.1
```

**Comment by cliffwoolley** [comment]
Ah sorry.  I'm not sure about in the 1.3.4 deb packages.  I was referring
to later versions.

**Comment by deepali-c** [comment]
@cliffwoolley, is that code in any branch? I do not see it in the [libnccl-dev.install](https://github.com/NVIDIA/nccl/blob/master/debian/libnccl-dev.install) as well.

**Comment by cliffwoolley** [comment]
NCCL 2 is available from https://developer.nvidia.com/nccl .

**Comment by deepali-c** [comment]
Oh I see, will check with `NCCL 2 `then. Thanks a lot @cliffwoolley .

**Comment by deepali-c** [comment]
Please advise if we can add this in NCCL 1 as well.
