### ISSUE TITLE
NCCL 2.0 support inter-node communication using Sockets?

### ISSUE THREAD

**Issue by pakio** [NVIDIA/nccl#111]
Hi 
I trying to test the difference between NCCL and NCCL2 on my project, and NCCL2 does not work correctly.
When I call commInitRank() in my program, this error will occur.
```
*server name* [0] include/socket.h:185 WARN Call to connect failed : Connection refused
NCCL failure *MyProgram*.cu:110 'unhandled system error'
```
This error occur only when I try to make communicator with inter-node environment, and when i try to make communicator with only one node this error will no be occurred.

And my question is that NCCL 2.0 is supporting inter-node communication using Sockets or it supports only with InfiniBand.
I don't have InfiniBand environment  so I haven't test my program with InfiniBand, so I'm not sure if my program is wrong or my test environment is not supporting inter-node communication.

**Comment by pakio** [comment]
The program that i'm trying to run was on http://docs.nvidia.com/deeplearning/sdk/nccl-developer-guide/index.html#onedevprothrd .

**Comment by cliffwoolley** [comment]
Please use developer.nvidia.com for NCCL2 support.  Thanks!
