### ISSUE TITLE
NCCL alltoall_perf hangs via PXN in our non-superpod network

### ISSUE THREAD

**Issue by gavin1332** [NVIDIA/nccl#1116]
The cluster contains 14 nodes of 112 A800 GPUs, and the topology of network is as follows:
<img width="1491" alt="32ed400e2c847347b37d15b95f7ab5a" src="https://github.com/NVIDIA/nccl/assets/1552048/aafacdd3-19d4-4334-be12-2b8445f86b84">

By running `alltoall_perf` on all 14 nodes with PXN off by setting NCCL_P2P_PXN_LEVEL=0, the bandwidth is ~9 GB/s. 

With PXN on, by running `all_reduce_perf` on all 14 nodes, the bandwidth is ~95 GB/s, but it hangs by `alltoall_perf` in which case our network engineering observed the "Progress threads" in nccl are idle during hanging.

We have tested  `alltoall_perf` successfully in different node pairing and even in several compositions of 8 nodes with PXN on or off. In case of 8 nodes, we geting bandwidth 12 GB/s with PXN on, and 10 GB/s with PXN off.

Could you help us analyze why it hangs while running `alltoall_perf` on all nodes, or give some suggestions to keep working on the problem fixing.

Docker image: nvcr.io/nvidia/pytorch:23.11-py3

**Comment by gavin1332** [comment]
up!

**Comment by gavin1332** [comment]
bug is found in NCCL `cumem` API

**Comment by PhdShi** [comment]
> bug is found in NCCL `cumem` API

hi, I have met the same error. Can you explain why it is a bug in NCCL CuMemAPI? thx

**Comment by AddyLaddy** [comment]
There was an issue with a deadlock during A2A connection establishment when NCCL_CUMEM_ENABLE=1 (default in 2.19.x).
Setting NCCL_CUMEM_ENABLE=0 on NCCL 2.19.x is a WAR and the fix will be in NCCL 2.20.x

**Comment by PhdShi** [comment]
> There was an issue with a deadlock during A2A connection establishment when NCCL_CUMEM_ENABLE=1 (default in 2.19.x). Setting NCCL_CUMEM_ENABLE=0 on NCCL 2.19.x is a WAR and the fix will be in NCCL 2.20.x

Thanks for replying and looking forward to NCCL 2.20.x
