### ISSUE TITLE
Do the experience values in the tuning.cc file include considerations of network congestion?

### ISSUE THREAD

**Issue by PhdShi** [NVIDIA/nccl#1128]
![image](https://github.com/NVIDIA/nccl/assets/109151574/a2336b61-461b-46be-8914-8a45283ee5a2)
The tuning.cc file has a large number of constant values. Do these constant values take into account network congestion?

**Comment by sjeaugey** [comment]
No it doesn't. The tubing is assuming a perfect, non blocking network.

**Comment by PhdShi** [comment]
> No it doesn't. The tuning is assuming a perfect, non blocking network.

thx!
