### ISSUE TITLE
libwrap.o compiling failed 

### ISSUE THREAD

**Issue by breadbread1984** [NVIDIA/nccl#113]
I met the following problem when compiling libwrap.o

> Compiling src/libwrap.cu                      > /home/xieyi/下载/caffe2/third_party/nccl/build/obj/libwrap.o
/usr/include/math_functions.h(8897): error: cannot overload functions distinguished by return type alone

>/usr/include/math_functions.h(8901): error: cannot overload functions distinguished by return type alone

>2 errors detected in the compilation of "/tmp/tmpxft_00000f0f_00000000-15_libwrap.compute_61.cpp1.ii".
Makefile:111: recipe for target '/home/xieyi/下载/caffe2/third_party/nccl/build/obj/libwrap.o' failed

How can I solve the problem Thx

**Comment by sjeaugey** [comment]
This should be posted on the Caffe2 project.
