### ISSUE TITLE
What are the benefits of using the cumem api?

### ISSUE THREAD

**Issue by sphish** [NVIDIA/nccl#1137]
In our tests, using the cumem api consumed more gpu memory than not using it. But there was no observable performance improvement. So what's the motivation for using cumem?

**Comment by AddyLaddy** [comment]
There are deadlock scenarios during allocation and free that are avoided by using the cuMem APIs. NCCL is moving to the point where we can use cuMem for all memory allocation and deallocation to improve scalability and deadlock avoidance. 
Also, products like Multi-Node NVLink are based solely on the cuMem APIs.
