### ISSUE TITLE
[QUESTION]How to improve compile(link) time by only build part of NCCL?

### ISSUE THREAD

**Issue by livingshade** [NVIDIA/nccl#1147]
Hi, I am trying to play with NCCL and make some modification. But it take like 10min to build, and apparently the linkage takes a lot of time. 
I noticed that NCCL has many transport plugins. Also, it seems that NCCL generates a lot of template to cover all cases. But since I am only working on a tiny part of NCCL and many those codes are never used. I wonder if there is any config could be used to only compile part of the NCCL so that it can be build faster?

Suppose I am only interested in `float32, algo_ring, proto_ll` with `net_ib` as transport, is there a way to only build that part?

Thanks in advance!

**Comment by AddyLaddy** [comment]
Some hints:
1. Make sure you're building with `make -j`
2. Set `NVCC_GENCODE` for just the GPUs you are working on: 
```
export NVCC_GENCODE="-gencode=arch=compute_80,code=sm_80 -gencode=arch=compute_90,code=sm_90"
```
3. Also my colleague reworked the build system recently:
```
    * Added a make variable `ONLY_FUNCS=<regex>` so that we can build only specific functions.
      Useful while debugging, especially to speed up gdb. See comments in "src/device/generate.py"
```
4. Build on `/tmp` if your networked filing system is slow

**Comment by livingshade** [comment]
Thanks for your reply!  
I combined `NVCC_GENCODE` and `ONLY_FUNCS` and the compile time reduced by more than 10x. That was really, really "Useful while debugging" 🥳
I will close the issue and hope anyone with same issue could find this.
