### ISSUE TITLE
How to install NCCL 2 from NVIDIA in Dockerfiles?

### ISSUE THREAD

**Issue by yoshihingis** [NVIDIA/nccl#115]
We can get NCCL2 deb file, but there is not the description of installation.
I want to use NCCL2 in the Dockerfile and I made test Dockerfile for NCCL2 as below.
But I could not build Dockerfile,I got Error Massages.
How to install NCCL 2 from NVIDIA in Dockerfiles?
Can we use NCCL2 in the Dockerfile?
Can I build my Dockerfile, if I will use CUDA9? 

(1)Development Enviroment 
OS : Ubuntu14.04LTS
CUDA8.0
Docker : 17.09.0-ce 

I could not get NCCL2 deb file by "wget" in my Dokcerfile, I download "nccl-repo-Ubuntu1404-2.0.5-ga-cuda8.0-2-1_amd64.deb and use COPY comnand to use NCCL2 in my Dockerfile.

(2) structure of  Deirectory
  Dockerfile (for NCCL2)
        /nccl 
            nccl-repo-Ubuntu1404-2.0.5-ga-cuda8.0-2-1_amd64.deb

(3)Dockerfile
FROM nvidia/cuda:8.0-cudnn5-devel-ubuntu14.04

ENV http_proxy my company proxy
ENV https_proxy my compnay proxy

RUN apt-get update && apt-get install -y --no-install-recommends nano \
        openssh-server \
        git \
        python-dev \
        wget \
        make \
        wget \
        file \
        python-opencv \
        python-pip &&\
        rm -rf /var/lib/apt/lists/*

#COPY NCCL deb Host to Docker Container
RUN mkdir /home/nccl
copy /nccl /home/nccl

WORKDIR /home/nccl/

#install NCCL2 
RUN dpkg -i nccl-repo-ubuntu1404-2.0.5-ga-cuda8.0_2-1_amd64.deb
RUN apt-get update
RUN  apt-get install libnccl2 libnccl-dev

ENV PATH /usr/local/bin:/usr/local/cuda/bin:$PATH
ENV LD_LIBRARY_PATH /usr/local/lib:/usr/local/cuda/lib64:$LD_LIBRARY_PATH
ENV LIBRARY_PATH /usr/local/lib:$LIBRARY_PATH
ENV CPATH /usr/local/cuda/include:/usr/local/include:$CPATH

(4)Error 
Reading package lists...
Building dependency tree...
Reading state information...
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libnccl2 : Depends: cuda-cudart-9-0 but it is not installable
E: Unable to correct problems, you have held broken packages.
The command '/bin/sh -c apt-get install libnccl2 libnccl-dev' returned a non-zero code: 100

**Comment by ginsongsong** [comment]
Maybe you could try to install  cuda-9 debian packages to solve this dependence problem.
The error msg is asking the cuda runtime package to  install nccl library.

libnccl2 : Depends: cuda-cudart-9-0 but it is not installable.

**Comment by fxrcode** [comment]
You can take a look at [horovod's Dockerfile](https://github.com/uber/horovod/blob/master/Dockerfile)
