### ISSUE TITLE
how to use net in intra-node ?

### ISSUE THREAD

**Issue by echobinarybytes** [NVIDIA/nccl#1150]
Hi, I have a question during reading the code about considering use net in intra-node situation. 

This line of code shows that in intra-node, all net node will be removed.
https://github.com/NVIDIA/nccl/blob/b6d7438d3145a619f924dbbca6c96db21fab716e/src/graph/paths.cc#L655

During ncclTopoCheckNet call, all net node actually trimed. so net will always not be used
https://github.com/NVIDIA/nccl/blob/b6d7438d3145a619f924dbbca6c96db21fab716e/src/graph/paths.cc#L439

Here the ncclTopoCheckNet function is called
https://github.com/NVIDIA/nccl/blob/b6d7438d3145a619f924dbbca6c96db21fab716e/src/transport/p2p.cc#L123

thx for answer !!!

**Comment by fanfanfanWu** [comment]
@echobinarybytes I am also confused about this and do you know why?

**Comment by shanleo1986** [comment]
Hi, you can use gdb to check those two values: system->nodes[GPU].count means the total GPUs of my node, but comm->nRanks means the total GPUs of all of the nodes.
If those two values is the same, that means we just have one node, so the NICs can be removed.
Others, the NICs will be kept.

**Comment by fanfanfanWu** [comment]
> Hi, you can use gdb to check those two values: system->nodes[GPU].count means the total GPUs of my node, but comm->nRanks means the total GPUs of all of the nodes. If those two values are the same, that means you just have one node, so the NICs can be removed. Otherwise, the NICs will be kept.

But now we discuss net in intra-node,  GPUs of my node and nranks are both 8 (one node and 8 gpu for example) and net are all removed, which means we can't use net later. And when checking net transport can connect or not, the return always is false.

**Comment by shanleo1986** [comment]
OH, net in intra-node, I noticed that. On my setup, all of the NETs are removed for intra-node, as the network card is useless here.
On your setup, does the NET still work in intra-node? Maybe the NET will work in intra-node for some platform.

**Comment by fanfanfanWu** [comment]
> OH, net in intra-node, I noticed that. On my setup, all of the NETs are removed for intra-node, as the network card is useless here. On your setup, does the NET still work in intra-node? Maybe the NET will work in intra-node for some platform.

I don't have a setup for test and just confused about the nccl source code. And the NET related logic is general for different platform I think.

**Comment by shanleo1986** [comment]
Oh, I understand your confusion. In the function ncclTopoTrimSystem, if remove the NET, the corresponding system->nodes[NET].count is decreased to 0 finally, this is in function: ncclTopoRemoveNode

ncclResult_t ncclTopoRemoveNode(struct ncclTopoSystem* system, int type, int index) {
  struct ncclTopoNode* delNode = system->nodes[type].nodes+index;
  for (int t=0; t<NCCL_TOPO_NODE_TYPES; t++) {
    free(delNode->paths[t]);
    for (int n=0; n<system->nodes[t].count; n++) {
      struct ncclTopoNode* node = system->nodes[t].nodes+n;
      if (node == delNode) continue;
      for (int l=0; l<node->nlinks; l++) {
        while (l<node->nlinks && node->links[l].remNode == delNode) {
          memmove(node->links+l, node->links+l+1, (node->nlinks-l-1)*sizeof(struct ncclTopoLink));
          node->nlinks--;
        }
        if (l<node->nlinks && node->links[l].remNode->type == type && node->links[l].remNode >= delNode) {
          node->links[l].remNode--;
        }
      }
    }
  }
  memmove(delNode, delNode+1, (system->nodes[type].count-index-1)*sizeof(struct ncclTopoNode));
  **system->nodes[type].count--;**
  return ncclSuccess;
}

**Comment by fanfanfanWu** [comment]
> Oh, I understand your confusion. In the function ncclTopoTrimSystem, if remove the NET, the corresponding system->nodes[NET].count is decreased to 0 finally, this is in function: ncclTopoRemoveNode
> 
> ncclResult_t ncclTopoRemoveNode(struct ncclTopoSystem* system, int type, int index) { struct ncclTopoNode* delNode = system->nodes[type].nodes+index; for (int t=0; t<NCCL_TOPO_NODE_TYPES; t++) { free(delNode->paths[t]); for (int n=0; nnodes[t].count; n++) { struct ncclTopoNode* node = system->nodes[t].nodes+n; if (node == delNode) continue; for (int l=0; lnlinks; l++) { while (lnlinks && node->links[l].remNode == delNode) { memmove(node->links+l, node->links+l+1, (node->nlinks-l-1)*sizeof(struct ncclTopoLink)); node->nlinks--; } if (lnlinks && node->links[l].remNode->type == type && node->links[l].remNode >= delNode) { node->links[l].remNode--; } } } } memmove(delNode, delNode+1, (system->nodes[type].count-index-1)*sizeof(struct ncclTopoNode)); **system->nodes[type].count--;** return ncclSuccess; }

Yes, ncclTopoRemoveNode remove NET in intra-node, but I still confuse about ncclTopoCheckNet function where checking whether going through the net rather than P2P/SHM. ncclTopoCheckNet will traversal system->nodes[NET].count and system->nodes[NET].count should be 0.
