### ISSUE TITLE
Pack bootstrapAllGather's

### ISSUE THREAD

**Issue by kwen2501** [NVIDIA/nccl#1155]
https://github.com/NVIDIA/nccl/blob/b6d7438d3145a619f924dbbca6c96db21fab716e/src/init.cc#L1315-L1316

Any chance of packing these two all-gathers into one?

**Comment by sjeaugey** [comment]
I don't think that would be a problem indeed.

**Comment by kwen2501** [comment]
Closed via NCCL 2.23.
