### ISSUE TITLE
Does NCCL support nvlink network with L2 nvswitches system?

### ISSUE THREAD

**Issue by Tuvie** [NVIDIA/nccl#1159]
NCCL has several transports such as p2p and net. For nvlink network with L2 nvswitches, what kind of transport it belongs to? It seems that it is neither p2p nor net. How does NCCL support such a system?

**Comment by AddyLaddy** [comment]
Multi-node NVLink (MNNVL) support in NCCL will first be available in NCCL 2.20.x which will be released shortly after CUDA 12.4 later this month.
The MNNVL support is implemented by making use of the cuMem APIs and handle exchange. The code paths still use the P2P transport like multi-GPU single node systems.

**Comment by Tuvie** [comment]
Thanks for your reply.

**Comment by shanleo1986** [comment]
Hi @AddyLaddy,
Does this funciton check the MNNLV: checkMNNVL()?
How to configute the MNNLV function?

Thank you.

**Comment by AddyLaddy** [comment]
There is no NCCL configuration required to support MNNVL. It is part of the MNNVL system software installation where we run a distributed Fabric Manager service with the FM daemons (GFM and LFM) normally running on embedded systems within each external MNNVL NVLink Switch.
NCCL just needs to query the Fabric UUID and CliqueID from the FM and it uses that information to correctly map the CUDA memory from the NVLink Fabric connected GPUs.

**Comment by hailiyidishui** [comment]
Hi @AddyLaddy,
Does FM support partitioning one compute node for multi-tenant? For example, I have 4 GPUs in one compute node, but I want to partition them into 2 nvlink groups, however there is no connection between these 2 groups with NVLink.
