### ISSUE TITLE
nccl on mutiple process in one host

### ISSUE THREAD

**Issue by zerocurve** [NVIDIA/nccl#116]
Hi, I am wondering if I want to use nccl in single host, but with multiple process. Each process take one GPU.. Should I have to use MPI?

**Comment by nluehr** [comment]
NCCL provides only the collective communication routines (e.g., allReduce). You also need a separate mechanism to launch the job and broadcast a unique initialization token among all ranks. There are a number of ways to do this, but MPI is a common choice.

**Comment by zerocurve** [comment]
Any example for other way? thanks for response

**Comment by nluehr** [comment]
Some common MPI alternatives would be SHMEM, GlobalArrays, or grpc. You can also write your own launch scripts to start your jobs, and then use Unix sockets, IPC shared memory, or even files to manage rendezvous and communication of the NCCL unique ID between workers.
