### ISSUE TITLE
Multinode NCCL 2.0 MPI Test code failure

### ISSUE THREAD

**Issue by mpatwary** [NVIDIA/nccl#118]
I was trying to run the mpi_test.cu (https://github.com/NVIDIA/nccl/blob/master/test/mpi/mpi_test.cu) code using NCCL 2.0. The code runs well on single node, but when I tried for 2 nodes, each with 8 GPUs, I get the following error.

"NCCL Init failed (10) 'cuda malloc failed'"

I ran the code using slurm which contains the following:
mpirun -np 16 build/test/mpi/mpi_test 0 1 2 3 4 5 6 7 0 1 2 3 4 5 6 7

Have anyone seen similar issues

**Comment by cliffwoolley** [comment]
NCCL 1.3's tests are not fully enabled for NCCL 2 features.  Please see https://github.com/NVIDIA/nccl-tests instead.

**Comment by mpatwary** [comment]
Thanks for pointing to the new NCCL test code. However, I am still seeing problem when I try multinode. I tried three ways, none worked. I am sure where the problem is:

1. mpirun -np 16 ./build/all_reduce_perf -b 32M -e 128M -f 2 -t 1 -g 1 -c 0

>> nThread 1 nGpus 1 minBytes 33554432 maxBytes 134217728 step: 2(factor) warmup iters: 5 iters: 20 validation: 0
>> Cuda failure common.cu:891 'invalid device ordinal'

2. mpirun -np 2 ./build/all_reduce_perf -b 32M -e 128M -f 2 -t 1 -g 8 -c 0

In this case, after printing the following line, the code hangs
nThread 1 nGpus 8 minBytes 33554432 maxBytes 134217728 step: 2(factor) warmup iters: 5 iters: 20 validation: 0

3. mpirun -np 2 ./build/all_reduce_perf -b 32M -e 128M -f 2 -t 8 -g 1 -c 0

Same as Case 2, after printing the following line, the code hangs

nThread 8 nGpus 1 minBytes 33554432 maxBytes 134217728 step: 2(factor) warmup iters: 5 iters: 20 validation: 0

I used SLURM to run the code using the following. In all the above cases, I set ntasks equals to np

#SBATCH --nodes=2
#SBATCH --ntasks=16
#SBATCH --gres=gpu:8

I set the following in the sbatch script.

export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/xyz/nccl/build/lib/
export LD_LIBRARY_PATH=/home/xyz/openmpi-2.0.1-sm-gcc48-cuda-8.0-slurm-14.11.7/lib:/home/xyz/cuda-8.0.61/lib64:$LD_LIBRARY_PATH
export PATH=/home/xyz/openmpi-2.0.1-sm-gcc48-cuda-8.0-slurm-14.11.7/bin:/home/xyz/cuda-8.0.61/bin:$PATH

Thanks for your help.

**Comment by sjeaugey** [comment]
Hi Mostafa,
Could you open this issue on the nccl-tests project instead ? It would be easier for others to benefit from the answers if they experience the same issues.
Thanks !

**Comment by mpatwary** [comment]
Sure.
