### ISSUE TITLE
NCCL 2.19.4 hang if NCCL_NVLS_ENABLE=1

### ISSUE THREAD

**Issue by Regina8023** [NVIDIA/nccl#1197]
My workload hang if set `NCCL_NVLS_ENABLE=1`; no issue if disable NVLS. We use cuda 12.1

Since we set `NCCL_ALGO=Ring` for the workload, we suspect NVLS graph initialization process is the culprit. The node topology is:
```
=== System : maxBw 24.0 totalBw 360.0 ===
CPU/0 (1/1/2)
+ PCI[24.0] - PCI/2000 (10b5879610b58796)
        + PCI[24.0] - GPU/4000 (0)
               + NVL[360.0] - NVS/0
        + PCI[24.0] - GPU/5000 (1)
               + NVL[360.0] - NVS/0
        + PCI[24.0] - NIC/6000
               + NET[25.0] - NET/0 (0/0/25.000000)
+ PCI[24.0] - PCI/8000 (10b5879610b58796)
        + PCI[24.0] - GPU/A000 (2)
               + NVL[360.0] - NVS/0
        + PCI[24.0] - GPU/B000 (3)
               + NVL[360.0] - NVS/0
        + PCI[24.0] - NIC/C000
               + NET[25.0] - NET/1 (1/0/25.000000)
+ SYS[10.0] - CPU/1
CPU/1 (1/1/2)
+ PCI[24.0] - PCI/82000 (10b5879610b58796)
        + PCI[24.0] - GPU/84000 (4)
               + NVL[360.0] - NVS/0
        + PCI[24.0] - GPU/85000 (5)
               + NVL[360.0] - NVS/0
        + PCI[24.0] - NIC/86000
               + NET[25.0] - NET/2 (2/0/25.000000)
+ PCI[24.0] - PCI/88000 (10b5879610b58796)
        + PCI[24.0] - GPU/8A000 (6)
               + NVL[360.0] - NVS/0
        + PCI[24.0] - GPU/8B000 (7)
               + NVL[360.0] - NVS/0
        + PCI[24.0] - NIC/8C000
               + NET[25.0] - NET/3 (3/0/25.000000)
+ SYS[10.0] - CPU/0
==========================================
```

The generated graph for ring, tree and NVLS:
```
NCCL INFO Pattern 4, crossNic 0, nChannels 12, bw 30.000000/30.000000, type NVL/PIX, sameChannels 1
NCCL INFO 0 : GPU/0 GPU/1 GPU/2 GPU/3 GPU/4 GPU/5 GPU/6 GPU/7
NCCL INFO 1 : GPU/0 GPU/1 GPU/2 GPU/3 GPU/4 GPU/5 GPU/6 GPU/7
NCCL INFO 2 : GPU/0 GPU/1 GPU/2 GPU/3 GPU/4 GPU/5 GPU/6 GPU/7
NCCL INFO 3 : GPU/0 GPU/1 GPU/2 GPU/3 GPU/4 GPU/5 GPU/6 GPU/7
NCCL INFO 4 : GPU/0 GPU/1 GPU/2 GPU/3 GPU/4 GPU/5 GPU/6 GPU/7
NCCL INFO 5 : GPU/0 GPU/1 GPU/2 GPU/3 GPU/4 GPU/5 GPU/6 GPU/7
NCCL INFO 6 : GPU/0 GPU/1 GPU/2 GPU/3 GPU/4 GPU/5 GPU/6 GPU/7
NCCL INFO 7 : GPU/0 GPU/1 GPU/2 GPU/3 GPU/4 GPU/5 GPU/6 GPU/7
NCCL INFO 8 : GPU/0 GPU/1 GPU/2 GPU/3 GPU/4 GPU/5 GPU/6 GPU/7
NCCL INFO 9 : GPU/0 GPU/1 GPU/2 GPU/3 GPU/4 GPU/5 GPU/6 GPU/7
NCCL INFO 10 : GPU/0 GPU/1 GPU/2 GPU/3 GPU/4 GPU/5 GPU/6 GPU/7
NCCL INFO 11 : GPU/0 GPU/1 GPU/2 GPU/3 GPU/4 GPU/5 GPU/6 GPU/7
NCCL INFO Pattern 1, crossNic 0, nChannels 12, bw 30.000000/30.000000, type NVL/PIX, sameChannels 1
NCCL INFO 0 : GPU/0 GPU/1 GPU/2 GPU/3 GPU/4 GPU/5 GPU/6 GPU/7
NCCL INFO 1 : GPU/0 GPU/1 GPU/2 GPU/3 GPU/4 GPU/5 GPU/6 GPU/7
NCCL INFO 2 : GPU/0 GPU/1 GPU/2 GPU/3 GPU/4 GPU/5 GPU/6 GPU/7
NCCL INFO 3 : GPU/0 GPU/1 GPU/2 GPU/3 GPU/4 GPU/5 GPU/6 GPU/7
NCCL INFO 4 : GPU/0 GPU/1 GPU/2 GPU/3 GPU/4 GPU/5 GPU/6 GPU/7
NCCL INFO 5 : GPU/0 GPU/1 GPU/2 GPU/3 GPU/4 GPU/5 GPU/6 GPU/7
NCCL INFO 6 : GPU/0 GPU/1 GPU/2 GPU/3 GPU/4 GPU/5 GPU/6 GPU/7
NCCL INFO 7 : GPU/0 GPU/1 GPU/2 GPU/3 GPU/4 GPU/5 GPU/6 GPU/7
NCCL INFO 8 : GPU/0 GPU/1 GPU/2 GPU/3 GPU/4 GPU/5 GPU/6 GPU/7
NCCL INFO 9 : GPU/0 GPU/1 GPU/2 GPU/3 GPU/4 GPU/5 GPU/6 GPU/7
NCCL INFO 10 : GPU/0 GPU/1 GPU/2 GPU/3 GPU/4 GPU/5 GPU/6 GPU/7
NCCL INFO 11 : GPU/0 GPU/1 GPU/2 GPU/3 GPU/4 GPU/5 GPU/6 GPU/7
NCCL INFO Pattern 5, crossNic 0, nChannels 8, bw 40.000000/60.000000, type NVL/PIX, sameChannels 0
NCCL INFO 0 : GPU/0 GPU/0 GPU/0 GPU/0 GPU/0 GPU/0 GPU/0 GPU/0
NCCL INFO 1 : GPU/1 GPU/0 GPU/0 GPU/0 GPU/0 GPU/0 GPU/0 GPU/0
NCCL INFO 2 : GPU/2 GPU/0 GPU/0 GPU/0 GPU/0 GPU/0 GPU/0 GPU/0
NCCL INFO 3 : GPU/3 GPU/0 GPU/0 GPU/0 GPU/0 GPU/0 GPU/0 GPU/0
NCCL INFO 4 : GPU/4 GPU/0 GPU/0 GPU/0 GPU/0 GPU/0 GPU/0 GPU/0
NCCL INFO 5 : GPU/5 GPU/0 GPU/0 GPU/0 GPU/0 GPU/0 GPU/0 GPU/0
NCCL INFO 6 : GPU/6 GPU/0 GPU/0 GPU/0 GPU/0 GPU/0 GPU/0 GPU/0
NCCL INFO 7 : GPU/7 GPU/0 GPU/0 GPU/0 GPU/0 GPU/0 GPU/0 GPU/0 
```

For NVLS graph (pattern 5), I think each channel looks suspicious: only contains 1 GPU in the route. What is NVLS graph supposed to look like? Is this a wrong graph and further caused NCCL to hang? Let me know if you need any more info. Thanks!

**Comment by sjeaugey** [comment]
All looks normal. NVLS graphs only use the first GPU to indicate a "head" gathering reduced data and broadcasting it back.

Can you share the log of a hung job with `NCCL_DEBUG=INFO`?

**Comment by Regina8023** [comment]
Thanks Sylvain for your reply! 

We found that the hang is due to Cuda "out of memory": the model we ran already consumes almost all GPU memory when NVLS is disabled, so we hit OOM error when enabling NVLS (needs extra mem to store NVLS connections). By running a smaller model, we found that enabling NVLS consumes ~8GB more GPU mem per rank compared with NVLS disabled (5-node, 12 NCCL comms initialized).

Since inter-node NVLS is not supported by our hardware, we measured the GPU memory that NVLS initialization consumed in 1-node and 4-node NCCL tests (to see if avoid inter-node connections can save some gpu mem): 
both tests show that enabling NVLS consumes ~1.5GB more GPU mem per rank compared with NVLS disabled.

Does this mean most of GPU mem usage from NVLS are consumed by intra-node connections? Could you please explain (or where can I find more info) about what connections are established by NVLS and corresponding GPU mem usage? Is the mem usage (per rank) affected by # of nodes in a NCCL comm?  

Thank you!

**Comment by Regina8023** [comment]
That's great news! Thanks Sylvain! May I please know the ETA of the 2.21?

While waiting for NCCL 2.21, any suggestion on how we can use NVLS without consuming so much mem and how we can better understand connections built by NVLS? Thanks for your advice!

**Comment by sjeaugey** [comment]
> While waiting for NCCL 2.21, any suggestion on how we can use NVLS without consuming so much mem 

I'm afraid you'll have to wait for 2.21 for that. There is no easy way to do that with 2.20.
2.21 should hopefully be released within the next month or so.

**Comment by Regina8023** [comment]
Thanks Sylvain!
