### ISSUE TITLE
What does out-of-place and in-place mean in the test routines?

### ISSUE THREAD

**Issue by linnanwang** [NVIDIA/nccl#12]
Hello,

What does out-of-place and in-place mean in the test routines? Thank you.

**Comment by cliffwoolley** [comment]
An in-place operation uses the same buffer for its output as was used to
provide its input.  An out-of-place operation has distinct input and output
buffers.

Hope this helps,
Cliff

**Comment by linnanwang** [comment]
Hello Cliff,

Thanks for the reply. This is very helpful. However, what if I can to see the difference between tree-based broadcast and ring-based broadcast? Is there such benchmarks so that I can compare with? Thanks.

**Comment by cliffwoolley** [comment]
NCCL's design allows it to choose among many algorithms for each
collective, but this early version of NCCL only thus far implements
ring-based (not tree-based or other) algorithms.

Thanks,
Cliff
