### ISSUE TITLE
How to use the API ncclReduceScatter?

### ISSUE THREAD

**Issue by shanleo1986** [NVIDIA/nccl#1200]
Hi @sjeaugey

I have some questions about the API ncclReduceScatter, can you help me?
ncclReduceScatter
There are 4 ranks total, size = 4, sendbuff is like as follows:
sendbuff
rank0 rank1 rank2 rank3
0     1     2     3
1     2     3     4
2     3     4     5
3     4     5     6

NCCLCHECK(ncclReduceScatter((const void *)sendbuff[i], (void*)recvbuff[i], size, datatype, ncclSum,comms[i], s[i]));

What should the recvbuff look like?(1) or (2)
On my env I got the (1) result, but I think the result should be (2) arrording the picture: 
https://docs.nvidia.com/deeplearning/nccl/user-guide/docs/usage/collectives.html#reducescatter

(1)
recvbuff:
rank0 rank1 rank2 rank3
6     10    14    18
0     0     0     0
0     0     0     0
0     0     0     0

(2)
recvbuff：
rank0 rank1 rank2 rank3
6     0     0     0
0     10    0     0
0     0     14    0
0     0     0     18

And also have some confusion with this Note:
https://docs.nvidia.com/deeplearning/nccl/user-guide/docs/api/colls.html#c.ncclReduceScatter
Note: This assumes the send count is equal to nranks*recvcount, which means that sendbuff should have a size of at least nranks*recvcount elements.

Can you give me an demo of ncclReduceScatter, thank you very much.

**Comment by sjeaugey** [comment]
The output should be like (1), unless you set the recvbuff to be base+rank*recvCount, in which case it will look like (2). Setting the recvbuff to sendbuff+rank*recvCount is also the recipe to perform in-place reduce scatter.

**Comment by shanleo1986** [comment]
The behavior of ncclReduceScatter is clear now, I will close this issue.
