### ISSUE TITLE
Duplicated ncclCommRegister in nccl.h.in?

### ISSUE THREAD

**Issue by kwen2501** [NVIDIA/nccl#1201]
![Screenshot 2024-02-27 at 9 04 22 AM](https://github.com/NVIDIA/nccl/assets/6676466/948b6c2f-a2e8-4f3a-a115-9b6422299e57)

**Comment by sjeaugey** [comment]
Yep, that was a bad merge. Will be fixed in 2.21.

**Comment by kwen2501** [comment]
Cool, thanks!
