### ISSUE TITLE
Question about ring performance between intra-node and inter-node

### ISSUE THREAD

**Issue by SongyuanZhao** [NVIDIA/nccl#1202]
Greetings,

Each of my servers have 4 L40S GPUs and 2*100G network cards **all connected to the same PCIe Switch**. 
![20240228-104436(WeLinkPC)](https://github.com/NVIDIA/nccl/assets/30497198/b88652c1-3e70-487f-96a7-c543147a3013)
When testing the performance of a single node, the bus bandwidth remains constant at 22GB/s regardless of the number of GPUs. However, during tests involving multiple nodes (with GDR enabled), performance decreases as the number of GPUs increases. 
![20240228-104738(WeLinkPC)](https://github.com/NVIDIA/nccl/assets/30497198/c56d597b-0f67-4d5f-8324-b83c015b8fed)
With one GPU per node, the performance can still maintain at 21.4GB/s, but adding more GPUs causes it to drop to below 20GB/s.
 I'd like to inquire about the reason behind this. 
My understanding is that since the performance with one GPU per node, it's not due to network limitations but rather limitations within the node itself, correct?
Why does the addition of network cards result in decreased performance? Are there any optimization methods available?

Best regards

**Comment by sjeaugey** [comment]
> My understanding is that since the performance with one GPU per node, it's not due to network limitations but rather limitations within the node itself, correct?

Correct.

> Why does the addition of network cards result in decreased performance? Are there any optimization methods available?

I didn't get that. Where did you add network cards and it degraded performance?

**Comment by SongyuanZhao** [comment]
Thank you for your reply!

My point is, why is there a performance drop when there are two GPUs per node(20GB/s) compared to one GPU per node(21.4GB)? As we discussed earlier, it could be assumed that this degradation due to the limitations within the node. **What exactly causes this limitation? possibly PCIe switching performance?**

However, performance testing within the node with 2/3/4 GPUs does not exhibit any degradation. From the perspective of a single server, compared to intra-node, inter-node simply adds another data stream from the NIC. If the degradation is due to switching performance, it should also happen during intra-node test.

Or could there be other reasons?

**Comment by sjeaugey** [comment]
Yes it could be the PCI switch degrading performance a bit, but it's not a big degradation; it's unlikely to matter much in real apps.

Can you see if NCCL_NET_GDR_READ=1 gets better results?

**Comment by SongyuanZhao** [comment]
Alright, thank you for your advice. 

Our servers are busy now, I will try once they are free.

**Comment by SongyuanZhao** [comment]
Thank you very much for your advice! It's really helpful.
Actually, I tried NCCL_NET_GDR_READ=0 and get better results (22GB/s). It seems that the default value in our environment is 1, although there is no NVLINK in my setup. Our NCCL version is 2.19.4.

**Comment by sjeaugey** [comment]
Ah, indeed GDR Read was disabled by default only on Volta and before. Since Ampere, it is enabled by default. Disabling it may improve performance, but it will cause more traffic to the CPU and back, so in a real application, that could slow down the CPU-GPU exchanges and NCCL could also be slowed down by those transfers. So I would advise to make sure real applications do see a benefit when using this environment variable before setting it.

**Comment by SongyuanZhao** [comment]
Got it. Thanks again.
