### ISSUE TITLE
Can NCCL_IB_PCI_RELAXED_ORDERING only be used in virtualized environments?

### ISSUE THREAD

**Issue by shanleo1986** [NVIDIA/nccl#1205]
From the NCCL doc, we can see the NCCL_IB_PCI_RELAXED_ORDERING can greatly help the performance of InfiniBand networks, I want to know if this env can work only in virtualized environments.
As I run some nccl-test on my setup, including 2 Nodes and 4 GPUs each node, setting or not setting NCCL_IB_PCI_RELAXED_ORDERING  has little impact on the results.
Thank you.

https://docs.nvidia.com/deeplearning/nccl/user-guide/docs/env.html#nccl-ib-pci-relaxed-ordering

**Comment by sjeaugey** [comment]
Indeed, that's expected.

Relaxed ordering is very important when ACS+ATS are enabled (i.e. inside VMs), but not so much on baremetal systems.

**Comment by shanleo1986** [comment]
> Indeed, that's expected.
> 
> Relaxed ordering is very important when ACS+ATS are enabled (i.e. inside VMs), but not so much on baremetal systems.

Thank you for helping me confirm and resolving a doubt in my heart.

**Comment by wangjiafu0310** [comment]
> Indeed, that's expected.
> 
> Relaxed ordering is very important when ACS+ATS are enabled (i.e. inside VMs), but not so much on baremetal systems.

Woud you please kindly share how to enable ACS+ATS inside the VM? THX a lot.

**Comment by AddyLaddy** [comment]
The link Sylvain posted originally has lots of details on how to enable ACS in combination with ATS.
Please note that the NCCL team are not VM and virtualization experts. Most of our experience and development is carried out on bare-metal systems or in Docker/container environments.

https://docs.nvidia.com/ai-enterprise/1.2/user-guide/index.html#enable-gpudirect-technology
