### ISSUE TITLE
Why { "16 GT/s", 120 } paired in kvDictPciGen?

### ISSUE THREAD

**Issue by shanleo1986** [NVIDIA/nccl#1206]
Hi, in kvDictPciGen, the 16 GT/s maps to 120, why?
As the some docs show that the 16 GT/s will map to 31.508GB/s, why here is 120?
What is the function to map 16 GT/s to 120?
Thank you.
![pcie](https://github.com/NVIDIA/nccl/assets/145751038/e2438107-6a9d-48af-9267-61532254f80b)

**Comment by sjeaugey** [comment]
At the end of the line, it says ` // x100 Mbps per lane`.

So, 120 means 12000 Mbps = 1.5 GB/s per lane. Your table says 1.969GB/s but that's line rate, it doesn't account for the protocol.

**Comment by shanleo1986** [comment]
Thank you for your quick clarification, now I got the meaning.
And the algorithm of calculating the link bw connectted by LINK_PCI is **width*speed/80.0**, **width** means how many lanes in total, **speed** means the bw in 100Mbps each lane, and divided by 80.0, finally got the bandwidth of the total lanes in GBps, for PCIe 4.0*16, the bandwidth is 24(GBps).
