### ISSUE TITLE
How the WaitFlag-Copy(thread 0-255)  keep pace with  PostFlag(thread 256) ?

### ISSUE THREAD

**Issue by meteortwinkle** [NVIDIA/nccl#122]
Hi,guys. As a rookie in CUDA and nccl, there's confusion for me about WaitFlag-Copy(thread 0-255)  keep pace with  PostFlag(thread 256) in the nccl/src/primitives.h.
**The runtime's log is like that**:

prevCommOp.wait(args.opIndex):0
WAIT OK  threadIdx.x:0,flag addr:0x10838c00010,*flag >= (val + shift),wait flag:0,val:0,shift:0
nextCommOp.wait(args.opIndex):0
WAIT OK  threadIdx.x:0,flag addr:0x1061c400010,*flag >= (val + shift),wait flag:0,val:0,shift:0
Rank:0 threadIdx.x 0 OpCounter wait OK

threadIdx.x:256

WaitOnFlags:1
WAIT OK  threadIdx.x:0,flag addr:0x1050da00004,*flag >= (val + shift),wait flag:0,val:1,shift:-4
ReduceOrCopy

WaitOnFlags:2
PostToFlags:1

Post OK threadIdx.x:256,flag addr:0x1061be00000,post flag:1,1,0 
WAIT OK  threadIdx.x:0,flag addr:0x1050da00004,*flag >= (val + shift),wait flag:0,val:2,shift:-4
threadIdx.x:256
ReduceOrCopy

WaitOnFlags:3
PostToFlags:2

Post OK threadIdx.x:256,flag addr:0x1061be00000,post flag:2,2,0 
WAIT OK  threadIdx.x:0,flag addr:0x1050da00004,*flag >= (val + shift),wait flag:0,val:3,shift:-4
threadIdx.x:256
ReduceOrCopy

WaitOnFlags:4
PostToFlags:3

Post OK threadIdx.x:256,flag addr:0x1061be00000,post flag:3,3,0 
WAIT OK  threadIdx.x:0,flag addr:0x1050da00004,*flag >= (val + shift),wait flag:1,val:4,shift:-4
threadIdx.x:256
ReduceOrCopy
PostToFlags:4

0 Wait for last update from next then reset the flag
Post OK threadIdx.x:256,flag addr:0x1061be00000,post flag:4,4,0 

**The code segment is like this**：

if(threadIdx.x < THREADS){
      //waitFlag
     ...
      for (int sub=0; sub<SUBSTEPS; ++sub) {
        if (AnyAre<WaitFlag>(flags...)) {
          if (threadIdx.x == 0) {
	    printf("\n\nWaitOnFlags:%d",SUBSTEPS*step + sub + 1);
            WaitOnFlags(SUBSTEPS*step + sub + 1, flags...);
	    printf("\nReduceOrCopy");
          }
          asm volatile ("bar.sync 1, %0;" :: "r"(THREADS));
        }
      ...
      //ReduceOrCopy
}
else {
      for(int sub=0; sub<SUBSTEPS; ++sub) {
        if (AnyAre<PostFlag>(flags...)) {
	  printf("\nthreadIdx.x:%d",threadIdx.x);
          __syncthreads();
          __threadfence_system();
	  printf("\nPostToFlags:%d\n",SUBSTEPS*step + sub + 1);
          PostToFlags(SUBSTEPS*step + sub + 1, flags...);
        }
      }
}

How do the 256 thread's  postFlag run parallel with the 0 thread's waitFlag in one step?

**Comment by sjeaugey** [comment]
The call to __syncthreads() ensures thread 256 posts the flag only after the 256 others have processed the data.
