### ISSUE TITLE
Questions about the usage of multimem in nccl

### ISSUE THREAD

**Issue by lpoyster** [NVIDIA/nccl#1230]
cuda PTX manual said "Only multimem.* operations are valid on multimem addresses", but it seems that these places in NCCL have not followed this rule.
1. the multimem_st_global of Size 1 and 2, here st.x is used instead of multiem.st.x.
2. the st_relaxed_sys_global function in postPeer, here use st.x, but when nvls is enabled, the connStepPtr is multimem.
please correct me if I'm wrong, very thanks.

**Comment by jbachan** [comment]
Yes that is a violation of the PTX spec. But if you check the SASS you'll see that multimem stores generate the same instructions as regular stores.
