### ISSUE TITLE
P2P Blocking Semantics and AlltoAll

### ISSUE THREAD

**Issue by osayamenja** [NVIDIA/nccl#1233]
As stated [here](https://docs.nvidia.com/deeplearning/nccl/user-guide/docs/api/p2p.html), `ncclSend` and `ncclRecv` are "blocking" to the GPU and [CPU, it seems](https://github.com/pytorch/pytorch/issues/117749#issue-2088510307). Given these semantics, I cannot wrap my head around how [`AlltoAll`](https://docs.nvidia.com/deeplearning/nccl/user-guide/docs/usage/p2p.html#all-to-all) as implemented in the linked documentation or [here](https://github.com/NVIDIA/nccl-tests/blob/c6afef0b6f76ffc55d4172d971be6cf5a08a73a4/src/alltoall.cu#L58C3-L61C4) works without deadlock. Obviously, this implementation _works fine_ in practice, hence my question.

For clarity, I will explain my mental model of this operation and hopefully someone can point out where it goes wrong.

1. Consider GPU 0, 1, and 2 performing `AlltoAll`[^1]
2. Per the loop, the first[^2] iteration entails GPU 0, GPU 1 and GPU 2 simultaneously issuing a `ncclSend` to GPU 1, GPU 0 and GPU 0, respectively.
3. The calling thread/stream blocks pending a `ncclRecv` issued by GPU 1 for GPU 0, GPU 0 for GPU 1 and GPU 0 for GPU 2. 
4. But naively this yields a deadlock between GPU 0 and GPU 1 as GPU 1 awaits a `recv` from GPU 0 and vice versa.

Please help me clarify!

[^1]: Let's also assume the concurrent implementation across channels as described in [GTC '24 S61368](https://static.rainfocus.com/nvidia/gtcs24/sess/1693876934119001DqDe/FinalPresPDF/S61368_1710778532525001A5Z4.pdf).
[^2]: For simplicity, let's not consider the iteration where a GPU sends/receives to and from itself.

**Comment by osayamenja** [comment]
@AddyLaddy Please let me know your thoughts.

**Comment by sjeaugey** [comment]
Using ncclGroupStart/ncclGroupEnd is key here. When wrapping multiple calls inside a group, then all calls are fused together logically, and you can create inter-GPU communication patterns which can happen concurrently.

**Comment by osayamenja** [comment]
@sjeaugey Thank you! So in that case are the send/recv calls no longer blocking? Another question would be can you explain precisely what happens as NCCL executes the fused All-to-All operation?

**Comment by sjeaugey** [comment]
The fused call of sends and recvs is still blocking. Individual sends and receives are not within the global fused operation.

**Comment by osayamenja** [comment]
Thanks again, when you say the fused call is blocking, do you mean that the operation does not complete until all of its send/recv calls complete? If so, how does NCCL keep track of which is completed or not?

**Comment by osayamenja** [comment]
Thanks for the help! I will close this as the main question was answered.

**Comment by sabuj7177** [comment]
Hi @osayamenja Have you figured out how the fused call of the AllToAll collective actually works and how the send and receive calls are ordered?
