### ISSUE TITLE
Does NCCL take one SM away and add more pressure to the underlying L2 cache?

### ISSUE THREAD

**Issue by Sampson1107** [NVIDIA/nccl#124]
"In our experiment, we demonstrate that although NCCL often leads to much faster data aggregation by itself, it doesn't necessarily lead to faster training. Our hypothesis is that the implicit copies are essentially free since they go to the copy engine on GPU, as long as its latency can be hidden by the main computation itself. Although NCCL can transfer data faster, it takes one SM away, and adds more pressure to the underlying L2 cache. "

Is it correct? Does it take one SM away and add more pressure to the underlying L2 cache?
If the data that need to transfer  among 8 GPUS in one server  is just 1MB in 0.05 seconds , will NCCL lead to a faster transfer than the implicit copies?

**Comment by sjeaugey** [comment]
NCCL indeed uses GPU resources (SMs), hence it can, in some cases, be faster to use cudaMemcpy to copy all gradients to the CPU, have the CPU do the reduction, then copy it back to the GPUs.

Of course, that's only true if the CPU has available cycles and it doesn't scale very well with many GPUs and large buffers as the CPUs is slower at performing reductions than the GPU.

Note you can control the GPU usage of NCCL with NCCL_NTHREADS and NCCL_MAX_NRINGS.
