### ISSUE TITLE
Question about the use of tree algorithm in DGX A100

### ISSUE THREAD

**Issue by GeofferyGeng** [NVIDIA/nccl#1245]
In the PCI platform, the tree algorithm is clear, establishing a tree algorithm between machines, connecting them in a linear fashion within the machine. But I came across a diagram in the PPT provided by NVIDIA showcasing the use of the tree algorithm in DGX A100. In the diagram, each network card has two channels, with one channel traversing 8 GPU and the other channel traversing only 7 GPU. In this scenario, how is AllReduce operation performed?
![PixPin_2024-04-02_17-41-57](https://github.com/NVIDIA/nccl/assets/31677955/6c8469b4-73fd-4a91-aa3c-326cc28202c3)

Additionally, there is a mention of "From the network perspective, data is coming from the same node and same NIC, but inside the node, NCCL pull data from two GPUs." This statement seems to describe the phenomenon, how should it be interpreted? 

Looking forward to your response.

**Comment by sjeaugey** [comment]
Those two paths from two GPUs to one NIC do not map to the two channels.
On each channel, the communication is split in half between each GPU to better balance the computation. That's the principle of the "balanced tree".

**Comment by renwuli** [comment]
@GeofferyGeng  have you figured it out?
