### ISSUE TITLE
NCCL1&2 Conflicts with hdf5

### ISSUE THREAD

**Issue by jsmlay** [NVIDIA/nccl#125]
When compile caffe ssd git from weiliu89's repo with NCCL on, the following error come about:

[----------] 8 tests from AdamSolverTest/2, where TypeParam = caffe::GPUDevice<float>
[ RUN ] AdamSolverTest/2.TestSnapshot
[ OK ] AdamSolverTest/2.TestSnapshot (65 ms)
[ RUN ] AdamSolverTest/2.TestAdamLeastSquaresUpdateWithEverything
*** Aborted at 1516069653 (unix time) try "date -d @1516069653" if you are using GNU date ***
PC: @ 0x7fd006fad998 H5SL_insert_common
*** SIGSEGV (@0x20) received by PID 35588 (TID 0x7fcfd3ad8700) from PID 32; stack trace: ***
  @ 0x7fcffb2cb100 (unknown)
  @ 0x7fd006fad998 H5SL_insert_common
  @ 0x7fd006fb0389 H5SL_insert
  @ 0x7fd006f85d10 H5P_close
  @ 0x7fd006f31ea8 H5I_dec_ref
  @ 0x7fd006ec6136 H5F_dest
  @ 0x7fd006ec712d H5F_try_close
  @ 0x7fd006ec7434 H5F_close
  @ 0x7fd006f31ea8 H5I_dec_ref
  @ 0x7fd006f320e2 H5I_dec_app_ref
  @ 0x7fd006ec1a28 H5Fclose
  @ 0x7fcffbc1aee0 caffe::HDF5DataLayer<>::LoadHDF5FileData()
  @ 0x7fcffbc19ba8 caffe::HDF5DataLayer<>::LayerSetUp()
  @ 0x7fcffbcb5e9c caffe::Net<>::Init()
  @ 0x7fcffbcb7af2 caffe::Net<>::Net()
  @ 0x7fcffbcc7450 caffe::Solver<>::InitTrainNet()
  @ 0x7fcffbcc83a3 caffe::Solver<>::Init()
  @ 0x7fcffbcc867f caffe::Solver<>::Solver()
  @ 0x7fcffbcd4541 caffe::Creator_AdamSolver<>()
  @ 0x7fcffbcc381e caffe::SolverRegistry<>::CreateSolver()
  @ 0x7fcffbcc3a9c caffe::Worker<>::InternalThreadEntry()
  @ 0x7fcffbb99fa0 caffe::InternalThread::entry()
  @ 0x7fcffbb9a8f6 boost::detail::thread_data<>::run()
  @ 0x7fd0056aeb99 thread_proxy
  @ 0x7fcffb2c3dc5 start_thread
  @ 0x7fcffaff0ced __clone
make: *** [runtest] Segmentation fault (core dumped)

The Error disappear when NCCL setting to off. 
Envs:
--> Centos7.2 with 4 x P40
--> yum install hdf5 hdf5-devel
Can ur team plz help to solve this problem?

**Comment by spotluri** [comment]
It seems like a Caffe issue. The Caffe project might be a better place to report this if it is still a concern.
