### ISSUE TITLE
Leak in FIFO queue

### ISSUE THREAD

**Issue by samsamoa** [NVIDIA/nccl#1251]
We are experiencing an issue where 8 processes, each controlling one GPU on a node, all lock up at the same time.  It seems to be deterministic, though we don't know exactly the operation that is causing trouble.  But something like "after N graph executions, all 8 processes stall at the same time".

We're relatively confident that this is a leak, because increasing NCCL_WORK_FIFO_DEPTH seems to increase the number of graphs that can be executed prior to stalling.  And decreasing it causes the stall to happen sooner.

Here is the stack trace for where we get stuck:
```
sched_yield (libc.so.6)
waitWorkFifoAvailable (enqueue.cc:745)
uploadWork (enqueue.cc:777)
ncclLaunchKernelBefore_NoUncapturedCuda (enqueue.cc:1008)
doLaunches (group.cc:172)
groupLaunch (group.cc:342)
ncclGroupEndInternal (group.cc:423)
ncclGroupEndInternal (group.cc:378)
ncclGroupEnd (group.cc:106)
```

This is on an older NCCL patch, a8511ca628f05cb83ed03e0b196ba89e6f710d57, but we have verified that the same issue is present on master as of yesterday.  The issue affects both H100 and A100.

We'll update the issue as we gather more info on the exact operation that is causing trouble.

**Comment by WhiteFangBuck** [comment]
@sjeaugey @KaimingOuyang

**Comment by jbachan** [comment]
Can you elaborate on the number of graphs, the number of nccl calls per graph, the number of non-graph nccl calls. With that, could you create a minimal reproducer? Also, @Ben ***@***.***> can you help them collect a nccl call trace?

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
