### ISSUE TITLE
cntk23 compiler erroe 

### ISSUE THREAD

**Issue by latifovic** [NVIDIA/nccl#126]
Error message:

In file included from Source/Math/Matrix.h:23:0,
                 from Source/ComputationNetworkLib/ComputationNetwork.h:10,
                 from Source/ActionsLib/Actions.h:12,
                 from Source/EvalDll/CNTKEval.cpp:15:
Source/Math/half.hpp:13:39: error: missing binary operator before token "("
 #if !defined(CPUONLY) && __has_include("cuda_fp16.h") 

when if block removed in cuda_fp16.h  (for case of GPU)  it compiles

**Comment by sjeaugey** [comment]
Shouldn't this issue be reported on the CNTK project rather than NCCL ?
