### ISSUE TITLE
some question about log

### ISSUE THREAD

**Issue by wangfakang** [NVIDIA/nccl#1263]
Why is there a line break at the beginning of the log when the log level is `NCCL_LOG_WARN`? thx. 

https://github.com/NVIDIA/nccl/blob/ab2b89c4c339bd7f816fbc114a4b05d386b66290/src/debug.cc#L178-L201
```[tasklist]
### Tasks
```

**Comment by wangfakang** [comment]
friendly ping @sjeaugey

**Comment by AddyLaddy** [comment]
I'm pretty sure it's deliberately put there so make sure the WARN message is easy to see and parse and not merged with a line of application output.
All NCCL_DEBUG output is written to stdout, so is prone to being mixed up with other application output.

**Comment by wangfakang** [comment]
> I'm pretty sure it's deliberately put there so make sure the WARN message is easy to see and parse and not merged with a line of application output. All NCCL_DEBUG output is written to stdout, so is prone to being mixed up with other application output.

Got it and many thanks.
