### ISSUE TITLE
How to get the NCCL_ROOT and NCCL_LIBRARIES path? 

### ISSUE THREAD

**Issue by Iven2132** [NVIDIA/nccl#1274]
How to get the NCCL_ROOT and NCCL_LIBRARIES path?  I'm using nvidia/cuda:12.2.2-devel-ubuntu22.04 image, I also tried installing it with `python -m cupyx.tools.install_library --cuda 12.x --library nccl` but I can't find any NCCL. 

I also tried to get that using nvidia/cuda:11.8.0-devel-ubuntu22.04 image but I can see three cuda in my usr/local directory `cuda  cuda-11  cuda-11.8` when I check `nvcc --version` It's `Build cuda_11.8.r11.8/compiler.31833905_0ff`

**Comment by sjeaugey** [comment]
This is a question for pytorch is seems, not for NCCL.

**Comment by kiskra-nvidia** [comment]
Exactly. The container you mentioned (nvidia/cuda:12.2.2-devel-ubuntu22.04) does include NCCL 2.19.3, installed in the system `/usr` directory. So I don't think that setting `NCCL_ROOT` would be necessary, but if you must, set it to `/usr`.
