### ISSUE TITLE
Why is GPUDirect Async not used in nccl

### ISSUE THREAD

**Issue by ziannchen** [NVIDIA/nccl#1278]
Will GPUDirect Async be included in future development plans?

NVSHMEM use GPUDirect Async bypass CPU.
https://developer.nvidia.com/blog/improving-network-performance-of-hpc-systems-using-nvidia-magnum-io-nvshmem-and-gpudirect-async/

**Comment by kiskra-nvidia** [comment]
We have been exploring using it in NCCL. No guarantees at this point if/when it will become available.

**Comment by kiskra-nvidia** [comment]
We found that, to fully leverage the advantages of GPUDirect Async, we need to make considerable changes within NCCL. This work is ongoing, and you will see the first outcomes in NCCL 2.27, with more work planned for subsequent releases. If you have access to GTC talks, I encourage you to watch Sylvain's presentation from this year, which covers this.

**Comment by VadimEisenberg** [comment]
@kiskra-nvidia Do you have any updates on the status of GPUDirect Async?

**Comment by sjeaugey** [comment]
We're actively working on it. It's not yet in a good enough shape to share it though.
