### ISSUE TITLE
One of the NODE will hang when NCCL_NET_GDR_READ=1 

### ISSUE THREAD

**Issue by shanleo1986** [NVIDIA/nccl#1288]
Hi, deer developer,
We have no any NVlinks, the GPU and NIC are connected with a PCIe switch and connect to the CPU.
With two nodes, we run the NCCL_test with NCCL_NET_GDR_READ=1 , that means we enable GDR both on send and recv side.
One of the NODE will hang when the tatal data about 64KB, with the error logs as follows:
![GDR error](https://github.com/NVIDIA/nccl/assets/145751038/79595bc8-a6b8-4cdf-8d46-17c6282526c4)

But if we enable the GDR only on side, the issue will gone.

The TOPO is as follows:
![GDR error TOPO](https://github.com/NVIDIA/nccl/assets/145751038/ab6e43c2-8aef-438b-abf4-cfc49bf889b9)

Can you give me some hint how to debug this issue? 
Thank you very much.

**Comment by sjeaugey** [comment]
You should probably post this question on the RCCL project.
