### ISSUE TITLE
unhandled cuda error on NCCL2

### ISSUE THREAD

**Issue by haNa-meister** [NVIDIA/nccl#129]
Hi,

I am trying to use NCCL2 train my net using caffe. And I encounter such error which I cannot solve it by myself.
![_152774601022](https://user-images.githubusercontent.com/34223424/40764076-1475b272-64da-11e8-8156-c618ff4e2769.png)
My set up is 2 machine with 8 Tesla P40 GPUs each.
And my shell code is:
mpiexec --allow-run-as-root -machinefile hosts --btl_openib_want-cuda-gdr 1 --mca plm_rsh_no_tree_spawn 1 ./parallel

Could you give me some hints about this error?

Thanks!

**Comment by haNa-meister** [comment]
And If I disable p2p and shm by NCCL_P2P_DISABLE=1, NCCL_SHM_DISABLE=1, it works. However, the performance will decrease.

**Comment by sjeaugey** [comment]
Are you using CUDA_VISIBLE_DEVICES to set the GPU each process is using ? If so, that will not work with NCCL because it prevents CUDA IPCs from being used.

Instead of setting CUDA_VISIBLE_DEVICES, it is often not too hard to set your own environment variable (e.g. CAFFE_CUDA_DEVICE), then call cudaSetDevice based on that environment variable.

**Comment by haNa-meister** [comment]
Hi sjeaugey,
In fact, I did not use CUDA_VISIBLE_DEVICES.
I use 16 process and 1 GPU for each, thus I use rank%8 to call cudaSetDevice

**Comment by kwen2501** [comment]
Hi haNa,
Could you please check if the two nodes have the same hostname? That would cause NCCL to believe all ranks are on the same node and try to connect them through IPC (which obviously doesn't work).

**Comment by sjeaugey** [comment]
Closing old bug ; feel free to reopen if this is still a problem.

Also, please make sure to try with the latest version since there have been fixes related to similar problems.
