### ISSUE TITLE
Is NCCL thread safe?

### ISSUE THREAD

**Issue by linnanwang** [NVIDIA/nccl#13]
Hello,

It comes to my attention that all examples are in single thread. I tried a multithread example by the following codes:
void _GPU(void_ threadid)
{
   const int size = 2;
   int tid = _((int_) threadid);
   cudaSetDevice(tid);
   ncclComm_t comm  = comms[tid];   //init as a in file variable in main thread 
   PerThreadData\* data = (PerThreadData_) malloc(sizeof(PerThreadData));
   int cudaDev;
   int rank;
   cudaDeviceProp prop;
   ncclCommCuDevice(comm, &cudaDev);
   ncclCommUserRank(comm, &rank);
   cudaGetDeviceProperties(&prop, cudaDev);
   //initialization
   cudaStreamCreate(&(data->stream));
   cudaMalloc(&(data->sendBuff), sizeof(double)_size);
   cudaMalloc(&(data->recvBuff), sizeof(double)_size);
   double temp[2] = {tid+1, tid+1};
   cudaMemcpy(data->sendBuff, temp, sizeof(double)_size, cudaMemcpyHostToDevice);
   cudaMemcpy(data->recvBuff, temp, sizeof(double)*size, cudaMemcpyHostToDevice);
   data->size = size;
   printf("#   Rank %2d uses device %2d [0x%02x] %s\n", rank, cudaDev, prop.pciBusID, prop.name);
   printf("Hello World! It's me, thread #%d!\n", tid);
   //destruction
   pthread_exit(NULL);
}

Each thread is responsible for a GPU running the above code. Then it creates a deadlock.

I assume NCCL is not thread safe in this case. Is that true? Do we only use it in a single thread? 
Thank you.

**Comment by nluehr** [comment]
NCCL does support multi-threaded control. In fact, calling ncclCommInitRank() from each thread, you can even perform the communicator initialization in multi-threaded mode. The code above contains only a couple of nccl calls, neither of which can deadlock. The hang most likely occurs during the comm initialization step. Can you include the listing of main?

**Comment by ladiemon** [comment]
I have similar dead lock issue when I called ncclCommInitRank from multiple threads.
And I found some threads stuck in syncRingDirect and closeGather.

**Comment by nluehr** [comment]
ladiemon, the latest commit (dba3ec942) should fix the deadlock in ncclCommInitRank.

**Comment by sjeaugey** [comment]
Closing old bug.
