### ISSUE TITLE
Could I compile nccl2 from the source?

### ISSUE THREAD

**Issue by CoinCheung** [NVIDIA/nccl#130]
Thanks a lot for providing so many fine tools for deep learning!!

I am compiling caffe and found that I have to install nccl first to use multi-gpus. I see in this repository that nccl is replaced by nccl2, so I feel I better install nccl2. Do I have a choice to compile nccl2 from the source rather than install it with deb, if so where could I download the source? By the way, will I suffer from compatibility problems with nccl1 if using nccl2?

**Comment by AddyLaddy** [comment]
nccl2 source code is not pubically available so there is no option for compiling it. debian packages and tarballs of the NCCL2 binaries are available from Nvidia. But for Deep Learning I would suggest you look at thre pre-built containers supplied on https://www.nvidia.com/en-us/gpu-cloud/deep-learning-containers/ which will have all the necessary libraries pre-installed.

**Comment by sjeaugey** [comment]
Should be solved now.
