### ISSUE TITLE
Why there are two IDs for MNNVL support?

### ISSUE THREAD

**Issue by dearsxx0918** [NVIDIA/nccl#1301]
Hi Sjeaugey,
    I've seen there are two IDs, clique ID & UUID to identify if MNNVL is possible, why we need two IDs here?
Best regards,
-Edda

**Comment by kiskra-nvidia** [comment]
The two IDs are simply what the NVML API gives us (https://docs.nvidia.com/deploy/nvml-api/structnvmlGpuFabricInfo__v2__t.html). clique ID by itself is not unique so we need to compare the cluster UUID as well.

**Comment by dearsxx0918** [comment]
Thanks for your quick reply. I think I've got the answer, users may config the fabric into many virtual partitions as well. The clique ID are used for these cases.
