### ISSUE TITLE
how double binary tree communicate

### ISSUE THREAD

**Issue by ltm920716** [NVIDIA/nccl#1327]
hi,  
    about https://developer.nvidia.com/blog/massively-scale-deep-learning-training-nccl-2-4/, there will be two trees commucate simultaneously,right?     
    the roots of these two trees are different, I am confused that where the data will be reduced finally. so the it can be broadcasted then.  
    thanks

**Comment by NEWPLAN** [comment]
In double binary tree, each tree includes all nodes in an communication group. Taking the first tree(i.e., all even nodes act as the leaf nodes in the tree.) At first, data in leaf node(i.e., 1,3,5,7,...,31) is first sent to its parent node(i.e., 2,6,10,14,18,22,26,30), after reducing with its local data, the results are then sent to the upper parents(i.e., 4,12,20,28), with the same operations. Finally, the root would owns the reduced data from all nodes in a group,  then, the reduced data would be broadcast along the reversal path,  and all nodes would get the same reduced data.

**Comment by ltm920716** [comment]
Hi @NEWPLAN,  
Thanks for your reply！   

I understand the first tree and it uses Log_N steps for data reduced to the root，as well as the ring method will take N-1 steps.  What I confused is that when the first tree does reduce or broadcast operation，all node are fixed at the moment，right？So how does the logical second tree work together？Or these two trees work together by different batch data on differents nodes？
   
I am new to this filed，thank again and expect your reply.

**Comment by NEWPLAN** [comment]
Hi @ltm920716 
The two trees are pre-computed communication paths, and each tree would be finally mapped to a channel (i.e., one tree is bound to a channel containing all nodes). From the view of each physical rank, there are 4 established connections with its peers according to the two trees, stored in the corresponding structure (i.e.,  channel[peer]). 
When all-reducing data (with 2N elements), the first N elements would be mapped to the channel belongs to the first tree, and the rest N elements are reduced with the second channel belongs to another tree. That's they are run in parallel.

**Comment by ltm920716** [comment]
> Hi @ltm920716 The two trees are pre-computed communication paths, and each tree would be finally mapped to a channel (i.e., one tree is bound to a channel containing all nodes). From the view of each physical rank, there are 4 established connections with its peers according to the two trees, stored in the corresponding structure (i.e., channel[peer]). When all-reducing data (with 2N elements), the first N elements would be mapped to the channel belongs to the first tree, and the rest N elements are reduced with the second channel belongs to another tree. They are running in parallel.

Thank you very much！
