### ISSUE TITLE
GID index change cause training to stop on ConnectX-7 400G Adapters when traing LLM

### ISSUE THREAD

**Issue by wangdaw2023** [NVIDIA/nccl#1333]
We have GPU cluster with ConnectX-7 400G Adapters/RoCE。When training LLM for sometime (12 hours ), the ConnectX-7 gid index changed from 3 to 4/8 (show_gids command), which cause the training to stop。We have to restart the node to recover the gid index to 3。

The server OS is ubuntu 22.04 The CX-7 adapter driver is MLNX_OFED_LINUX-24.01-0.3.3.1-ubuntu22.04-x86_64.tgz

With nccl 2.21 doc, it seems even gid index change, nccl 2.21 could continue the model training with pytorch/nccl 2.21/rdma stack.  How to leverage this feature in training? Use NCCL_IB_ROCE_VERSION_NUM=2 to replace NCCL_IB_GID_INDEX=3 setting?

**Comment by sjeaugey** [comment]
The new feature in 2.21 is to automatically find the GID index. Which means that you wouldn't need to reboot the node, on the next run NCCL will pick GID 6 automatically on that node (and keep GID 3 on other nodes). Before you couldn't do that easily, as setting GID index to 3 would mean all nodes need to use GID 3.

So when the GID changes, the NCCL communication will still be broken and error out. You will need the application to tear down the NCCL communicator and recreate a new one. Or restart the application. But there is no automatic reconnect/recover.

**Comment by wangdaw2023** [comment]
Thanks for you explanation.
