### ISSUE TITLE
How to switch between run_tree_up_down and run_tree_split algorithm

### ISSUE THREAD

**Issue by ZhiyiHu1999** [NVIDIA/nccl#1336]
Hello! Is there a setting that we can change like NCCL_ALGO or NCCL_PROTO environmental variable so that we can switch between run_tree_up_down and run_tree_split algorithm when we use tree algorithm. Thanks a lot!

**Comment by Hizhaoyuan** [comment]
`https://github.com/NVIDIA/nccl/blob/master/src/device/all_reduce.h#L231-L240`
