### ISSUE TITLE
/usr/local/lib/libnccl.so.2 is not a symbolic link

### ISSUE THREAD

**Issue by ghost** [NVIDIA/nccl#134]
I wanted to reinstall libappstream3 using following command:
sudo apt install --reinstall libappstream3
but I got the error: 
/sbin/ldconfig.real: /usr/local/lib/libnccl.so.2 is not a symbolic link

I have no idea how to solve this issue

**Comment by sjeaugey** [comment]
It seems to be due to an improper NCCL install.

Closing, re-open if needed.
