### ISSUE TITLE
Enabling read for P2p transport

### ISSUE THREAD

**Issue by NEWPLAN** [NVIDIA/nccl#1349]
Hi, I'm following the code, when setting up the p2ptransport (p2pSendSetup->p2pGetInfo->ncclTopoCheckP2p), I have found that the p2p read requires path_type=nvls and cudaCompCap==80 (ref: https://github.com/NVIDIA/nccl/blob/master/src/graph/paths.cc#L342-L343 )
I'm wondering that can Hopper or a later architecture (with NVLink) support p2p read? and why p2p read is only enabled in Ampere/NVLink?

**Comment by kiskra-nvidia** [comment]
Please see: https://github.com/NVIDIA/nccl/issues/512#issuecomment-1927876187
