### ISSUE TITLE
Building Debian package

### ISSUE THREAD

**Issue by xkb1984** [NVIDIA/nccl#135]
when I install the nccl on my ubuntu system,I get the following errors:
```
/home/ild/nccl/src
make[4]: Leaving directory '/home/ild/nccl/src'
make[3]: Leaving directory '/home/ild/nccl'
Building Debian package
/bin/sh: 1: debuild: not found
Makefile:31: recipe for target 'build' failed
make[2]: *** [build] Error 127
make[2]: Leaving directory '/home/ild/nccl/pkg/debian'
Makefile:23: recipe for target 'debian.build' failed
make[1]: *** [debian.build] Error 2
make[1]: Leaving directory '/home/ild/nccl/pkg'
Makefile:27: recipe for target 'pkg.debian.build' failed
make: *** [pkg.debian.build] Error 2
```

**Comment by AddyLaddy** [comment]
Looks like you need to install the debuild package;

sudo apt install devscripts

**Comment by XiongChengxin** [comment]
@xkb1984 
Where did you install your CUDA?

If CUDA is not installed in the default /usr/local/cuda path, you can define the CUDA path with:
$ make src.build CUDA_HOME=<path to cuda install>

my <path to cuda install> is my home directory
I met the same error as you, and I solved it by add LD_LIBRARY_PATH to bashrc like:
export LD_LIBRARY_PATH=/home/usrname/nccl/build/lib:$LD_LIBRARY_PATH

**Comment by XiongChengxin** [comment]
@xkb1984 I met the same error as you, and I have solved it.

Where did you install your CUDA?

If CUDA is not installed in the default /usr/local/cuda path, you can define the CUDA path with:
$ make src.build CUDA_HOME=<path to cuda install>

If you have define the CUDA path with above step, you should add LD_LIBRARY_PATH to bashrc. For example, my <path to cuda install> is my home directory, and I add:
export LD_LIBRARY_PATH=/home/usrname/nccl/build/lib:$LD_LIBRARY_PATH

**Comment by XiongChengxin** [comment]
@xkb1984  I met the same error as you, and I have solved it.

Where did you install your CUDA?

If CUDA is not installed in the default /usr/local/cuda path, you can define the CUDA path with:
$ make src.build CUDA_HOME="path to cuda install"

Above is the step in NCCL README.md. 

If you have define the CUDA path with above step, you should add LD_LIBRARY_PATH to bashrc. For example, my "path to cuda install" is my home directory, and I add:
export LD_LIBRARY_PATH=/home/usrname/nccl/build/lib:$LD_LIBRARY_PATH

**Comment by sjeaugey** [comment]
Indeed, that could cause the debian build to fail, but I think that would produce a different error message than :
```
/bin/sh: 1: debuild: not found
```
