### ISSUE TITLE
How to tell nccl that those network communication is disabled?

### ISSUE THREAD

**Issue by gpzlx1** [NVIDIA/nccl#1350]
I have two machines, and their topology is as follows:

```shell
        GPU0    GPU1    GPU2    GPU3    GPU4    GPU5    GPU6    GPU7    NIC0    NIC1    CPU Affinity    NUMA Affinity   GPU NUMA ID
GPU0     X      NV4     NODE    NODE    SYS     SYS     SYS     SYS     NODE    SYS     0-95    0               N/A
GPU1    NV4      X      NODE    NODE    SYS     SYS     SYS     SYS     NODE    SYS     0-95    0               N/A
GPU2    NODE    NODE     X      NV4     SYS     SYS     SYS     SYS     PIX     SYS     0-95    0               N/A
GPU3    NODE    NODE    NV4      X      SYS     SYS     SYS     SYS     PIX     SYS     0-95    0               N/A
GPU4    SYS     SYS     SYS     SYS      X      NV4     NODE    NODE    SYS     NODE    96-191  1               N/A
GPU5    SYS     SYS     SYS     SYS     NV4      X      NODE    NODE    SYS     NODE    96-191  1               N/A
GPU6    SYS     SYS     SYS     SYS     NODE    NODE     X      NV4     SYS     PIX     96-191  1               N/A
GPU7    SYS     SYS     SYS     SYS     NODE    NODE    NV4      X      SYS     PIX     96-191  1               N/A
NIC0    NODE    NODE    PIX     PIX     SYS     SYS     SYS     SYS      X      SYS
NIC1    SYS     SYS     SYS     SYS     NODE    NODE    PIX     PIX     SYS      X 
```

As you have observed, each machine has two NICs, and these NICs are connected in a point-to-point configuration, meaning that `mlx5_0` can only communicate with `mlx5_0`, and `mlx5_1` can only communicate with `mlx5_1`. There is no physical connection between `mlx5_0` and `mlx5_1` between the two machines.

This configuration works well for `allreduce`, but it seems to cause issues for `all2all` operations, likely because NCCL is attempting to leverage the non-existent `mlx5_0-mlx5_1` communication.

A possible solution is that try to tell NCCL with information about the network topology. But how to do it?

**Comment by kiskra-nvidia** [comment]
Can you try running with `NCCL_CROSS_NIC=0` (https://docs.nvidia.com/deeplearning/nccl/user-guide/docs/env.html#nccl-cross-nic)?

**Comment by gpzlx1** [comment]
> Can you try running with `NCCL_CROSS_NIC=0` (https://docs.nvidia.com/deeplearning/nccl/user-guide/docs/env.html#nccl-cross-nic)?

It works well. Thank you.
