### ISSUE TITLE
Is it possible to swap the calling order of `initTransportsRank` and `ncclTunerPluginLoad`

### ISSUE THREAD

**Issue by jeseszhang1010** [NVIDIA/nccl#1351]
Hi NCCL team,

I'd like to set a few NCCL environment variables during tuner plugin initialization to further tune the performance on specific platform.
But I realized that some of them have been already set during initTransportsRank() which is prior to tuner plugin load/initialization. 

Is it possible to swap the calling order of  `initTransportsRank` and `ncclTunerPluginLoad/init` in `ncclCommInitRankFunc`? Will it break anything?

https://github.com/NVIDIA/nccl/blob/master/src/init.cc#L1408-L1413

**Comment by gcongiu** [comment]
The `tuner->init` call needs `comm->nNodes`, which is only computed at `initTrasportRank`. Thus, inverting the order of `tuner->init` and `initTransportRank` would be challenging without a change to the `init` interface.
