### ISSUE TITLE
work request complete err: status 5 and vendor err 249

### ISSUE THREAD

**Issue by 913871734** [NVIDIA/nccl#1353]
Hi,
   I have met an issue that the mission failed due to the work complete failed. the detailed log as followings, I wonder what does the err log mean? And what scenarios usually produce such error codes?
   
![image](https://github.com/NVIDIA/nccl/assets/26898771/a05ffd8d-9257-459b-9021-810a3e5da576)

**Comment by Yangruipis** [comment]
same issue here

**Comment by sjeaugey** [comment]
Two main reasons:
1. Make sure ACS is disabled
2. If you are using a Dell server, make sure you have the latest FW updates.

**Comment by 913871734** [comment]
> Two main reasons:
> 
> 1. Make sure ACS is disabled
> 2. If you are using a Dell server, make sure you have the latest FW updates.

what is the ACS mean ?

**Comment by sjeaugey** [comment]
> What does the firmware check you mentioned mainly focus on?

You should reach out to Dell for that, they should be able to assist you.

**Comment by 913871734** [comment]
> > What does the firmware check you mentioned mainly focus on?
> 
> You should reach out to Dell for that, they should be able to assist you.

I don't know what element's firmware to be checked, the nccl firmware version? or the vendor platform firmware version? or rdma-core version?

**Comment by kiskra-nvidia** [comment]
The vendor platform firmware (BIOS/UEFI/whatever you want to call it). There is some general info at https://docs.nvidia.com/deeplearning/nccl/user-guide/docs/troubleshooting.html, specifically the subsection on ACS.

**Comment by 913871734** [comment]
> vendor platform firmware

ok, thanks a lot
