### ISSUE TITLE
(Bug) posix_fallocate() call should handle EINTR

### ISSUE THREAD

**Issue by frankseide** [NVIDIA/nccl#137]
Hi, I am seeing intermittent failures in `ncclCommInitRank()` (`groupEnd()`, to be precise) reported as `WARN Unable to allocate shared memory (4214784 bytes) : Interrupted system call`.

I tracked that down to spurious `SIGPROF` signals received while in `int res = posix_fallocate(fd, 0, shmsize);` in `include/shm.h`. Receiving a signal leads to `posix_fallocate()` return error code `EINTR`. If I understand it right, those signals arise from use of timers in our code, so this may not be uncommon.

I believe the current NCCL code is incorrect in that it does not handle `EINTR`. It should intercept the special case `res == EINTR` and retry. There may be other places in the code that have the same issue.

(This does not block me presently, as I am able to work around this issue in [Marian](https://github.com/marian-nmt/marian-dev) by temporarily blocking the `SIGPROF` signal when initializating the NCCL communicator, but it would be good to have this fixed for everyone else.)

**Comment by sjeaugey** [comment]
@frankseide can you review #152 and confirm that would fix your issue ? Thanks !

**Comment by sjeaugey** [comment]
Is there a problem installing a newer package  ?
```shell
# build package
make pkg.debian.build
# install it (should be more recent hence replace the current one)
dpkg -i build/pkg/deb/*.deb
```
Then revert with :
```shell
# remove our custom NCCL
dpkg -r libnccl-dev libnccl2
# reload NCCL from the local/network installer
apt install libnccl-dev libnccl2
```
