### ISSUE TITLE
Missing 2.3.5 tag

### ISSUE THREAD

**Issue by sclarkson** [NVIDIA/nccl#138]
Would be nice to have

**Comment by AddyLaddy** [comment]
Should be there now;

git tag
v1.2.1-1+cuda7.5
v1.2.1-1+cuda7.5-1
v1.2.1-1+cuda8.0
v1.2.1-1+cuda8.0-1
v1.2.1-2+cuda7.5
v1.2.2-1+cuda7.5
v1.2.2-1+cuda8.0
v1.2.3-1+cuda7.5
v1.2.3-1+cuda8.0
v1.3.0-1
v1.3.4-1
v2.3.5-5
