### ISSUE TITLE
Will ncclSend, ncclRecv launched in different cuda streams blocking each other?

### ISSUE THREAD

**Issue by billwu01** [NVIDIA/nccl#1389]
I want to implement asynchronous communication with ncclSend/ncclRecv in different streams.
For single process with multiple devices. My code is like following: 

On program initialization: 
GPU0 (thread 0): 
**1.**   ncclRecv(recv_buffer0, max_size, ncclFloat32, 1, comm0, **stream0**)

GPU1 (thread1): 
**2.**  ncclRecv(recv_buffer1, max_size, ncclFloat32, 0, comm1, **stream1**)

and in later time when send data is ready on GPU0 or GPU1, will execute:
GPU0 (thread 0): 
ncclSend(send_buffer0, max_size, ncclFloat32, 1, comm0, **stream2**)

but the ncclSend seems blocking on ncclGroupEnd, I guess the blocking is because of the ncclRecv is not completed in **1.**
My question is will the ncclRecv/ncclSend for the same pair of gpu ranks launched in different streams still blocking each other?
I think ncclRecv and ncclSend are also common cuda kernels. Since kernels in different streams can be executed in parallel on the GPU, ncclSend/ncclRecv in different streams should also be executed in parallel.

@sjeaugey @jbachan

**Comment by chenhongyu2048** [comment]
hello bro! May I ask do you get a solution?
I have a similar problem, and I hope to make a ncclsend and a ncclrecv (in different stream) parallel on one single GPU.
