### ISSUE TITLE
make failed while test

### ISSUE THREAD

**Issue by XiongChengxin** [NVIDIA/nccl#139]
my steps:
cd nccl
make -j src.build
make src.build CUDA_HOME=/home/xiongcx/cuda-8.0
make -j src.build NVCC_GENCODE="-gencode=arch=compute_70,code=sm_70"
make pkg.debian.build
ls build/pkg/deb/
git clone https://github.com/NVIDIA/nccl-tests.git
cd nccl-tests
make

Then I met errors:
make -C src build
make[1]: Entering directory '/home/xiongcx/nccl-master/nccl-tests/src'
Compiling  all_reduce.cu                       > ../build/all_reduce.o
In file included from all_reduce.cu:8:0:
common.h:7:18: fatal error: nccl.h: No such file or directory
compilation terminated.
Makefile:70: recipe for target '../build/all_reduce.o' failed
make[1]: *** [../build/all_reduce.o] Error 1
make[1]: Leaving directory '/home/xiongcx/nccl-master/nccl-tests/src'
Makefile:17: recipe for target 'src.build' failed
make: *** [src.build] Error 2

My device is ubuntu 16.04, cuda-8.0, cudnn5.1, glibc 2.23

Any suggestions?

**Comment by sjeaugey** [comment]
You need to pass where the NCCL install is when building the NCCL tests. In your case, it should be 
```
cd nccl
make -j src.build
make src.build CUDA_HOME=/home/xiongcx/cuda-8.0
make -j src.build NVCC_GENCODE="-gencode=arch=compute_70,code=sm_70"
make pkg.debian.build
ls build/pkg/deb/
git clone https://github.com/NVIDIA/nccl-tests.git
cd nccl-tests
```
```
make NCCL_HOME=$PWD/../build
```

**Comment by XiongChengxin** [comment]
@sjeaugey Thanks! It worked.
