### ISSUE TITLE
Which path will be choosen with the Specific TOPO？

### ISSUE THREAD

**Issue by shanleo2024** [NVIDIA/nccl#1402]
Hi Dear developer,
I want to know which path will be choosen with the communication between GPU0 and GPU3, if the topo is as follows.
I think the path will be the blow one, but cannot make sure, could anyone please give some confirmation, thank you a lot!
<img width="386" alt="16卡" src="https://github.com/user-attachments/assets/6a1d5ed1-b5e7-4a06-b2ae-1e69f89cee5b">

**Comment by kiskra-nvidia** [comment]
Yeah, I think it will have to be the blue one. NCCL supports using an intermediate NVLink hop to communicate with a non-local NIC (what we refer to as `PXN`) but I don't think we can do the same when the destination is another GPU...

You should be able to verify that by running with `NCCL_DEBUG=INFO NCCL_DEBUG_SUBSYS=INIT,ENV,GRAPH`. NCCL will then output the paths between all the GPUs, CPUs, and NETs on a node, in terms of the number of hops, bandwidth, and type of connectivity.

Going over the CPUs typically disables P2P support so I'm guessing that NCCL will use SHM in the above case, although it could instead opt to use NET if it looks like the bandwidth will be higher that way.

**Comment by shanleo2024** [comment]
Thank you@kiskra-nvidia
Is the path from GPU0 to GPU3 called PATH_NVB?
```
// Connection through NVLink using an intermediate GPU
#define PATH_NVB 2
```
And can you give me an example of PATH_NVB, cannot understand the type correctlly.

If the TOPO is not match PATH_NVB or PATH_PXN, maybe I have to modify the source code to adapt this topo.
Thank yoy again.

**Comment by kiskra-nvidia** [comment]
Yeah, but in your case there's no way to get from GPU0 to GPU3 using NVLinks so I don't think that NVB is applicable.

What does `nvidia-smi topo -m` show you in terms of connectivity?
