### ISSUE TITLE
Is nccl planning to support CUDA_LAUNCH_BLOCKING=1?

### ISSUE THREAD

**Issue by acgtyrant** [NVIDIA/nccl#141]
See https://github.com/pytorch/pytorch/issues/9163#issuecomment-402827130

**Comment by sjeaugey** [comment]
As mentioned in the pytorch bug, NCCL should work with CUDA_LAUNCH_BLOCKING, but only starting with CUDA 9 (the report mentions CUDA 8), since we can then launch kernels on multiple GPUs in a single cuda operation using cudaLaunchCooperativeKernelMultiDevice.
