### ISSUE TITLE
[Question] Why are thread affinities not set for nccl proxy threads?

### ISSUE THREAD

**Issue by joerowell** [NVIDIA/nccl#1426]
I see that in nccl [2.18.1-1](https://github.com/poolsideai/nccl/commit/d97a32fac84f69cbd022ffdc57d5687c760742c7) the following line was commented out:

https://github.com/NVIDIA/nccl/blob/178b6b759074597777ce13438efb0e0ba625e429/src/proxy.cc#L1400

Other than the fact that the argument to `ncclProxyService` changed, may I ask why this change was made?

**Comment by joerowell** [comment]
Thank you!

**Comment by sjeaugey** [comment]
Actually, after reviewing the code again, it looks like patch is not necessary. The affinity is set in the main thread during init and the service and progress threads should both be launched at that time, when the affinity is set. There should therefore be no need to set the affinity again inside the thread main function.

Did you see any difference with the patch applied?
