### ISSUE TITLE
Why the kernel duration time was affected by NCCL kernel?

### ISSUE THREAD

**Issue by JuiceLemonLemon** [NVIDIA/nccl#1428]
Hello, I have a question about LLM training.

I profiled GPT model training with Nsight system. And I found the computation kernel (such as attention, gemm, elementwise) duration time will increase when they overlap with NCCL kernel (such as AllGather).

Attention kernel w/   overlap 0.33 ms
Attention kernel w/o overlap 0.18 ms

GEMM kernel w/   overlap 2.08 ms
GEMM kernel w/o overlap 1.18 ms

elementwise kernel w/   overlap  0.05 ms
elementwise kernel w/o overlap  0.02 ms

So I want to ask do you know the reason?

**Comment by sjeaugey** [comment]
Very likely, they're competing for memory bandwidth.

**Comment by JuiceLemonLemon** [comment]
> Very likely, they're competing for memory bandwidth.

Thanks a lot for your reply. And I have another question.

We use NVIDIA A100-SXM4-80GB. The HBM bandwidth should be 2T GB/s, and intra-node bandwidth for nccl is 300 GB/s.
I think the nccl only affects the HBM bandwidth a little, but from my profiling result, the Attention kernel time increased about 1.8 times.

So could you please give me more information about this, thank you very much.

**Comment by sjeaugey** [comment]
300GB/s needs to be multiplied by at least 2x for memory bandwidth, as we need to store to memory, then read back from it. If you add reading from or writing to user data, it can be 3x.

**Comment by JuiceLemonLemon** [comment]
> 300GB/s needs to be multiplied by at least 2x for memory bandwidth, as we need to store to memory, then read back from it. If you add reading from or writing to user data, it can be 3x.

ok, I see. Thank you very much for your reply.
