### ISSUE TITLE
Why NCCL P2P(send/recv) operators need a datatype parameters?

### ISSUE THREAD

**Issue by MoFHeka** [NVIDIA/nccl#1440]
If I use uint8 for all kind of P2P data transmission, is there any performance overhead?

**Comment by jbachan** [comment]
No overhead. Internally all datatypes translate to the same single byte type code path.

**Comment by MoFHeka** [comment]
Thanks for your answer, so why does this function need to pass in a datatype? Just to keep the code style consistent, right?

**Comment by jbachan** [comment]
Consistency is important. But also by accepting the datatype now we can change the implementation to someday leverage datatype alignment without affecting user code. Not accepting the datatype would make such transparent optimizations impossible. As it stands we prefer the reduced binary size of libnccl that comes with all types using the single-byte path, and foregoing possible better performance for large element types.
