### ISSUE TITLE
NCCL 2.3 Makefile Install Target

### ISSUE THREAD

**Issue by jkelling** [NVIDIA/nccl#145]
Recently the v2.3.5-5 release appeared, but it looks a bit sketchy. The main issue is, that there is no install target anymore in the Makefile.

It is not tagged as the latest release. Are you planning on adding an install target or will future releases only come with the package generating targets?

**Comment by jkelling** [comment]
I just found, that the install target is still there, but it is in src/Makefile . Just adding
```make
install: src.install
```
to the the toplevel Makefile works. This would be very helpful to not break standard workflows and package managers like [https://github.com/spack/spack]() .

**Comment by sjeaugey** [comment]
Sorry we were not aware of anyone using this target. Can you confirm that #149 is what you want ?

**Comment by jkelling** [comment]
Yes. This is exactly it. Thanks.

**Comment by sjeaugey** [comment]
OK, merged.
