### ISSUE TITLE
Nccl collective block other kernels

### ISSUE THREAD

**Issue by fortianyou** [NVIDIA/nccl#146]
I am using nccl to do gradients ring-reduce in tensorflow. I found that nccl all-reduce kernels didn't launch synchronously, even when I use Group primitive. Also, it seems nccl will block the launch of kernels in the different stream on the same device.  This leads to some nccl participants started early will stall the gpu and do nothing to wait other participants ready.

I guess nccl all-reduce participants are enqueuing at the same time. But it might be launched at any time by gpu scheduler, which is asynchronous for nccl all-reduce participants. Especially when the workloads on other streams are heavy.

I didn't know what exactly happen, could somebody help me?

**Comment by sjeaugey** [comment]
I'm not sure what the question/problem is. Indeed, NCCL operations being CUDA kernels, they are bound by CUDA stream semantics and scheduling (waiting for the stream to be done before starting and potentially blocking other work enqueued after the NCCL launch).

And indeed those are blocking kernels, waiting for other GPUs to launch their NCCL kernels. So if your workload is different between the GPUs, you might want to synchronize on the CPU side before launching NCCL operations to avoid NCCL kernels using GPU time waiting for others to arrive.

Something like the code below, which would need an additional round-trip to the CPU. Not as good in terms of latency, but in the case of highly desynchronized workloads, might still be better.
```
ncclThread() {
  cudaStreamSynchronize(stream);
  MPI_Barrier(mpi_comm);
  ncclAllReduce(..., stream);
}
```

**Comment by fortianyou** [comment]
```

void callback(int i) {
   // some time after the worker_cuda_kernel was launched into stream queue.
   cudaEventRecord(event[i], stream[i]);
   // do nccl reduce request
   add_to_nccl_collective(result[i]);
   ...
}

worker_thread() {
  ...
  for(int gpu_id = 0; gpu_id < num_gpu; ++ gpu_id) {
     // do some compute and return the result
     threadpool.run_async(worker_cuda_kernel(
             result[gpu_id], 
             stream[gpu_id],
             event[gpu_id],
             callback));
  }
  ...
}

ncclThread() {
   // some time after all the participants issued the nccl all-reduce request.
  for (int gpu_id = 0; gpu_id < gpu_num; ++ gpu_id) {
     cudaEventSynchronize(event[gpu_id]);
  }

  ncclGroupStart();
  for(int gpu_id = 0; gpu_id < gpu_num; ++ gpu_id) {
      ncclAllReduce(..., result[i], ..., stream[gpu_id]);
  }
  ncclGroupEnd();
}
```

**Comment by sjeaugey** [comment]
The problem here is that on device 2, you might have another thread launch many CUDA kernels between the events and the actual NCCL launch.

To solve that problem, some frameworks are using events in both directions. Others are defining a static launch order to make sure the execution is similar on all GPUs.

**Comment by fortianyou** [comment]
What is the events in both directions?  And how to implement it?

**Comment by sjeaugey** [comment]
Currently, NCCL waits for other work to complete before starting (using events).
Having events in both directions means making other work wait for NCCL to complete before starting. This is usually not the preferred approach since NCCL can no longer overlap with other workloads.

**Comment by sjeaugey** [comment]
Closing old bug. Feel free to reopen if you have further questions.

**Comment by zhuzilin** [comment]
@fortianyou Have you figured out a solution for this problem? I faced a similar one when using tensorflow...
