### ISSUE TITLE
How to interpret NCCL's NVTX data

### ISSUE THREAD

**Issue by martin-belanger** [NVIDIA/nccl#1477]
I see that NCCL is instrumented with NVTX. As shown below, NVTX is used to trace what NCCL is doing. I would like to be able to retrieve this information. In this particular example, I would like to be able to retrieve the "_Message size [bytes]_" for this All-Reduce operation.
```
ncclResult_t ncclAllReduce(const void* sendbuff, void* recvbuff, size_t count,
    ncclDataType_t datatype, ncclRedOp_t op, ncclComm* comm, cudaStream_t stream) {
  struct NvtxParamsAllReduce {
    size_t bytes;
    ncclRedOp_t op;
  };
  // Just pass the size of one message and not the total bytes sent/received.
  static constexpr nvtxPayloadSchemaEntry_t AllReduceSchema[] = {
    {0, NVTX_PAYLOAD_ENTRY_TYPE_SIZE, "Message size [bytes]"},
    {0, NVTX_PAYLOAD_ENTRY_NCCL_REDOP, "Reduction operation", nullptr, 0,
      offsetof(NvtxParamsAllReduce, op)}
  };
  NvtxParamsAllReduce payload{count * ncclTypeSize(datatype), op};
  NVTX3_FUNC_WITH_PARAMS(AllReduce, AllReduceSchema, payload)
```
I use `nsys` to profile the code while running the `all_reduce_perf` test as shown here:
```
nsys profile -o trace -t nvtx -s none -f true ./nccl-tests/build/all_reduce_perf -b 8 -e 128M -f 2 -g 8
```
Then, I convert the binary data to JSON as follows:
```
nsys export -t json -o trace.json trace.nsys-rep
```
And here's an example of a payload entry that I see in the generated JSON file. 
```
{
    "Type": 59,
    "NvtxEvent": {
        "Type": 59,
        "Timestamp": "5583282789",
        "Payload": {
            "BinaryData": [
                {
                    "SchemaId": "16777221",
                    "Data": "AAAAAgAAAAAAAAAAQbZCsQ=="
                }]
        },
        "GlobalTid": "281511802701971",
        "EndTimestamp": "5583283938",
        "TextId": 37,
        "DomainId": "1",
        "NsTime": true
    }
}
```
Unfortunately, the data is gibberish (e.g. `"AAAAAgAAAAAAAAAAQbZCsQ=="`). Is it encoded? I was hoping I could see the Message size (i.e. number of bytes) that NCCL is processing. How can I do that?

**Comment by kiskra-nvidia** [comment]
I'm not an expert on NVTX but I inquired internally and this is what I got:

> Currently we do not have a unique mapping of NCCL API calls from NVTX with NCCL GPU kernels. Due to that you are not able to get the message sizes from Nsight export. The alternative right now is to use Nsight GUI and find the mapping between `ncclGroupEnd` and the GPU kernel and then look right before the `ncclGroupEnd` and see the message size. It should be under `NVTX.jsonText`

I hope this helps!
