### ISSUE TITLE
1000x latency with `ncclSend` and `ncclRecv`

### ISSUE THREAD

**Issue by goelayu** [NVIDIA/nccl#1487]
I am running a simple nccl benchmark on 2 NVIDIA H100, on the same node connected via NVLink.
`ncclSend/Recv` API is taking about ~700ms to send 1000 bytes.

nccl-tests report the expected latency (~3us). I am trying to understand what my custom benchmark is doing wrong? 

Code snippet
```
auto start = std::chrono::high_resolution_clock::now();
if (rank == 0) {
    NCCL_CHECK(ncclSend(sendBuff, size, ncclChar, 1, comm, 0));
} else if (rank == 1) {
    NCCL_CHECK(ncclRecv(recvBuff, size, ncclChar, 0, comm, 0));
}
auto end = std::chrono::high_resolution_clock::now();
auto ms = std::chrono::duration_cast<std::chrono::milliseconds>(end - start).count();
std::cout << "Time taken: " << ms << " ms" << std::endl;
```

Based on the profiling results from nsight, I can see a large number of `cuMemSetAccess` and `cuMemImportFromShareableHandle` calls, each of which is taking 30-40ms. 

Am I missing something obvious? I have tried different configurations -- both devices handled by a single thread, one thread per device. I get the same result for both -- ~700ms latency.

**Comment by kiskra-nvidia** [comment]
Are you measuring the performance of the first `ncclSend`/`ncclRecv` invocation? Try to ignore that "warm-up" and measure the performance of 2nd/3rd/...100th. I'm guessing you're seeing the effects of `NCCL_RUNTIME_CONNECT`, which delays some of the initialization until the first use (you can try running with `NCCL_RUNTIME_CONNECT=0` to see if it makes a difference).

**Comment by goelayu** [comment]
@kiskra-nvidia I am trying to measure the latency of both send and recv (each process outputs its respective latency). 
I tried adding a few warmup iterations earlier and the latency went down slightly, but it is still 3-4 orders of magnitude more. 
`NCCL_RUNTIME_CONNECT=0` didn't change the result.

What is more interesting is that when I used `NCCL_P2P_LEVEL=LOC`, i.e., disable P2P, the logs output `NCCL INFO Channel 01 : 0[0] -> 1[1] via SHM/direct/direct`, and the e2e latency goes from 700 to 30ms. 

But when I set `NCCL_P2P_LEVEL=NVL`, the latency is back to 700ms. And the logs say `NCCL INFO Channel 00/1 : 0[0] -> 1[1] via P2P/CUMEM`. 

Shouldn't NVL be the faster one?

**Comment by AddyLaddy** [comment]
NCCL P2P always uses dynamic connection establishement, so you need to do one or more warmup loops before trying to measure the latency of the actual communications.
For example, the nccl-tests do 5 warmup loops before the measurement ones.

It is known that he cuMem APIs for exporting and importing memory handles are expensive, but they are only done once during initial P2P connection establishment.

**Comment by kiskra-nvidia** [comment]
Can you post a complete source so that we can try it out?

**Comment by goelayu** [comment]
Thanks for the prompt responses. 

Here is the script.
```
#include <iostream>
#include <mpi.h>
#include <nccl.h>
#include <cuda_runtime.h>
#include <chrono>

#define CUDA_CHECK(cmd) do { \
    cudaError_t e = cmd; \
    if (e != cudaSuccess) { \
        printf("Failed: Cuda error %s:%d '%s'\n", __FILE__, __LINE__, cudaGetErrorString(e)); \
        exit(EXIT_FAILURE); \
    } \
} while(0)

#define NCCL_CHECK(cmd) do { \
    ncclResult_t r = cmd; \
    if (r != ncclSuccess) { \
        printf("Failed: NCCL error %s:%d '%s'\n", __FILE__, __LINE__, ncclGetErrorString(r)); \
        exit(EXIT_FAILURE); \
    } \
} while(0)

int main(int argc, char* argv[]) {
    MPI_Init(&argc, &argv);

    int rank, size_c;
    MPI_Comm_rank(MPI_COMM_WORLD, &rank);
    MPI_Comm_size(MPI_COMM_WORLD, &size_c);

    if (size_c != 2) {
        std::cerr << "This example requires exactly 2 processes." << std::endl;
        MPI_Finalize();
        return -1;
    }

    // Select GPU based on rank
    CUDA_CHECK(cudaSetDevice(rank));

    ncclComm_t comm;
    ncclUniqueId id;

    if (rank == 0) {
        int canAccessPeer;
        CUDA_CHECK(cudaDeviceCanAccessPeer(&canAccessPeer, 0, 1));
        if (canAccessPeer) {
            CUDA_CHECK(cudaDeviceEnablePeerAccess(1, 0));
        }
    } else if (rank == 1) {
        int canAccessPeer;
        CUDA_CHECK(cudaDeviceCanAccessPeer(&canAccessPeer, 1, 0));
        if (canAccessPeer) {
            CUDA_CHECK(cudaDeviceEnablePeerAccess(0, 0));
        }
    }

    // Rank 0 generates a unique NCCL ID and shares it with rank 1 via MPI
    if (rank == 0) {
        NCCL_CHECK(ncclGetUniqueId(&id));
        MPI_Send(&id, sizeof(id), MPI_BYTE, 1, 0, MPI_COMM_WORLD);
    } else {
        MPI_Recv(&id, sizeof(id), MPI_BYTE, 0, 0, MPI_COMM_WORLD, MPI_STATUS_IGNORE);
    }

    // Create NCCL communicator
    NCCL_CHECK(ncclCommInitRank(&comm, 2, id, rank));

    // Allocate memory on the GPU
    float* sendBuff;
    float* recvBuff;
    size_t size = 1000;
    size_t bytes = size * sizeof(float);
    CUDA_CHECK(cudaMalloc(&sendBuff, bytes));
    CUDA_CHECK(cudaMalloc(&recvBuff, bytes));

    // perform send and recv and measure time
    auto start = std::chrono::high_resolution_clock::now();
    NCCL_CHECK(ncclGroupStart());
    if (rank == 0) {
        NCCL_CHECK(ncclSend(sendBuff, bytes, ncclFloat, 1, comm, 0));
    } else if (rank == 1) {
        NCCL_CHECK(ncclRecv(recvBuff, bytes, ncclFloat, 0, comm, 0));
    }
    NCCL_CHECK(ncclGroupEnd());

    auto end = std::chrono::high_resolution_clock::now();
    auto ms = std::chrono::duration_cast<std::chrono::milliseconds>(end - start).count();
    std::cout << "Time taken: " << ms << " ms" << std::endl;

    // Clean up
    CUDA_CHECK(cudaFree(sendBuff));
    CUDA_CHECK(cudaFree(recvBuff));
    NCCL_CHECK(ncclCommDestroy(comm));

    MPI_Finalize();
    return 0;
}
```

**Comment by kiskra-nvidia** [comment]
After making the following changes to your code:

```
$ diff -up sr.cc.orig sr.cc
--- sr.cc.orig  2024-10-18 13:31:39.217171891 -0700
+++ sr.cc       2024-10-18 13:32:17.796809164 -0700
@@ -72,6 +72,7 @@ int main(int argc, char* argv[]) {
     CUDA_CHECK(cudaMalloc(&sendBuff, bytes));
     CUDA_CHECK(cudaMalloc(&recvBuff, bytes));
 
+    for (int i = 0; i < 10; i++) {
     // perform send and recv and measure time
     auto start = std::chrono::high_resolution_clock::now();
     if (rank == 0) {
@@ -81,8 +82,9 @@ int main(int argc, char* argv[]) {
     }
 
     auto end = std::chrono::high_resolution_clock::now();
-    auto ms = std::chrono::duration_cast<std::chrono::milliseconds>(end - start).count();
-    std::cout << "Time taken: " << ms << " ms" << std::endl;
+    auto us = std::chrono::duration_cast<std::chrono::microseconds>(end - start).count();
+    std::cout << "Rank " << rank << " time taken: " << us << " us" << std::endl;
+    }
 
     // Clean up
     CUDA_CHECK(cudaFree(sendBuff));
```

this is the performance I get on a DGX H100 box:

```
Rank 0 time taken: 214477 us
Rank 0 time taken: 14 us
Rank 0 time taken: 5 us
Rank 0 time taken: 3 us
Rank 0 time taken: 4 us
Rank 0 time taken: 5 us
Rank 0 time taken: 4 us
Rank 0 time taken: 4 us
Rank 0 time taken: 4 us
Rank 0 time taken: 4 us
Rank 1 time taken: 214601 us
Rank 1 time taken: 14 us
Rank 1 time taken: 5 us
Rank 1 time taken: 4 us
Rank 1 time taken: 4 us
Rank 1 time taken: 4 us
Rank 1 time taken: 5 us
Rank 1 time taken: 5 us
Rank 1 time taken: 5 us
Rank 1 time taken: 4 us
```

I hope this helps!

**Comment by goelayu** [comment]
Ah, thanks! My warm up code wasn't working as expected. 

As a side note, for some reason with `nccl-tests`, when I remove the warm up iterations `-w 0`, it still only takes 2ms, but in my benchmark this number was 700ms. Strange.

**Comment by goelayu** [comment]
Btw as a separate thought, I wonder if it is worth investigating the incredibly high latency of the very first invocation. I can imagine that in a lot of cases, it would be hard to eliminate this warm up cost from the critical path of your application.

**Comment by kiskra-nvidia** [comment]
I believe it's due to NVLink SHARP support, which was introduced with Hopper. You can try experimenting with `NCCL_NVLS_ENABLE=0`... On an 8xA100 system the first iteration is 10x shorter (but the subsequent ones are 2-4x longer -- you win some, you lose some...). We were initially seeing significantly longer execution times of `ncclCommInitRank` on Hopper as well, until we optimized our topology discovery code to collect partial results on each rank in parallel, followed by an intra-node allgather (see https://developer.nvidia.com/blog/memory-efficiency-faster-initialization-and-cost-estimation-with-nvidia-collective-communications-library-2-22/).

**Comment by goelayu** [comment]
@kiskra-nvidia `NCCL_NVLS_ENABLE=0` didn't change the latency for the first iteration for me. `NCCL_P2P_LEVEL=LOC` did reduce the latency of the first iteration significantly though (700ms --> 200ms).
