### ISSUE TITLE
nvlsAllocateMem report error

### ISSUE THREAD

**Issue by shanleo2024** [NVIDIA/nccl#1488]
Hi, Dear developer,

I run the nccl_test on h100 with nvswitch, nvlsAllocateMem report error as follows:
node23:12098:12141 [2] transport/nvls.cc:244 NCCL WARN Cuda failure 1 'invalid argument'
```
node23:12098:12141 [2] NCCL INFO transport/nvls.cc:394 -> 1
node23:12098:12141 [2] NCCL INFO init.cc:1196 -> 1
node23:12098:12141 [2] NCCL INFO init.cc:1462 -> 1
node23:12098:12141 [2] NCCL INFO group.cc:75 -> 1 [Async thread]
```

Did I miss some configuration?

**Comment by shanleo2024** [comment]
The root cause seems like if "systemctl start nvidia-fabricmanager.service" then "systemctl stop nvidia-fabricmanager.service", then "systemctl start nvidia-fabricmanager.service" again, the NCCL test will report this error, can solve this issue only reboot the system.

Seems it is not an issue, but can someone give me some hints if this is expected?
Thank you.

**Comment by AddyLaddy** [comment]
I believe you need to reset the GPU in-between if the FM is stopped and restarted.

See this documentation for the correct sequence:

https://docs.nvidia.com/datacenter/tesla/pdf/[fabric-manager-user-guide.pdf](https://docs.nvidia.com/datacenter/tesla/pdf/fabric-manager-user-guide.pdf#2.2)#2.2

**Comment by shanleo2024** [comment]
Thank you @AddyLaddy ,but the link is out of date, can you post the link again? thank you.

**Comment by shanleo2024** [comment]
Thank you @kiskra-nvidia , and I will notice the correct sequence, close this issue now.

**Comment by ziwon** [comment]
Same issue was here. After diving deep into every logs, wrestling with CUDA drivers and nccl configuration, restarting fabricmanager and resetting GPU memories, and sacrificing 10 cups of artisanal coffee to the GPU gods... turns out all the H100 needed was the old 'turn it off and on again.' classic. Thank you.

**Comment by kiskra-nvidia** [comment]
You're welcome 😃. FYI, I just edited my earlier comment, updating the section number to match the current version of the document (October 23, 2024).
