### ISSUE TITLE
Question about ncclTopoConnectNodes in topo.cc

### ISSUE THREAD

**Issue by JK-Jiagn** [NVIDIA/nccl#1498]
Hello! I have a question about the code of ```ncclTopoConnectNodes``` in the ```topo.cc``` file.

Location (Line 168) : ```if (link->remNode == NULL) node->nlinks++;```
![Image](https://github.com/user-attachments/assets/e012a45b-4b03-4697-918c-2f3c416f58eb)

Will this statement be executed? 
- If the loop statement at line 161 exits with a ```break```, then ```link->remNode``` will be ```remNode``` and not be ```NULL```. 
- Whereas if the loop statement executes until the condition ```link - node->links != NCCL_TOPO_MAX_LINKS``` is no longer met, then the if statement at line 164 will be executed, and this function will return at line 166.

It seems that the statement at line 168 will not be executed, unless we set input arg ```remNode``` to ```NULL```.

**Comment by kiskra-nvidia** [comment]
I'm not sure if I understand the problem. There is also the `&& link->remNode` condition at line 161. So the loop should also exit if `link->remNode == nullptr`, no?

**Comment by JK-Jiagn** [comment]
> I'm not sure if I understand the problem. There is also the `&& link->remNode` condition at line 161. So the loop should also exit if `link->remNode == nullptr`, no?

Oh, you're right, I'm sorry I ignored this condition.
