### ISSUE TITLE
/bin/sh: 1: debuild: not found, make: *** [pkg.debian.build] Error 2

### ISSUE THREAD

**Issue by forhonourlx** [NVIDIA/nccl#150]
Hi,
I was trying to install on Ubuntu18.04.1, CUDA10，the following error is raised:

make -C pkg debian.build BUILDDIR=/home/simon/Downloads/nccl/build
make[1]: enter“/home/simon/Downloads/nccl/pkg”
make -C debian build BUILDDIR=/home/simon/Downloads/nccl/build
make[2]: enter“/home/simon/Downloads/nccl/pkg/debian”
make[3]: enter“/home/simon/Downloads/nccl”
make[4]: enter“/home/simon/Downloads/nccl/src”
make[5]: enter“/home/simon/Downloads/nccl/src/collectives/device”
make[5]: enter“/home/simon/Downloads/nccl/src/collectives/device”
Linking    libnccl.so.2.3.7                    > /home/simon/Downloads/nccl/build/lib/libnccl.so.2.3.7
Archiving  libnccl_static.a                    > /home/simon/Downloads/nccl/build/lib/libnccl_static.a
/home/simon/Downloads/nccl/src
make[4]: exit“/home/simon/Downloads/nccl/src”
make[3]: exit“/home/simon/Downloads/nccl”
Building Debian package
/bin/sh: 1: debuild: not found
Makefile:31: recipe for target 'build' failed
make[2]: *** [build] Error 127
make[2]: exit“/home/simon/Downloads/nccl/pkg/debian”
Makefile:23: recipe for target 'debian.build' failed
make[1]: *** [debian.build] Error 2
make[1]: exit“/home/simon/Downloads/nccl/pkg”
Makefile:27: recipe for target 'pkg.debian.build' failed
make: *** [pkg.debian.build] Error 2

**Comment by sjeaugey** [comment]
Would those extra-instructions work for you ?

https://github.com/NVIDIA/nccl/tree/sjeaugey-pkg-doc#install

```shell
$ # Install tools to create debian packages
$ sudo apt install build-essential devscripts debhelper
$ # Build NCCL deb package
$ make pkg.debian.build
$ ls build/pkg/deb/
```

**Comment by forhonourlx** [comment]
Thank you indeed. It does work.
Suggest that put these requirements in the readme installation instructions.
Please close this issue.

make -C pkg debian.build BUILDDIR=/home/simon/Downloads/nccl/build
make[1]: 进入目录“/home/simon/Downloads/nccl/pkg”
make -C debian build BUILDDIR=/home/simon/Downloads/nccl/build
make[2]: 进入目录“/home/simon/Downloads/nccl/pkg/debian”
make[3]: 进入目录“/home/simon/Downloads/nccl”
make[4]: 进入目录“/home/simon/Downloads/nccl/src”
make[5]: 进入目录“/home/simon/Downloads/nccl/src/collectives/device”
make[5]: 离开目录“/home/simon/Downloads/nccl/src/collectives/device”
Linking    libnccl.so.2.3.7                    > /home/simon/Downloads/nccl/build/lib/libnccl.so.2.3.7
Archiving  libnccl_static.a                    > /home/simon/Downloads/nccl/build/lib/libnccl_static.a
/home/simon/Downloads/nccl/src
make[4]: 离开目录“/home/simon/Downloads/nccl/src”
make[3]: 离开目录“/home/simon/Downloads/nccl”
Building Debian package
 dpkg-buildpackage -rfakeroot -us -uc -ui -d -b
dpkg-buildpackage: info: 源码包 nccl
dpkg-buildpackage: info: 源码版本 2.3.7-1+cuda10.0
dpkg-buildpackage: info: source distribution trusty
dpkg-buildpackage: info: 源码修改者 cudatools <cudatools@nvidia.com>
 dpkg-source --before-build build
dpkg-buildpackage: info: 主机架构 amd64
 fakeroot debian/rules clean
dh clean --parallel
   debian/rules override_dh_auto_clean
make[1]: 进入目录“/home/simon/Downloads/nccl/build”
# Do not make clean
make[1]: 离开目录“/home/simon/Downloads/nccl/build”
   dh_clean -O--parallel
 debian/rules build
dh build --parallel
   dh_update_autotools_config -O--parallel
   debian/rules override_dh_auto_test
make[1]: 进入目录“/home/simon/Downloads/nccl/build”
# Do not make test
make[1]: 离开目录“/home/simon/Downloads/nccl/build”
 fakeroot debian/rules binary
dh binary --parallel
   dh_testroot -O--parallel
   dh_prep -O--parallel
   debian/rules override_dh_auto_install
make[1]: 进入目录“/home/simon/Downloads/nccl/build”
PREFIX=debian/tmp dh_auto_install
make[1]: 离开目录“/home/simon/Downloads/nccl/build”
   dh_install -O--parallel
   dh_installdocs -O--parallel
   dh_installchangelogs -O--parallel
   dh_perl -O--parallel
   dh_link -O--parallel
   dh_strip_nondeterminism -O--parallel
   dh_compress -O--parallel
   dh_fixperms -O--parallel
   dh_missing -O--parallel
   dh_strip -O--parallel
   dh_makeshlibs -O--parallel
   dh_shlibdeps -O--parallel
dpkg-shlibdeps: 警告: symbol pthread_mutexattr_setpshared used by debian/libnccl2/usr/lib/x86_64-linux-gnu/libnccl.so.2.3.7 found in none of the libraries
dpkg-shlibdeps: 警告: symbol pthread_yield used by debian/libnccl2/usr/lib/x86_64-linux-gnu/libnccl.so.2.3.7 found in none of the libraries
dpkg-shlibdeps: 警告: symbol pthread_detach used by debian/libnccl2/usr/lib/x86_64-linux-gnu/libnccl.so.2.3.7 found in none of the libraries
dpkg-shlibdeps: 警告: symbol pthread_join used by debian/libnccl2/usr/lib/x86_64-linux-gnu/libnccl.so.2.3.7 found in none of the libraries
dpkg-shlibdeps: 警告: symbol dlerror used by debian/libnccl2/usr/lib/x86_64-linux-gnu/libnccl.so.2.3.7 found in none of the libraries
dpkg-shlibdeps: 警告: symbol pthread_mutexattr_destroy used by debian/libnccl2/usr/lib/x86_64-linux-gnu/libnccl.so.2.3.7 found in none of the libraries
dpkg-shlibdeps: 警告: symbol pthread_once used by debian/libnccl2/usr/lib/x86_64-linux-gnu/libnccl.so.2.3.7 found in none of the libraries
dpkg-shlibdeps: 警告: symbol sem_timedwait used by debian/libnccl2/usr/lib/x86_64-linux-gnu/libnccl.so.2.3.7 found in none of the libraries
dpkg-shlibdeps: 警告: symbol pthread_rwlock_trywrlock used by debian/libnccl2/usr/lib/x86_64-linux-gnu/libnccl.so.2.3.7 found in none of the libraries
dpkg-shlibdeps: 警告: symbol pthread_rwlock_tryrdlock used by debian/libnccl2/usr/lib/x86_64-linux-gnu/libnccl.so.2.3.7 found in none of the libraries
dpkg-shlibdeps: 警告: 28 other similar warnings have been skipped (use -v to see them all)
dpkg-shlibdeps: 警告: package could avoid a useless dependency if debian/libnccl2/usr/lib/x86_64-linux-gnu/libnccl.so.2.3.7 was not linked against libstdc++.so.6 (it uses none of the library's symbols)
dpkg-shlibdeps: 警告: package could avoid a useless dependency if debian/libnccl2/usr/lib/x86_64-linux-gnu/libnccl.so.2.3.7 was not linked against libgcc_s.so.1 (it uses none of the library's symbols)
   dh_installdeb -O--parallel
   dh_gencontrol -O--parallel
dpkg-gencontrol: 警告: Depends field of package libnccl-dev: 未知的替换变量 ${shlibs:Depends}
   dh_md5sums -O--parallel
   dh_builddeb -O--parallel
dpkg-deb: 正在 '../libnccl2_2.3.7-1+cuda10.0_amd64.deb' 中构建软件包 'libnccl2'。
dpkg-deb: 正在 '../libnccl-dev_2.3.7-1+cuda10.0_amd64.deb' 中构建软件包 'libnccl-dev'。
dpkg-deb: 正在 'debian/.debhelper/scratch-space/build-libnccl2/libnccl2-dbgsym_2.3.7-1+cuda10.0_amd64.deb' 中构建软件包 'libnccl2-dbgsym'。
	Renaming libnccl2-dbgsym_2.3.7-1+cuda10.0_amd64.deb to libnccl2-dbgsym_2.3.7-1+cuda10.0_amd64.ddeb
 dpkg-genbuildinfo --build=binary
 dpkg-genchanges --build=binary >../nccl_2.3.7-1+cuda10.0_amd64.changes
dpkg-genchanges: info: binary-only upload (no source code included)
 dpkg-source --after-build build
dpkg-buildpackage: info: binary-only upload (no source included)
Now running lintian nccl_2.3.7-1+cuda10.0_amd64.changes ...
Finished running lintian.
make[2]: 离开目录“/home/simon/Downloads/nccl/pkg/debian”
make[1]: 离开目录“/home/simon/Downloads/nccl/pkg”

**Comment by sjeaugey** [comment]
OK, merging PR #151 then.
