### ISSUE TITLE
Potential host memory leak on NCCL 2.23

### ISSUE THREAD

**Issue by PatriosTheGreat** [NVIDIA/nccl#1534]
Hi NCCL team.

We noticed a potential memory leak over the time when the same communicators are used for multiple collective operations.
We put together a following reproducible, which basically does an ncclReduce calls over 2 local GPUs in a single thread in an infinite loop:

```
  // Allocate host memory 
  const int data_size = 8;
  std::vector<double> host_data(data_size);
  for (int i = 0; i < data_size; i++) host_data[i] = 1;

  int num_local_devices = 2;
  // Array of pointers to the memory of each device
  std::vector<double *> devices_data(num_local_devices);

  // Allocate device memory
  for (int device = 0; device < num_local_devices; device++) {
    cudaSetDevice(device);
    cudaMalloc(&devices_data[device], data_size * sizeof(double));
    cudaMemcpy(devices_data[device], host_data.data(),
               data_size * sizeof(double), cudaMemcpyHostToDevice);
  }

  /*-----Initialize NCCL communicators-----*/
  std::vector<ncclComm_t> communicators(num_local_devices);
  ncclCommInitAll(communicators.data(), num_local_devices, /*devlist=*/nullptr);

  /*-----Initialize CUDA Streams-----*/
  std::vector<cudaStream_t> streams(num_local_devices);
  for (int device = 0; device < num_local_devices; device++) {
    cudaSetDevice(device);
    cudaStreamCreate(&streams[device]);
  }

  const int root_gpu = 0;

  while (true) {
    ncclGroupStart();
    for (int device = 0; device < num_local_devices; device++) {
      cudaSetDevice(device);

      ncclReduce(
          devices_data[device],
          devices_data[device], data_size, ncclDouble, ncclSum,
          root_gpu,
          communicators[device], streams[device]);
    }

    ncclGroupEnd();

    // Synchronize CUDA Streams
    for (int device = 0; device < num_local_devices; device++) {
      cudaSetDevice(device);
      cudaStreamSynchronize(streams[device]);
    }
  }
```

This code over the time consumes more and more host memory leading to the OOM at the end.
When we ran this code with `NCCL_DEBUG=INFO NCCL_DEBUG_SUBSYS=ALLOC` we got the following logs:
...
[0] NCCL INFO nccl/src/misc/utils.cc:233 memory stack hunk malloc(26345472)
[1] NCCL INFO nccl/src/misc/utils.cc:233 memory stack hunk malloc(26345472)
[0] NCCL INFO nccl/src/misc/utils.cc:233 memory stack hunk malloc(26411008)
[1] NCCL INFO nccl/src/misc/utils.cc:233 memory stack hunk malloc(26411008)
...

And these allocations increasing over the time (https://github.com/NVIDIA/nccl/blob/master/src/misc/utils.cc#L233)
We also checked a stack trace of these allocations and found that it happens only when  comm->memPermanent is used (in this line: https://github.com/NVIDIA/nccl/blob/master/src/enqueue.cc#L2271)

We tried to replace this line to use comm->memScoped:
struct ncclTaskColl* t = ncclMemoryPoolAlloc<struct ncclTaskColl>(&comm->memPool_ncclTaskColl, &comm->memScoped);

And this fixed the leak we observe.

So my questions here are:
What might be proper fix here? Is this save to replace the comm->memPermanent by the comm->memScoped here?
Or are we misusing a NCCL API here?

**Comment by gcongiu** [comment]
I think this bug might have been already fixed. If so, the fix should be in the next release. I need to confirm this.

**Comment by gcongiu** [comment]
Yes, the bug was fixed and the fix should be in the release after the next

**Comment by PatriosTheGreat** [comment]
Thanks Giuseppe for a response!

Is it possible to share a fix so we can patch this locally until the next version will be released?

**Comment by gcongiu** [comment]
[nccl_v2.23_profiler_memleak.patch](https://github.com/user-attachments/files/18047899/nccl_v2.23_profiler_memleak.patch)

**Comment by PatriosTheGreat** [comment]
I checked the patch and it fixes a leak.
Many thanks Giuseppe!
