### ISSUE TITLE
Explicit support for comments in nccl.conf

### ISSUE THREAD

**Issue by sclarkson** [NVIDIA/nccl#1540]
I'm a little reluctant to add comments to my `nccl.conf` files in case there are changes to  the parser later and it breaks them. Currently any line without an `=` is effectively skipped. A simple `if (line[0] == '#') continue;` would inspire confidence that this won't break in the future.

**Comment by sjeaugey** [comment]
That's a very legitimate ask. Let's fix that.

**Comment by sjeaugey** [comment]
Done in 2.26.

**Comment by sclarkson** [comment]
Thank you
