### ISSUE TITLE
Mesos containerizer does not isolate UTS namespace

### ISSUE THREAD

**Issue by alsrgv** [NVIDIA/nccl#155]
Hi folks,

Mesos containerizer [does not have](https://issues.apache.org/jira/browse/MESOS-7605) native support for isolating UTS namespace.

Because of that, NCCL always assumes that different containers running on the same host are able to do P2P and SHM to each other: [code1](https://github.com/NVIDIA/nccl/blob/b56650c7f59b8cd40d18809784a6d6be38ef8acb/src/misc/utils.cu#L38), [code2](https://github.com/NVIDIA/nccl/blob/f93fe9bfd94884cec2ba711897222e0df5569a53/src/transport/shm.cu#L72).

Do you think it'd be reasonable to extend getHostHash() to include other isolation namespaces, e.g. `/proc/self/ns/mnt`?

**Comment by alsrgv** [comment]
@AddyLaddy, I'm thinking it may make sense to throw in all `/proc/self/ns/*` in the hash, making it equivalent to `echo $(hostname) $(readlink /proc/self/ns/*)`.

This way, we're making sure that `getHostHash()` always identifies a container with any degree of isolation.

It's possible (but not very likely) that somebody would want to run SHM/P2P over containers.  It would not work with Docker even today which is a common use case since Docker provides UTS isolation, so I suggest if anybody comes with requirements like that, an additional opt-in flag could be added later.

If this sounds fine, I can submit a PR.

**Comment by AddyLaddy** [comment]
Thanks for the feedback Alex! That sounds good to us. If you have the time, please feel free to make a PR and we can review it.
