### ISSUE TITLE
ptrSupport is a function pointer being used before assignment

### ISSUE THREAD

**Issue by egg-west** [NVIDIA/nccl#159]
`ptrSupport` is a function pointer in `nccl_net.h`, But I did not find any assignment of `ptrSupport` before it being used in `net.h` line: 23.

I may misunderstand somewhere.

**Comment by sjeaugey** [comment]
ncclNet is initialized here : https://github.com/NVIDIA/nccl/blob/master/src/init.cu#L72-L79

It is supposed to be set to ncclNetSocket (https://github.com/NVIDIA/nccl/blob/master/src/transport/net_socket.cu#L224) or ncclNetIb (https://github.com/NVIDIA/nccl/blob/master/src/transport/net_ib.cu#L904) and should therefore be equal to one of the two functions.

**Comment by egg-west** [comment]
Thanks for your clear answer.
