### ISSUE TITLE
Use of uninitialised value of size 8

### ISSUE THREAD

**Issue by nwestlake** [NVIDIA/nccl#160]
I received many errors similar to the following:
    ==29308== Use of uninitialised value of size 8
    ==29308==    at 0x4E6C623: tolower (ctype.c:46)
    ==29308==    by 0x5E61F43B: getCudaPath(int, char**) (in /usr/local/lib/python3.6/dist-packages/tensorflow/python/_pywrap_tensorflow_internal.so)
    ==29308==    by 0x5E620BFE: p2pCanConnect(long*, char (*) [64], char (*) [64]) (in /usr/local/lib/python3.6/dist-packages/tensorflow/python/_pywrap_tensorflow_internal.so)
    ==29308==    by 0x5E5ED402: fillConnect(ncclInfo*, int, int, int*, long*) (in /usr/local/lib/python3.6/dist-packages/tensorflow/python/_pywrap_tensorflow_internal.so)
    ==29308==    by 0x5E5F548D: ncclCommInitAll (in /usr/local/lib/python3.6/dist-packages/tensorflow/python/_pywrap_tensorflow_internal.so)
    ==29308==    by 0x5E5DDE42: tensorflow::NcclManager::GetCommunicator(tensorflow::NcclManager::Collective*) (in /usr/local/lib/python3.6/dist-packages/tensorflow/python/_pywrap_tensorflow_internal.so)
    ==29308==    by 0x5E5DE751: tensorflow::NcclManager::RunCollective(std::string const&, tensorflow::NcclManager::Collective*) (in /usr/local/lib/python3.6/dist-packages/tensorflow/python/_pywrap_tensorflow_internal.so)
    ==29308==    by 0x5E5DEB24: tensorflow::NcclManager::AddParticipant(int, std::string const&, std::unique_ptr<tensorflow::NcclManager::Participant, std::default_delete<tensorflow::NcclManager::Participant> >, tensorflow::DataType, tensorflow::NcclManager::CollectiveType, ncclRedOp_t) (in /usr/local/lib/python3.6/dist-packages/tensorflow/python/_pywrap_tensorflow_internal.so)
    ==29308==    by 0x5E5DEFC1: tensorflow::NcclManager::AddToAllReduce(int, std::string const&, ncclRedOp_t, stream_executor::StreamExecutor*, int, tensorflow::EventMgr*, stream_executor::Stream*, tensorflow::Tensor const*, tensorflow::Tensor*, std::function<void (tensorflow::Status)> const&) (in /usr/local/lib/python3.6/dist-packages/tensorflow/python/_pywrap_tensorflow_internal.so)
    ==29308==    by 0x5E5D9B17: tensorflow::(anonymous namespace)::NcclAllReduceOpKernel::ComputeAsync(tensorflow::OpKernelContext*, std::function<void ()>) (in /usr/local/lib/python3.6/dist-packages/tensorflow/python/_pywrap_tensorflow_internal.so)
    ==29308==    by 0x3ED3F933: tensorflow::BaseGPUDevice::ComputeAsync(tensorflow::AsyncOpKernel*, tensorflow::OpKernelContext*, std::function<void ()>) (in /usr/local/lib/python3.6/dist-packages/tensorflow/libtensorflow_framework.so)
    ==29308==    by 0x3ED8BB1C: tensorflow::(anonymous namespace)::ExecutorState::Process(tensorflow::(anonymous namespace)::ExecutorState::TaggedNode, long long) (in /usr/local/lib/python3.6/dist-packages/tensorflow/libtensorflow_framework.so)
    ==29308==  Uninitialised value was created by a stack allocation
    ==29308==    at 0x5E61F2E4: getCudaPath(int, char**) (in /usr/local/lib/python3.6/dist-packages/tensorflow/python/_pywrap_tensorflow_internal.so)

It appears to me to relate to [include/topo.h](https://github.com/NVIDIA/nccl/blob/master/src/include/topo.h). I note that cudaDeviceGetPCIBusId "pciBusId should be large enough to store 13 characters including the NULL-terminator. ", but there is no check in the loop for the null-terminator in the line

 for (int i=0; i<16; i++) busId[i] = tolower(busId[i]);

**Comment by sjeaugey** [comment]
Can you try to apply this patch and see if it makes the warning disappear ?
```
diff --git a/src/include/topo.h b/src/include/topo.h
index 971ae68..e824a81 100644
--- a/src/include/topo.h
+++ b/src/include/topo.h
@@ -12,13 +12,16 @@
 #include <stdlib.h>
 #include <ctype.h>
 
+#define BUSID_SIZE (sizeof("0000:00:00.0"))
+#define BUSID_REDUCED_SIZE (sizeof("0000:00"))
+
 static ncclResult_t getCudaPath(int cudaDev, char** path) {
-  char busId[16];
-  CUDACHECK(cudaDeviceGetPCIBusId(busId, 16, cudaDev));
-  for (int i=0; i<16; i++) busId[i] = tolower(busId[i]);
+  char busId[BUSID_SIZE];
+  CUDACHECK(cudaDeviceGetPCIBusId(busId, BUSID_SIZE, cudaDev));
+  for (int i=0; i<BUSID_SIZE; i++) busId[i] = tolower(busId[i]);
   char busPath[] = "/sys/class/pci_bus/0000:00/../../0000:00:00.0";
-  memcpy(busPath+sizeof("/sys/class/pci_bus/")-1, busId, sizeof("0000:00")-1);
-  memcpy(busPath+sizeof("/sys/class/pci_bus/0000:00/../../")-1, busId, sizeof("0000:00:00.0")-1);
+  memcpy(busPath+sizeof("/sys/class/pci_bus/")-1, busId, BUSID_REDUCED_SIZE-1);
+  memcpy(busPath+sizeof("/sys/class/pci_bus/0000:00/../../")-1, busId, BUSID_SIZE-1);
   *path = realpath(busPath, NULL);
   if (*path == NULL) {
     WARN("Could not find real path of %s", busPath);
```

**Comment by nwestlake** [comment]
Many thanks for the quick reply. This looks like an excellent fix. While I managed to reinstall the libnccl library with the patch, it appears that tensorflow has a the function statically compiled rather than using libnccl.so so I cannot test. I have also been unsuccessful in compiling tensorflow myself.


However, I tested with a small program and the error does indeed disappear:
    #include <assert.h>
    
    #include "src/include/core.h"
    #include "src/include/topo.h"
    
    int main(int argc, char** argv)
    {
      char* str;
      ncclResult_t result(getCudaPath(0, &str));
    
      assert(result == 0);
    
      return 0;
    }

**Comment by sjeaugey** [comment]
Oops, I referenced the PR instead of the issue. Closing anyway.
