### ISSUE TITLE
Compilation fails with CUDA 8.0: init.cu(165): error: identifier "NCCL_VERSION_CODE" is undefined

### ISSUE THREAD

**Issue by emjotde** [NVIDIA/nccl#166]
Hi,
compilation from source fails with CUDA 8.0 with the following error:
```
init.cu(165): error: identifier "NCCL_VERSION_CODE" is undefined
```

Works fine with 9.2 and 10.0.

**Comment by sjeaugey** [comment]
Could it be you have an old nccl.h in /usr/local/cuda-8.0/include/ ?

**Comment by emjotde** [comment]
Yes, good catch. I am wondering how I can convince make to use the local header in such a situation. I assume many of my users might have the same situation. The includes in the nccl source already use quotes `#include "nccl.h"` , not `<nccl.h>`, so that should be local.

**Comment by sjeaugey** [comment]
Seems like it's due to the Makefile adding -I $(CUDA_INC). Maybe we can remove that.

**Comment by sjeaugey** [comment]
This include has been removed from the Makefile so it should be fixed now. Closing.
