### ISSUE TITLE
Gefore 1080Ti's NCCL performance is very bad since GPU-P2P can't be enabled in the VM

### ISSUE THREAD

**Issue by thincal** [NVIDIA/nccl#175]
Hi,

We have created a virtual machine based on QEMU to pass through the GPU to VM correctly, and also create the PCI capability to let the GPU driver in VM know the GPU topology.

In such a setup, we find that the GPU-P2P could be enabled for the Tesla serial GPU but can't be enabled for the Gefore 1080Ti, which reports that the chipset not supported.

Do someone have some insight with this ? These GPUs are just used for study and education.

Thanks,
Song

**Comment by sjeaugey** [comment]
Can you explain what precisely tells you that "GPU-P2P can't be enabled for the Geforce 1080Ti, which reports that the chipset not supported".

I'm trying to figure out whether it is CUDA or NCCL not letting you use P2P.

**Comment by thincal** [comment]
It seems like its the cuda driver, since the nvidia-smi show the p2p topo as the chipset not surported.

**Comment by thincal** [comment]
@sjeaugey any idea about the p2p enabling in cuda driver？

**Comment by sjeaugey** [comment]
Not really. That would be a question to ask to CUDA support.

**Comment by sjeaugey** [comment]
Closing as this is a not a NCCL bug.
