### ISSUE TITLE
NCCL_SOCKET_IFNAME prefix match ?

### ISSUE THREAD

**Issue by zrss** [NVIDIA/nccl#177]
er, hello, i encounter a case that i have a node with three NIC

```
bond0: flags=5187<UP,BROADCAST,RUNNING,MASTER,MULTICAST>  mtu 8888
        inet 192.168.42.7  netmask 255.255.255.224  broadcast 192.168.42.31
        inet6 fe80::f816:3eff:feff:5ca1  prefixlen 64  scopeid 0x20<link>
        ether fa:16:3e:ff:5c:a1  txqueuelen 1000  (Ethernet)
        RX packets 849354998  bytes 1077773855404 (1003.7 GiB)
        RX errors 0  dropped 2645  overruns 0  frame 0
        TX packets 727482315  bytes 1097474068380 (1022.1 GiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

bond0.2973: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 10.0.106.189  netmask 255.255.0.0  broadcast 10.0.255.255
        inet6 fe80::f816:3eff:fe5d:8ecb  prefixlen 64  scopeid 0x20<link>
        ether fa:16:3e:5d:8e:cb  txqueuelen 1000  (Ethernet)
        RX packets 102800  bytes 11179497 (10.6 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 102675  bytes 11889256 (11.3 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

bond0.2973.1: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1496
        inet6 fe80::f816:3eff:fe5d:8ecb  prefixlen 64  scopeid 0x20<link>
        ether fa:16:3e:5d:8e:cb  txqueuelen 1000  (Ethernet)
        RX packets 102639  bytes 10758943 (10.2 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 102525  bytes 11468326 (10.9 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```

and i want to select the `bond0`, how can i do it with `NCCL_SOCKET_IFNAME`

thx so much

**Comment by wangxicoding** [comment]
try NCCL_SOCKET_IFNAME=^bond0.2973

**Comment by sjeaugey** [comment]
Indeed `NCCL_SOCKET_IFNAME=^bond0.209` should work in that case.

We might want to improve that mechanism in the future (both for `NCCL_SOCKET_IFNAME` and `NCCL_IB_HCA`) to avoid prefix collision.

**Comment by zrss** [comment]
thx for the reply.

I get the idea about `^` exclude. And i found another env i.e. `NCCL_SOCKET_FAMILY` in the master branch of nccl code but i can't see it in docs, and this env can specific `socket_family`

and i confirm my nccl version is `NCCL version 2.2.12+cuda9.0`, but i can't find which tag or release in ncc repo that match my version

does anyone know the history ? or how can i find the code of `NCCL version 2.2.12+cuda9.0`

**Comment by zrss** [comment]
To clarify

NCCL docs [ENV](https://docs.nvidia.com/deeplearning/sdk/nccl-developer-guide/docs/env.html)

and my full story is, currently, i make my effort to run `horovod` with `openmpi` like this cmd

```
mpirun 
            -x LD_LIBRARY_PATH \
            -x NCCL_DEBUG=INFO -x NCCL_SOCKET_IFNAME=ib0,bond0,eth0 -x NCCL_SOCKET_FAMILY=AF_INET \
            -x NCCL_IB_DISABLE=0 \
            -x NCCL_IB_CUDA_SUPPORT=1  \
            -x HOROVOD_MPI_THREADS_DISABLE=1 \
```

and NCCL find three matched NIC as

* bond0
* bond0.2973
* bond0.2973.1

but `bond0.2973.1` is IPv6 address and can't be used for comm, so i expected NCCL can select bond0, bond0.2973 rather than bond0.2973.1 (ipv6)

**Comment by kwen2501** [comment]
NCCL was closed source at the time of 2.2.12, so this version does not exist on Github. 

But you may still use `NCCL_SOCKET_FAMILY` as you mentioned above with 2.2.12. This env existed earlier than 2.2.12.

It is indeed a bit weird that `bond0.2973.1` still gets picked. Do you mind posting the NCCL logs here?

**Comment by sjeaugey** [comment]
I'm not sure I understand why you would want to use both ib0 and other interfaces. Usually it is better to only use ib0, if functional. If not functional on all nodes then it should not be used at all.

In general you should only select the fastest interface. If using sockets (not IB verbs/RoCE), you can get better performance using multiple interfaces, if they end up on different network cards running at same speeds.

**Comment by zrss** [comment]
@sjeaugey , yes, as i try to cover these different types of machines

* vm
    * with a common network (as eth0)
* bare metal
    * with a highway network (such as bond0.2973) but i can't determine the name of the device. it named in the format `bond0.XXXX`, and with a IPv6 address NIC `bond0.XXXX.1`
    * with a IB. it named `ib0`

**Comment by zrss** [comment]
@kwen2501 , oh, i get it. I can upload some logs for viewing

**Comment by zrss** [comment]
thx @kwen2501 , currently i can make my job work with `NCCL_SOCKET_FAMILY=AF_INET` and `NCCL_SOCKET_IFNAME=ib0,bond0,eth0`

these are my logout of NCCL

```
NCCL version 2.2.12+cuda9.0
bms-k80-2:159:282 [0] INFO NET : Using interface bond0:192.168.60.159<0>
bms-k80-2:159:282 [0] INFO NET/IB : Using interface bond0 for sideband communication
bms-k80-2:159:282 [0] INFO Using internal Network Socket
bms-k80-2:159:282 [0] INFO Using NCCL Low-latency algorithm for sizes below 16384
bms-k80-2:160:281 [1] INFO comm 0x7fe4f0479740 rank 3 nranks 4
bms-k80-2:160:281 [1] INFO NET : Using interface bond0:192.168.60.159<0>
bms-k80-2:160:281 [1] INFO NET : Using interface bond0.1098:10.0.91.211<0>
bms-k80-2:160:281 [1] INFO NET/Socket : 2 interfaces found
bms-k80-1:153:274 [1] INFO comm 0x7f48f8492150 rank 1 nranks 4
bms-k80-1:153:274 [1] INFO NET : Using interface bond0:192.168.51.195<0>
bms-k80-1:153:274 [1] INFO NET : Using interface bond0.1098:10.0.146.97<0>
bms-k80-1:153:274 [1] INFO NET/Socket : 2 interfaces found
bms-k80-1:152:275 [0] INFO comm 0x7f5fc8357570 rank 0 nranks 4
bms-k80-2:159:282 [0] INFO comm 0x7f77084b8030 rank 2 nranks 4
bms-k80-2:159:282 [0] INFO NET : Using interface bond0:192.168.60.159<0>
bms-k80-2:159:282 [0] INFO NET : Using interface bond0.1098:10.0.91.211<0>
bms-k80-2:159:282 [0] INFO NET/Socket : 2 interfaces found
bms-k80-1:152:275 [0] INFO Using 128 threads
bms-k80-1:152:275 [0] INFO Min Comp Cap 3
bms-k80-1:152:275 [0] INFO NCCL_SINGLE_RING_THRESHOLD=131072
bms-k80-1:152:275 [0] INFO Ring 00 :    0   1   2   3
bms-k80-1:152:275 [0] INFO Ring 01 :    0   1   2   3
bms-k80-1:152:275 [0] INFO 3 -> 0 via NET/Socket/0
bms-k80-1:152:275 [0] INFO Ring 00 : 0[0] -> 1[1] via P2P/IPC
bms-k80-2:159:282 [0] INFO 1 -> 2 via NET/Socket/0
bms-k80-2:159:282 [0] INFO Ring 00 : 2[0] -> 3[1] via P2P/IPC
bms-k80-2:159:282 [0] INFO 1 -> 2 via NET/Socket/1
bms-k80-2:159:282 [0] INFO Ring 01 : 2[0] -> 3[1] via P2P/IPC
bms-k80-1:152:275 [0] INFO 3 -> 0 via NET/Socket/1
bms-k80-1:152:275 [0] INFO Ring 01 : 0[0] -> 1[1] via P2P/IPC
bms-k80-1:152:275 [0] INFO Launch mode Parallel
INFO:tensorflow:step: 0(global step: 0)	batch/sec: 0.067	ent_loss: 6.926	top-1: 0.000	top-5: 0.000	reg_loss: 2.680	total_loss: 9.609
```

**Comment by sjeaugey** [comment]
OK, so you want to select `bond.*` but not `bond.*.1`. Well at that point, it would become some significant complexity to implement that in NCCL.

I think you should just use a shell script which would look at the IP interfaces, match the pattern you want and set NCCL_SOCKET_IFNAME to that interface.

Something like :
`select_if.sh`
```
#!/bin/bash
netif=`<list IP interfaces and filter>`
NCCL_SOCKET_IFNAME=$netif $@
```
Then launch with :
```
mpirun <mpirun options without NCCL_SOCKET_IFNAME> select_if.sh <my program>
```

**Comment by zrss** [comment]
thx for the reply. it's a nice solution for my case 😎
