### ISSUE TITLE
include .pc (pkgconfig) file in the repo

### ISSUE THREAD

**Issue by sl1pkn07** [NVIDIA/nccl#186]
Hi

actually, the project lack the pkgconfig (.pc) file, usefull for do other project detect the library/includes for use in other projects

is possible add it?

greetings

**Comment by AddyLaddy** [comment]
Sure we could add one. Do you have an example for us to look at ?

**Comment by sl1pkn07** [comment]
@AddyLaddy  please test PR #188 

greetings

**Comment by sl1pkn07** [comment]
merged by #190 

greetings
