### ISSUE TITLE
Can create 2 ncclComm_t in one process with same GPU?

### ISSUE THREAD

**Issue by amazingyyc** [NVIDIA/nccl#206]
My scenario: I have 2 thread in every process, and want 2 thread can be communicate with other process's thread separately. So i want to create 2 ncclComm_t for 2 thread. Than each thread can only sync with the corresponding thread.This is my create ncclComm_t code,
```
ncclUniqueId nccl_id;
if (0 == local_rank) {
  NCCL_CHECK(entries, "ncclGetUniqueId", ncclGetUniqueId(&nccl_id));
}

MPI_CHECK(entries, "MPI_Bcast", MPI_Bcast((void*)&nccl_id, sizeof(nccl_id), MPI_BYTE, 0, global_state.local_comm));

NCCL_CHECK(entries, "ncclCommInitRank",
            ncclCommInitRank(&nccl_comm, nccl_size, nccl_id, nccl_rank));

NCCL_CHECK(entries, "ncclCommInitRank",
            ncclCommInitRank(&end_nccl_comm, nccl_size, nccl_id, nccl_rank));
```

So I want to know it is reasonable to use different ncclComm_t in different thread to do collection? And Is it right to create 2 ncclComm_t like above(I can not find any doc about how to create multi-communicator)?

**Comment by kwen2501** [comment]
Hi, yes, you can create different communicators for corresponding threads under different processes. Just be aware that you would need to use different ncclUniqueId's for the two communicators.

**Comment by amazingyyc** [comment]
Thanks your response, But I read the document by nccl and find "ncclGetUniqueId should be called once" in   https://docs.nvidia.com/deeplearning/sdk/nccl-developer-guide/docs/api/comms.html#ncclgetuniqueid. If i call only once so How can i get 2 ncclUniqueId?

**Comment by kwen2501** [comment]
Thanks for reading the documentation closely! That sentence actually means 

> ncclGetUniqueId should be called once **(per communicator)**

So in your case, it is safe to call `ncclGetUniqueId` twice. We will improve the documentation.

**Comment by amazingyyc** [comment]
Thanks kwen2501, it means the below code is accepted? By the way, from source code the ncclGetUniqueId will call function bootstrapGetUniqueId, and i found id->pid = -1/id->pid = getpid(); getpid() measn process id right? if so 2 thread in 1 process how can it distinguish 2 different communicator?

```
ncclUniqueId nccl_id;

if (0 == local_rank) {
  NCCL_CHECK(entries, "ncclGetUniqueId", ncclGetUniqueId(&nccl_id));
}

MPI_CHECK(entries, "MPI_Bcast", MPI_Bcast((void*)&nccl_id, sizeof(nccl_id), MPI_BYTE, 0, global_state.local_comm));

NCCL_CHECK(entries, "ncclCommInitRank",
            ncclCommInitRank(&nccl_comm, nccl_size, nccl_id, nccl_rank));

ncclUniqueId end_nccl_id;
if (0 == local_rank) {
  NCCL_CHECK(entries, "ncclGetUniqueId", ncclGetUniqueId(&end_nccl_id));
}

MPI_CHECK(entries, "MPI_Bcast", MPI_Bcast((void*)&end_nccl_id, sizeof(end_nccl_id), MPI_BYTE, 0, global_state.local_comm));

NCCL_CHECK(entries, "ncclCommInitRank",
            ncclCommInitRank(&end_nccl_comm, nccl_size, end_nccl_id, nccl_rank));
```

**Comment by kwen2501** [comment]
It will be distinguished by the IP port of a listening socket created by the caller of `ncclGetUniqueId`

**Comment by amazingyyc** [comment]
Thanks so much kwen2501, it's really helpful for me.
