### ISSUE TITLE
NCCL error in: /torch/lib/c10d/ProcessGroupNCCL.cpp:260, unhandled system error

### ISSUE THREAD

**Issue by Lausannen** [NVIDIA/nccl#207]
Hi , I try to use torch.distributed.launch to run code in multi node with multi gpus. However, I have met this bug with unhandled system error in NCCL, I wonder if some one can give me some suggestions. Thank you very much!!! My NCCL version is 2.3.7 and pytorch version is 1.0.0.dev20190327

**Comment by kwen2501** [comment]
Would you mind setting NCCL_DEBUG=INFO and show the log? We are not sure what the error is by the current description. Thanks!

**Comment by Lausannen** [comment]
@kwen2501 Thank you for your quick reply. 
In my experiment, I have two node , each node has 4 GPUs
Here is the log info :
**For Node 0:**
gpu2:46654:46654 [0] NCCL INFO NET : Using interface ib0:12.12.12.102<0>
gpu2:46654:46654 [0] NCCL INFO NET/IB : Using interface ib0 for sideband communication
gpu2:46654:46654 [0] NCCL INFO Using internal Network Socket
gpu2:46654:46654 [0] NCCL INFO NET : Using interface ib0:12.12.12.102<0>
gpu2:46654:46654 [0] NCCL INFO NET/Socket : 1 interfaces found
NCCL version 2.3.7+cuda9.0
gpu2:46654:46654 [0] NCCL INFO rank 0 nranks 8
gpu2:46655:46655 [1] NCCL INFO NET : Using interface ib0:12.12.12.102<0>
gpu2:46655:46655 [1] NCCL INFO NET/IB : Using interface ib0 for sideband communication
gpu2:46655:46655 [1] NCCL INFO Using internal Network Socket
gpu2:46655:46655 [1] NCCL INFO rank 1 nranks 8
gpu2:46656:46656 [2] NCCL INFO NET : Using interface ib0:12.12.12.102<0>
gpu2:46656:46656 [2] NCCL INFO NET/IB : Using interface ib0 for sideband communication
gpu2:46656:46656 [2] NCCL INFO Using internal Network Socket
gpu2:46656:46656 [2] NCCL INFO rank 2 nranks 8
gpu2:46655:47153 [1] NCCL INFO comm 0x7f132405ad20 rank 1 nranks 8
gpu2:46655:47153 [1] NCCL INFO NET : Using interface ib0:12.12.12.102<0>
gpu2:46655:47153 [1] NCCL INFO NET/Socket : 1 interfaces found
gpu2:46654:47152 [0] NCCL INFO comm 0x7ff08805ad20 rank 0 nranks 8
gpu2:46657:46657 [3] NCCL INFO NET : Using interface ib0:12.12.12.102<0>
gpu2:46657:46657 [3] NCCL INFO NET/IB : Using interface ib0 for sideband communication
gpu2:46657:46657 [3] NCCL INFO Using internal Network Socket
gpu2:46657:46657 [3] NCCL INFO rank 3 nranks 8
gpu2:46656:47154 [2] NCCL INFO comm 0x7fc1dc05ad20 rank 2 nranks 8
gpu2:46656:47154 [2] NCCL INFO NET : Using interface ib0:12.12.12.102<0>
gpu2:46656:47154 [2] NCCL INFO NET/Socket : 1 interfaces found
gpu2:46657:47155 [3] NCCL INFO comm 0x7fdd7805ad20 rank 3 nranks 8
gpu2:46657:47155 [3] NCCL INFO NET : Using interface ib0:12.12.12.102<0>
gpu2:46657:47155 [3] NCCL INFO NET/Socket : 1 interfaces found

**For Node 1**:
gpu1:44940:44940 [1] NCCL INFO 
gpu1:44942:44942 [3] NCCL INFO 
NET : Using interface ib0:12.12.12.101<0>NET : Using interface ib0:12.12.12.101<0>
gpu1:44941:44941 [2] NCCL INFO 
gpu1:44940:44940 [1] NCCL INFO 
NET/IB : Using interface ib0 for sideband communicationgpu1:44942:44942 [3] NCCL INFO 
NET : Using interface ib0:12.12.12.101<0>
NET/IB : Using interface ib0 for sideband communication

gpu1:44941:44941 [2] NCCL INFO NET/IB : Using interface ib0 for sideband communication
gpu1:44940:44940 [1] NCCL INFO Using internal Network Socket
gpu1:44940:44940 [1] NCCL INFO rank 5 nranks 8
gpu1:44941:44941 [2] NCCL INFO Using internal Network Socket
gpu1:44941:44941 [2] NCCL INFO rank 6 nranks 8
gpu1:44942:44942 [3] NCCL INFO Using internal Network Socket
gpu1:44942:44942 [3] NCCL INFO rank 7 nranks 8
gpu1:44941:45430 [2] NCCL INFO comm 0x7fb16405ad20 rank 6 nranks 8
gpu1:44941:45430 [2] NCCL INFO NET : Using interface ib0:12.12.12.101<0>
gpu1:44941:45430 [2] NCCL INFO NET/Socket : 1 interfaces found
gpu1:44942:45431 [3] NCCL INFO comm 0x7faa8805ad20 rank 7 nranks 8
gpu1:44940:45429 [1] NCCL INFO comm 0x7fd05005ad20 rank 5 nranks 8
gpu1:44942:45431 [3] NCCL INFO 
gpu1:44940:45429 [1] NCCL INFO 
NET : Using interface ib0:12.12.12.101<0>NET : Using interface ib0:12.12.12.101<0>

gpu1:44942:45431 [3] NCCL INFO gpu1:44940:45429 [1] NCCL INFO NET/Socket : 1 interfaces foundNET/Socket : 1 interfaces found

gpu1:44939:44939 [0] NCCL INFO NET : Using interface ib0:12.12.12.101<0>
gpu1:44939:44939 [0] NCCL INFO NET/IB : Using interface ib0 for sideband communication
gpu1:44939:44939 [0] NCCL INFO Using internal Network Socket
gpu1:44939:44939 [0] NCCL INFO rank 4 nranks 8
gpu1:44939:45432 [0] NCCL INFO comm 0x7fe00005ad20 rank 4 nranks 8
gpu1:44939:45432 [0] NCCL INFO NET : Using interface ib0:12.12.12.101<0>
gpu1:44939:45432 [0] NCCL INFO NET/Socket : 1 interfaces found

gpu1:44942:45431 [3] include/socket.h:369 NCCL WARN 
gpu1:44940:45429 [1] include/socket.h:369 NCCL WARN Call to connect failed : No route to host
gpu1:44941:45430 [2] include/socket.h:369 NCCL WARN 
gpu1:44939:45432 [0] include/socket.h:369 NCCL WARN 
Call to connect failed : No route to hostCall to connect failed : No route to hostCall to connect failed : No route to host
gpu1:44942:45431 [3] NCCL INFO 

gpu1:44939:45432 [0] NCCL INFO transport/net_socket.cu:138 -> 2gpu1:44940:45429 [1] NCCL INFO gpu1:44941:45430 [2] NCCL INFO transport/net_socket.cu:138 -> 2
transport/net_socket.cu:138 -> 2transport/net_socket.cu:138 -> 2
gpu1:44942:45431 [3] NCCL INFO 

gpu1:44939:45432 [0] NCCL INFO bootstrap.cu:19 -> 2gpu1:44940:45429 [1] NCCL INFO gpu1:44941:45430 [2] NCCL INFO bootstrap.cu:19 -> 2
bootstrap.cu:19 -> 2bootstrap.cu:19 -> 2
gpu1:44942:45431 [3] NCCL INFO 

bootstrap.cu:195 -> 2gpu1:44939:45432 [0] NCCL INFO gpu1:44940:45429 [1] NCCL INFO gpu1:44941:45430 [2] NCCL INFO 
bootstrap.cu:195 -> 2bootstrap.cu:195 -> 2bootstrap.cu:195 -> 2gpu1:44942:45431 [3] NCCL INFO 


gpu1:44940:45429 [1] NCCL INFO init.cu:446 -> 2gpu1:44939:45432 [0] NCCL INFO gpu1:44941:45430 [2] NCCL INFO init.cu:446 -> 2
init.cu:446 -> 2init.cu:446 -> 2
gpu1:44942:45431 [3] NCCL INFO 

init.cu:593 -> 2gpu1:44940:45429 [1] NCCL INFO gpu1:44939:45432 [0] NCCL INFO gpu1:44941:45430 [2] NCCL INFO 
init.cu:593 -> 2init.cu:593 -> 2init.cu:593 -> 2gpu1:44942:45431 [3] NCCL INFO 


misc/group.cu:69 -> 2 [Async thread]
gpu1:44940:45429 [1] NCCL INFO gpu1:44939:45432 [0] NCCL INFO gpu1:44941:45430 [2] 
NCCL INFO misc/group.cu:69 -> 2 [Async thread]misc/group.cu:69 -> 2 [Async thread]misc/group.cu:69 -> 2 [Async thread]

**Comment by kwen2501** [comment]
Okay, it seems node 1 cannot reach node 0. Have you checked your network setting?
Is node 0 is ping-able from node 1? Does node 0 have firewall turned on?
If it is ping-able and the firewall is off, then you may need to set NCCL_SOCKET_IFNAME to an IP interface the two nodes can talk to each other with.

**Comment by Lausannen** [comment]
@kwen2501  Thank you for your advice! I have successfully run my code with 2 machines. However, when I train COCO dataset with 8 GPUs  with 2 machines, it is slower than 4 GPUs in single node. Should I adjust some NCCL parameters or this is the communicating time which can not be ignored ?

**Comment by kwen2501** [comment]
The inter-node communication may become the bottleneck as you are using a single socket interface (ib0) for communication. Why not use Infiniband or RoCE over the IB card you have? Did you set NCCL_IB_DISABLE to 1?

**Comment by sjeaugey** [comment]
Closing since it seems to be resolved.

**Comment by JerryDaHeLian** [comment]
遇到同样的问题，不过我的系统里有多张网卡。以下方法仅供参考：
首先关闭防火墙。（设置规则我没太弄明白，直接暴力方式，关闭了防火墙。安全起见，最好是设置防火墙规则）
总结起来，通过Lightning run on预训练时要在命令行里加上：
NCCL_SOCKET_IFNAME=enx0826ae3dd6c5 NCCL_DEBUG=info lightning run mode...
NCCL_SOCKET_IFNAME=enx0826ae3dd6c5 指定网卡名（带有有效ip地址的）
NCCL_DEBUG=info 给出较为详细的debug信息，用于出错分析。

**Comment by JerryDaHeLian** [comment]
遇到同样的问题，不过我的系统里有多张网卡。以下方法仅供参考：
首先关闭防火墙。（设置规则我没太弄明白，直接暴力方式，关闭了防火墙。安全起见，最好是设置防火墙规则）
总结起来，通过Lightning run on预训练时要在命令行里加上：
NCCL_SOCKET_IFNAME=enx0826ae3dd6c5 NCCL_DEBUG=info lightning run mode...
NCCL_SOCKET_IFNAME=enx0826ae3dd6c5 指定网卡名（带有有效ip地址的）
NCCL_DEBUG=info 给出较为详细的debug信息，用于出错分析。
