### ISSUE TITLE
how to use specify ring or tree algorithm?

### ISSUE THREAD

**Issue by CCrainys** [NVIDIA/nccl#211]
Hi, 

Tree algorithm has been added to nccl2.4. So NCCL has supported tree algorithm and ring algorithm in allreduce. 

I'm confused when we use ncclAllReduce, how does this API decide which algorithm to use? tree or ring?

Can the user specify which algorithm to use?

**Comment by kwen2501** [comment]
Hi, NCCL only enables the tree algorithm in multi-node cases, for now. If you set NCCL_DEBUG=INFO and search for keyword "Tree", you may see up to which size NCCL enables the tree algorithm. You may change this threshold by setting `NCCL_TREE_THRESHOLD` (see https://docs.nvidia.com/deeplearning/sdk/nccl-developer-guide/docs/env.html#nccl-tree-threshold).

To force the ring algorithm for all sizes, you can set `NCCL_TREE_THRESHOLD` to 0.

To force the tree algorithm for all sizes, you can set `NCCL_TREE_THRESHOLD` to the maximum size accepted.

**Comment by CCrainys** [comment]
thanks

**Comment by fanshiqing** [comment]
`NCCL_TREE_THRESHOLD` is enabled since 2.4 and is removed in 2.5. 

And now we use the `NCCL_ALGO` variable defines which algorithms NCCL will use. See https://docs.nvidia.com/deeplearning/nccl/user-guide/docs/env.html#nccl-algo for details.
