### ISSUE TITLE
Support for sparse All-Reduce in NCCL?

### ISSUE THREAD

**Issue by yaroslavvb** [NVIDIA/nccl#215]
Are there plans to add Sparse all-reduce to NCCL? It's been added to PyTorch Gloo backend recently. This feature could make [Deep Gradient Compression](https://arxiv.org/abs/1712.01887) practical

**Comment by sjeaugey** [comment]
Could you elaborate on the kind of API we would need in NCCL to better support sparse all-reduce ?

**Comment by yaroslavvb** [comment]
cc @pietern @ngimel who may have a better idea on a good API for this

**Comment by pietern** [comment]
For NCCL it's element wise operations all the way down, so I think this belongs in the PyTorch NCCL process group instead. Parts will be coalescing sparse tensors, communicating dimensionality, and broadcasting indices and values. These all depend on the sparse tensor representation. The sparse allreduce in the Gloo process group is 90% PyTorch code and 10% Gloo code (for allgatherv). @ngimel mentioned that allgatherv can be approximated by doing a batch of NCCL broadcast kernels, so I think it will be possible to support sparse allreduce in the NCCL process group without NCCL modifications.
