### ISSUE TITLE
Dynamically linking to libcudart

### ISSUE THREAD

**Issue by jakirkham** [NVIDIA/nccl#216]
It looks like `libnccl` is [statically linked to `libcudart`]( https://github.com/NVIDIA/nccl/blob/9db4b1d801624a00591b7aafd426d6dd23547443/src/Makefile#L36 ). Would it be possible to dynamically link to `libcudart` instead? Or are there issues with this?

**Comment by sjeaugey** [comment]
It is possible to link `libcudart` dynamically (it used to be the case). Linking statically works better when mixing different toolkits versions within the same application, which happen sometimes and is hard to debug.

**Comment by jakirkham** [comment]
Thanks for the response. IIUC this is more a question of ease of deployment. Does that sound right? If so, would it be reasonable to add an option to dynamically link `libcudart` (if enabled)? For example allowing an environment variable to switch between dynamic and static linking?

**Comment by sjeaugey** [comment]
Indeed, although that's an option we need to then support, i.e. not break every time we touch the Makefiles.

Is there a reason why you would want to link dynamically ? I understand it's a bit of space wasted, but the CUDA runtime is less than 1MB.

**Comment by jakirkham** [comment]
Sure, there are two main reasons.

First we would like to start contributing GPU packages to a package management ecosystem ( [conda-forge]( https://conda-forge.org ) ). Their standard is to dynamically link things, which we would like to follow.

Second they have modified their package manager ( [conda]( https://conda.io/en/latest/ ) ) with a bit of logic to align `cudatoolkit` to the driver version ( https://github.com/conda/conda/pull/8267 ). This would allow the solver to effectively constrain packages (e.g. NCCL) to match the user's driver version. However this only works if downstream packages depend on `cudatoolkit`. While we could still statically link and depend on `cudatoolkit` this is a bit wasteful and quickly becomes expensive over many packages.

**Comment by sjeaugey** [comment]
Makes sense. In any case, feel free to give it a try and submit a PR (should be easy but let me know if you need help).

**Comment by jakirkham** [comment]
Sure, happy too. Thanks for your engagement here btw.

**Comment by jakirkham** [comment]
Have submitted a small change in PR ( https://github.com/NVIDIA/nccl/pull/220 ). Please let me know what you think. 🙂

**Comment by sjeaugey** [comment]
Merged. Perfect solution : simple and low maintenance :-)

**Comment by jakirkham** [comment]
Thank you. Thought you might like it 😉
