### ISSUE TITLE
API/ABI Compatibility

### ISSUE THREAD

**Issue by jakirkham** [NVIDIA/nccl#218]
Am curious what the intended API/ABI compatibility of NCCL is. When do breaking changes occur? When do new features get added? Is there backwards and/or forwards compatibility? How are these (and other) changes noted in the version?

**Comment by sjeaugey** [comment]
As for other libraries, breaking changes occur only when the major number changes. The NCCL API only changed between NCCL 1.x and NCCL 2.0.

Note this is a general rule : the compiler will link applications against the major version of the library (i.e. `libnccl.so.2`), which means it cannot work with a different major version (`libnccl.so.1`, not binary compatible) but can work with any future version.

Features can be added on any version, although main features would generally increase the minor number. Patches and small features (e.g. a new environment variable to control a setting) would usually only increase the patch number.

Changes are usually in the git commit message, but you can also find release notes for the binaries provided on the developer zone :
https://docs.nvidia.com/deeplearning/sdk/nccl-release-notes/index.html

Let me know if that answers your question.

**Comment by jakirkham** [comment]
Yep, this is exactly what I was looking for. Thanks for your detailed response, Sylvain. 🙂
