### ISSUE TITLE
Include gencodes for CUDA 10

### ISSUE THREAD

**Issue by jakirkham** [NVIDIA/nccl#219]
Currently [CUDA 8 and CUDA 9 gencodes]( https://github.com/NVIDIA/nccl/blob/9db4b1d801624a00591b7aafd426d6dd23547443/makefiles/common.mk#L26-L36 ) are listed. However CUDA 10 gencodes are not listed. Would it be possible to add the CUDA 10 gencodes as well?

**Comment by sjeaugey** [comment]
CUDA 10 did not introduce new SM architectures (the latest, `sm_70`, is already supported by CUDA 9), so we didn't need to add a new line for CUDA 10.

**Comment by jakirkham** [comment]
Thanks for the clarification.

**Comment by jakirkham** [comment]
Submitted PR ( https://github.com/NVIDIA/nccl/pull/221 ) adding a comment to this effect. Please let me know what you think. 🙂
