### ISSUE TITLE
NCCL not upgrading to a newer version over CUDA 10.0

### ISSUE THREAD

**Issue by mijo2** [NVIDIA/nccl#227]
I have NCCL version 2.3.7 installed with Cuda 10.0 and I want to install version 2.4.7. But unfortunately, no matter whatever steps I take, be it using network installer, local installer, etc the older version remains while the new one isn't installed. Is there a way around this?

**Comment by sjeaugey** [comment]
Can you provide more details about your current setup (Linux distribution, NCCL installation method) and the steps you followed to install NCCL 2.4 ?

That would help us provide you with the easiest upgrade path.

**Comment by mijo2** [comment]
Linux Distribution - Ubuntu 16.04.6

Method 1:- 
1. Downloading the local installer deb file.
2. sudo gdebi deb_file

Method 2:-
1. sudo dkpg -i deb_file
2. sudo apt-get install -f

Even after installing multiple times, the version of nccl used is still 2.3.7. Followed something similar to install 2.3.7

**Comment by sjeaugey** [comment]
Installing a repo is not enough. You need to `apt update` and then upgrade nccl with `apt install libnccl2 linbccl-dev`.

More info in the install guide here :

https://docs.nvidia.com/deeplearning/sdk/nccl-install-guide/index.html#debian

Let me know if It helps.
