### ISSUE TITLE
Issue on K10 board

### ISSUE THREAD

**Issue by fmana** [NVIDIA/nccl#23]
Hi NCCL team, 
I downloaded NCCL library and compiled the whole suite (lib+sample code) under CUDA 7.5.
Then, I tried one of your sample run (./build/test/single/all_reduce_test 10000000) 
using my in-house hw setup (K10/K80).

In case of K10 run, I have this:
**CuRAND error 204 at test/include/test_utilities.h:111**
triggered by a Randomize() into the sample code. 
I can overcome that simply by resetting to 0 the buffer instead of in random way,
but weird elapsed and bandwidth estimation values are print on screen like this:
```
$ ./build/test/single/all_reduce_test 10000000
# Using devices
#   Rank  0 uses device  0 [0x26] Tesla K10.G1.8GB
#   Rank  1 uses device  1 [0x27] Tesla K10.G1.8GB
#   Rank  2 uses device  2 [0x2a] Tesla K10.G1.8GB
#   Rank  3 uses device  3 [0x2b] Tesla K10.G1.8GB

#                                                 out-of-place                    in-place
#      bytes             N    type      op     time  algbw  busbw      res     time  algbw  busbw      res
    10000000      10000000    char     sum    0.009  1153.20  1729.81   2e-316    0.020  493.75  740.63   7e-310
    10000000      10000000    char    prod    0.008  1239.88  1859.82   7e-310    0.020  510.67  766.01   7e-310
    10000000      10000000    char     max    0.008  1221.47  1832.21   7e-310    0.020  510.46  765.70   7e-310
    10000000      10000000    char     min    0.008  1244.91  1867.37   7e-310    0.020  511.95  767.93   7e-310
```
In case of K80 (Randomize replaced by memset0) it seems fine:
```
$ ./build/test/single/all_reduce_test 10000000
# Using devices
#   Rank  0 uses device  0 [0x0c] Tesla K80
#   Rank  1 uses device  1 [0x0d] Tesla K80
#   Rank  2 uses device  2 [0x10] Tesla K80
#   Rank  3 uses device  3 [0x11] Tesla K80
#   Rank  4 uses device  4 [0x14] Tesla K80
#   Rank  5 uses device  5 [0x15] Tesla K80
#   Rank  6 uses device  6 [0x18] Tesla K80
#   Rank  7 uses device  7 [0x19] Tesla K80

#                                                 out-of-place                    in-place
#      bytes             N    type      op     time  algbw  busbw      res     time  algbw  busbw      res
    10000000      10000000    char     sum    2.887   3.46   6.06    0e+00    2.895   3.45   6.05    0e+00
    10000000      10000000    char    prod    2.547   3.93   6.87    0e+00    2.583   3.87   6.77    0e+00
    10000000      10000000    char     max    2.151   4.65   8.14    0e+00    2.166   4.62   8.08    0e+00
    10000000      10000000    char     min    1.966   5.09   8.90    0e+00    1.994   5.02   8.78    0e+00
```
What's going to happen with K10? It seems to me covered by NCCL requirement.
In any case, could you support K10? Despite we're moving toward new GPU arch, my lab is quite populate by K10.

Thanks,
Franco

*Edited for legibility by @lukeyeager*

**Comment by nluehr** [comment]
K10 has compute capability 3.0. By default NCCL is built for sm_35 and newer. If you tweak the makefile to include sm_30 support, NCCL should work on the K10. You will still need to forgo the random number generator, however, as cuRand's MT19937 supports sm_35 and newer only.

**Comment by fmana** [comment]
indeed recompiling including sm_30 support fixes my issue on K10 (cuRand till disabled).
Thanks.

**Comment by fmana** [comment]
I succeeded in running on K10 and so I tried profiling all_reduce_test sample code.
In attach I reported the nvvp picture of all_reduce_test/float/sum "outplace/inplace".
Looking at GTC16 NCCL presentation, I expected to see the whole memory plit in chunks and each
chunk sent in concurrency between each gpu pairs (ring algorithm).

![nccl_allreduce_4](https://cloud.githubusercontent.com/assets/18715804/14916585/cd09d64c-0e1a-11e6-8bc8-e2ea8399c0ee.gif)

What I see is a serial data move cross gpus to complete a loop.
What did I miss?
Something related to K10?

Thanks,
Franco

**Comment by cliffwoolley** [comment]
Most of what you see there is bookkeeping for the test framework.  The
actual reduction is the smaller kernel in the middle that actually does run
simultaneously on all GPUs.  Zoom in on the timeline and you'll see it.

PS: For sm_30, rather than forgoing the random number generation in the
test suite completely, you could just switch cuRAND to a different
generator.  It has other ones that do support older GPUs.

-Cliff

**Comment by nluehr** [comment]
Adding to Cliff's comments, all of the "chunking" and inter-gpu synchronizations are handled by direct peer memory accesses from within a single CUDA kernel (rather than, for example, using cudaEvents and separate cudaMemcpys). So the details of the algorithm won't show up in the nvvp profile.

**Comment by fmana** [comment]
Thanks for comments. I'll had a deeper look at the kernel realizing the core processing (chunk&transfer). It is quite interesting since I never wrote so complex algorithm into a single kernel.
I'll learn a lot.
I'll go to integrate your NCCL lib into a my toy sample code using the lib into my target scenario.
I'll let you know my findings and in case issues.
BTW what about of repeatability? 
Do you have fixed order collecting contributes in case of collectives?

Thanks,
Franco

**Comment by cliffwoolley** [comment]
As long as the mapping of GPU IDs to ranks remains the same, then yes, the
calculations should be deterministic and therefore the output repeatable.

**Comment by fmana** [comment]
Hi NCCL team,

I've finished in writing my sample code integrating NCCL into a multi-threads logic application.
I followed your's sample code: no problem at all. I can run w/ our in-house K10/K20/K80.
Just 2 comments:
1] I read about 8GPU limitation (GTC slides). According to my trials, NCCL works till 16GPU
    Was I lucky? Did I misunderstand the GTC slide content?
2] I verified your comment on repeatability: changing the commIgpu allocation I lost repeatability.
    No work-around on that? This is quite common using cluster that my app will be allocated
    to different machines at each run. Isn't possible into your "ring algorithm" define the starting
    point of the ring? The thread0 could define to NCCL which is the gpu to be used as start/end 
    of the ring. In this case, could make sense having repeatability achieved?

Thanks,
Franco

**Comment by nluehr** [comment]
I'm glad you're up and running. The 8 GPU requirement was relaxed in revision Iaa1841036a7bfdad6ebec99fed0adcd2bbe6ffad. The GTC slide was just out of date.

At this point, we don't have a good solution for general reproducibility. To avoid contending PCIe links, GPUs must communicate in a specific hardware order. If the software changes the mapping of ranks to physical GPUs, the communication order must change too, and the (non-associative) floating-point operations get carried out in a different order. Without a significant performance penalty, we can only provide deterministic output for runs with the same configuration.
