### ISSUE TITLE
Fail or report when using the same device multiple times in a communicator

### ISSUE THREAD

**Issue by sjeaugey** [NVIDIA/nccl#231]
Opening a new issue to discuss this (as it was mentioned in #209).

Using a CUDA device multiple times (as different ranks) in a NCCL communicator is not supported. https://docs.nvidia.com/deeplearning/sdk/nccl-developer-guide/docs/usage/communicators.html

NCCL should try to detect this situation and report it. Ideally `ncclCommInitRank` would return `ncclInvalidUsage`.

As doing so is not guaranteed to work but might work in specific situations, we might want to only report it through a `WARN` line.

As a third option, we would print a `WARN` line and return an error unless an environment variable is set to allow it.

**Comment by kwen2501** [comment]
Moving my comment under #209 over here:

> For the case of multiple ranks reusing the same GPU (if it indeed goes through initialization successfully), one may be able to notice such usage from the `Init COMPLETE` log that comes with `NCCL_DEBUG=INFO`.
> 
> For example:
> `NCCL INFO comm 0x556fe4c70860 rank 3 nranks 16 cudaDev 3 nvmlDev 3 - Init COMPLETE`
> And later another line with the same nvmlDev but different rank:
> `NCCL INFO comm 0x5644e6e34af0 rank 4 nranks 16 cudaDev 3 nvmlDev 3 - Init COMPLETE`
> 
> But indeed, this does not distinguish from a (more valid) use case of having multiple communicators, where ranks of different communicators reside on the same GPU. Just providing a quick method to check for the use case before a fix is in place for #231.

**Comment by sjeaugey** [comment]
Should be fixed in 2.5.6. Closing.

**Comment by marcelgwerder** [comment]
I am looking to use the same GPU in multiple processes for training my deep learning model because my GPU is starving and one process is not enough to keep it busy. It looks like this change is the cause for the `ncclInvalidUsage` error I am getting from `ncclCommInitRank`. Is there a way to get around this limitation? I am not quite sure if I understand why this should not be possible.

**Comment by sjeaugey** [comment]
There are multiple reasons for that, but overall, it is not deadlock safe, and even broken in some cases. Since we want the usage to be functional on all platforms and all GPUs, we can't allow for usage that will cause random hangs in some situations (which are hard to determine).

There is no guarantee the two NCCL kernels on the same GPU will never block each other, making the NCCL call hang. If you run on a smaller GPU which has less SMs, or if NCCL decides to use more SMs, one kernel might block the other and cause a hang. It would also break when using multiple threads to manage ranks.

The safe solution is to reduce intra-GPU first, then call NCCL with 1 rank per GPU.

**Comment by marcelgwerder** [comment]
Great, thanks a lot for the clarification. Does this behavior in any way depend on whether I use MPS or the GPU architecture (e.g. Volta vs. Pascal)?

**Comment by sjeaugey** [comment]
It can depend on the architecture indeed, although I don't have a precise example.
Regarding MPS, it is not supported with NCCL either.
