### ISSUE TITLE
NCCL performance for Deep Learning workloads on AWS EFA network

### ISSUE THREAD

**Issue by yaroslavvb** [NVIDIA/nccl#235]
I'm wondering if there are settings I can use to improve NCCL performance on AWS EFA network with 8 GPU instances.

Generally over 2 instances I've [observed](https://github.com/cybertronai/aws-network-benchmarks/blob/efa/nccl-bench-wandb.ipynb) effective bandwidth improvement of 17 Gbps -> 50 Gbps by switching from ethernet to EFA, and then up to [126.4 Gbps](https://app.wandb.ai/yaroslavvb/nccl_bench/runs/7f2viiy2/logs) when applying aws-ofi-nccl [patch](https://github.com/aws/aws-ofi-nccl/commit/2806caf377972c2cfef11fbd7961abb668699042)

However, going to 4 and 8 instances, the performance drops up to 1.6x. I'm wondering if it's due to jitter, or if it's something that can be improved by customizing nccl settings.

Below are numbers for 70MB allreduce in nccl 2.4.7ms1+cuda10.0, which is a size chosen to balance total time + time to wait for last layer to sync
- 16 GPU: 11ms [log](https://app.wandb.ai/yaroslavvb/nccl_bench/runs/nhq32eh5/logs)
- 32 GPU: 16ms [log](https://app.wandb.ai/yaroslavvb/nccl_bench/runs/sjixfpr3/logs)
- 64 GPU: 18ms [log](https://app.wandb.ai/yaroslavvb/nccl_bench/runs/wzntgf6f/logs)

**Comment by kwen2501** [comment]
Hi, in the two-node cases, NCCL uses the tree algorithm for all message sizes by default. As explained [here](https://github.com/NVIDIA/nccl/issues/209#issuecomment-498745923), this will give a 2x improvement over the ring algorithm in theoretical bandwidth.

However, this 2x factor does not hold for >= 3 nodes cases. That may explain why you see a drop.

Also, for >= 3 nodes, NCCL will calculate something called tree threshold, for message size greater than which NCCL will switch back to the ring algorithm. So the peak BWs you observed in the 4 and 8 nodes cases are indeed the peak BW of the ring algorithm, which is a "true" reflection of the network link BW you can have (+ overhead).

That said, we have not yet fully confirmed that the default tree thresholds calculated by NCCL (you can see it in the INFO log) is the best switching points on AWS+EFA, for all node scales. So you can try to tweak it a little bit and see how it impact the performance. But it may only have impact on the (medium) sizes around the threshold but not the big ones.

**Comment by yaroslavvb** [comment]
I'm manually setting `NCCL_TREE_THRESHOLD=4294967296` which is threshold suggested by EFA team, so I think I'm using a tree for 64 GPU case as well, here's INFO [log](https://app.wandb.ai/yaroslavvb/nccl_bench/runs/vn9989ul/logs).

BTW, using NCCL_DEBUG=INFO instead of NCCL_DEBUG=VERSION I no longer get version of nccl printed, is there a way to get both?

**Comment by yaroslavvb** [comment]
I did some tree vs ring comparisons for 2, 8,1 6, 24 and 32 machine configurations, and tree seems to be better for sizes between 1k and 500MB regardless of the number of machines

![2mach](https://user-images.githubusercontent.com/23068/60313823-5fac4880-9915-11e9-9d74-5d32432529f0.png)

2-machine tree:  https://app.wandb.ai/yaroslavvb/nccl_bench/runs/xey7bzxc/logs
2-machine ring:  https://app.wandb.ai/yaroslavvb/nccl_bench/runs/8ghilchv/logs

![8mach](https://user-images.githubusercontent.com/23068/60313850-75217280-9915-11e9-8311-d7bccdfa08f9.png)

8-machine tree:  https://app.wandb.ai/yaroslavvb/nccl_bench/runs/4gxbcaiy/logs
8-machine ring:  https://app.wandb.ai/yaroslavvb/nccl_bench/runs/6ntnyd3b/logs

![16mach](https://user-images.githubusercontent.com/23068/60313854-78b4f980-9915-11e9-96ac-d5cb2366795b.png)

16-machine tree:  https://app.wandb.ai/yaroslavvb/nccl_bench/runs/y6ica2li/logs
16-machine ring:  https://app.wandb.ai/yaroslavvb/nccl_bench/runs/q5rgn137/logs

![24mach](https://user-images.githubusercontent.com/23068/60313858-7ce11700-9915-11e9-8ae4-a1dc3670b984.png)

24-machine tree:  https://app.wandb.ai/yaroslavvb/nccl_bench/runs/wwj2s6ng/logs
24-machine ring:  https://app.wandb.ai/yaroslavvb/nccl_bench/runs/j31hhw08/logs

![32mach](https://user-images.githubusercontent.com/23068/60313865-810d3480-9915-11e9-8b0d-ae537155a617.png)

32-machine tree:  https://app.wandb.ai/yaroslavvb/nccl_bench/runs/sg4cboyq/logs
32-machine ring:  https://app.wandb.ai/yaroslavvb/nccl_bench/runs/3xq522ok/logs

**Comment by bobzhuyb** [comment]
@yaroslavvb I don't think the busbw was reported correctly here. https://github.com/NVIDIA/nccl-tests/ was developed before NCCL had trees. nccl-tests is calculating busbw from algbw using the *ring* equations (https://github.com/NVIDIA/nccl-tests/blob/master/doc/PERFORMANCE.md). I read nccl-test code before. The busbw is calculated, not measured.

I suggest you only focus on the algbw, which is the real allreduce throughput. That is, if you have X MB data to allreduce, NCCL will need (X/algbw) wall clock time. This is what application cares in the end.

NCCL developers, please correct me if I am wrong.

**Comment by yaroslavvb** [comment]
I agree that the time to complete the operation is the important metric. I made graphs to determine the cut-off point for switching from ring to tree. The values in graph were obtained by taking the time to complete (column right before busbw) and dividing by 50% of total transfer size, you can see the calculation in my notebook here -- https://github.com/cybertronai/aws-network-benchmarks/blob/efa/nccl-bench-wandb.ipynb

**Comment by bobzhuyb** [comment]
@yaroslavvb With large number of machines, your calculation (and also nccl-test calculation) is about right, though accurate. But for 2-machine case, the calculation is way off. The 120Gbps number is basically wrong, because the busbw is mistakenly calculated as algbw*2*(16-1)/16. 16 is the number of GPUs. While for tree, the real bandwidth between the two machines should be exactly algbw.

**Comment by sjeaugey** [comment]
@rashikakheria,

FYI @yaroslavvb reported a few numbers above running with the EFA plugin. He gets 80Gb/s (10GB/s) on 2 nodes, but performance drops to 50-60Gb/s (6-8 GB/s) when using 8 to 32 nodes.

Should we move this issue to https://github.com/aws/aws-ofi-nccl/ ?

**Comment by rashikakheria** [comment]
> @rashikakheria,
> 
> FYI @yaroslavvb reported a few numbers above running with the EFA plugin. He gets 80Gb/s (10GB/s) on 2 nodes, but performance drops to 50-60Gb/s (6-8 GB/s) when using 8 to 32 nodes.
> 
> Should we move this issue to https://github.com/aws/aws-ofi-nccl/ ?

Sure, we can!

**Comment by yaroslavvb** [comment]
https://docs.google.com/document/d/1C0iiKGI2lm-c7VaVZimlgrpBH1C8Oo2R_muxZJvjkrM/edit#

Closing issue and moving to aws-ofi-nccl
