### ISSUE TITLE
Failed build on Ubuntu 16.04

### ISSUE THREAD

**Issue by i55code** [NVIDIA/nccl#237]
Hi, I am trying to install NCCL on a Ubuntu machine 16.04, with Cuda  9.1. But there is an error when I am trying to excute "make pkg.debian.build", do you have any ideas? 

:~/nccl$ make pkg.debian.build
make -C pkg debian.build BUILDDIR=/nccl/build
make[1]: Entering directory '/nccl/pkg'
make -C debian build BUILDDIR=/nccl/build
make[2]: Entering directory '/nccl/pkg/debian'
make[3]: Entering directory '/nccl'
make[4]: Entering directory '/nccl/src'
make[5]: Entering directory '/nccl/src/collectives/device'
make[5]: Leaving directory '/nccl/src/collectives/device'
make[4]: Leaving directory '/nccl/src'
make[3]: Leaving directory '/nccl'
Building Debian package
/bin/sh: 1: debuild: not found
Makefile:31: recipe for target 'build' failed
make[2]: *** [build] Error 127
make[2]: Leaving directory '/nccl/pkg/debian'
Makefile:23: recipe for target 'debian.build' failed
make[1]: *** [debian.build] Error 2
make[1]: Leaving directory '/nccl/pkg'
Makefile:28: recipe for target 'pkg.debian.build' failed
make: *** [pkg.debian.build] Error 2

**Comment by sjeaugey** [comment]
The error is :
`/bin/sh: 1: debuild: not found`

Did you make sure you installed the needed tools to build debian packages ?
From the main page documentation https://github.com/NVIDIA/nccl#install :
```
$ # Install tools to create debian packages
$ sudo apt install build-essential devscripts debhelper fakeroot
```

**Comment by i55code** [comment]
Yes, I followed it step by step. And I tried it on two machines, both have this error. 

Feel free to let me know if there is anything else that I can try. Thanks!

**Comment by jimmauro** [comment]
Is debuild installed on the machines, and in your path?

What does "debuild" or "which debuild" return when executed in your shell?

**Comment by sjeaugey** [comment]
@i55code CUDA 8 does not have the compute_70 target. You can just remove those two lines and it should compile fine :
https://github.com/NVIDIA/nccl-tests/blob/master/src/Makefile#L23-L24

**Comment by i55code** [comment]
Thank you @sjeaugey and @jimmauro! 

For "debuild" and "which debuild", this is what it returns: 

~/nccl$ debuild
debuild: fatal error at line 633:
cannot find readable debian/changelog anywhere!
Are you in the source code tree?
~/nccl$ which debuild
/usr/bin/debuild
