### ISSUE TITLE
CuRAND Error on Tesla M2070 + CUDA 7.0

### ISSUE THREAD

**Issue by InnovArul** [NVIDIA/nccl#24]
I am facing an issue while installing 'nccl' for Tesla M2070 + CUDA library 7.0.

```
 -> % ./build/test/single/all_gather_test 10000000
 # Using devices
 #   Rank  0 uses device  0 [0x06] Tesla M2070
 #   Rank  1 uses device  1 [0x14] Tesla M2070
 #   Rank  2 uses device  2 [0x11] Tesla M2070

 #      bytes             N    type     time  algbw  busbw    delta
 CuRAND error 204 at test/include/test_utilities.h:112
```

NCCL has been compiled without any error. but when the test is run, CuRAND error occurs.
What could be the reason & how to fix this?

Thanks in advance!

**Comment by nluehr** [comment]
M2070 is based on the Fermi architecture and has compute capability 2.0. By default NCCL builds for compute capability 3.5 and newer. Issue #23 has some more details.

**Comment by InnovArul** [comment]
Thanks for the info!
