### ISSUE TITLE
Weird performace score of IB 

### ISSUE THREAD

**Issue by ligonzheng** [NVIDIA/nccl#243]
I use nccl-tests and mpi to test the bandwidth of my IB and eth network.  The mpi config is as below:
mpirun -x NCCL_DEBUG=INFO -x NCCL_IB_DISABLE=0 -x NCCL_SOCKET_IFNAME=ib  --allow-run-as-root -n 2 -hostfile ./hostfile -np 2 ./build/all_reduce_perf -b 1G -e 3G2-f  -g 1 -c 0
My hostfile :
root@42.186.128.164 slots=1
localhost slots=1

So I use a very simple case which just include two processes on two nodes and two GPUs. The purpose is the bandwidth between eth and IB.
The topolopy on each node is this:
 	GPU0	GPU1	GPU2	GPU3	GPU4	GPU5	mlx5_1	mlx5_0	CPU Affinity
GPU0	 X 	PIX	NODE	SYS	SYS	SYS	SYS	NODE	0-13,28-41
GPU1	PIX	 X 	NODE	SYS	SYS	SYS	SYS	NODE	0-13,28-41
GPU2	NODE	NODE	 X 	SYS	SYS	SYS	SYS	PIX	0-13,28-41
GPU3	SYS	SYS	SYS	 X 	PIX	NODE	NODE	SYS	14-27,42-55
GPU4	SYS	SYS	SYS	PIX	 X 	NODE	NODE	SYS	14-27,42-55
GPU5	SYS	SYS	SYS	NODE	NODE	 X 	PIX	SYS	14-27,42-55
mlx5_1	SYS	SYS	SYS	NODE	NODE	PIX	 X 	SYS	
mlx5_0	NODE	NODE	PIX	SYS	SYS	SYS	SYS	 X 	

However, the results really confuse me. 
No matter how many ib cards I used( one or two ), or no matter if I enable shared memory or RDMA, the bandwidth is always around 5.7GBps.  Theoretically every ib card has a 100Gbps so two cards has 200Gbps, But my results shows it only has around 50Gbps even with two ib cards. Besides, the shared memory and RDMA also has a little affect on the bandwidth.  Why the bandwidth of IB is so stable ?
Is there anyone help me ? Thank you a lot !

**Comment by kwen2501** [comment]
Hi, the bottleneck seems to be the SYS link between the GPUs, i.e. the data has to cross the QPI link (or similar on other systems).  That caps the bandwidth regardless of how many rings are created (which is related to the number of NICs as you mentioned). 

Are you using an Intel Skylake CPU? Note that by default NCCL does not use P2P across PCI root complexes on Skylake. You may try setting NCCL_P2P_LEVEL=5 to force the use of P2P across root complexes. It will require an updated BIOS to show a performance improvement.

**Comment by sjeaugey** [comment]
Unfortunately, you cannot aggregate the speed of the two IB NICs (2x12=24GB/s) since the intra-node bandwidth is 9 GB/s at best (with the setting Ke mentioned above).

Only systems with NVLink connectivity within the node are able to get increased performance when using more than one 100G NIC.

**Comment by ligonzheng** [comment]
@kwen2501 @sjeaugey 
A question there is that I never use intra-node communication because I just use one GPU on each node.  As I mentioned at first ,I just want to know the bandwidth of IB and eth which only work between nodes so I turn off the intra-node communication.

**Comment by kwen2501** [comment]
Sorry we missed that. If you launch nccl-test with 1 GPU per node, by default nccl-test will use GPU0 from each node. 

Based on the affinity matrix you show, the two NICs are respectively NODE and SYS away from GPU0. Hence the theory mentioned by Sylvain still applies. (And in this specific case, setting NCCL_P2P_LEVEL will not have an effect).

**Comment by kwen2501** [comment]
You may set `CUDA_VISIBLE_DEVICES` to 2 or 5 (whose distances to the NICs are PIX) to observe maybe higher inter-node bandwidth in this 1-GPU-per-node case. But I don't think NCCL will aggregate the PIX NIC bandwidth and the SYS NIC bandwidth either, because the lower speed channel will make the total execution time longer.

When you use all GPUs on the two nodes, NCCL will automatically pick the GPUs that are closest to the NICs as the in/out GPUs. But as mentioned before, the overall BW will be limited by the intra-node BW in this case.

**Comment by ligonzheng** [comment]
Thank you people all ! I figure it out. My computer does not support RDMA and P2P. The PIX only work when P2P is open. If there is no P2P, the PIX get a lower bandwith because under same PCIe switch.
