### ISSUE TITLE
error: 'SO_REUSEPORT' was not declared in this scope

### ISSUE THREAD

**Issue by adamjstewart** [NVIDIA/nccl#244]
I'm trying to build NCCL 2.4.6 on Cray CNL5 with GCC 6.3.0 and CUDA 9.1.85, but I'm getting the following error message:
```
In file included from include/core.h:14:0,
                 from bootstrap.cc:8:
include/socket.h: In function 'ncclResult_t createListenSocket(int*, socketAddress*)':
include/socket.h:329:60: error: 'SO_REUSEPORT' was not declared in this scope
     SYSCHECK(setsockopt(sockfd, SOL_SOCKET, SO_REUSEADDR | SO_REUSEPORT, &opt, sizeof(opt)), "setsockopt");
                                                            ^
include/checks.h:46:12: note: in definition of macro 'SYSCHECKSYNC'
   retval = call; \
            ^~~~
include/checks.h:34:3: note: in expansion of macro 'SYSCHECKVAL'
   SYSCHECKVAL(call, name, retval); \
   ^~~~~~~~~~~
include/socket.h:329:5: note: in expansion of macro 'SYSCHECK'
     SYSCHECK(setsockopt(sockfd, SOL_SOCKET, SO_REUSEADDR | SO_REUSEPORT, &opt, sizeof(opt)), "setsockopt");
     ^~~~~~~~
make[1]: *** [/mnt/c/scratch/sciteam/stewart1/spack-stage/spack-stage-vvgU_S/spack-src/build/obj/bootstrap.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory `/mnt/c/scratch/sciteam/stewart1/spack-stage/spack-stage-vvgU_S/spack-src/src'
make: *** [src.build] Error 2
```
Any idea how to solve this?
```console
$ uname -a
Linux h2ologin3 3.0.101-0.47.106.59-default #1 SMP Wed Jan 23 09:00:24 UTC 2019 (624897e) x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by AddyLaddy** [comment]
We don't have access to a Cray CNL machine to investigate, but on our local Linux machines that define comes from;

/usr/include/include/asm-generic/socket.h:#define SO_REUSEPORT     15

which is probably included from <bits/socket.h> which should have been included by <sys/socket.h> in the NCCL header file.

You could try modifying the the NCCL file; include/socket.h to include <asm/socket.h> or maybe <linux/net.h> ?

But maybe the Cray distribution of Linux is too old to include that functionality? I notice that the manual page for socket(7) says;

> SO_REUSEPORT (since Linux 3.9)
              Permits multiple AF_INET or AF_INET6 sockets to be bound to an identical socket address.  

If that is the case, then I'd suggest removing SO_REUSEPORT from the NCCL setsockopt() call as I don't believe it will hurt functionality.

**Comment by adamjstewart** [comment]
Thanks @AddyLaddy, that makes sense as SO_REUSEPORT was added in Linux 3.9 and I'm on Linux 3.0. I'm going to be honest with you, I don't know much C, I was just trying to build NCCL as a dependency of PyTorch. Do you think you could write a patch for me to make SO_REUSEPORT conditional on whether or not it has actually been defined? Or just remove it altogether.

**Comment by AddyLaddy** [comment]
Sure, the patch would look something like this; 

```
diff --git a/src/include/socket.h b/src/include/socket.h
index 68ce235..b4f09b9 100644
--- a/src/include/socket.h
+++ b/src/include/socket.h
@@ -327,7 +327,11 @@ static ncclResult_t createListenSocket(int *fd, union socketAddress *localAddr)
   if (socketToPort(&localAddr->sa)) {
     // Port is forced by env. Make sure we get the port.
     int opt = 1;
+#if defined(SO_REUSEPORT)
     SYSCHECK(setsockopt(sockfd, SOL_SOCKET, SO_REUSEADDR | SO_REUSEPORT, &opt, sizeof(opt)), "setsockopt");
+#else
+    SYSCHECK(setsockopt(sockfd, SOL_SOCKET, SO_REUSEADDR, &opt, sizeof(opt)), "setsockopt");
+#endif
   }
 
   // localAddr port should be 0 (Any port)
```

That code path is only used when the user is specifying a NCCL bootstrap IP address via the environment, so isn't executed in normal usage.

**Comment by rgommers** [comment]
The problem is not unique to Cray, I see it on Antergos Linux, kernel version 5.2.8-arch1-1-ARCH (64-bit). Googling for `SO_REUSEPORT` and "Arch Linux" finds more issues with `SO_REUSEPORT`.

The patch does get me past this issue. Thanks @AddyLaddy and @adamjstewart

**Comment by adamjstewart** [comment]
I confirmed that this patch also works for me!
