### ISSUE TITLE
Architecture mismatch: arm64, want: aarch64

### ISSUE THREAD

**Issue by peardox** [NVIDIA/nccl#247]
Building on a Jetson Nano results in the command:
```
# make pkg.debian.build
```
Throwing this error
```
> dh: No packages to build. Architecture mismatch: arm64, want: aarch64
```
Err ARM64 === aarch64 afaik!

**Comment by AddyLaddy** [comment]
Does PR #222 resolve this issue?

**Comment by peardox** [comment]
Nope

Got what I needed anyway by doing an xz package for personal use then manually copying everything to adjusted directories.

It was a requirement for a Tensorflow 1.14.0 build - all worked well in the end, 7.5 (it's a Nano) hours later CAPI / JNI + Python all look good

**Comment by sjeaugey** [comment]
This should be fixed now. Closing.
