### ISSUE TITLE
NCCL with Python code (question)

### ISSUE THREAD

**Issue by abidmalikwaterloo** [NVIDIA/nccl#253]
Can we use NCCL with python code?
Thanks

**Comment by keisukefukuda** [comment]
The answer is Yes and No.

If you use some deep learning frameworks, NCCL is supported by most major frameworks. So the answer is Yes.

NCCL is a C library and Python can call C functions, so the answer is yes in that sense.
However, NCCL is for NVIDIA GPUs, so you need to allocate GPU device memory & pass memory pointers to NCCL.  In bare Python programs, this is not easy. In that sense, No.

Many deep learning frameworks have support libraries that bridge between Python and NCCL. I guess Horovod is the most major one. 
If you are NOT using deep learning frameworks and want to use only NCCL, I guess CuPy(https://cupy.chainer.org/) is an option. CuPy is a Python library for CUDA and supports NCCL. Here is an example of using NCCL through CuPy.
https://github.com/chainer/chainer/blob/master/chainermn/communicators/pure_nccl_communicator.py#L166

**Comment by abidmalikwaterloo** [comment]
@keisukefukuda Thank you for the detailed guidance. It is really helpful.
