### ISSUE TITLE
Questions in single node with multiple GPUs

### ISSUE THREAD

**Issue by ElegantLin** [NVIDIA/nccl#254]
Hi, I am running the [imagenet](https://github.com/pytorch/examples/tree/master/imagenet) code from Pytorch Example. I ran it on the single node with the IP `tcp://127.0.0.1:FREEPORT`. I wonder the function of this IP and how it works on a single node.

Thanks a lot.

**Comment by sjeaugey** [comment]
This `IP:PORT` is used for the NCCL bootstrap, i.e. when different processes of a job exchange their information with others.

**Comment by ElegantLin** [comment]
Yes, I have tested it using one single node. And I tried testing the traffic using `iptraf-ng`. But I found nothing in the `lo` interface. Do you have some suggestions on this?

Thanks a lot.

**Comment by ElegantLin** [comment]
And thanks for your help again. :-)

**Comment by sjeaugey** [comment]
I see. Well there could be a different mechanism used when Pytorch detects this is all on a local node, but really I don't know. I guess it would be better to ask that question on the Pytorch project.

**Comment by ElegantLin** [comment]
Yes, I have proposed an issue in Pytorch. Anyway, thanks for your reply.
