### ISSUE TITLE
nccl-test cuda-gdb error

### ISSUE THREAD

**Issue by lljjgg** [NVIDIA/nccl#258]
when I compile and run nccl-test,use
`./build/all_reduce_perf -b 8 -e 128M -f 2 -g 8`
It can run successfully,But an error occurred when running the program with cuda-gdb.

>    Rank  0 Pid  12414 on 51e6e7896958 device  0 [0x1a] Tesla V100-SXM3-32GB
>    Rank  1 Pid  12414 on 51e6e7896958 device  1 [0x1b] Tesla V100-SXM3-32GB
>    Rank  2 Pid  12414 on 51e6e7896958 device  2 [0x1c] Tesla V100-SXM3-32GB
>    Rank  3 Pid  12414 on 51e6e7896958 device  3 [0x1e] Tesla V100-SXM3-32GB
> [New Thread 0x7fffe6d73700 (LWP 12424)]
> [New Thread 0x7fffe6572700 (LWP 12425)]
> [New Thread 0x7fffe5a55700 (LWP 12426)]
> [New Thread 0x7fffe523c700 (LWP 12427)]
> [New Thread 0x7fffe4a23700 (LWP 12428)]
> warning: Cuda API error detected: cudaDeviceEnablePeerAccess returned (0x2c0)
> warning: Cuda API error detected: cudaGetLastError returned (0x2c0)
> warning: Cuda API error detected: cudaDeviceEnablePeerAccess returned (0x2c0)

nccl-test is  the official detection code of nccl.Does anyone have a similar problem.

**Comment by sjeaugey** [comment]
The `warning` lines are just warning. NCCL tries to enable P2P access between GPUs but in your case it seems P2P is not available, hence NCCL will fall back to using shared memory.

Is there another error ?

**Comment by lljjgg** [comment]
No problem for the time being,Thanks

**Comment by lljjgg** [comment]
P2P is not available?Are there any common reasons?Maybe the docker caused the problem？look forward to your reply，Thanks

**Comment by sjeaugey** [comment]
It could be that some GPUs don't have NVLink connectivity and can't use P2P through PCI. Can you share the result of the NCCL tests (you mentioned they can run successfully) and the output of `nvidia-smi topo -m` ?

**Comment by lljjgg** [comment]
I am so sorry.I replied to you late recently because of some other matters.I only run the  all_reduce_perf with mpirun -np 1 ./build/all_reduce_perf -b 8 -e 128M -f 2 -g 4 in https://github.com/nvidia/nccl-tests.This is output of program.
`# Using devices
#   Rank  0 Pid  71327 on 51e6e7896958 device  0 [0x1a] Tesla V100-SXM3-32GB
#   Rank  1 Pid  71327 on 51e6e7896958 device  1 [0x1b] Tesla V100-SXM3-32GB
#   Rank  2 Pid  71327 on 51e6e7896958 device  2 [0x1c] Tesla V100-SXM3-32GB
#   Rank  3 Pid  71327 on 51e6e7896958 device  3 [0x1e] Tesla V100-SXM3-32GB
#
#                                                     out-of-place                       in-place
#       size         count    type   redop     time   algbw   busbw  error     time   algbw   busbw  error
#        (B)    (elements)                     (us)  (GB/s)  (GB/s)            (us)  (GB/s)  (GB/s)
           8             2   float     sum    158.3    0.00    0.00  1e-07    158.4    0.00    0.00  0e+00
          16             4   float     sum    160.4    0.00    0.00  3e-08    160.7    0.00    0.00  3e-08
          32             8   float     sum    159.2    0.00    0.00  3e-08    159.9    0.00    0.00  3e-08
          64            16   float     sum    159.3    0.00    0.00  3e-08    278.1    0.00    0.00  3e-08
         128            32   float     sum    427.0    0.00    0.00  3e-08    158.6    0.00    0.00  3e-08
         256            64   float     sum    279.4    0.00    0.00  3e-08    157.6    0.00    0.00  3e-08
         512           128   float     sum    158.9    0.00    0.00  3e-08    277.9    0.00    0.00  1e-08
        1024           256   float     sum    576.3    0.00    0.00  1e-07    423.0    0.00    0.00  1e-07
        2048           512   float     sum    485.4    0.00    0.01  1e-07    447.7    0.00    0.01  1e-07
        4096          1024   float     sum    368.4    0.01    0.02  2e-07    371.8    0.01    0.02  2e-07
        8192          2048   float     sum   1002.9    0.01    0.01  2e-07    761.1    0.01    0.02  2e-07
       16384          4096   float     sum    879.4    0.02    0.03  2e-07    834.0    0.02    0.03  2e-07
       32768          8192   float     sum    560.7    0.06    0.09  2e-07    422.6    0.08    0.12  2e-07
       65536         16384   float     sum    521.4    0.13    0.19  2e-07    637.3    0.10    0.15  2e-07
      131072         32768   float     sum    570.9    0.23    0.34  2e-07   1203.1    0.11    0.16  2e-07
      262144         65536   float     sum   1155.5    0.23    0.34  2e-07    935.3    0.28    0.42  2e-07
      524288        131072   float     sum   1285.8    0.41    0.61  2e-07   1302.5    0.40    0.60  2e-07
     1048576        262144   float     sum   1275.1    0.82    1.23  2e-07   2698.2    0.39    0.58  2e-07
     2097152        524288   float     sum   2663.9    0.79    1.18  2e-07   3722.5    0.56    0.85  2e-07
     4194304       1048576   float     sum   3705.9    1.13    1.70  2e-07   3963.8    1.06    1.59  2e-07
     8388608       2097152   float     sum   7450.1    1.13    1.69  2e-07   5361.3    1.56    2.35  2e-07
    16777216       4194304   float     sum   7090.2    2.37    3.55  2e-07   5979.6    2.81    4.21  2e-07
    33554432       8388608   float     sum    14333    2.34    3.51  2e-07    19334    1.74    2.60  2e-07
    67108864      16777216   float     sum    30633    2.19    3.29  2e-07    34043    1.97    2.96  2e-07
   134217728      33554432   float     sum    54261    2.47    3.71  2e-07    57985    2.31    3.47  2e-07
# Out of bounds values : 0 OK
# Avg bus bandwidth    : 0.832915
`
And the output of nvidia-smi topo -m is 
`        GPU0    GPU1    GPU2    GPU3    GPU4    GPU5    GPU6    GPU7    GPU8    GPU9    GPU10   GPU11   GPU12   GPU13   GPU14   GPU15   mlx5_0  mlx5_1  mlx5_2  mlx5_3  CPU Affinity
GPU0     X      NV6     NV6     NV6     NV6     NV6     NV6     NV6     NV6     NV6     NV6     NV6     NV6     NV6     NV6     NV6     PIX     NODE    SYS     SYS     0-23,48-71
GPU1    NV6      X      NV6     NV6     NV6     NV6     NV6     NV6     NV6     NV6     NV6     NV6     NV6     NV6     NV6     NV6     PIX     NODE    SYS     SYS     0-23,48-71
GPU2    NV6     NV6      X      NV6     NV6     NV6     NV6     NV6     NV6     NV6     NV6     NV6     NV6     NV6     NV6     NV6     PIX     NODE    SYS     SYS     0-23,48-71
GPU3    NV6     NV6     NV6      X      NV6     NV6     NV6     NV6     NV6     NV6     NV6     NV6     NV6     NV6     NV6     NV6     PIX     NODE    SYS     SYS     0-23,48-71
GPU4    NV6     NV6     NV6     NV6      X      NV6     NV6     NV6     NV6     NV6     NV6     NV6     NV6     NV6     NV6     NV6     NODE    PIX     SYS     SYS     0-23,48-71
GPU5    NV6     NV6     NV6     NV6     NV6      X      NV6     NV6     NV6     NV6     NV6     NV6     NV6     NV6     NV6     NV6     NODE    PIX     SYS     SYS     0-23,48-71
GPU6    NV6     NV6     NV6     NV6     NV6     NV6      X      NV6     NV6     NV6     NV6     NV6     NV6     NV6     NV6     NV6     NODE    PIX     SYS     SYS     0-23,48-71
GPU7    NV6     NV6     NV6     NV6     NV6     NV6     NV6      X      NV6     NV6     NV6     NV6     NV6     NV6     NV6     NV6     NODE    PIX     SYS     SYS     0-23,48-71
GPU8    NV6     NV6     NV6     NV6     NV6     NV6     NV6     NV6      X      NV6     NV6     NV6     NV6     NV6     NV6     NV6     SYS     SYS     PIX     NODE    24-47,72-95
GPU9    NV6     NV6     NV6     NV6     NV6     NV6     NV6     NV6     NV6      X      NV6     NV6     NV6     NV6     NV6     NV6     SYS     SYS     PIX     NODE    24-47,72-95
GPU10   NV6     NV6     NV6     NV6     NV6     NV6     NV6     NV6     NV6     NV6      X      NV6     NV6     NV6     NV6     NV6     SYS     SYS     PIX     NODE    24-47,72-95
GPU11   NV6     NV6     NV6     NV6     NV6     NV6     NV6     NV6     NV6     NV6     NV6      X      NV6     NV6     NV6     NV6     SYS     SYS     PIX     NODE    24-47,72-95
GPU12   NV6     NV6     NV6     NV6     NV6     NV6     NV6     NV6     NV6     NV6     NV6     NV6      X      NV6     NV6     NV6     SYS     SYS     NODE    PIX     24-47,72-95
GPU13   NV6     NV6     NV6     NV6     NV6     NV6     NV6     NV6     NV6     NV6     NV6     NV6     NV6      X      NV6     NV6     SYS     SYS     NODE    PIX     24-47,72-95
GPU14   NV6     NV6     NV6     NV6     NV6     NV6     NV6     NV6     NV6     NV6     NV6     NV6     NV6     NV6      X      NV6     SYS     SYS     NODE    PIX     24-47,72-95
GPU15   NV6     NV6     NV6     NV6     NV6     NV6     NV6     NV6     NV6     NV6     NV6     NV6     NV6     NV6     NV6      X      SYS     SYS     NODE    PIX     24-47,72-95
mlx5_0  PIX     PIX     PIX     PIX     NODE    NODE    NODE    NODE    SYS     SYS     SYS     SYS     SYS     SYS     SYS     SYS      X      NODE    SYS     SYS
mlx5_1  NODE    NODE    NODE    NODE    PIX     PIX     PIX     PIX     SYS     SYS     SYS     SYS     SYS     SYS     SYS     SYS     NODE     X      SYS     SYS
mlx5_2  SYS     SYS     SYS     SYS     SYS     SYS     SYS     SYS     PIX     PIX     PIX     PIX     NODE    NODE    NODE    NODE    SYS     SYS      X      NODE
mlx5_3  SYS     SYS     SYS     SYS     SYS     SYS     SYS     SYS     NODE    NODE    NODE    NODE    PIX     PIX     PIX     PIX     SYS     SYS     NODE     X

Legend:

  X    = Self
  SYS  = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)
  NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node
  PHB  = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)
  PXB  = Connection traversing multiple PCIe switches (without traversing the PCIe Host Bridge)
  PIX  = Connection traversing a single PCIe switch
  NV#  = Connection traversing a bonded set of # NVLinks
`

**Comment by sjeaugey** [comment]
OK indeed it seems P2P is not being used. Could you run the p2pBandwidthLatencyTest from the CUDA samples ?

You can find the test in `/usr/local/cuda/samples/1_Utilities/p2pBandwidthLatencyTest/` (run `make` as root or `sudo make`, then run `./p2pBandwidthLatencyTest`).

I'd like to ensure CUDA P2P is functional.

**Comment by lljjgg** [comment]
I don't find p2pBandwidthLatencyTest in "/usr/local/cuda/".But I find nvlink_bandwidth in /usr/local/cuda/extras/CUPTI/samples/nvlink_bandwidth.I run ./nvlink_bandwidth --gpu-to-gpu.The output is 

`There are 16 devices.
CUDA Device 0 Name: Tesla V100-SXM3-32GB
CUDA Device 1 Name: Tesla V100-SXM3-32GB
CUDA Device 2 Name: Tesla V100-SXM3-32GB
CUDA Device 3 Name: Tesla V100-SXM3-32GB
CUDA Device 4 Name: Tesla V100-SXM3-32GB
CUDA Device 5 Name: Tesla V100-SXM3-32GB
CUDA Device 6 Name: Tesla V100-SXM3-32GB
CUDA Device 7 Name: Tesla V100-SXM3-32GB
CUDA Device 8 Name: Tesla V100-SXM3-32GB
CUDA Device 9 Name: Tesla V100-SXM3-32GB
CUDA Device 10 Name: Tesla V100-SXM3-32GB
CUDA Device 11 Name: Tesla V100-SXM3-32GB
CUDA Device 12 Name: Tesla V100-SXM3-32GB
CUDA Device 13 Name: Tesla V100-SXM3-32GB
CUDA Device 14 Name: Tesla V100-SXM3-32GB
CUDA Device 15 Name: Tesla V100-SXM3-32GB
Total Device Memory available : 31.7 GB
Memcpy size is set to 67108864 B (64 MB)
typeDev0 1, typeDev1 1, sysmem 0, peer 1, physical links 6, portdev0 0, 1, 2, 3, portDev1 4, 5, -1, -1, bandwidth 18446744073709551615
typeDev0 1, typeDev1 1, sysmem 0, peer 1, physical links 6, portdev0 0, 1, 2, 3, portDev1 4, 5, -1, -1, bandwidth 18446744073709551615
typeDev0 1, typeDev1 1, sysmem 0, peer 1, physical links 6, portdev0 0, 1, 2, 3, portDev1 4, 5, -1, -1, bandwidth 18446744073709551615
typeDev0 1, typeDev1 1, sysmem 0, peer 1, physical links 6, portdev0 0, 1, 2, 3, portDev1 4, 5, -1, -1, bandwidth 18446744073709551615
typeDev0 1, typeDev1 1, sysmem 0, peer 1, physical links 6, portdev0 0, 1, 2, 3, portDev1 4, 5, -1, -1, bandwidth 18446744073709551615
typeDev0 1, typeDev1 1, sysmem 0, peer 1, physical links 6, portdev0 0, 1, 2, 3, portDev1 4, 5, -1, -1, bandwidth 18446744073709551615
typeDev0 1, typeDev1 1, sysmem 0, peer 1, physical links 6, portdev0 0, 1, 2, 3, portDev1 4, 5, -1, -1, bandwidth 18446744073709551615
typeDev0 1, typeDev1 1, sysmem 0, peer 1, physical links 6, portdev0 0, 1, 2, 3, portDev1 4, 5, -1, -1, bandwidth 18446744073709551615
typeDev0 1, typeDev1 1, sysmem 0, peer 1, physical links 6, portdev0 0, 1, 2, 3, portDev1 4, 5, -1, -1, bandwidth 18446744073709551615
typeDev0 1, typeDev1 1, sysmem 0, peer 1, physical links 6, portdev0 0, 1, 2, 3, portDev1 4, 5, -1, -1, bandwidth 18446744073709551615
typeDev0 1, typeDev1 1, sysmem 0, peer 1, physical links 6, portdev0 0, 1, 2, 3, portDev1 4, 5, -1, -1, bandwidth 18446744073709551615
typeDev0 1, typeDev1 1, sysmem 0, peer 1, physical links 6, portdev0 0, 1, 2, 3, portDev1 4, 5, -1, -1, bandwidth 18446744073709551615
typeDev0 1, typeDev1 1, sysmem 0, peer 1, physical links 6, portdev0 0, 1, 2, 3, portDev1 4, 5, -1, -1, bandwidth 18446744073709551615
typeDev0 1, typeDev1 1, sysmem 0, peer 1, physical links 6, portdev0 0, 1, 2, 3, portDev1 4, 5, -1, -1, bandwidth 18446744073709551615
typeDev0 1, typeDev1 1, sysmem 0, peer 1, physical links 6, portdev0 0, 1, 2, 3, portDev1 4, 5, -1, -1, bandwidth 18446744073709551615
typeDev0 1, typeDev1 1, sysmem 0, peer 1, physical links 6, portdev0 0, 1, 2, 3, portDev1 4, 5, -1, -1, bandwidth 18446744073709551615
typeDev0 1, typeDev1 1, sysmem 0, peer 1, physical links 6, portdev0 0, 1, 2, 3, portDev1 4, 5, -1, -1, bandwidth 18446744073709551615
typeDev0 1, typeDev1 1, sysmem 0, peer 1, physical links 6, portdev0 0, 1, 2, 3, portDev1 4, 5, -1, -1, bandwidth 18446744073709551615
typeDev0 1, typeDev1 1, sysmem 0, peer 1, physical links 6, portdev0 0, 1, 2, 3, portDev1 4, 5, -1, -1, bandwidth 18446744073709551615
typeDev0 1, typeDev1 1, sysmem 0, peer 1, physical links 6, portdev0 0, 1, 2, 3, portDev1 4, 5, -1, -1, bandwidth 18446744073709551615
typeDev0 1, typeDev1 1, sysmem 0, peer 1, physical links 6, portdev0 0, 1, 2, 3, portDev1 4, 5, -1, -1, bandwidth 18446744073709551615
typeDev0 1, typeDev1 1, sysmem 0, peer 1, physical links 6, portdev0 0, 1, 2, 3, portDev1 4, 5, -1, -1, bandwidth 18446744073709551615
typeDev0 1, typeDev1 1, sysmem 0, peer 1, physical links 6, portdev0 0, 1, 2, 3, portDev1 4, 5, -1, -1, bandwidth 18446744073709551615
typeDev0 1, typeDev1 1, sysmem 0, peer 1, physical links 6, portdev0 0, 1, 2, 3, portDev1 4, 5, -1, -1, bandwidth 18446744073709551615
typeDev0 1, typeDev1 1, sysmem 0, peer 1, physical links 6, portdev0 0, 1, 2, 3, portDev1 4, 5, -1, -1, bandwidth 18446744073709551615
......
typeDev0 1, typeDev1 1, sysmem 0, peer 1, physical links 6, portdev0 0, 1, 2, 3, portDev1 4, 5, -1, -1, bandwidth 18446744073709551615
typeDev0 1, typeDev1 1, sysmem 0, peer 1, physical links 6, portdev0 0, 1, 2, 3, portDev1 4, 5, -1, -1, bandwidth 18446744073709551615
Data tranferred between Device 0 & Device 1 :
nvlink_total_data_transmitted = 24.2 MB
nvlink_total_data_received = 33.8 MB
nvlink_transmit_throughput = 225.1 GB/Sec
nvlink_receive_throughput = 314.7 GB/Sec
`
I don't know the result whether you want. Thanks again for your reply

**Comment by AddyLaddy** [comment]
The CUDA p2p_bandwidth test can also be downloaded and compiled from the github code; https://github.com/NVIDIA/cuda-samples/tree/master/Samples/p2pBandwidthLatencyTest

**Comment by lljjgg** [comment]
> The CUDA p2p_bandwidth test can also be downloaded and compiled from the github code; https://github.com/NVIDIA/cuda-samples/tree/master/Samples/p2pBandwidthLatencyTest

Thank you for your advice

**Comment by sjeaugey** [comment]
OK this is strange. CUDA samples do enable P2P (and perf is normal) but it fails in NCCL. Can you run the NCCL tests on only 2 GPUs (`-g 2`) and with debug enabled (`NCCL_DEBUG=INFO`) ?

**Comment by lljjgg** [comment]
Hi sjeaugey:
        I am so sorry,I haven't replied to you for such a long time,due to my computer of v100 can't work in these time.I run the program in debug mode all the time.I run it with cuda-gdb.Or I misunderstood you.This is output whitout debug.May My description is not clear enough.But I wonder how you judge that P2P is not available.
'''
# nThread 1 nGpus 2 minBytes 16 maxBytes 1073741824 step: 2(factor) warmup iters: 5 iters: 20 validation: 1
#
# Using devices
#   Rank  0 Pid  21183 on 51e6e7896958 device  0 [0x1a] Tesla V100-SXM3-32GB
#   Rank  1 Pid  21183 on 51e6e7896958 device  1 [0x1b] Tesla V100-SXM3-32GB
#
#                                                     out-of-place                       in-place
#       size         count    type   redop     time   algbw   busbw  error     time   algbw   busbw  error
#        (B)    (elements)                     (us)  (GB/s)  (GB/s)            (us)  (GB/s)  (GB/s)
          16             4   float     sum    10.01    0.00    0.00  0e+00     9.89    0.00    0.00  0e+00
          32             8   float     sum     9.90    0.00    0.00  0e+00     9.72    0.00    0.00  0e+00
          64            16   float     sum    10.01    0.01    0.01  0e+00     9.73    0.01    0.01  0e+00
         128            32   float     sum     9.76    0.01    0.01  0e+00     9.78    0.01    0.01  0e+00
         256            64   float     sum     9.83    0.03    0.03  0e+00     9.77    0.03    0.03  0e+00
         512           128   float     sum    10.06    0.05    0.05  0e+00     9.89    0.05    0.05  0e+00
        1024           256   float     sum     9.82    0.10    0.10  0e+00     9.82    0.10    0.10  0e+00
        2048           512   float     sum     9.89    0.21    0.21  0e+00     9.93    0.21    0.21  0e+00
        4096          1024   float     sum    10.18    0.40    0.40  0e+00    10.05    0.41    0.41  0e+00
        8192          2048   float     sum    11.92    0.69    0.69  0e+00    11.59    0.71    0.71  0e+00
       16384          4096   float     sum    15.14    1.08    1.08  0e+00    14.88    1.10    1.10  0e+00
       32768          8192   float     sum    17.57    1.87    1.87  0e+00    17.30    1.89    1.89  0e+00
       65536         16384   float     sum    22.43    2.92    2.92  0e+00    22.28    2.94    2.94  0e+00
      131072         32768   float     sum    29.89    4.39    4.39  0e+00    29.56    4.43    4.43  0e+00
      262144         65536   float     sum    45.06    5.82    5.82  0e+00    44.89    5.84    5.84  0e+00
      524288        131072   float     sum    50.45   10.39   10.39  0e+00    49.63   10.56   10.56  0e+00
     1048576        262144   float     sum    64.89   16.16   16.16  0e+00    63.56   16.50   16.50  0e+00
     2097152        524288   float     sum    81.96   25.59   25.59  0e+00    80.47   26.06   26.06  0e+00
     4194304       1048576   float     sum    116.9   35.87   35.87  0e+00    115.8   36.22   36.22  0e+00
     8388608       2097152   float     sum    112.4   74.60   74.60  0e+00    112.0   74.89   74.89  0e+00
    16777216       4194304   float     sum    180.7   92.86   92.86  0e+00    177.1   94.75   94.75  0e+00
    33554432       8388608   float     sum    313.6  106.99  106.99  0e+00    312.9  107.23  107.23  0e+00
    67108864      16777216   float     sum    593.9  113.00  113.00  0e+00    592.5  113.27  113.27  0e+00
   134217728      33554432   float     sum   1141.9  117.53  117.53  0e+00   1137.9  117.95  117.95  0e+00
   268435456      67108864   float     sum   2234.0  120.16  120.16  0e+00   2233.5  120.18  120.18  0e+00
   536870912     134217728   float     sum   4416.8  121.55  121.55  0e+00   4419.2  121.49  121.49  0e+00
  1073741824     268435456   float     sum   8784.9  122.23  122.23  0e+00   8788.8  122.17  122.17  0e+00
# Out of bounds values : 0 OK
# Avg bus bandwidth    : 36.176
'''

**Comment by sjeaugey** [comment]
The output does not contain debug information. You would need to add `NCCL_DEBUG=INFO` on the command line, e.g. :
```
NCCL_DEBUG=INFO ./build/all_reduce_perf -g 2 -b 8 -e 1G -f 2
```
Or add `-x NCCL_DEBUG=INFO` to your `mpirun` command.

Anyway, the performance you report on your last comment shows 122 GB/s. That is as good as it can be; you were initially reporting 3.47 GB/s on 4 GPUs. Did something change on your system ? Can you run again on 4 or 8 GPUs and see if you see 122 GB/s as well ?

**Comment by lljjgg** [comment]
Before in order to run the program with cuda-gdb, compile program with``` -O0 -g -G -ggdb3```.l'm sorry that I may not have described it clearly ago.I run it on 8 gpu can get 120GB/s as well. This is output with debug.
```
# nThread 1 nGpus 2 minBytes 8 maxBytes 1073741824 step: 2(factor) warmup iters: 5 iters: 20 validation: 1
#
# Using devices
#   Rank  0 Pid  34902 on 51e6e7896958 device  0 [0x1a] Tesla V100-SXM3-32GB
#   Rank  1 Pid  34902 on 51e6e7896958 device  1 [0x1b] Tesla V100-SXM3-32GB
51e6e7896958:34902:34902 [0] NCCL INFO Bootstrap : Using [0]eth0:172.17.0.3<0>
51e6e7896958:34902:34902 [0] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so).

51e6e7896958:34902:34902 [0] misc/ibvwrap.cc:63 NCCL WARN Failed to open libibverbs.so[.1]
51e6e7896958:34902:34902 [0] NCCL INFO NET/Socket : Using [0]eth0:172.17.0.3<0>
NCCL version 2.4.8+cuda10.1
51e6e7896958:34902:34902 [1] NCCL INFO nranks 2
51e6e7896958:34902:34902 [0] NCCL INFO Setting affinity for GPU 0 to ffffff
51e6e7896958:34902:34902 [1] NCCL INFO Setting affinity for GPU 1 to ffffff
51e6e7896958:34902:34902 [1] NCCL INFO Using 256 threads, Min Comp Cap 7, Trees disabled
51e6e7896958:34902:34902 [1] NCCL INFO Channel 00 :    0   1
51e6e7896958:34902:34902 [1] NCCL INFO Channel 01 :    0   1
51e6e7896958:34902:34902 [1] NCCL INFO Channel 02 :    0   1
51e6e7896958:34902:34902 [1] NCCL INFO Channel 03 :    0   1
51e6e7896958:34902:34902 [1] NCCL INFO Channel 04 :    0   1
51e6e7896958:34902:34902 [1] NCCL INFO Channel 05 :    0   1
51e6e7896958:34902:34902 [1] NCCL INFO Channel 06 :    0   1
51e6e7896958:34902:34902 [1] NCCL INFO Channel 07 :    0   1
51e6e7896958:34902:34902 [1] NCCL INFO Channel 08 :    0   1
51e6e7896958:34902:34902 [1] NCCL INFO Channel 09 :    0   1
51e6e7896958:34902:34902 [1] NCCL INFO Channel 10 :    0   1
51e6e7896958:34902:34902 [1] NCCL INFO Channel 11 :    0   1
51e6e7896958:34902:34902 [0] NCCL INFO Ring 00 : 0[0] -> 1[1] via P2P/direct pointer
51e6e7896958:34902:34902 [1] NCCL INFO Ring 00 : 1[1] -> 0[0] via P2P/direct pointer
51e6e7896958:34902:34902 [0] NCCL INFO Ring 01 : 0[0] -> 1[1] via P2P/direct pointer
51e6e7896958:34902:34902 [1] NCCL INFO Ring 01 : 1[1] -> 0[0] via P2P/direct pointer
51e6e7896958:34902:34902 [0] NCCL INFO Ring 02 : 0[0] -> 1[1] via P2P/direct pointer
51e6e7896958:34902:34902 [1] NCCL INFO Ring 02 : 1[1] -> 0[0] via P2P/direct pointer
51e6e7896958:34902:34902 [0] NCCL INFO Ring 03 : 0[0] -> 1[1] via P2P/direct pointer
51e6e7896958:34902:34902 [1] NCCL INFO Ring 03 : 1[1] -> 0[0] via P2P/direct pointer
51e6e7896958:34902:34902 [0] NCCL INFO Ring 04 : 0[0] -> 1[1] via P2P/direct pointer
51e6e7896958:34902:34902 [1] NCCL INFO Ring 04 : 1[1] -> 0[0] via P2P/direct pointer
51e6e7896958:34902:34902 [0] NCCL INFO Ring 05 : 0[0] -> 1[1] via P2P/direct pointer
51e6e7896958:34902:34902 [1] NCCL INFO Ring 05 : 1[1] -> 0[0] via P2P/direct pointer
51e6e7896958:34902:34902 [0] NCCL INFO Ring 06 : 0[0] -> 1[1] via P2P/direct pointer
51e6e7896958:34902:34902 [1] NCCL INFO Ring 06 : 1[1] -> 0[0] via P2P/direct pointer
51e6e7896958:34902:34902 [0] NCCL INFO Ring 07 : 0[0] -> 1[1] via P2P/direct pointer
51e6e7896958:34902:34902 [1] NCCL INFO Ring 07 : 1[1] -> 0[0] via P2P/direct pointer
51e6e7896958:34902:34902 [0] NCCL INFO Ring 08 : 0[0] -> 1[1] via P2P/direct pointer
51e6e7896958:34902:34902 [1] NCCL INFO Ring 08 : 1[1] -> 0[0] via P2P/direct pointer
51e6e7896958:34902:34902 [0] NCCL INFO Ring 09 : 0[0] -> 1[1] via P2P/direct pointer
51e6e7896958:34902:34902 [1] NCCL INFO Ring 09 : 1[1] -> 0[0] via P2P/direct pointer
51e6e7896958:34902:34902 [0] NCCL INFO Ring 10 : 0[0] -> 1[1] via P2P/direct pointer
51e6e7896958:34902:34902 [1] NCCL INFO Ring 10 : 1[1] -> 0[0] via P2P/direct pointer
51e6e7896958:34902:34902 [0] NCCL INFO Ring 11 : 0[0] -> 1[1] via P2P/direct pointer
51e6e7896958:34902:34902 [1] NCCL INFO Ring 11 : 1[1] -> 0[0] via P2P/direct pointer
#
#                                                     out-of-place                       in-place
#       size         count    type   redop     time   algbw   busbw  error     time   algbw   busbw  error
#        (B)    (elements)                     (us)  (GB/s)  (GB/s)            (us)  (GB/s)  (GB/s)
51e6e7896958:34902:34902 [0] NCCL INFO Launch mode Group/CGMD
           8             2   float     sum     9.34    0.00    0.00  0e+00     9.31    0.00    0.00  0e+00
          16             4   float     sum     9.32    0.00    0.00  0e+00     9.29    0.00    0.00  0e+00
          32             8   float     sum     9.28    0.00    0.00  0e+00     9.20    0.00    0.00  0e+00
          64            16   float     sum     9.25    0.01    0.01  0e+00     9.34    0.01    0.01  0e+00
         128            32   float     sum     9.24    0.01    0.01  0e+00     9.28    0.01    0.01  0e+00
         256            64   float     sum     9.43    0.03    0.03  0e+00     9.23    0.03    0.03  0e+00
         512           128   float     sum     9.26    0.06    0.06  0e+00     9.24    0.06    0.06  0e+00
        1024           256   float     sum     9.33    0.11    0.11  0e+00     9.27    0.11    0.11  0e+00
        2048           512   float     sum     9.31    0.22    0.22  0e+00     9.34    0.22    0.22  0e+00
        4096          1024   float     sum     9.51    0.43    0.43  0e+00     9.38    0.44    0.44  0e+00
        8192          2048   float     sum    11.45    0.72    0.72  0e+00    11.19    0.73    0.73  0e+00
       16384          4096   float     sum    11.53    1.42    1.42  0e+00    11.29    1.45    1.45  0e+00
       32768          8192   float     sum    11.54    2.84    2.84  0e+00    11.31    2.90    2.90  0e+00
       65536         16384   float     sum    13.76    4.76    4.76  0e+00    13.38    4.90    4.90  0e+00
      131072         32768   float     sum    15.82    8.28    8.28  0e+00    15.43    8.49    8.49  0e+00
      262144         65536   float     sum    23.31   11.25   11.25  0e+00    23.21   11.29   11.29  0e+00
      524288        131072   float     sum    31.91   16.43   16.43  0e+00    30.91   16.96   16.96  0e+00
     1048576        262144   float     sum    36.19   28.97   28.97  0e+00    35.64   29.42   29.42  0e+00
     2097152        524288   float     sum    48.02   43.67   43.67  0e+00    46.59   45.01   45.01  0e+00
     4194304       1048576   float     sum    68.49   61.24   61.24  0e+00    67.09   62.52   62.52  0e+00
     8388608       2097152   float     sum    107.1   78.35   78.35  0e+00    107.3   78.18   78.18  0e+00
    16777216       4194304   float     sum    179.5   93.46   93.46  0e+00    179.5   93.46   93.46  0e+00
    33554432       8388608   float     sum    319.8  104.91  104.91  0e+00    318.1  105.49  105.49  0e+00
    67108864      16777216   float     sum    626.5  107.12  107.12  0e+00    612.4  109.58  109.58  0e+00
   134217728      33554432   float     sum   1188.8  112.90  112.90  0e+00   1183.7  113.39  113.39  0e+00
   268435456      67108864   float     sum   2326.1  115.40  115.40  0e+00   2321.0  115.66  115.66  0e+00
   536870912     134217728   float     sum   4552.5  117.93  117.93  0e+00   4553.2  117.91  117.91  0e+00
  1073741824     268435456   float     sum   8979.4  119.58  119.58  0e+00   8980.2  119.57  119.57  0e+00
# Out of bounds values : 0 OK
# Avg bus bandwidth    : 36.9265
#

```

**Comment by sjeaugey** [comment]
Hum, so you mean compiling with debug was the cause for performance being so low ? Could be, but I was susprised to see `Cuda API error detected: cudaDeviceEnablePeerAccess returned (0x2c0)`. That would indicate that P2P was not used and that would indeed result in bad performance. Now with your latest runs, P2P is used and performance is normal.

Anyway, feel free to close if all is back to normal. Thanks.

**Comment by lljjgg** [comment]
Hi.Recently I was testing the speed of the program.I find the fastest busbw is 122 with 8 gpu in NVswitch But the busbw is 130 with 8 gpu in the NVlink.  Is this normal?The nvswitch is slower than nvlink when running the program with 8 gpu. 
        Looking forward to your reply，Thanks

**Comment by sjeaugey** [comment]
It is expected. NVswitch has a slightly higher overhead compared to point-to-point NVlink. On the other hand, it delivers a consistent 120 GB/s from 2 to 16 GPUs while point-to-point only gives you full bandwidth when running on 8 GPUs.

**Comment by lljjgg** [comment]
Thank you for your reply.I recently found out that the p2pLevel is PATH_NODE for PCIE when I was studying code.But I want to close the p2p when there is only PCIE.Can I change this default configuration?What should I do if I can.
