### ISSUE TITLE
gencode for arch 6.1

### ISSUE THREAD

**Issue by soumith** [NVIDIA/nccl#26]
architecture 6.1 is missing for the GTX1080 cards here:
https://github.com/NVIDIA/nccl/blob/master/Makefile#L41

as reported here: https://github.com/torch/cunn/issues/289

**Comment by borisfom** [comment]
Fixed in last release:

I have  published updated versions of both 7.5 and 8.0 packages for  NCCL:
https://github.com/NVIDIA/nccl/releases/tag/v1.2.2-1%2Bcuda8.0
https://github.com/NVIDIA/nccl/releases/tag/v1.2.2-1%2Bcuda7.5

**Comment by soumith** [comment]
Thanks Boris.
