### ISSUE TITLE
Concerning the Environment Variables in NCCL

### ISSUE THREAD

**Issue by chrishkchris** [NVIDIA/nccl#260]
I am using NCCL for multi-node allreduce. I am trying to tune the performance using the environment variables https://docs.nvidia.com/deeplearning/sdk/nccl-developer-guide/docs/env.html

Is it necessary to export the environment variable to multiple nodes, or it uses the environment at rank 0 only? In my previous test, I did not export the environment variable using mpi, but it seems to be working (I am not sure not exporting the environment variables is okay). 

Thanks a lot!

**Comment by AddyLaddy** [comment]
You need to export the environment variables to all nodes and processes - either by using a resource manager such as SLURM or via the mpirun -x option

**Comment by chrishkchris** [comment]
I see. Thanks a lot for your reply!
