### ISSUE TITLE
Missing tags between v2.4.2-1 and v2.4.6-1

### ISSUE THREAD

**Issue by jakirkham** [NVIDIA/nccl#263]
Appears there are no tags for releases between `v2.4.2-1` and `v2.4.6-1`. Would it be possible to include them?

**Comment by sjeaugey** [comment]
That's because there are no commits between 2.4.2 and 2.4.6. We don't push all intermediate (=broken) versions to github, only the ones that are stable.

**Comment by jakirkham** [comment]
Good to know. Let's go ahead and close this then.
