### ISSUE TITLE
New release (v2.4.9-1 ?)

### ISSUE THREAD

**Issue by jakirkham** [NVIDIA/nccl#264]
Would be great to have a new release of NCCL. In particular would be great to have a release including commit ( https://github.com/NVIDIA/nccl/commit/7f2b337e703d73ed369937c9996e1f3d5f664ad0 ).

**Comment by AddyLaddy** [comment]
That commit is in the NCCL 2.5.4-1 branch; https://github.com/NVIDIA/nccl/blob/67436391dc4614ff6eb284c254bdb59513fb6982/src/include/socket.h#L332

**Comment by jakirkham** [comment]
Ah I see that is pending release. ( https://github.com/NVIDIA/nccl/pull/255 ).

Given how small this commit is, would it be possible to have a 2.4 patch release with that change? Appears to be in `master` already. Also it's very useful (as you say) for building on older systems. 🙂

**Comment by AddyLaddy** [comment]
It's also committed to the master branch on top of the NCCL 2.4.8-1 release but we don't have a new tag for it

**Comment by jakirkham** [comment]
Yep, that's why I was hoping we could get a new 2.4 tag. Would that be reasonable to do?

**Comment by jakirkham** [comment]
Thoughts? 😉

**Comment by AddyLaddy** [comment]
@sjeaugey Any comment ?

**Comment by sjeaugey** [comment]
Closing since 2.5.6 has been merged.
