### ISSUE TITLE
Building NCCL from source on Power8 system

### ISSUE THREAD

**Issue by ghltshubh** [NVIDIA/nccl#266]
I am trying to build nccl 2.4.8-1 for IBM power8, CUDA 9.2 but getting this on my console: `/usr/bin/uuidgen: /gpfs/alpine/world-shared/gen011/shubhankar/summitdev/anaconda3/lib/libuuid.so.1: no version information available (required by /usr/bin/uuidgen)
`

**Comment by sjeaugey** [comment]
This is strange, but it doesn't seem related to NCCL. Is nvcc working correctly ?
