### ISSUE TITLE
neighborhood collectives 

### ISSUE THREAD

**Issue by xiaodong-yu** [NVIDIA/nccl#270]
Dear NCCL team,

I'm new to this library. I'm wondering does the current version provide neighborhood collectives APIs? If not, is it easy to use existing NCCL APIs to realize the neighborhood communication?

Besides, I'm now playing with nccl-tests; is that possible to printout what topology nccl uses on my server (ring or tree?) and how my devices are placed and connected? Thank you so much in advance!

**Comment by sjeaugey** [comment]
Hi,

We do not provide neighbor collectives yet. That functionality would come when we add ncclSend/ncclRecv as tracked in #212 : using ncclSend/ncclRecv and ncclGroupStart/ncclGroupEnd, you would be able to express any neighbor collective as a set of concurrent individual sends and receives.

To print the topology and tuning, you would need to set `NCCL_DEBUG=INFO NCCL_DEBUG_SUBSYS=GRAPH,TUNING`. `GRAPH` will show you the server topology and intra-node path(s) NCCL is using. `TUNING` will show you the {tree,ring}×{ll,ll128,simple} latencies and bandwidth used to decide when each combination is used. You can also set `NCCL_ALGO=RING` or `NCCL_ALGO=TREE` to force one algorithm or the other.

**Comment by xiaodong-yu** [comment]
Hi Sylvain,

Thank you so much for your detailed reply! I tried the DEBUG mode, the test programs print out multiple following warnings:
![image](https://user-images.githubusercontent.com/28902368/70261356-dfa5cc80-1757-11ea-9317-0aa1f7dd013c.png)
Does it mean the NCCL actually can't form a ring or tree? And what does the simple order mean? Thank you so much!

**Comment by sjeaugey** [comment]
OK. The fallback to "simple order" is actually 0,1,2,3,4,5,6,7 which should be the best for your PCI topology. But the search should easily find a pattern on such a simple hardware topology ... I don't understand why it doesn't. There is something weird here.

If you can reduce the problem (e.g. launching on less GPUs) and paste the full log that would be helpful.

**Comment by xiaodong-yu** [comment]
I test the program with different numbers of GPUs (4,6,8). I attach the log info as .txt files.
[gpu=6.txt](https://github.com/NVIDIA/nccl/files/3928924/gpu.6.txt)
[gpu=8.txt](https://github.com/NVIDIA/nccl/files/3928925/gpu.8.txt)


[gpu=4.txt](https://github.com/NVIDIA/nccl/files/3928907/gpu.4.txt)
It looks like when GPU number is reduced, the path for pattern 2 warning disappears but the pattern 4 warning still exists.

**Comment by sjeaugey** [comment]
I see, you are using 8x RTX 2080 Ti. According to https://devtalk.nvidia.com/default/topic/1046951/cuda-programming-and-performance/does-titan-rtx-support-p2p-access-w-o-nvlink-/ , we won't be able to use GPU Direct P2P through PCI (only through NVLink).

That means NCCL has to communicate through CPU memory and performance will go down as you increase the number of GPUs since the same PCI link will be used and CPU memory bandwidth is quite limited. The `WARN` should disappear in the next version (it's a side effect of the computed bandwidth dropping below 3 GB/s) but the performance will remain low.

**Comment by xiaodong-yu** [comment]
Get it. In my case, the NCCL actually uses a simple-order ring 0-1-2-3-4-5-6-7-0, or it doesn't use any ring path? The debug info seems don't specify the paths.

**Comment by sjeaugey** [comment]
It should use that in-order ring. And the performance you get is consistent with that.

**Comment by xiaodong-yu** [comment]
Clear. Thank you so much for your answers!
