### ISSUE TITLE
P2P Samples

### ISSUE THREAD

**Issue by wschin** [NVIDIA/nccl#273]
Do you have any document/sample for P2P communication? I saw the keyword P2P in [some slides](http://on-demand.gputechconf.com/gtc/2018/presentation/s8462-multi-gpu-training-with-nccl.pdf) for NCCL >= 2.4 but it's difficult to actually use it. Thanks.

**Comment by sjeaugey** [comment]
P2P means GPU Direct P2P, which is direct GPU to GPU communication, through PCI or NVLink, as CUDA allows (https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__PEER.html).

A sample test can be found in /usr/local/cuda/samples/1_Utilities/p2pBandwidthLatencyTest.

**Comment by wschin** [comment]
Ah ok. I thought P2P means cross-machine communication. Many thanks.
