### ISSUE TITLE
NCCL Error 4: invalid argument

### ISSUE THREAD

**Issue by chi0tzp** [NVIDIA/nccl#276]
I'm trying to use PyTorch `DataParallel` with CUDA 10.2 (`cuda-10.2.89-1`) and NCCL 2.5 (`nccl-2.5.6-1`). PyTorch version: `python-pytorch-cuda-1.3.1-4`. (I'm on Arch Linux)

Running my code using `NCCL_DEBUG=INFO` gives:

```
YYY:2396:2428 [0] NCCL INFO Bootstrap : Using [0]enp0s25:x.x.x.x<0>
YYY:2396:2428 [0] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation

YYY:2396:2428 [0] misc/ibvwrap.cc:63 NCCL WARN Failed to open libibverbs.so[.1]
YYY:2396:2428 [0] NCCL INFO NET/Socket : Using [0]enp0s25:x.x.x.x<0>
NCCL version 2.5.6+cuda10.2

YYY:2396:2428 [0] misc/argcheck.cc:40 NCCL WARN Reduce : invalid root 0 (root should be in the 0..0 range)
YYY:2396:2428 [0] NCCL INFO enqueue.cc:447 -> 4

YYY:2396:2428 [0] init.cc:840 NCCL WARN comm 0x7fdee40000c0 has already been destroyed
YYY:2396:2428 [0] NCCL INFO group.cc:184 -> 4
terminate called after throwing an instance of 'std::runtime_error'
  what():  NCCL Error 4: invalid argument
Aborted (core dumped)

```

**Comment by AddyLaddy** [comment]
Do you have this fix applied to your Pytorch environment?
https://github.com/pytorch/pytorch/pull/29014

**Comment by chi0tzp** [comment]
@AddyLaddy No, I wasn't aware of that. Thank you!

**Comment by sjeaugey** [comment]
Combining Init with Collectives inside an aggregated call was never intended to be correct. It happened to work before out of luck. Maybe we could make it functional inside NCCL -- not sure.

**Comment by chi0tzp** [comment]
Also take a look here: https://github.com/pytorch/pytorch/issues/31045
