### ISSUE TITLE
How to close p2p 

### ISSUE THREAD

**Issue by lljjgg** [NVIDIA/nccl#277]
I recently found out that the p2pLevel is PATH_NODE for PCIE when I was studying code.But I want to close the p2p when there is only PCIE.Can I change this default configuration?What should I do if I can.Looking forward to your reply,Thanks

**Comment by keisukefukuda** [comment]
Does `NCCL_P2P_DISABLE` env var help?

**Comment by lljjgg** [comment]
I'am so sorry.I don't find this function in nccl.Maybe this is my version of the program?And I'd like to ask you another question.The cluster is equipped with both Nvlink and PCIe. All the GPUs(V100) can communicate directly through both PCIe or NvLink.When we don't want use Peer-to-Peer transfers(NVSwitch), then data transfers (e.g. cudaMemcpy, cudaMemcpyAsync, cudaMemcpyPeerAsync) between those two devices will flow from the source GPU over PCIE to the CPU socket, (perhaps traversing intermediate PCIE switches, perhaps also flowing over a socket-level link such as QPI) and then over PCIE from the CPU socket to the other GPU.May the function of NCCL_P2P_DISABLE can make nccl  get a similar transmission? Or nccl can Break cuda restrictions and can specify one use p2p communication beturn PCIE and NVswitch.Looking forward to your reply,Thanks

**Comment by sjeaugey** [comment]
The `PATH_NODE` default you refer to is the P2P level. You can change it with the `NCCL_P2P_LEVEL` environment variable, as documented here :
https://docs.nvidia.com/deeplearning/sdk/nccl-developer-guide/docs/env.html#nccl-p2p-level

However, even with `NCCL_P2P_LEVEL=1`, GPUs connected to the same PCI switch (and with no NVLink between them) will use PCI for communication. We do not have a level currently to communicate only through NVLink.

**Comment by lljjgg** [comment]
Your reply is very helpful to me,Thanks.But I'm a little confused.If I set the NCCL_P2P_DISABLE =1,the p2p will be disabled,Does it mean that nvlink and PCIE(switch) is disabled and the GPUs connected will use shm?

**Comment by sjeaugey** [comment]
Yes `NCCL_P2P_DISABLE=1` will completely disable P2P, even through NVLink, using shared memory instead. Which is why I believe what you are looking for is `NCCL_P2P_LEVEL`. `NCCL_P2P_DISABLE=1` is equivalent to `NCCL_P2P_LEVEL=0`. Setting `NCCL_P2P_LEVEL` to 1, you will still use NVLink. But you might also use it through PCI switches if you have GPUs on the same PCI switch and without NVLink.

**Comment by sjeaugey** [comment]
Closing as I think the question has been answered.
