### ISSUE TITLE
MPI_test failed using cuda 7.5

### ISSUE THREAD

**Issue by Laurawly** [NVIDIA/nccl#28]
Dear NCCL developers,

I got a confusing error message when trying to run mpi_test.

I build mpi_test using $ make CUDA_HOME=/usr/local/cuda MPI_HOME=$WORK_PATH/openmpi mpitest

And then $ export PATH=$PATH:./build/test/mpi/
 
And when I run the test using $ mpirun -np 2 mpi_test 0 1 (there are 4 gpus in the machine), I got the follwoing message:

*** stack smashing detected ***: mpi_test terminated
[snake07:16792] *** Process received signal ***
[snake07:16792] Signal: Aborted (6)
[snake07:16792] Signal code:  (-6)
[snake07:16792] [ 0] /lib/x86_64-linux-gnu/libc.so.6(+0x36cb0)[0x7f1ffd7c7cb0]
[snake07:16792] [ 1] /lib/x86_64-linux-gnu/libc.so.6(gsignal+0x37)[0x7f1ffd7c7c37]
[snake07:16792] [ 2] /lib/x86_64-linux-gnu/libc.so.6(abort+0x148)[0x7f1ffd7cb028]
[snake07:16792] [ 3] /lib/x86_64-linux-gnu/libc.so.6(+0x732a4)[0x7f1ffd8042a4]
[snake07:16792] [ 4] /lib/x86_64-linux-gnu/libc.so.6(__fortify_fail+0x5c)[0x7f1ffd89bbbc]
[snake07:16792] [ 5] /lib/x86_64-linux-gnu/libc.so.6(__fortify_fail+0x0)[0x7f1ffd89bb60]
[snake07:16792] [ 6] /net/mlfs01/export/users/leywang/openmpi/lib/libopen-pal.so.13(+0x7e315)[0x7f1ffd0a5315]
[snake07:16792] [ 7] /net/mlfs01/export/users/leywang/openmpi/lib/libopen-pal.so.13(opal_hwloc191_hwloc_backends_notify_new_object+0x41)[0x7f1ffd0a0291]
[snake07:16792] [ 8] /net/mlfs01/export/users/leywang/openmpi/lib/libopen-pal.so.13(opal_hwloc191_hwloc_insert_pci_device_list+0x1b5)[0x7f1ffd0a47d5]
[snake07:16792] [ 9] /net/mlfs01/export/users/leywang/openmpi/lib/libopen-pal.so.13(+0x821fc)[0x7f1ffd0a91fc]
[snake07:16792] [10] /net/mlfs01/export/users/leywang/openmpi/lib/libopen-pal.so.13(opal_hwloc191_hwloc_topology_load+0x29d)[0x7f1ffd0c6abd]
[snake07:16792] [11] /net/mlfs01/export/users/leywang/openmpi/lib/libopen-pal.so.13(opal_hwloc_base_get_topology+0xe2)[0x7f1ffd0991d2]
[snake07:16792] [12] /net/mlfs01/export/users/leywang/openmpi/lib/libmpi.so(ompi_mpi_init+0x5dd)[0x7f20046f7b2d]
[snake07:16792] [13] /net/mlfs01/export/users/leywang/openmpi/lib/libmpi.so(MPI_Init+0x16b)[0x7f20047176eb]
[snake07:16792] [14] mpi_test[0x4014e4]
[snake07:16792] [15] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf5)[0x7f1ffd7b2f45]
[snake07:16792] [16] mpi_test[0x401c77]
[snake07:16792] *** End of error message ***
*** stack smashing detected ***: mpi_test terminated
[snake07:16793] *** Process received signal ***
[snake07:16793] Signal: Aborted (6)
[snake07:16793] Signal code:  (-6)
[snake07:16793] [ 0] /lib/x86_64-linux-gnu/libc.so.6(+0x36cb0)[0x7f975342fcb0]
[snake07:16793] [ 1] /lib/x86_64-linux-gnu/libc.so.6(gsignal+0x37)[0x7f975342fc37]
[snake07:16793] [ 2] /lib/x86_64-linux-gnu/libc.so.6(abort+0x148)[0x7f9753433028]
[snake07:16793] [ 3] /lib/x86_64-linux-gnu/libc.so.6(+0x732a4)[0x7f975346c2a4]
[snake07:16793] [ 4] /lib/x86_64-linux-gnu/libc.so.6(__fortify_fail+0x5c)[0x7f9753503bbc]
[snake07:16793] [ 5] /lib/x86_64-linux-gnu/libc.so.6(__fortify_fail+0x0)[0x7f9753503b60]
[snake07:16793] [ 6] /net/mlfs01/export/users/leywang/openmpi/lib/libopen-pal.so.13(+0x7e315)[0x7f9752d0d315]
[snake07:16793] [ 7] /net/mlfs01/export/users/leywang/openmpi/lib/libopen-pal.so.13(opal_hwloc191_hwloc_backends_notify_new_object+0x41)[0x7f9752d08291]
[snake07:16793] [ 8] /net/mlfs01/export/users/leywang/openmpi/lib/libopen-pal.so.13(opal_hwloc191_hwloc_insert_pci_device_list+0x1b5)[0x7f9752d0c7d5]
[snake07:16793] [ 9] /net/mlfs01/export/users/leywang/openmpi/lib/libopen-pal.so.13(+0x821fc)[0x7f9752d111fc]
[snake07:16793] [10] /net/mlfs01/export/users/leywang/openmpi/lib/libopen-pal.so.13(opal_hwloc191_hwloc_topology_load+0x29d)[0x7f9752d2eabd]
[snake07:16793] [11] /net/mlfs01/export/users/leywang/openmpi/lib/libopen-pal.so.13(opal_hwloc_base_get_topology+0xe2)[0x7f9752d011d2]
[snake07:16793] [12] /net/mlfs01/export/users/leywang/openmpi/lib/libmpi.so(ompi_mpi_init+0x5dd)[0x7f975a35fb2d]
[snake07:16793] [13] /net/mlfs01/export/users/leywang/openmpi/lib/libmpi.so(MPI_Init+0x16b)[0x7f975a37f6eb]
[snake07:16793] [14] mpi_test[0x4014e4]
[snake07:16793] [15] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf5)[0x7f975341af45]
[snake07:16793] [16] mpi_test[0x401c77]
[snake07:16793] *** End of error message ***

I don't get any clue from the error message. Could you help me?

**Comment by sjeaugey** [comment]
Can you give us more details on which version of Open MPI you are using ?

Also, is the MPI lib working correctly (with an hello world program) ? It seems to me that the error is in MPI_Init and therefore before NCCL is even initialized.

I think I've already seen that error before.

**Comment by Laurawly** [comment]
Hi,

Thanks for your reply. The Open MPI I'm using is 1.10.2. And mpirun works fine for basic hello world program. I've tested using code from https://github.com/wesleykendall/mpitutorial.

**Comment by Laurawly** [comment]
I've found the error. It's the reason of MPI installation. I didn't export the correct mpirun and mpicc path.

**Comment by sjeaugey** [comment]
Thank you for following up. Glad you found the problem !
