### ISSUE TITLE
Variable name typo? "slice" must be "chunk" in AllReduceRingKernel

### ISSUE THREAD

**Issue by aokomoriuta** [NVIDIA/nccl#287]
https://github.com/NVIDIA/nccl/blob/3701130b3c1bcdb01c14b3cb70fe52498c1e82b7/src/collectives/device/all_reduce.h#L40

This variable name seems to be "chunk", not "slice".

According to later lines, e.g., https://github.com/NVIDIA/nccl/blob/3701130b3c1bcdb01c14b3cb70fe52498c1e82b7/src/collectives/device/all_reduce.h#L43-L47, the "slice" variable is set to the rank number.
And the "offset", which is used to calculate the head pointer of sending data whose size is chunkSize, is calculated as `chunkOffset + slice * chunkSize`.

Those must say that the "slice" variable represents a **chunk** number, not a slice number.
Generally speaking, a expression `offsetX + numberX*sizeX` naturally must represent the head of X.

Additionally, the term "slice" means the number of send/recv on the `primitives::GenericOp` https://github.com/NVIDIA/nccl/blob/299c554dccf923230321ad7495946543f3e9b457/src/collectives/device/primitives.h#L189 .
The meaning is different from the code on the `AllReduceRingKernel`.

Am I wrong? or may I send PR to fix this?

**Comment by sjeaugey** [comment]
Indeed, `chunk` might be a better name for it. I don't remember the history for that, but in any case, I won't complain if the code is easier to understand.

Feel free to submit a PR; just make sure to check the other operations as well (reduce_scatter and all_gather in particular).

**Comment by sjeaugey** [comment]
Merged. Sorry for the delay.
