### ISSUE TITLE
Build error __builtin_ia32_monitorx is undefined solution

### ISSUE THREAD

**Issue by superphil0** [NVIDIA/nccl#29]
Distro: Linux 4.2.6-300.fc23.x86_64 

/usr/lib/gcc/x86_64-redhat-linux/5.3.1/include/mwaitxintrin.h(36): error: identifier "__builtin_ia32_monitorx" is undefined

/usr/lib/gcc/x86_64-redhat-linux/5.3.1/include/mwaitxintrin.h(42): error: identifier "__builtin_ia32_mwaitx" is undefined

However when I add the CXX flags:
-D_MWAITXINTRIN_H_INCLUDED
-D_FORCE_INLINES
-D__STRICT_ANSI__

the build completes successfully see here: 
https://github.com/tensorflow/tensorflow/issues/1066

**Comment by sjeaugey** [comment]
Thanks for the workaround, that can be helpful indeed !

CUDA 7.5 is not supported on FC23, and that's likely the reason why the compilation fails. So you could either downgrade to FC21 or upgrade to CUDA 8.0(RC) to avoid that problem.

**Comment by mrluker** [comment]
Where do you add those cxx flags?

**Comment by root29** [comment]
Hi, Should I add cxx flag into makefile or CMakeLists? THANKS!
@superphil0 @sjeaugey

**Comment by superphil0** [comment]
Long time ago, I think you have to directly add it to the makefile

**Comment by sjeaugey** [comment]
Closing, please re-open if it is still a problem.
