### ISSUE TITLE
Question about NCCL 2.5.6 with CUDA 9.2

### ISSUE THREAD

**Issue by likueimo** [NVIDIA/nccl#292]
Thanks for developing this powerful library!
I am a HPC system administration.  
I try to offer new package for users and I have a little question about NCCL.

From the official NCCL download page, 
there is only CUDA 9.0/10.0/10.1/10.2 for NCCL 2.5.6.
I am wondering that why no CUDA 9.2 ? 
Is there any compatibility issues with CUDA 9.2 ? 
Or I can just download this repo source code and build with CUDA 9.2 ?

![image](https://user-images.githubusercontent.com/11157543/74589129-93231b00-503d-11ea-9ad7-1884c7a6bef2.png)

Many thanks !

**Comment by cliffwoolley** [comment]
Though we didn't provide prebuilt binaries for it, you should be able to build NCCL with CUDA 9.2 yourself without problems.  Thanks!

**Comment by likueimo** [comment]
> Though we didn't provide prebuilt binaries for it, you should be able to build NCCL with CUDA 9.2 yourself without problems. Thanks!

Thank you!
