### ISSUE TITLE
nccl not working with cuda 7.5 and ubuntu 16.04

### ISSUE THREAD

**Issue by ani16** [NVIDIA/nccl#294]
Hi

I am not able to build nccl with cuda 7.5. It throws error:

3 errors detected in the compilation of "/tmp/tmpxft_0000525e_00000000-7_all_reduce.cpp1.ii".

Thanks in advance.

**Comment by sjeaugey** [comment]
This is a very old version of CUDA which we don't support. I suggest you upgrade to CUDA 10.1.

Also note the error above is just the summary, not the real error; there must be other errors in the log above that line.

**Comment by sjeaugey** [comment]
Closing.
