### ISSUE TITLE
Is there any paper or document can explain detail in NCCL

### ISSUE THREAD

**Issue by redglass1984** [NVIDIA/nccl#299]
Hi, all

I am tring to understand how nccl build topology, and how to connect each node.
Is there any thing I can find, which can explain some details.

Thanks~

**Comment by sjeaugey** [comment]
I think I covered most of those points in my talk last year at GTC :
https://on-demand-gtc.gputechconf.com/gtcnew/sessionview.php?sessionName=s9656-distributed+training+and+fast+inter-gpu+communication+with+nccl

**Comment by redglass1984** [comment]
Thanks sjeaugey.

But I still not very clear the meaning of muliple rings.

In the video, says we build 4 rings on DGX1 machine to connect 8 video cards.
What does 4 rings means? why we need 4 ring?
When we do 1 ring-all-reduce operation, traffic go through 4 rings at same time? how does this happen？
That means we partitioned data we want to send into 4 pieces, and transport each pieces on 1 ring?

Thanks

**Comment by kwen2501** [comment]
> Quote: What does 4 rings means? why we need 4 ring?

Those rings are concurrent data movement channels. We do that because we want to maximize the link utilization of the physical topology (e.g. cube mesh in a DGX1), so that we can achieve maximal bandwidth.

> Quote: When we do 1 ring-all-reduce operation, traffic go through 4 rings at same time? how does this happen？
> That means we partitioned data we want to send into 4 pieces, and transport each pieces on 1 ring?

Yes, you can think of it that way.

**Comment by redglass1984** [comment]
Thanks Kwen.

But, if I only take 7 cards from my DGX. And some one else take the left one to build another ring, the left one don't know PCIE bandwidth has been ocupied by the 7 cards‘ PCIE ring. 

That means if we don't take all GPU in a machine, the left card will only got very limited bandwidgh, right?

**Comment by kwen2501** [comment]
Well, there won't be a ring if a communicator has only 1 GPU.

**Comment by redglass1984** [comment]
Sorry， Kwen. 

May be I should ask:

multiple ring will only be built on NVlink, not using PCIE P2P simutaniously right?

Because, if P2P also use, current ring will occupy PCIE bandwidth.

**Comment by redglass1984** [comment]
In another word. 
If NVlinks are all connected, PCIE traffic only exist when GPU communicate with NIC. 
Right?

**Comment by kwen2501** [comment]
> Quote: If NVlinks are all connected, PCIE traffic only exist when GPU communicate with NIC.
> Right?

Yes, that is right.

NCCL will use channels formed of NVLinks if they exist. Otherwise, NCCL will turn to PCI-e or shared memory.

**Comment by redglass1984** [comment]
Thanks @kwen2501 @sjeaugey .
