### ISSUE TITLE
all_reduce_test stop.

### ISSUE THREAD

**Issue by ClaireYang** [NVIDIA/nccl#30]
I used CentOS 7.0 and CUDA 7.5 on the server with 6pcs Tesla cards, it stop and has no response when running ./all_reduce_test 10000000 under single folder.
![2](https://cloud.githubusercontent.com/assets/2720586/16167844/1b0a5004-352d-11e6-84c7-1e38fd4ecae0.jpg)

My GPU topo is as below

CPU 0  -- GPU0
             -- GPU1
             -- GPU2
CPU 1   -- GPU3
             -- GPU4
             -- GPU5
Even I ran with ./all_reduce_test 2 0 1, it still didn't run.
Do I need to install MPI even if I use tests in single folder? Is single test valid for multi-CPU as the topo above? 
I checked ACSCtl, all are negative. I don't know what I can do.

**Comment by sjeaugey** [comment]
Could this be the same problem as in #19, i.e. you need to turn off ACS ?

**Comment by ClaireYang** [comment]
No. I used Lspci –vvv | grep ACSCtl to check, and all have disabled ACSCtl.
![1](https://cloud.githubusercontent.com/assets/2720586/16167788/2bd97dc0-352c-11e6-9339-ba2c94a1bcf0.jpg)

**Comment by ClaireYang** [comment]
An new driver can be fixed this issue, which has been posted on nvidia website.
