### ISSUE TITLE
Is a closed ring on NVLINK still important?

### ISSUE THREAD

**Issue by cofiiwu** [NVIDIA/nccl#301]
If a group of GPU cannot form a closed ring on NVLINKs, will the bandwidth be limited by a bus with lower bandwidth?  I saw some documents refereed that NCCL is not always use ring All-Reduce now, so I want to know if a closed ring on NVLINK is still important. 
Is ring all-reduce still adopted in intra-node communication?

**Comment by kwen2501** [comment]
NCCL will use PCI-e bus or shared memory if there is no NVLink. Those may provide lower bandwidth than NVLink. 
In the newer versions (>= 2.5), whether NCCL uses the ring or tree algorithm depends on an auto-tuning mechanism inside NCCL, which takes into account many factors such as message size, link bandwidth and latency, number of ranks, etc.
For most intra-node cases, I believe the ring algorithm is still the default. You may change the algorithm by setting `NCCL_ALGO=RING | TREE`.

**Comment by cofiiwu** [comment]
Hi @kwen2501 ,
Assuming  a job is executed on GPUs 0,1,2,3,7 of DGX-1.  The bandwidth will be limited by shared memory even if GPU 3 and 7 are connected with NVlink, am I right?

The NVLINK topology of DGX-1
```
    GPU0    GPU1    GPU2    GPU3    GPU4    GPU5    GPU6    GPU7    mlx5_0  CPU Affinity
GPU0     X      NV1     NV1     NV1     NV1     PHB     PHB     PHB     PHB     0-47
GPU1    NV1      X      NV1     NV1     PHB     NV1     PHB     PHB     PHB     0-47
GPU2    NV1     NV1      X      NV1     PHB     PHB     NV1     PHB     PHB     0-47
GPU3    NV1     NV1     NV1      X      PHB     PHB     PHB     NV1     PHB     0-47

GPU4    NV1     PHB     PHB     PHB      X      NV1     NV1     NV1     PHB     0-47
GPU5    PHB     NV1     PHB     PHB     NV1      X      NV1     NV1     PHB     0-47
GPU6    PHB     PHB     NV1     PHB     NV1     NV1      X      NV1     PHB     0-47
GPU7    PHB     PHB     PHB     NV1     NV1     NV1     NV1      X      PHB     0-47
mlx5_0  PHB     PHB     PHB     PHB     PHB     PHB     PHB     PHB      X

```

**Comment by kwen2501** [comment]
In your case, if you set `NCCL_ALGO=TREE` (for NCCL 2.5), it is still possible that the entire traffic stay in the NVLink domain.

For NCCL 2.4, I think you can set `NCCL_TREE_THRESHOLD` to infinity (i.e. a very large number).

**Comment by kwen2501** [comment]
Actually, in NCCL 2.5, even if you don't set `NCCL_ALGO`, NCCL will pick the tree algorithm for you automatically :)
