### ISSUE TITLE
Training on two GPU nodes slower than that on one node.

### ISSUE THREAD

**Issue by YingleiZhang** [NVIDIA/nccl#318]
Hi, i am using PyTorch DistributedDataParallel to train some models and surpisingly. It become slower when i move from one GPU node to 2 GPU nodes.

Here is the example i am running: https://github.com/huggingface/transformers/blob/v2.3.0/examples/run_lm_finetuning.py

Here is my infrastructure:

Single Node: p3.16xlarge
Training time: 36 mins

Two Nodes: p3.16xlarge
Training time: 1 h 45 mins

In both cases, i am using PyTorch distributed data parallel and GPU utilization is almost always be 100%. 

I have enabled NCCL_DEBUG=INFO
I copied the nccl output from single node training and multiple node training in this link below.
https://gist.github.com/YingleiZhang/a8df48eb534ba20ff8f26b5309094b55

It seems on single node mode, NCCL are creating a lot of CHANNELs, but not in the multiple node mode. Could this slow speed due to the networking issues between different GPU nodes? 

Any help is appreciated.

**Comment by kwen2501** [comment]
Hi I don't spot anything abnormal from the logs you provided. 
It seems the instances you use, p3.16xlarge, have only 25Gbps network bandwidth. See https://aws.amazon.com/ec2/instance-types/p3/
It could be the bottleneck here.

**Comment by YingleiZhang** [comment]
> Hi I don't spot anything abnormal from the logs you provided.
> It seems the instances you use, p3.16xlarge, have only 25Gbps network bandwidth. See https://aws.amazon.com/ec2/instance-types/p3/
> It could be the bottleneck here.

Thanks for your reply, i also tried p3dn.24xlarge, which provide 100Gbps network bandwidth, and it doesn't help much. In the 2 nodes case, it reduce the training time to 1h 30mins, still much slower than single node. I am suspecting there might be something else.

**Comment by kwen2501** [comment]
Can you run [nccl-tests](https://github.com/nvidia/nccl-tests) on those two p3dn.24xlarge nodes to confirm the NCCL bandwidth?

Two environment variables related to AWS network are `NCCL_SOCKET_NTHREADS` and `NCCL_NSOCKS_PERTHREAD` (see descriptions [here](https://docs.nvidia.com/deeplearning/sdk/nccl-developer-guide/docs/env.html#nccl-socket-nthreads)). We have pre-tuned those values to 2 and 8, but you may change them to see if it makes a difference, for example, to 4 and 4. But I doubt it would give you a big speed-up to bring the time down to the 1-node level.

MPI is not related to the perf here.

**Comment by ccarter-cs** [comment]
Ya, as previous commenter suggested, verify bandwidth. But, I would be surprised if what you are trying to do works anyways. For synchronous distributed training, the function being trained has forward and backward time t_fb and transfer of gradients to other node t_g. In the case of a transformer model, I would bet t_fb < t_g. I'd suggest calculating these timings and then you should have a better understanding. The reason I believe some have shown success in distributed training of this type of model is because intra node nvlink is very fast, and the hit for the inter node communication is fine since it's being used to transfer the summed gradients for 8x or 16x local gpus. I'd suggest first focusing on single node distributed training on GPUS first. I haven't trained a distributed model in some time, but these are my thoughts and hope they are correct and can help.

**Comment by sjeaugey** [comment]
To give an order of magnitude, on a single node with NVLink, your communication operations (allreduce) operate around 120 GB/s. When running on two nodes, even with a 100Gb NIC, those operations are now 10x slower, at 12 GB/s (at best, usually between 8-10).
![slide6_resize_p3dn](https://user-images.githubusercontent.com/12857445/78917782-3728b180-7a44-11ea-8c08-a76acc54210a.png)

Now on the question of "will it scale to X GPUs?", the critical ratio is the compute vs communication time. If you have a very long compute time, then you can run on pretty much any platform and it will scale just fine. If your compute time is small however (especially if, when going to two nodes, you halved the batch size to keep the total batch size constant), then the communication time will be crucial. If you run the NCCL tests, you'll be able to see what time that means for the size that matters to you and you'll be able to compare that with your compute time (forward/backward).

So the solution to your problem is to either increase your compute time (= your batch size)  or decrease your communication time (= run on a system with faster inter-node communication).

**Comment by YingleiZhang** [comment]
Thanks everyone for your reply. These are all good knowledge. I know that Horovod is also using NCCL as backend to do distributed training. It looks like it scales pretty well even with "RoCE-capable 25 Gbit/s network" as you can see here: https://github.com/horovod/horovod#why-horovod.

I am not entirely sure how they can scale beyond the bandwidth limits. One thing i can see is that they are using hvd.DistributedOptimizer, could this be the trick that helps reduce communication time.

**Comment by sjeaugey** [comment]
Horovod might have a slightly different optimization than PyTorch but given both use NCCL it will probably not change much in the end. In particular, if the problem is that your communication time is too high compared to the compute time, there is no magic, you won't scale better.

Note those numbers are fairly old now, ResNet50 is scaling OK because P100 is slower than V100 (high compute time), and RN50 doesn't transmit much data (50-100MB, hence low communication time). But you can see that VGG16 (which communicates ~500MB) isn't scaling that well at that network speed.

It's really not hard to predict how much your network will scale. You just need to know the size of the parameters/gradients you're exchanging through NCCL (total gradients across all layers) and see how much time it takes NCCL to allreduce that size. Then compare it with your forward/backward time.

**Comment by YingleiZhang** [comment]
Thanks, i think we are getting there. This training example is based on roberta-base, which has 125M parameters. The model size is about 500MB. In two nodes cases, i think each gpu core is going to have a copy of the model, and it would be 8*2 * 500MB of data getting synchronized across the network. For each batch, consider forward and backward, we should double this number. So likely 16GB of data will be moving across the network. 

Here are some testing i have done on p3.16xlarge instances:
```
./build/all_reduce_perf -b 8 -e 4G -f 2 -g 8

# nThread 1 nGpus 8 minBytes 8 maxBytes 4294967296 step: 2(factor) warmup iters: 5 iters: 20 validation: 1 
#
# Using devices
#   Rank  0 Pid  86829 on ip-10-0-3-39 device  0 [0x00] Tesla V100-SXM2-16GB
#   Rank  1 Pid  86829 on ip-10-0-3-39 device  1 [0x00] Tesla V100-SXM2-16GB
#   Rank  2 Pid  86829 on ip-10-0-3-39 device  2 [0x00] Tesla V100-SXM2-16GB
#   Rank  3 Pid  86829 on ip-10-0-3-39 device  3 [0x00] Tesla V100-SXM2-16GB
#   Rank  4 Pid  86829 on ip-10-0-3-39 device  4 [0x00] Tesla V100-SXM2-16GB
#   Rank  5 Pid  86829 on ip-10-0-3-39 device  5 [0x00] Tesla V100-SXM2-16GB
#   Rank  6 Pid  86829 on ip-10-0-3-39 device  6 [0x00] Tesla V100-SXM2-16GB
#   Rank  7 Pid  86829 on ip-10-0-3-39 device  7 [0x00] Tesla V100-SXM2-16GB
#
#                                                     out-of-place                       in-place          
#       size         count    type   redop     time   algbw   busbw  error     time   algbw   busbw  error
#        (B)    (elements)                     (us)  (GB/s)  (GB/s)            (us)  (GB/s)  (GB/s)       
           8             2   float     sum    70.46    0.00    0.00  2e-07    68.58    0.00    0.00  1e-07
          16             4   float     sum    72.36    0.00    0.00  6e-08    69.58    0.00    0.00  6e-08
          32             8   float     sum    69.07    0.00    0.00  6e-08    69.48    0.00    0.00  6e-08
          64            16   float     sum    71.01    0.00    0.00  6e-08    68.47    0.00    0.00  6e-08
         128            32   float     sum    71.31    0.00    0.00  6e-08    70.64    0.00    0.00  6e-08
         256            64   float     sum    70.15    0.00    0.01  6e-08    68.85    0.00    0.01  6e-08
         512           128   float     sum    71.05    0.01    0.01  6e-08    72.12    0.01    0.01  6e-08
        1024           256   float     sum    70.81    0.01    0.03  2e-07    68.91    0.01    0.03  2e-07
        2048           512   float     sum    69.74    0.03    0.05  2e-07    73.90    0.03    0.05  2e-07
        4096          1024   float     sum    68.47    0.06    0.10  2e-07    70.02    0.06    0.10  2e-07
        8192          2048   float     sum    70.94    0.12    0.20  2e-07    71.65    0.11    0.20  2e-07
       16384          4096   float     sum    72.81    0.23    0.39  2e-07    71.69    0.23    0.40  2e-07
       32768          8192   float     sum    71.58    0.46    0.80  2e-07    75.28    0.44    0.76  2e-07
       65536         16384   float     sum    74.62    0.88    1.54  2e-07    71.21    0.92    1.61  2e-07
      131072         32768   float     sum    76.21    1.72    3.01  2e-07    76.95    1.70    2.98  2e-07
      262144         65536   float     sum    80.13    3.27    5.73  5e-07    80.79    3.24    5.68  5e-07
      524288        131072   float     sum    87.11    6.02   10.53  5e-07    82.56    6.35   11.11  5e-07
     1048576        262144   float     sum    98.70   10.62   18.59  5e-07    96.17   10.90   19.08  5e-07
     2097152        524288   float     sum    119.4   17.57   30.74  5e-07    119.2   17.60   30.80  5e-07
     4194304       1048576   float     sum    189.6   22.12   38.72  5e-07    187.5   22.37   39.15  5e-07
     8388608       2097152   float     sum    295.5   28.38   49.67  5e-07    295.8   28.36   49.63  5e-07
    16777216       4194304   float     sum    345.8   48.52   84.92  5e-07    344.3   48.73   85.27  5e-07
    33554432       8388608   float     sum    558.2   60.11  105.19  5e-07    556.5   60.30  105.52  5e-07
    67108864      16777216   float     sum    965.0   69.55  121.70  5e-07    967.2   69.39  121.43  5e-07
   134217728      33554432   float     sum   1849.6   72.57  126.99  5e-07   1848.6   72.61  127.06  5e-07
   268435456      67108864   float     sum   3642.2   73.70  128.98  5e-07   3647.0   73.61  128.81  5e-07
   536870912     134217728   float     sum   7196.9   74.60  130.55  5e-07   7204.9   74.51  130.40  5e-07
  1073741824     268435456   float     sum    14337   74.89  131.06  5e-07    14348   74.84  130.96  5e-07
  2147483648     536870912   float     sum    28586   75.12  131.47  5e-07    28590   75.11  131.45  5e-07
  4294967296    1073741824   float     sum    57092   75.23  131.65  5e-07    57135   75.17  131.55  5e-07
# Out of bounds values : 0 OK
# Avg bus bandwidth    : 41.7781 
#

```

Here is the performance testing on p3dn.24xlarge instance (AWS claims this would provide up to 100Gbps bandwidth)
```
./build/all_reduce_perf -b 8 -e 4G -f 2 -g 8

# nThread 1 nGpus 8 minBytes 8 maxBytes 4294967296 step: 2(factor) warmup iters: 5 iters: 20 validation: 1 
#
# Using devices
#   Rank  0 Pid  23638 on ip-10-0-26-117 device  0 [0x00] Tesla V100-SXM2-32GB
#   Rank  1 Pid  23638 on ip-10-0-26-117 device  1 [0x00] Tesla V100-SXM2-32GB
#   Rank  2 Pid  23638 on ip-10-0-26-117 device  2 [0x00] Tesla V100-SXM2-32GB
#   Rank  3 Pid  23638 on ip-10-0-26-117 device  3 [0x00] Tesla V100-SXM2-32GB
#   Rank  4 Pid  23638 on ip-10-0-26-117 device  4 [0x00] Tesla V100-SXM2-32GB
#   Rank  5 Pid  23638 on ip-10-0-26-117 device  5 [0x00] Tesla V100-SXM2-32GB
#   Rank  6 Pid  23638 on ip-10-0-26-117 device  6 [0x00] Tesla V100-SXM2-32GB
#   Rank  7 Pid  23638 on ip-10-0-26-117 device  7 [0x00] Tesla V100-SXM2-32GB
#
#                                                     out-of-place                       in-place          
#       size         count    type   redop     time   algbw   busbw  error     time   algbw   busbw  error
#        (B)    (elements)                     (us)  (GB/s)  (GB/s)            (us)  (GB/s)  (GB/s)       
           8             2   float     sum    59.98    0.00    0.00  2e-07    56.81    0.00    0.00  1e-07
          16             4   float     sum    63.28    0.00    0.00  6e-08    57.17    0.00    0.00  6e-08
          32             8   float     sum    62.34    0.00    0.00  6e-08    57.12    0.00    0.00  6e-08
          64            16   float     sum    62.45    0.00    0.00  6e-08    57.75    0.00    0.00  6e-08
         128            32   float     sum    65.87    0.00    0.00  6e-08    56.61    0.00    0.00  6e-08
         256            64   float     sum    63.86    0.00    0.01  6e-08    57.26    0.00    0.01  6e-08
         512           128   float     sum    64.40    0.01    0.01  6e-08    56.73    0.01    0.02  6e-08
        1024           256   float     sum    62.20    0.02    0.03  2e-07    59.85    0.02    0.03  2e-07
        2048           512   float     sum    63.27    0.03    0.06  2e-07    57.76    0.04    0.06  2e-07
        4096          1024   float     sum    62.71    0.07    0.11  2e-07    58.62    0.07    0.12  2e-07
        8192          2048   float     sum    83.86    0.10    0.17  2e-07    77.23    0.11    0.19  2e-07
       16384          4096   float     sum    64.67    0.25    0.44  2e-07    58.78    0.28    0.49  2e-07
       32768          8192   float     sum    64.01    0.51    0.90  2e-07    58.79    0.56    0.98  2e-07
       65536         16384   float     sum    65.59    1.00    1.75  2e-07    59.88    1.09    1.92  2e-07
      131072         32768   float     sum    64.54    2.03    3.55  2e-07    61.57    2.13    3.73  2e-07
      262144         65536   float     sum    67.96    3.86    6.75  5e-07    70.80    3.70    6.48  5e-07
      524288        131072   float     sum    71.68    7.31   12.80  5e-07    68.84    7.62   13.33  5e-07
     1048576        262144   float     sum    96.13   10.91   19.09  5e-07    95.60   10.97   19.19  5e-07
     2097152        524288   float     sum    118.8   17.65   30.89  5e-07    118.7   17.66   30.91  5e-07
     4194304       1048576   float     sum    189.6   22.13   38.72  5e-07    182.8   22.95   40.16  5e-07
     8388608       2097152   float     sum    310.1   27.05   47.34  5e-07    310.7   27.00   47.25  5e-07
    16777216       4194304   float     sum    342.3   49.01   85.77  5e-07    339.4   49.43   86.50  5e-07
    33554432       8388608   float     sum    569.3   58.94  103.14  5e-07    568.0   59.07  103.37  5e-07
    67108864      16777216   float     sum    990.6   67.75  118.56  5e-07    992.1   67.64  118.38  5e-07
   134217728      33554432   float     sum   1879.6   71.41  124.97  5e-07   1884.8   71.21  124.62  5e-07
   268435456      67108864   float     sum   3707.6   72.40  126.70  5e-07   3711.1   72.33  126.58  5e-07
   536870912     134217728   float     sum   7306.1   73.48  128.59  5e-07   7307.2   73.47  128.58  5e-07
  1073741824     268435456   float     sum    14527   73.91  129.35  5e-07    14542   73.84  129.21  5e-07
  2147483648     536870912   float     sum    28925   74.24  129.93  5e-07    28939   74.21  129.86  5e-07
  4294967296    1073741824   float     sum    57733   74.39  130.19  5e-07    57790   74.32  130.06  5e-07
# Out of bounds values : 0 OK
# Avg bus bandwidth    : 41.3639 
#

```

How should i interpret the bandwidth? It seems more like the bandwidth between different gpus on single node. How can i test all reduce between different nodes?

**Comment by kwen2501** [comment]
To run nccl-tests on multiple nodes, you would need to first compile the test with MPI:
`make MPI=1 MPI_HOME=/path/to/mpi CUDA_HOME=/path/to/cuda NCCL_HOME=/path/to/nccl`
On 2 nodes, 16 GPUs, you can run the test with:
`mpirun -np 16 -N 8 -H <host1,host2> ./build/all_reduce_perf -b 8 -e 1G -f 2`

**Comment by YingleiZhang** [comment]
I think sjeaugey already provided those numbers above (120 GB/s vs 10 GB/s). After we estimate the amount of data need to be moved across network, we believe it is indeed the bottleneck. 

Thanks folks, i certainly learned a lot. Closing this issue.

**Comment by xiefeiwhu** [comment]
> Thanks, i think we are getting there. This training example is based on roberta-base, which has 125M parameters. The model size is about 500MB. In two nodes cases, i think each gpu core is going to have a copy of the model, and it would be 8*2 * 500MB of data getting synchronized across the network. For each batch, consider forward and backward, we should double this number. So likely 16GB of data will be moving across the network.
> 
> Here are some testing i have done on p3.16xlarge instances:
> 
> ```
> ./build/all_reduce_perf -b 8 -e 4G -f 2 -g 8
> 
> # nThread 1 nGpus 8 minBytes 8 maxBytes 4294967296 step: 2(factor) warmup iters: 5 iters: 20 validation: 1 
> #
> # Using devices
> #   Rank  0 Pid  86829 on ip-10-0-3-39 device  0 [0x00] Tesla V100-SXM2-16GB
> #   Rank  1 Pid  86829 on ip-10-0-3-39 device  1 [0x00] Tesla V100-SXM2-16GB
> #   Rank  2 Pid  86829 on ip-10-0-3-39 device  2 [0x00] Tesla V100-SXM2-16GB
> #   Rank  3 Pid  86829 on ip-10-0-3-39 device  3 [0x00] Tesla V100-SXM2-16GB
> #   Rank  4 Pid  86829 on ip-10-0-3-39 device  4 [0x00] Tesla V100-SXM2-16GB
> #   Rank  5 Pid  86829 on ip-10-0-3-39 device  5 [0x00] Tesla V100-SXM2-16GB
> #   Rank  6 Pid  86829 on ip-10-0-3-39 device  6 [0x00] Tesla V100-SXM2-16GB
> #   Rank  7 Pid  86829 on ip-10-0-3-39 device  7 [0x00] Tesla V100-SXM2-16GB
> #
> #                                                     out-of-place                       in-place          
> #       size         count    type   redop     time   algbw   busbw  error     time   algbw   busbw  error
> #        (B)    (elements)                     (us)  (GB/s)  (GB/s)            (us)  (GB/s)  (GB/s)       
>            8             2   float     sum    70.46    0.00    0.00  2e-07    68.58    0.00    0.00  1e-07
>           16             4   float     sum    72.36    0.00    0.00  6e-08    69.58    0.00    0.00  6e-08
>           32             8   float     sum    69.07    0.00    0.00  6e-08    69.48    0.00    0.00  6e-08
>           64            16   float     sum    71.01    0.00    0.00  6e-08    68.47    0.00    0.00  6e-08
>          128            32   float     sum    71.31    0.00    0.00  6e-08    70.64    0.00    0.00  6e-08
>          256            64   float     sum    70.15    0.00    0.01  6e-08    68.85    0.00    0.01  6e-08
>          512           128   float     sum    71.05    0.01    0.01  6e-08    72.12    0.01    0.01  6e-08
>         1024           256   float     sum    70.81    0.01    0.03  2e-07    68.91    0.01    0.03  2e-07
>         2048           512   float     sum    69.74    0.03    0.05  2e-07    73.90    0.03    0.05  2e-07
>         4096          1024   float     sum    68.47    0.06    0.10  2e-07    70.02    0.06    0.10  2e-07
>         8192          2048   float     sum    70.94    0.12    0.20  2e-07    71.65    0.11    0.20  2e-07
>        16384          4096   float     sum    72.81    0.23    0.39  2e-07    71.69    0.23    0.40  2e-07
>        32768          8192   float     sum    71.58    0.46    0.80  2e-07    75.28    0.44    0.76  2e-07
>        65536         16384   float     sum    74.62    0.88    1.54  2e-07    71.21    0.92    1.61  2e-07
>       131072         32768   float     sum    76.21    1.72    3.01  2e-07    76.95    1.70    2.98  2e-07
>       262144         65536   float     sum    80.13    3.27    5.73  5e-07    80.79    3.24    5.68  5e-07
>       524288        131072   float     sum    87.11    6.02   10.53  5e-07    82.56    6.35   11.11  5e-07
>      1048576        262144   float     sum    98.70   10.62   18.59  5e-07    96.17   10.90   19.08  5e-07
>      2097152        524288   float     sum    119.4   17.57   30.74  5e-07    119.2   17.60   30.80  5e-07
>      4194304       1048576   float     sum    189.6   22.12   38.72  5e-07    187.5   22.37   39.15  5e-07
>      8388608       2097152   float     sum    295.5   28.38   49.67  5e-07    295.8   28.36   49.63  5e-07
>     16777216       4194304   float     sum    345.8   48.52   84.92  5e-07    344.3   48.73   85.27  5e-07
>     33554432       8388608   float     sum    558.2   60.11  105.19  5e-07    556.5   60.30  105.52  5e-07
>     67108864      16777216   float     sum    965.0   69.55  121.70  5e-07    967.2   69.39  121.43  5e-07
>    134217728      33554432   float     sum   1849.6   72.57  126.99  5e-07   1848.6   72.61  127.06  5e-07
>    268435456      67108864   float     sum   3642.2   73.70  128.98  5e-07   3647.0   73.61  128.81  5e-07
>    536870912     134217728   float     sum   7196.9   74.60  130.55  5e-07   7204.9   74.51  130.40  5e-07
>   1073741824     268435456   float     sum    14337   74.89  131.06  5e-07    14348   74.84  130.96  5e-07
>   2147483648     536870912   float     sum    28586   75.12  131.47  5e-07    28590   75.11  131.45  5e-07
>   4294967296    1073741824   float     sum    57092   75.23  131.65  5e-07    57135   75.17  131.55  5e-07
> # Out of bounds values : 0 OK
> # Avg bus bandwidth    : 41.7781 
> #
> ```
> 
> Here is the performance testing on p3dn.24xlarge instance (AWS claims this would provide up to 100Gbps bandwidth)
> 
> ```
> ./build/all_reduce_perf -b 8 -e 4G -f 2 -g 8
> 
> # nThread 1 nGpus 8 minBytes 8 maxBytes 4294967296 step: 2(factor) warmup iters: 5 iters: 20 validation: 1 
> #
> # Using devices
> #   Rank  0 Pid  23638 on ip-10-0-26-117 device  0 [0x00] Tesla V100-SXM2-32GB
> #   Rank  1 Pid  23638 on ip-10-0-26-117 device  1 [0x00] Tesla V100-SXM2-32GB
> #   Rank  2 Pid  23638 on ip-10-0-26-117 device  2 [0x00] Tesla V100-SXM2-32GB
> #   Rank  3 Pid  23638 on ip-10-0-26-117 device  3 [0x00] Tesla V100-SXM2-32GB
> #   Rank  4 Pid  23638 on ip-10-0-26-117 device  4 [0x00] Tesla V100-SXM2-32GB
> #   Rank  5 Pid  23638 on ip-10-0-26-117 device  5 [0x00] Tesla V100-SXM2-32GB
> #   Rank  6 Pid  23638 on ip-10-0-26-117 device  6 [0x00] Tesla V100-SXM2-32GB
> #   Rank  7 Pid  23638 on ip-10-0-26-117 device  7 [0x00] Tesla V100-SXM2-32GB
> #
> #                                                     out-of-place                       in-place          
> #       size         count    type   redop     time   algbw   busbw  error     time   algbw   busbw  error
> #        (B)    (elements)                     (us)  (GB/s)  (GB/s)            (us)  (GB/s)  (GB/s)       
>            8             2   float     sum    59.98    0.00    0.00  2e-07    56.81    0.00    0.00  1e-07
>           16             4   float     sum    63.28    0.00    0.00  6e-08    57.17    0.00    0.00  6e-08
>           32             8   float     sum    62.34    0.00    0.00  6e-08    57.12    0.00    0.00  6e-08
>           64            16   float     sum    62.45    0.00    0.00  6e-08    57.75    0.00    0.00  6e-08
>          128            32   float     sum    65.87    0.00    0.00  6e-08    56.61    0.00    0.00  6e-08
>          256            64   float     sum    63.86    0.00    0.01  6e-08    57.26    0.00    0.01  6e-08
>          512           128   float     sum    64.40    0.01    0.01  6e-08    56.73    0.01    0.02  6e-08
>         1024           256   float     sum    62.20    0.02    0.03  2e-07    59.85    0.02    0.03  2e-07
>         2048           512   float     sum    63.27    0.03    0.06  2e-07    57.76    0.04    0.06  2e-07
>         4096          1024   float     sum    62.71    0.07    0.11  2e-07    58.62    0.07    0.12  2e-07
>         8192          2048   float     sum    83.86    0.10    0.17  2e-07    77.23    0.11    0.19  2e-07
>        16384          4096   float     sum    64.67    0.25    0.44  2e-07    58.78    0.28    0.49  2e-07
>        32768          8192   float     sum    64.01    0.51    0.90  2e-07    58.79    0.56    0.98  2e-07
>        65536         16384   float     sum    65.59    1.00    1.75  2e-07    59.88    1.09    1.92  2e-07
>       131072         32768   float     sum    64.54    2.03    3.55  2e-07    61.57    2.13    3.73  2e-07
>       262144         65536   float     sum    67.96    3.86    6.75  5e-07    70.80    3.70    6.48  5e-07
>       524288        131072   float     sum    71.68    7.31   12.80  5e-07    68.84    7.62   13.33  5e-07
>      1048576        262144   float     sum    96.13   10.91   19.09  5e-07    95.60   10.97   19.19  5e-07
>      2097152        524288   float     sum    118.8   17.65   30.89  5e-07    118.7   17.66   30.91  5e-07
>      4194304       1048576   float     sum    189.6   22.13   38.72  5e-07    182.8   22.95   40.16  5e-07
>      8388608       2097152   float     sum    310.1   27.05   47.34  5e-07    310.7   27.00   47.25  5e-07
>     16777216       4194304   float     sum    342.3   49.01   85.77  5e-07    339.4   49.43   86.50  5e-07
>     33554432       8388608   float     sum    569.3   58.94  103.14  5e-07    568.0   59.07  103.37  5e-07
>     67108864      16777216   float     sum    990.6   67.75  118.56  5e-07    992.1   67.64  118.38  5e-07
>    134217728      33554432   float     sum   1879.6   71.41  124.97  5e-07   1884.8   71.21  124.62  5e-07
>    268435456      67108864   float     sum   3707.6   72.40  126.70  5e-07   3711.1   72.33  126.58  5e-07
>    536870912     134217728   float     sum   7306.1   73.48  128.59  5e-07   7307.2   73.47  128.58  5e-07
>   1073741824     268435456   float     sum    14527   73.91  129.35  5e-07    14542   73.84  129.21  5e-07
>   2147483648     536870912   float     sum    28925   74.24  129.93  5e-07    28939   74.21  129.86  5e-07
>   4294967296    1073741824   float     sum    57733   74.39  130.19  5e-07    57790   74.32  130.06  5e-07
> # Out of bounds values : 0 OK
> # Avg bus bandwidth    : 41.3639 
> #
> ```
> 
> How should i interpret the bandwidth? It seems more like the bandwidth between different gpus on single node. How can i test all reduce between different nodes?

Hello, How does 8*2*500MB come from?  As using AllReduce which only transmits one time, with batch size is 8, I think it should be  8*500MB. Also, the communication should happens in backward not in forward. So the transmission data size is just 4GB

**Comment by ginobilinie** [comment]
> using

I think he means 2 nodes, so totally 8*2 gpus, each gpu core maintained a copy of model.

**Comment by sjeaugey** [comment]
You need to compile the NCCL tests with MPI support (add `MPI=1` to the make command line and maybe `MPI_HOME=/path/to/mpi` as well), then run the perf tests with `mpirun`. See the [NCCL tests usage](https://github.com/NVIDIA/nccl-tests#usage) for examples.

**Comment by ArtificialZeng** [comment]
how to solve
