### ISSUE TITLE
Another Infiniband Question

### ISSUE THREAD

**Issue by christopherhesse** [NVIDIA/nccl#325]
Hi!  Thanks for answering my previous questions!

I have 3 nodes, and the performance between nodes 1 + 2 (25 GB/s) vs the performance between 1 + 3 (39 GB/s) is dramatically different.  Nothing stood out to me from the NCCL output, so I'm curious if you guys think this is likely to be a fabric issue, or if it's likely a NCCL issue.

`NCCL_DEBUG_SUBSYS=GRAPH,INIT,NET NCCL_DEBUG=INFO NCCL_ALGO=RING mpiexec -f /tmp/rcall-mpi-hosts-2 /root/nccl-tests/build/all_reduce_perf -b 1M -e 2048M -f 2 -g 1 -c 0 -d half > first-pair.txt`
[first-pair.txt](https://github.com/NVIDIA/nccl/files/4484172/first-pair.txt)

`NCCL_DEBUG_SUBSYS=GRAPH,INIT,NET NCCL_DEBUG=INFO NCCL_ALGO=RING mpiexec -f /tmp/rcall-mpi-hosts-3 /root/nccl-tests/build/all_reduce_perf -b 1M -e 2048M -f 2 -g 1 -c 0 -d half > second-pair.txt`

[second-pair.txt](https://github.com/NVIDIA/nccl/files/4484174/second-pair.txt)

Thanks!

**Comment by sjeaugey** [comment]
Indeed nothing seems wrong in the logs. One way to confirm it's a fabric issue (and not a node issue) is to find a 4th node which can communicate at full speed with node 2. Basically, if 1<->3 is good, and 2<->4 is good, but 1<->2 is bad, then it's a good sign this is due to a fabric routing collision.

**Comment by christopherhesse** [comment]
Yeah, it is as you said, I was able to find nodes that can talk to 1 and 2 at full speed, though they cannot talk to each other at full speed.  Thanks again!
