### ISSUE TITLE
Running NCCL mpi test accros multiple nodes

### ISSUE THREAD

**Issue by sharannarang** [NVIDIA/nccl#33]
Hi, 

I've built and run the `mpi_test` on 1 node with 8 TitanX gpus successfully. I use `srun` to launch the mpi test and it passes.  However, the test fails when run across 2 nodes with 8 TitanX gpus per node. I use the following command line:

```
srun -N2 -n16 --gres=gpu:8 -p TitanXx8 build/test/mpi/mpi_test 0 1 2 3 4 5 6 7 0 1 2 3 4 5 6 7
```

The test fails with the following error:

```
WARN src/core.cu:225 failed to allocate 2101248 byte device buffer
WARN src/core.cu:596 rank 12 failed to allocate device buffer
WARN src/core.cu:683 rank 12 failed to allocate communicator
NCCL Init failed (10) 'cuda malloc failed'
```

Does NCCL run across multiple nodes?

**Comment by sjeaugey** [comment]
No, indeed, NCCL doesn't run across multiple nodes.

**Comment by sharannarang** [comment]
Are there any plans to add this support?

**Comment by sjeaugey** [comment]
Inter-node communication has been implemented in NCCL2, which is now available at https://developer.nvidia.com/nccl.
