### ISSUE TITLE
No plugin found (libnccl-net.so)

### ISSUE THREAD

**Issue by kimchitsigai** [NVIDIA/nccl#333]
Hi,

I'm trying to run a Horovod/TensorFlow application on two nodes.

My configuration is: 
    - Network is Intel OPA
    - Horovod is 0.19 and TensorFlow is 2.1
    - CUDA is 10.1.2
    - NCCL is 2.5.6
    - OpenMPI is 4.0.2
    - Application is  started with Slurm 18.08

I get the following logs:

> xxx:16090:16180 [0] NCCL INFO Bootstrap : Using [0]ib0:10.10.10..2<0> [1]ib1:10.11.10.2<0>
xxx:16090:16180 [0] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so).
xxx:16090:16180 [0] NCCL INFO NET/IB : Using [0]hfi1_0:1/IB [1]hfi1_1:1/IB [2]hfi1_2:1/IB [3]hfi1_3:1/IB ; OOB ib0:10.10.10.2<0>
NCCL version 2.5.6+cuda10.1
xxx:16092:16181 [1] NCCL INFO Bootstrap : Using [0]ib0:10.10.10.2<0> [1]ib1:10.11.10.2<0>
xxx:16092:16181 [1] NCCL INFO NET/Plugin : **No plugin found (libnccl-net.so)**.
xxx:16092:16181 [1] NCCL INFO NET/IB : Using [0]hfi1_0:1/IB [1]hfi1_1:1/IB [2]hfi1_2:1/IB [3]hfi1_3:1/IB ; OOB ib0:10.10.10.2<0>
xxx:16092:16181 [1] NCCL INFO Setting affinity for GPU 1 to 0c,00000c00
xxx:16090:16180 [0] NCCL INFO Setting affinity for GPU 0 to 03,ff0003ff
xxx:16090:16180 [0] NCCL INFO CUDA Dev 0[0], IB NIC distance :  PIX NODE SYS SYS
xxx:16092:16181 [1] NCCL INFO CUDA Dev 1[1], IB NIC distance :  PIX NODE SYS SYS
xxx:16090:16180 [0] NCCL INFO Channel 00 :    0   1
xxx:16090:16180 [0] NCCL INFO Channel 01 :    0   1
xxx:16090:16180 [0] NCCL INFO NET/IB : **GPU Direct RDMA Disabled for GPU 0**[0] / HCA 0 'hfi1_0' (no module or not supported by GPU)
xxx:16092:16181 [1] NCCL INFO NET/IB : GPU Direct RDMA Disabled for GPU 1[1] / HCA 0 'hfi1_0' (no module or not supported by GPU)
>

My understanding is that no plugin (libnccl-net.so) is found and, as a consequence, RDMA is disabled.

Where can I find this NCCL-OPA plugin ?

Thanks in advance,
Kimchi

**Comment by sjeaugey** [comment]
Hi,

RDMA is not disabled, only GPU Direct RDMA.

GPU Direct RDMA permits direct NIC-GPU communication and is only important when :
 - the NIC and GPUs are connected to the same PCI switch
 - the NIC speed matches the PCI speed (e.g. 100Gbps / 12 GB/s with PCI Gen3).

GPU Direct RDMA requires some kernel support to allow the NIC to access the GPU physical memory directly. The IB verbs network in NCCL tries to detect whether the nv_peer_mem module is loaded and the message you see is just NCCL not finding the nv_peer_mem module. I don't know whether Intel OPA supports GPU Direct RDMA with IB verbs, nor how to detect the feature is available. So we might want to remove the check here : https://github.com/NVIDIA/nccl/blob/master/src/transport/net_ib.cc#L218-L224 or have different code for Intel OPA.

Also, you are currently using the IB verbs network API, and depending on your hardware, there might be other network APIs which would work faster. For Intel OPA, the libfabrics plugin (https://github.com/aws/aws-ofi-nccl) might be something to investigate.

**Comment by kimchitsigai** [comment]
Thanks a lot for your help.
