### ISSUE TITLE
Direct save the data to remote gpu right after reduction.

### ISSUE THREAD

**Issue by Isaacleee** [NVIDIA/nccl#334]
In case of allreduce, nccl said reduce and communication operation were overlapped.

Right after two operands are reduce, they are save the result to memory of local gpu? or next gpu?

""Reduction + save to local gpu memory + d2dmemcpy""  or ""Reduction + direct access to remote gpu memory and save data""

Thanks

**Comment by kwen2501** [comment]
In current NCCL, if two GPUs belong to the same process, the reduction result would be written directly to the output buffer of the next GPU. If the two GPUs belong to different processes, the reduction result would be written to an intermediate buffer of the next GPU, and the next GPU would do a local copy in the last step to save the final result to the output buffer.

**Comment by Isaacleee** [comment]
you said that ,in short, they not pass through local gpu memory, result would be written directly to remote gpu memory, correct?

And how they can access to remote memory right away? aren't they using dma to access the remote memory directly?

**Comment by kwen2501** [comment]
Correct.
Not sure if I understand the second question.

**Comment by Isaacleee** [comment]
Very nice ! 

Thanks.

**Comment by Isaacleee** [comment]
One more question related seconds, 

I want to know about datapath  how they directly access to remote gpu memory in hardware view.
Generally, when we use D2Dmemcpy, DMA engine assist to transfer the data from one gpu to another gpu. Does it also uses it or other technique in there?

**Comment by kwen2501** [comment]
If there are NVLinks, it would be through NVLinks. If there are not, it would be through PCI-E.

**Comment by Isaacleee** [comment]
Ok thanks!
