### ISSUE TITLE
how to reduce the extra memory usage?

### ISSUE THREAD

**Issue by cjnewstar111** [NVIDIA/nccl#34]
while i use the nccl for the program, i found that every gpu would use the extra memorys. For example, i used 4 gpus, and every gpu would use the extra 3 memorys of 110M. just like the iamge. my question is how to reduce the 110M?

**Comment by nluehr** [comment]
A couple of questions. What GPUs are you using, and is NCCL being used to communicate between multiple processes (e.g. MPI ranks), or from within a single OS process?

**Comment by cjnewstar111** [comment]
i use m40. and between multiple processes (MPI ranks). thanks very much

**Comment by nluehr** [comment]
The extra memory footprints should be eliminated in the latest change set.

**Comment by cjnewstar111** [comment]
thanks
