### ISSUE TITLE
What does pnccl* use for?

### ISSUE THREAD

**Issue by jianyinglang** [NVIDIA/nccl#344]
Could anyone explain what pnccl* stands for and when it should be used? Thanks!

**Comment by sjeaugey** [comment]
The pnccl calls are similar to PMPI, and allow to write profiling layers (the "p" standing for "profiling").

Using those, you can write a library to intercept NCCL calls, for example :
```
// My allreduce intercept function
ncclResult_t ncclAllReduce(
  const void* sendbuff, void* recvbuff, size_t count, ncclDataType_t datatype,
  ncclRedOp_t op, ncclComm_t comm, cudaStream_t stream) {

   // accumulate some stats, record the calls, the start time, ...

   // Calls the real ncclAllReduce
   ncclResult_t ret = pncclAllReduce(sendbuff, recvbuff, count, datatype, op, comm, stream);

   // record the end time, ...
  return ret;
}
```
Then link your program against your own library, then NCCL, so that all calls to NCCL are going through your profiling layer.

**Comment by jianyinglang** [comment]
Got it! Thank you very much!

**Comment by walkup** [comment]
There is a problem with this response : the NCCL library does not contain entry points for the profiling interfaces such as pncclAllReduce, so with the current software (I checked version 2.7.8) you cannot successfully link with profiling wrappers of the form indicated above.  It would be nice to have this capability.

**Comment by sjeaugey** [comment]
Indeed, the profiling API has never been compiled in any release. So if you want to use it you need to recompile NCCL adding `PROFAPI=1` to your make command.

**Comment by walkup** [comment]
Thanks.  I have one related question.  For MPI profiling wrappers, the profiler output is normally written in the wrapper for MPI_Finalize(), and a call to that routine is almost always present in MPI applications.  So ... is there an equivalent convenient NCCL routine to use to provide profiler output?

**Comment by sjeaugey** [comment]
NCCL has a ncclCommDestroy function as well. Granted one can recreate a new NCCL communicator after that, but that's usually not what applications do.

Alternatively, if you really want to profile an application for the entire life of the process, you can initialize the profiling upon the first call to NCCL, and use `atexit()` to dump all profiling information at the exit of the process.

For example call this function at the beginning of ncclCommInitRank :
```
ncclProfileCheckInit() {
  static firstcall = 1;
  if (firstcall) {
    ncclProfileInit();
    atexit(ncclProfileFini());
    firstcall = 0;
  }
```
