### ISSUE TITLE
What is the single-thread multi-GPU's execution mode?

### ISSUE THREAD

**Issue by xiaodong-yu** [NVIDIA/nccl#347]
I know NCCL supports the single-thread multiple devices communication. I'm wondering, in such case, are all devices launched asynchronously and execute simultaneously? Or they execute in sequence? Thanks!

**Comment by sjeaugey** [comment]
All devices execute simultaneously, which is key to having data flow through all GPUs.

Note that launching on multiple devices requires the use of ncclGroupStart/ncclGroupEnd, which will delay all launches until the ncclGroupEnd call. So nothing will start during the ncclAllReduce calls, and ncclGroupEnd will launch the kernels on all devices.
