### ISSUE TITLE
Question on HF support

### ISSUE THREAD

**Issue by fmana** [NVIDIA/nccl#35]
Hi,

I included the Nickel library into my tool and I'm up and running.
Till now I used ncclAllReduce with float 32 bufferes and ncclSum reduction.
Is there an easy way to have the API working with float 32 buffers but transfer and adding 
realized with HF16 floats? (sum even emulated on float 32 but transfer at HF 16)

Thanks,
franco

**Comment by nluehr** [comment]
Hi Franco,

There is no easy mechanism to accomplish this in NCCL today. But it would be a useful feature.

-Nathan

**Comment by spotluri** [comment]
We do not intend to support this in NCCL as it could affect other applications (like HPC) that do not expect it. We believe, higher level application-specific frameworks like DL FW/Horovod would be a better place to do such a conversion.
