### ISSUE TITLE
Algorithm and progress model used in broadcast 

### ISSUE THREAD

**Issue by aydinbuluc** [NVIDIA/nccl#358]
Hello,

I am wondering what exact algorithm is used for NCCL's broadcast implementation. I am thinking relative to the known broadcast algorithms such as the tree broadcast or Van De Geijn's algorithm as described in https://www.mcs.anl.gov/~thakur/papers/ijhpca-coll.pdf

My cursory look into the source code suggests that the implementation is some sort of pipelined ring broadcast but I wanted to make sure. 

I also wanted to know the progress and completion models. 

Thanks,
- Aydin

**Comment by kwen2501** [comment]
Hi Aydin, you are right, NCCL implements broadcast based on the ring algorithm currently. 

Progress is made based on credit return (between peer GPUs on the ring). Not sure if that answers your question about progress model.

**Comment by aydinbuluc** [comment]
Thank you for clarifying the algorithm.

I was referring to progress and completion as two distinct things. If I understand correctly, the code splits a large message M into batches, each are of size m. Let's say for simplicity that the message is not that large and M=m. Once the sender sends its data to its "neighbor", does the broadcast function return on the sender? Similarly for process i, once it sends what it needs to send to process i+1, does the function return on that process (without waiting for what happens in processes i+2 and beyond)?

For progress, I meant "who is polling the network". Is that a thread on the CPU side? or is it pure GPU initiated and polled.

Thanks again
-Aydin

**Comment by sjeaugey** [comment]
All network communication is done by a CPU thread. And indeed if there is a single chunk to send, then the sender just sends it then exits.

**Comment by aydinbuluc** [comment]
Thank you!

**Comment by aydinbuluc** [comment]
Sorry for reopening but one more question: Is this entrance to broadcast synchronizing? Meaning, can root start the broadcast function before some of the other participating processes arrive?

**Comment by sjeaugey** [comment]
Yes, indeed, for small enough operations, the root may just send the data to the next GPU and exit. It's not a guarantee, and it is how it should work today, but NCCL will avoid any unnecessary synchronization.

**Comment by aydinbuluc** [comment]
very cool. Thanks
