### ISSUE TITLE
can nccl select the right ib card?

### ISSUE THREAD

**Issue by davidstack** [NVIDIA/nccl#366]
there are five ib cards on each of my two host (A and B ), all the ib card is active,but only one ib card on A host can communicate with on ib card on B host,can nccl select the right ib card? thanks

**Comment by sjeaugey** [comment]
NCCL can detect the topology and which NIC is closer to the GPU, but it cannot detect which local NIC can talk to which remote NIC.

If some NICs are close to the GPU but cannot be used to communicate between GPUs, you can force which IB card to use with the NCCL_IB_HCA setting.

**Comment by davidstack** [comment]
@sjeaugey  thank you
