### ISSUE TITLE
A100 pytorch distributed all_reduce fails with nccl error

### ISSUE THREAD

**Issue by girifb** [NVIDIA/nccl#368]
# ISSUE 

We are testing on A100. We can run NVIDIA nccl_tests (https://github.com/NVIDIA/nccl-tests) fine however same `all_reduce` via pytorch distributed framework fails with NCCL error like so:

```
RuntimeError: NCCL error in: ../torch/lib/c10d/ProcessGroupNCCL.cpp:628, unhandled system error, NCCL version 2.7.3
``` 

## NCCL AND CUDA VERSIONS

```
NCCL version 2.7.3+cuda11.0
```

## DETAILED ERROR

We run our benchmarking script using `mpirun` like so: 

```
mpirun -np 8 -N 8 -x NCCL_DEBUG=WARN -x NCCL_DEBUG_SUBSYS=ALL ./comms.py --b 8 --e 256M --n 100 --f 2 --z 1 --collective all_reduce
```

The script can run multiple things. If needed we can share that too but to keep noise low, we have pulled out just the `all_reduce` to show the error. See repro section below. Full error stack:

```
giri-a100-8g-instance-1:18739:19248 [5] graph/xml.cc:332 NCCL WARN Could not find real path of /sys/class/pci_bus/fffffff/../../fffffff:ffff
giri-a100-8g-instance-1:18739:19248 [5] NCCL INFO graph/xml.cc:644 -> 2
giri-a100-8g-instance-1:18739:19248 [5] NCCL INFO graph/xml.cc:660 -> 2
giri-a100-8g-instance-1:18739:19248 [5] NCCL INFO graph/topo.cc:523 -> 2
giri-a100-8g-instance-1:18739:19248 [5] NCCL INFO init.cc:586 -> 2
giri-a100-8g-instance-1:18739:19248 [5] NCCL INFO init.cc:845 -> 2
giri-a100-8g-instance-1:18739:19248 [5] NCCL INFO group.cc:73 -> 2 [Async thread]

Traceback (most recent call last):
  File "./comms.py", line 269, in <module>
    main()
  File "./comms.py", line 265, in main
    runComms(comms_world_info, commsParams)
  File "./comms.py", line 180, in runComms
    backendObj.benchmark_comms()
  File "/home/giriman/nccl_pyt/comms/pytorch_nccl_backend.py", line 134, in benchmark_comms
    self.commsParams.benchTime(index, self.commsParams, self)
  File "./comms.py", line 139, in benchTime
    timeElapsedNS, algBW, busBW, memSize, x = runColl(collectiveFunc, collectiveArgs, compute_fn=computeFunc)
  File "./comms.py", line 14, in runColl
    collectiveArgs.backendFuncs.complete_accel_ops(collectiveArgs, initOp=True)
  File "/home/giriman/nccl_pyt/comms/pytorch_nccl_backend.py", line 56, in complete_accel_ops
    dist.all_reduce(temp)
  File "/opt/conda/envs/pytorch-source/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 936, in all_reduce
    work = _default_pg.allreduce([tensor], opts)
RuntimeError: NCCL error in: ../torch/lib/c10d/ProcessGroupNCCL.cpp:628, unhandled system error, NCCL version 2.7.3
```

## SCRIPT TO REPRO THE ISSUE

[allreduce.py.zip](https://github.com/NVIDIA/nccl/files/5059139/allreduce.py.zip)

I have attached a sample `allreduce.py` (inside the zip file, had to compress to let github allow the attachment) that one can use to reproduce the issue. Simply run `python allreduce.py` on an A100 instance.

**Comment by sjeaugey** [comment]
Could you try again with the latest version of NCCL ? This error looks like what was fixed in [2.7.6](https://github.com/NVIDIA/nccl/commit/195232556936b39b01cc908296e1650b80d4a3e9). Are you running inside a VM or baremetal ?

**Comment by girifb** [comment]
I am running inside a VM (i am using Google Cloud A100 instances) but we will soon be on bare metal. I will try out with 2.7.6. Thanks for the suggestion.

**Comment by mrshenli** [comment]
PyTorch master branch has been bumped up to NCCL 2.7.6 a few days ago (https://github.com/pytorch/pytorch/pull/42645). Compiling from source would enable it.

**Comment by girifb** [comment]
Verified that it works with `NCCL version 2.7.6+cuda11.0`
