### ISSUE TITLE
allreduce and barriers

### ISSUE THREAD

**Issue by cypof** [NVIDIA/nccl#37]
I'm looking at the NV branch of Caffe with NCCL support. It uses a barrier before doing allreduce. Is it still necessary, or is NCCL tracking data dependencies already?

**Comment by sjeaugey** [comment]
I don't think it is really necessary, just better while developing and debugging. I didn't experience much performance degradation with the barrier, but that may depend on the network/use case.

**Comment by cypof** [comment]
OK thanks, also did you see a significant difference between layer by layer reduce, v.s. a single large reduce at the end?

**Comment by cliffwoolley** [comment]
@slayton58 to comment on that.

**Comment by slayton58** [comment]
@cypof Layer-by-layer allows for overlapping of allReduce calls and other computation, so there can be large improvements in performance and scalability.

**Comment by cypof** [comment]
OK, I could not see a significant difference but I think I'm measuring wrong. I will try again. thks

**Comment by cypof** [comment]
It seems layer-wise or not, the barrier is necessary. Otherwise occasionally NCCL hangs, and some of the GPUs are pegged to 100%, as if some of them skipped a collective and were still polling on the other ones. Have you seen that behavior?

I guess leaving the barrier is OK in single process mode, as it only seems to cost a few percent, but I hope I don't have this issue in multi-process mode as we are trying to finish Caffe's python version. thks

**Comment by cypof** [comment]
Have you tried to remove the barrier in the NV version of Caffe? It's hanging pretty systematically for me. As we add more collectives in Caffe, e.g. for solver state broadcast and support of both layer by layer and global all-reduce it's becoming a bit tedious to pass the barrier around and call it before every collective.

**Comment by fmana** [comment]
Hi folks,

I've just opened an issue (#48) since I fall into some deadlock condition using NCCL. 
My case is different from yours since multiple allreduce hang waiting for someone 
who never will meet enqueued in some place.

I wanted to evaluate the choice to introduce a CPU-based barrier.
Do you have any suggestion in using a specific C/C++ barrier implementation?

Franco

**Comment by cypof** [comment]
Boost:barrier works great. But it's a large dependency if your app doesn't already uses boost.

**Comment by fmana** [comment]
Thanks for feedbacks.... let me try. 
If it will be successful I'll take care of boost dependency.

**Comment by cypof** [comment]
Is anybody looking at this? The only way to get full reliability is to call a barrier before each collective, which for Caffe means before each layer during backprop. If I only call the barrier once per iteration, perf is in some case up to 20% better on 8 GPUs, but it will occasionally hang with some of the GPUs at 100%, apparently polling on something. If you have a plan to fix this, I can wait or leave it like that, otherwise I can try to switch to a separate thread for reduce and barriers, but it's more complicated.

**Comment by slayton58** [comment]
@cypof Currently a barrier is required due to a programming model limitation - we expect this restriction to be relaxed in a future version of CUDA.

**Comment by cliffwoolley** [comment]
For the programming model issue Simon mentioned, we have to wait for a
later version of CUDA (after 8.0).  The feature we're wanting is in
development by the CUDA team, so hopefully we're talking sooner rather than
later, but we can't comment on CUDA release schedules or roadmaps of which
future version will contain which feature.

-Cliff

**Comment by hiyijian** [comment]
hi @cypof. I come across the same issue. Dose barrier in a sperate thread works? I think it is maybe better since we can keep computing without any barrier in main thread?

**Comment by cypof** [comment]
It might help but not sure, I tried playing a bit with using multiple streams, waiting on events etc. but it didn't seem to help vs just making the main thread wait. It hard to know exactly how the tasks interact internally. I'd like to remove the barrier for speed, but also mostly to simplify the code.

**Comment by hiyijian** [comment]
Thanks @cypof .  Do you think the MPI_Barrier should work too in mutiple-process mode please?

**Comment by cypof** [comment]
It should, but I never tried MPI on a single node.

**Comment by hiyijian** [comment]
Why not?

**Comment by sjeaugey** [comment]
Closing old issue. Should no longer be a problem since NCCL 2.1.
