### ISSUE TITLE
Time for all reduction

### ISSUE THREAD

**Issue by vineeths96** [NVIDIA/nccl#373]
Is there any specific advantage, in terms of time for all reduction, if we have a large number of zeros in the tensor?

For example, consider two tensors of int32 type.
`A = [1, 12, 345, 562, 234, 76, 1],    B = [15, 27, 5, 352, 34, 576, 12]`

`C = [1, 0, 0, 0, 1, 12, 0],    D = [0, 23, 0, 5, 0, 12, 0]`

Would these two tensors have a similar time of all reduction operation or would it be different? 
(Of course, I know I can test them empirically. I want to know whether there is an internal mechanism to reduce communication in the case where transmitted value is 0).

**Comment by sjeaugey** [comment]
There should be no difference. There is no compression in case of zeroes.
