### ISSUE TITLE
Missing CPU node attributes with topology injection

### ISSUE THREAD

**Issue by rashikakheria** [NVIDIA/nccl#379]
NCCL detects CPU nodes only when underlying GPU node is used. So in 2-socket system with each socket having 4 GPUs, if we use less than 5 GPUs then the other CPU or its attributes isn't detected. This will hit the following error when a topology is ingested using `NCCL_TOPO_FILE`.

```
graph/xml.h:77 NCCL WARN Attribute arch of node cpu not found
NCCL INFO graph/topo.cc:380 -> 3
NCCL INFO graph/topo.cc:466 -> 3
NCCL INFO graph/topo.cc:569 -> 3
NCCL INFO init.cc:581 -> 3
NCCL INFO init.cc:840 -> 3
NCCL INFO group.cc:73 -> 3 [Async thread]
```

To fix it, NCCL should force read information of all CPUs on the system if the topology provides it.

**Comment by sjeaugey** [comment]
This should be fixed in 2.8 (see preview branch).
