### ISSUE TITLE
Large performance gap when using SHM

### ISSUE THREAD

**Issue by anchenchai** [NVIDIA/nccl#384]
Hi, I was doing some profiling work using nccl-test.

When I used SHM, I saw a very big performance gap of the maximum bandwidth achieved by Broadcast and Allgather for 2 gpus.
Here are some profilling results from nccl-test:
Allreduce: 3.9GB/s,  Allgather: 3.17GB/s， ReduceScatter: 3.17GB/s
**Broadcast: 10.31GB/s， Reduce: 9.62GB/s**.

Experiment environment:
NCCL Version: 2.4.8
CUDA Version: 10.0
OS Version: CentOS 7
PCIE: Gen3 16X

NCCL settings:
NCCL_MAX_NCHANNELS=1
NCCL_P2P_DISABLE=1
NCCL_SHM_DISABLE=0

My question is why the performances of Broadcast and Reduce are crazily high when using SHM for 2 GPUs?  They are comparable with the maximum bandwidth achieved by PCIE P2P ( without NVLINK). Is there any special optimization for Broadcast and Reduce when using SHM transport?

Thanks for your response!

**Comment by sjeaugey** [comment]
On 2 GPUs, Broadcast and Reduce are unidirectional, i.e. they only flow in one direction, contrary to other operations which are bidirectional.

Some components (in particular some CPUs) do not handle bidirectional traffic well, and we've seen similar performance differences on our platforms.

**Comment by anchenchai** [comment]
Ok, thanks a lot
