### ISSUE TITLE
[Question] Interpreting ring sequence from nccl_debug info?

### ISSUE THREAD

**Issue by Luo-Liang** [NVIDIA/nccl#385]
I'm using `NCCL_DEBUG=INFO` to understand how rings are formed. I have 16 GPUs on 2 nodes (8 each). I have a few questions on the following output:

First, from line 1, we see 12's next hop is 11, then from line 11, its next hop is 13? Which one is it?
Second, what does the `[send]` label mean in line 7-8?

```
line content
1  [4] NCCL INFO Ring 00 : 12[41000] -> 11[2d000] via P2P/IPC
2  [5] NCCL INFO Ring 00 : 13[42000] -> 12[41000] via P2P/IPC
3  [6] NCCL INFO Ring 00 : 14[4c000] -> 13[42000] via P2P/IPC
4  [7] NCCL INFO Ring 00 : 15[4d000] -> 14[4c000] via P2P/IPC
5  [0] NCCL INFO Ring 00 : 8[1e000] -> 15[4d000] via P2P/IPC
6  [3] NCCL INFO Ring 00 : 3[2d000] -> 2[28000] via P2P/IPC
7  [1] NCCL INFO Ring 00 : 1[23000] -> 8[1e000] [send] via NET/IB/1/GDRDMA
8  [1] NCCL INFO Ring 00 : 9[23000] -> 0[1e000] [send] via NET/IB/1/GDRDMA
9  [2] NCCL INFO Ring 00 : 10[28000] -> 11[2d000] via P2P/IPC
10 [3] NCCL INFO Ring 00 : 11[2d000] -> 12[41000] via P2P/IPC
11 [4] NCCL INFO Ring 00 : 12[41000] -> 13[42000] via P2P/IPC
```

Many thanks!

**Comment by sjeaugey** [comment]
You should probably not look at connections traces to figure out the rings. Rings are printed in the log before connections are established.

**Comment by Luo-Liang** [comment]
Thank you! May I know where are those rings? The closest I can find are the channels:

[0] NCCL INFO Channel 12/16 :    0   7   6   5  12  11  10   9   8  15  14  13   4   3   2   1
[0] NCCL INFO Channel 13/16 :    0   7   6   4  13  11  10   9   8  15  14  12   5   3   2   1
[0] NCCL INFO Channel 14/16 :    0   5   4   7  14  11  10   9   8  13  12  15   6   3   2   1
[0] NCCL INFO Channel 15/16 :    0   5   4   6  15  11  10   9   8  13  12  14   7   3   2   1

Is this what I should be looking at?

**Comment by sjeaugey** [comment]
Yes, those are the rings.

**Comment by Luo-Liang** [comment]
Thanks!
