### ISSUE TITLE
How to determine a optimal value of NCCL_BUFFSIZE

### ISSUE THREAD

**Issue by firejq** [NVIDIA/nccl#387]
I am using nccl for machine learning training and I have found that NCCL_BUFFSIZE can affect the performance a lot in my case. However, I can't find more suggestions about it on [NCCL Document](https://docs.nvidia.com/deeplearning/nccl/user-guide/docs/env.html#nccl-buffsize).

Could you please give some suggestions or experience to me? : )

**Comment by sjeaugey** [comment]
Can you elaborate on the architecture you're running on (CPU type, number of GPUs, network technology if multiple nodes, ...) and the performance you see at different buffer sizes ? The size should be tuned to be ideal, so if it's not we might want to adjust it.

Changing the NCCL_BUFFSIZE is usually affecting performance in a regular way. The larger the buffer, the better the performance. At least up to some point, then it can drop a bit if it becomes too large and goes beyond some cache sizes.
