### ISSUE TITLE
Documentation on ordering of P2P calls?

### ISSUE THREAD

**Issue by cadedaniel** [NVIDIA/nccl#389]
Hi team, thanks for the work on this great library.

I am trying to use P2P communication in an MPI/distributed training scenario. When I am batching `ncclSend`/`ncclRecv`, how does call order impact the correctness and performance of the result?

For example, will the difference between these two snippets cause any concern?
```cpp
NCCL_CHECK(ncclGroupStart());
if (rank == 0) {
  NCCL_CHECK(ncclSend(dev_ptr_0, count, ncclUint8, 1, nccl_comm, 0));
  NCCL_CHECK(ncclSend(dev_ptr_1, count, ncclUint8, 1, nccl_comm, 0));
}

if (rank == 1) {
  NCCL_CHECK(ncclRecv(dev_ptr_0, count, ncclUint8, 0, nccl_comm, 0));
  NCCL_CHECK(ncclRecv(dev_ptr_1, count, ncclUint8, 0, nccl_comm, 0));
}
NCCL_CHECK(ncclGroupEnd());
```

vs.

```cpp
NCCL_CHECK(ncclGroupStart());
if (rank == 0) {
  NCCL_CHECK(ncclSend(dev_ptr_0, count, ncclUint8, 1, nccl_comm, 0));
  NCCL_CHECK(ncclSend(dev_ptr_1, count, ncclUint8, 1, nccl_comm, 0));
}

if (rank == 1) {
  NCCL_CHECK(ncclRecv(dev_ptr_1, count, ncclUint8, 0, nccl_comm, 0));
  NCCL_CHECK(ncclRecv(dev_ptr_0, count, ncclUint8, 0, nccl_comm, 0)); // Order changed.
}
NCCL_CHECK(ncclGroupEnd());
```

I tried finding documentation on this, but couldn't find anything. The source code shows some system which enqueues requests, then sends them to the kernel. But I can't make out implications of differing orders in `ncclGroup` batches.

Additionally, when `ncclGroupStart`/`ncclGroupEnd` are not used, does the relative order of `ncclRecv`/`ncclSend` begin to matter? I think so in this case, since the kernel is GPU-blocking.

**Comment by sjeaugey** [comment]
This is not yet supported :
https://docs.nvidia.com/deeplearning/nccl/release-notes/rel_2-7-8.html#rel_2-7-8
« Aggregation is not supported on a given source-destination pair, meaning that there can only be one send/receive per source-destination pair. »
You need to copy *ptr_0 and *ptr_1 into a contiguous buffer before sending it.

**Comment by sjeaugey** [comment]
Sorry, forgot to answer the questions at the end. 

Given sends and receive are in different `if (rank == ...)` cases, the order of send/recv does not matter, both send and receive will never be executed on the same rank.

Other than that, without ncclGroupStart/ncclGroupEnd, this code would actually work, doing one send after the other.

And just like with MPI, if you reverse the order of the receives, the content of dev_ptr_0 on rank 1 will be equal to the content of dev_ptr_1 on rank 0.

**Comment by cadedaniel** [comment]
Thanks!
