### ISSUE TITLE
Question about the behavior of allreduce with NCCL_BUFFSIZE

### ISSUE THREAD

**Issue by zarzen** [NVIDIA/nccl#391]
Hi,
I am wondering how does the `NCCL_BUFFSIZE` affect the behavior of allreduce algorithm. 
I see the default `NCCL_BUFFSIZE` is 4MB. 
Does that mean nccl will do allreduce on entire buffer in 4MB by 4MB order? (e.g. a 32MB buffer will be done in 8 consecutive steps, if only 1 channel/ring is used)

**Comment by sjeaugey** [comment]
It's a bit more complicated than that. `NCCL_BUFFSIZE` is the size of the circular FIFO. The FIFO has 8 slots, so each slot is 512KB (for a 4MB FIFO). Rings do not need 8 slots (only 4) so they actually use 2 slots for each chunk, hence 1MB.
Trees and chains(broadcast/reduce), however do benefit from more back to back pipelining so they use all 8 slots and their chunk size is 512KB.
