### ISSUE TITLE
error: an illegal memory access was encountered

### ISSUE THREAD

**Issue by Hamidreza-Ramezani** [NVIDIA/nccl#393]
Hello everyone. 

After adding a few lines into ring all_reduce kernel in my own nccl fork ([here](https://github.com/Hamidreza-Ramezani/nccl/blob/5b21356d1fbc9f7fa11919e84158375c19ad2973/src/collectives/device/all_reduce.h#L77-L88))  and running nccl tests, I got an error. Here is the stack trace:

Test CUDA failure [common.cu:334](https://github.com/Hamidreza-Ramezani/nccl-tests/blob/0bd441c1722e85cdfb37283b7ea848619f37a442/src/common.cu#L334) 'an illegal memory access was encountered'
  Test failure [common.cu:395](https://github.com/Hamidreza-Ramezani/nccl-tests/blob/0bd441c1722e85cdfb37283b7ea848619f37a442/src/common.cu#L395)
  Test failure [common.cu:494
](https://github.com/Hamidreza-Ramezani/nccl-tests/blob/0bd441c1722e85cdfb37283b7ea848619f37a442/src/common.cu#L494)  Test failure [all_reduce.cu:103](https://github.com/Hamidreza-Ramezani/nccl-tests/blob/0bd441c1722e85cdfb37283b7ea848619f37a442/src/all_reduce.cu#L103)

I was wondering if anybody has any idea about this error.

**Comment by Hamidreza-Ramezani** [comment]
as an update, after trying to debug [this](https://docs.nvidia.com/deeplearning/nccl/archives/nccl_278/user-guide/docs/examples.html#example-1-single-process-single-thread-multiple-devices) example with cuda-gdb, I got the following error:

CUDA Exception: Warp Illegal Address
The exception was triggered at PC 0x2aab6c6583b0 ([common_kernel.h:245](https://github.com/NVIDIA/nccl/blob/de49a77074e884758e689ff0204f066eac7aae46/src/collectives/device/common_kernel.h#L245))

common_kernel.h: 245 is:

  asm volatile("st.volatile.global.v2.u64 [%0], {%1,%2};" :: "l"(p), "l"(v.x), "l"(v.y) : "memory");

**Comment by sjeaugey** [comment]
Load/stores in NCCL are 16B (128b) operations, so you need to make sure accesses are also aligned to 16B.

**Comment by Hamidreza-Ramezani** [comment]
@sjeaugey Thank you :)
