### ISSUE TITLE
where the all_reduce kernel is launched? 

### ISSUE THREAD

**Issue by Hamidreza-Ramezani** [NVIDIA/nccl#396]
Hello everyone! I am trying to figure out where the kernel function for ring allreduce is launched. I searched for triple angle brackets in nccl source code, but I could not find any.  I was wondering if that kernel is launched [here](https://github.com/NVIDIA/nccl/blob/de49a77074e884758e689ff0204f066eac7aae46/src/enqueue.cc#L84)?

**Comment by AddyLaddy** [comment]
Yes all the NCCL kernels are launch from the `ncclLaunchCooperativeKernelMultiDevice()` function in enqueue.cc either via `cudaLaunchCooperativeKernelMultiDevice()` or `cudaLaunchKernel()` depeding on the CGMD mode.

**Comment by Hamidreza-Ramezani** [comment]
@AddyLaddy Thank you :)
