### ISSUE TITLE
Compiling NCCL on Fedora 24

### ISSUE THREAD

**Issue by TheStroj** [NVIDIA/nccl#40]
Hello everyone!

I tried compiling NCCL from source on Fedora 24 with GCC 6.1 and CUDA 8.0 on a server with 2 GPUs (a single Tesla K80 card). However, I ran into the following error while trying to compile:

**/usr/local/cuda/include/cuda_fp16.h(2970): error: more than one instance of overloaded function "isinf" matches the argument list**

I then tried adding the **-std=c++98** flag to the **CXXFLAGS** in the Makefile, and it progressed further, albeit with the following warnings:

**cc1: warning: command line option ‘-std=c++98’ is valid for C++/ObjC++ but not for C**

The error it threw this time was:

**error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support must be enabled with the -std=c++11 or -std=gnu++11 compiler options**

So if I understand correctly, if I try to compile with GCC 6 without any flags, it throws the overloaded error, but if I try to compile with an older GCC standard, it can't compile because it needs the newer GCC functions.

Do you maybe have any suggestions or am I out of luck trying to get NCCL working in this environment? Is there perhaps any alternative to NCCL for multi-GPU usage for Deep Learning (specifically, Caffe)?

Thank you very much! :)

**Comment by nluehr** [comment]
Unfortunately, CUDA does not support GCC 6.x yet. You would need to install an older GCC along side the system default.

**Comment by TheStroj** [comment]
Thanks for the reply! I actually tried that previously (I installed GCC 4.9) and tried compiling with that, but the errors persisted (I think it was the same "ISO C++ 2011 standard" error). But no matter - I'll wait for future versions of CUDA that will support GCC 6.1. :)

**Comment by spotluri** [comment]
This should be resolved with newer versions of CUDA.
