### ISSUE TITLE
What each thread does in the ncclAllReduceRingKernel? 

### ISSUE THREAD

**Issue by Hamidreza-Ramezani** [NVIDIA/nccl#400]
Hello everyone! 

I would like to know what the responsibility of each thread in [ncclAllReduceRingKernel](https://github.com/NVIDIA/nccl/blob/de49a77074e884758e689ff0204f066eac7aae46/src/collectives/device/all_reduce.h#L12) is? In particular, in primitives like [send](https://github.com/NVIDIA/nccl/blob/de49a77074e884758e689ff0204f066eac7aae46/src/collectives/device/primitives.h#L296-L299) and [receive](https://github.com/NVIDIA/nccl/blob/de49a77074e884758e689ff0204f066eac7aae46/src/collectives/device/primitives.h#L305-L308), does each thread care about a group elements of the array? Is there any formula that specifies thread with id _x_ is responsible for which group of elements?

**Comment by sjeaugey** [comment]
Not easy. That depends on a lot of factors, like the chunk side, the number of channels we use, ... and it will probably be even more complex in 2.8.

**Comment by Hamidreza-Ramezani** [comment]
@sjeaugey Thank you :)
