### ISSUE TITLE
NCCL_SHM_DISABLE

### ISSUE THREAD

**Issue by david-macleod** [NVIDIA/nccl#406]
Hi 

I noticed when setting `NCCL_SHM_DISABLE=1` I see a large drop in performance, and I was wondering if you could explain what this option is doing (and when you would ever want to use it). The docs say

> NCCL will use network (i.e. InfiniBand or IP sockets) to communicate between the CPU sockets when SHM is disabled

Which seems to imply data is being sent between the CPUs (over QPI?), but the cards I am testing this on are both connected to the same CPU, so I clearly have misunderstood this.

Many thanks

**Comment by sjeaugey** [comment]
If you disable SHM, NCCL will use the network to communicate between GPUs that are on different sockets and would use SHM otherwise.

Now, using the network might well use QPI if you don't have a NIC attached to each socket, in which case it is usually not helping much. This is mainly useful when you have GPUs connected to PCI switches, and you also have one NIC connected to each PCI switch; in which case using NICs instead of SHM you would always stay within the PCI switch and achieve 12GB/s instead of 9 or 6.

**Comment by david-macleod** [comment]
Thanks for the response! So would we still expect a difference in behavior using this setting when both GPUs have the same CPU affinity? Is SHM also used when GPUs are attached to different CPUs?

**Comment by sjeaugey** [comment]
SHM is primarily used when GPUs are on different CPUs. Otherwise, P2P might be used (depending on the situations SHM could still be better).

In any case, if both GPUs are on the same socket, I don't see how using NET instead of SHM would help.

**Comment by david-macleod** [comment]
In my current setup my GPUs don't have P2P enabled (2080 ti) so always SHM used and I get acceptable performance. However they all have the same CPU affinity and I am trying to gauge what sort of performance I might get in a dual root setting where half of the GPUs are connected to each CPU. Should I expect similar performance to single CPU SHM, or it is largely dependent on the intersocket bandwidth as I imagine it will have to make an extra copy from one CPU memory to the other?

Are there are notes on what SHM is doing? I couldn't find much info in the docs

Many thanks

**Comment by david-macleod** [comment]
OK thanks, so whether the GPUs are connected to the same CPU or different CPUs is less of a factor than the the CPU memory bandwidth itself? I had guessed that the additional copy from CPU1 memory to CPU2 memory would be an important factor in determining throughput?

**Comment by sjeaugey** [comment]
Indeed the inter-CPU link could be a bottleneck as well, but I'd expect that link to be able to sustain 12GB/s in each direction.

**Comment by david-macleod** [comment]
Great, thanks for the info!
