### ISSUE TITLE
ReduceCopyMulti

### ISSUE THREAD

**Issue by Hamidreza-Ramezani** [NVIDIA/nccl#407]
Hello everyone! 

I was wondering what **srcs** and **MAXSRCS** represent in [common_kernel:257](https://github.com/NVIDIA/nccl/blob/master/src/collectives/device/common_kernel.h#L257). 

Best,
Hamid

**Comment by sjeaugey** [comment]
srcs is the array of buffers we read from, reduce; dsts is the array of buffers we write the result to.

Or said differently, considering the reduction operation is a sum,
```
 dsts[0] = dsts[1] = ... = dsts[ndsts] = srcs[0] + srcs[1] + .. + srcs[nsrcs]
```
MINSRCS, MAXSRCS, MINDSTS, MAXDSTS are constants which help to unroll and optimize code.

**Comment by Hamidreza-Ramezani** [comment]
@sjeaugey Thanks a lot :)
