### ISSUE TITLE
How to verify NCCL_ALGO and NCCL_PROTO?

### ISSUE THREAD

**Issue by mabdullahsoyturk** [NVIDIA/nccl#408]
I want to use Ring algorithm with Simple proto. This is the command I use to run the ncclAllReduce application in nccl-tests:

`NCCL_ALGO=Ring NCCL_PROTO=Simple NCCL_DEBUG_FILE=debug.%h.%p NCCL_DEBUG=INFO ./all_reduce_perf -b 128M -e 128M -g 4 -n 1 -w 0 -c 0 -m 0`

When I check the debug file, I can't see anything related to ring creation or protocol change. I was expecting to see info messages specified in [tuning.c](https://github.com/NVIDIA/nccl/blob/01afd20a77b5804e0ecf1042509dd9d20ebf9e93/src/graph/tuning.cc#L161), but there is no info message related to that. 

How can I verify whether the application uses Ring algorithm and Simple protocol?

**Comment by sjeaugey** [comment]
If you set `NCCL_DEBUG_SUBSYS=TUNING` you should see all proto/algo combinations have a bandwidth of 0, except Ring/Simple.

**Comment by mabdullahsoyturk** [comment]
Great. Thanks!
