### ISSUE TITLE
nccl long compilation time

### ISSUE THREAD

**Issue by hamid-ramezani** [NVIDIA/nccl#414]
Hi everyone! 

In order to compile nccl, I usually need to wait almost 5mins. As I am only interested in allReduce collective, is there any specific part in the makefile which I can comment in order to exclude other collectives to be compiled? It seems to me that I need to change at least these files: functions.cu, gen_rules.sh, enqueue.cc. 

Best,

**Comment by sjeaugey** [comment]
The best is usually to set NVCC_GENCODE to restrict it to only your GPU architecture. And of course compile in parallel on multiple cores. Something like `$ make -j src.build NVCC_GENCODE="-gencode=arch=compute_70,code=sm_70"`, as mentioned in https://github.com/NVIDIA/nccl#build.

**Comment by hamid-ramezani** [comment]
@sjeaugey Thanks a lot :)
