### ISSUE TITLE
Very slow inter-node communication calls

### ISSUE THREAD

**Issue by wangraying** [NVIDIA/nccl#416]
Hi, 

We found that there exists very slow nccl calls in inter-node communications. The job was launched on 2-nodes, and we only all-gather the data of GPU-0. 

We initiated 4 all-gather calls in one iteration, but found that the execution time varies significantly. And it seems for some very long calls, the two nodes were not waiting for each other. For example, the 9th all-gather starts at near time, but ends very differently. Why it possibly takes such a long time for the first one? 

![屏幕快照 2020-11-07 下午5 11 34](https://user-images.githubusercontent.com/45031995/98437424-f51c3700-211c-11eb-9aa4-f82be5f3495f.png)

![屏幕快照 2020-11-07 下午5 11 25](https://user-images.githubusercontent.com/45031995/98437429-f9485480-211c-11eb-82e4-74678e15fb5f.png)

Thanks!

**Comment by wangraying** [comment]
And the timeline of the slower node is:
![屏幕快照 2020-11-07 下午5 36 38](https://user-images.githubusercontent.com/45031995/98438073-66aab400-2122-11eb-9bf4-f6488a418e02.png)

**Comment by sjeaugey** [comment]
Do you see any noise or bad performance when running the performance tests ?

**Comment by wangraying** [comment]
> Do you see any noise or bad performance when running the performance tests ?

This problem has been solved after we changed some RDMA network configurations.

Thanks.

**Comment by sjeaugey** [comment]
Thanks for the update @wangraying . Closing.
