### ISSUE TITLE
NCCL not found when build NV caffe

### ISSUE THREAD

**Issue by m5061125** [NVIDIA/nccl#42]
Hi, I am new guy to Digits and Linux, So pls forgive me if the issue is too naive.
I biuld the NV caffe using the source code, my system have 4 K40c Tesla cards.
I build the nccl lib according the guidline in this page, but when I "cmake .." the caffe,
the system tell me that NCCL not found. I think it is some problem with enveirment 
paras setup. So would pls tell me how to fix it, thanks.

**Comment by lukeyeager** [comment]
Try using these CMake flags when configuring your Caffe build:

    -DUSE_NCCL=ON -DNCCL_ROOT_DIR=/path/to/nccl

That's assuming you're following these build instructions:
https://github.com/NVIDIA/DIGITS/blob/digits-4.0/docs/BuildCaffe.md#build

**Comment by m5061125** [comment]
Thanks Luk, the NCCL is found during the cmake process, but when build the caffe with make commond, it tell me the nccl.h file can't find when build nccl.hpp. I have to manually include the full path of the nccl.h.
So do you have other more efficient method to assigne the include path, thanks again.
