### ISSUE TITLE
unexpected result running ncclGroupEnd on child thread

### ISSUE THREAD

**Issue by janilbols-w** [NVIDIA/nccl#421]
Hi guys, I'm trying to write my own code with nccl, with threadpool.  

Is it possible to modify single thread code like below, to a theadpool mode, with each nccl execution running on a new thread.  
my project seems a little messy, so that the actual nccl function calls are a little bit strange.

```
ncclGroupStart()
for (int i=0; i<nDevs; i++){
    ncclAllReduce(...)
}
ncclGroupEnd()
```
to

```
mainThread calling:
      thread 1 : execution with: ncclGroupStart() 
      join thread 1
      thread 2 : execution with ncclAllReduce
      join thread 2
      thread 3 : ...
      ...
      thread N: execution with: ncclGroupEnd()
      join thread N
```

----------------------------------------------------

Even we we tried migrate cuda context to all threads, to make their cudaContext all the same,  
The result is still wrong.

Is threadlocal parameters used in "group.cc" causing this issue?

[nccl_theadmode.cu.txt](https://github.com/NVIDIA/nccl/files/5564836/nccl_theadmode.cu.txt)

**Comment by sjeaugey** [comment]
Yes, indeed, the group semantics are used to define a group of operations which will be fused together, and are purely local to each thread. They just allow for expressing more complex operations from basic verbs; they don't allow aggregation across different threads.

If you want to aggregate between threads, you need a module common to all threads which will keep the list of operations to perform and trigger them all at once from one thread.

**Comment by janilbols-w** [comment]
Thanks man, very helpful~ I'll try redesign my work.
