### ISSUE TITLE
Some questions on Group Call

### ISSUE THREAD

**Issue by zhuzilin** [NVIDIA/nccl#430]
Hi there. From the documentation, we have the following documentation on Group Call:
> The group semantics can also be used to have multiple collective operations performed within a single NCCL launch. This is useful for reducing the launch overhead, in other words, latency, as it only occurs once for multiple operations. Init functions cannot be aggregated with other init functions, nor with communication functions.
>
> Aggregation of collective operations can be done simply by having multiple calls to NCCL within a ncclGroupStart / ncclGroupEnd section.
> 
> In the following example, we launch one broadcast and two allReduce operations together as a single NCCL launch.
> ```c++
> ncclGroupStart();
> ncclBroadcast(sendbuff1, recvbuff1, count1, datatype, root, comm, stream);
> ncclAllReduce(sendbuff2, recvbuff2, count2, datatype, comm, stream);
> ncclAllReduce(sendbuff3, recvbuff3, count3, datatype, comm, stream);
> ncclGroupEnd();
> ```
> https://docs.nvidia.com/deeplearning/nccl/user-guide/docs/usage/groups.html

However, from the source code of `GroupEnd`, it seems that the collectives are called one by one:
```c++
NCCL_API(ncclResult_t, ncclGroupEnd);
ncclResult_t ncclGroupEnd() {
  // ...
  // 1. Barrier Check In. Only the last call may call cudaLaunchKernel[cooperative]
  for (int i=0; i<ncclGroupIndex; i++) {
    struct ncclAsyncArgs* args = ncclGroupArgs+i;
    if (args->funcType == ASYNC_FUNC_COLL) {
      if (args->coll.comm->userStream == NULL)
        CUDACHECKGOTO(cudaSetDevice(args->coll.comm->cudaDev), ret, end);
      NCCLCHECKGOTO(ncclBarrierEnqueue(args->coll.comm), ret, end);
    }
  }
  // ...
}
```
As far as I can tell, `ncclBarrierEnqueue` will run `cudaLaunchCooperativeKernelMultiDevice` or `cudaLaunchKernel` for the `i`th collectives in the group.
Could you give some hints on how the collectives are aggregated into one nccl call?

Thank you :).

**Comment by sjeaugey** [comment]
The code mentioned is only for synchronization on the CPU side. On the GPU side, one CUDA kernel will execute all aggregated operations. Operations to execute by the CUDA kernel are stored in the workFifo of each channel.

**Comment by zhuzilin** [comment]
@sjeaugey Thank you for your information!
