### ISSUE TITLE
negative nelem

### ISSUE THREAD

**Issue by hamid-ramezani** [NVIDIA/nccl#436]
Hi all, 

I tried to print the [nelem](https://github.com/NVIDIA/nccl/blob/920dbe5b359fe5817b8ba874476ca4ba2dc5f1ef/src/collectives/device/all_reduce.h#L56) variable that seems to represent the number of elements that are communicated. I noticed it can have a negative value in some cases. 

I would like to know, in cases where [nelem](https://github.com/NVIDIA/nccl/blob/920dbe5b359fe5817b8ba874476ca4ba2dc5f1ef/src/collectives/device/all_reduce.h#L56) is a negative number, how many elements are communicated in a statement like [this](https://github.com/NVIDIA/nccl/blob/master/src/collectives/device/all_reduce.h#L58)?  is it `offset + nelem` ?

**Comment by sjeaugey** [comment]
It should do as for a 0-elements step, i.e. it will still synchronize but exchange no data.

**Comment by hamid-ramezani** [comment]
@sjeaugey Thank you:)
