### ISSUE TITLE
6x slowdown on Pascal TitanX on 80 lane PCIe switch.

### ISSUE THREAD

**Issue by scott-gray** [NVIDIA/nccl#44]
So we have some 8 gpu machines running Maxwell TitanX's and we decided to try swapping them out with the newer cards.  The basic hardware architecture is a pair of 80 lane switches connected to the same CPU.  The driver is version 367.35

When running your benchmark on the Maxwell cards I get pretty much the expected numbers:
```
./build/test/single/all_reduce_test 10000000 2 0 1
       N    type      op     time  algbw  busbw
10000000    char     sum    0.886  11.28  11.28

./build/test/single/all_reduce_test 10000000 2 0 7
       N    type      op     time  algbw  busbw
10000000    char     sum    1.215   8.23   8.23
```

I get about a 6x slowdown running on the exact same system but with Pascal instead of Maxwell cards.  Also, the test that traverses the CPU runs at the same speed:
```
./build/test/single/all_reduce_test 10000000 2 0 1
       N    type      op     time  algbw  busbw
10000000    char     sum    5.650   1.77   1.77

./build/test/single/all_reduce_test 10000000 2 0 7
       N    type      op     time  algbw  busbw
10000000    char     sum    5.661   1.77   1.77
```
The slowdown is about 5x when running the test with all 8 gpus enabled.

Here are the results on a on an Intel Z170 chipset running two Pascal Titans on 8x PCIe.  There doesn't seem to be an issue here (about 2x slower than the Maxwells running on 16x PCIe).
```
       N    type      op     time  algbw  busbw
10000000    char     sum    1.674   5.97   5.97
```

When testing with the cuda sample p2pBandwidthLatencyTest program, I get nearly identical results with the 2 sets of cards.  The exception is the latency numbers with peer access enabled:

Maxwell:
```
P2P=Enabled Latency Matrix (us)
   D\D     0      1      2      3      4      5      6      7 
     0   4.10   8.03   8.22   7.46   7.25   6.95   7.47   6.76 
     1   7.37   4.49   7.26   7.25   7.05   6.66   7.25   6.72 
     2   7.27   7.33   4.24   7.34   7.16   6.66   7.49   6.85 
     3   7.19   7.05   7.38   4.04   6.94   6.47   6.86   6.73 
     4   7.03   6.85   6.89   7.30   3.90   6.52   7.19   6.72 
     5   7.42   7.24   6.94   7.02   7.00   4.22   7.17   7.09 
     6   8.68   7.32   7.11   7.24   7.07   7.10   4.41   6.39 
     7   7.77   7.76   7.20   7.68   8.09   6.77   7.55   4.01 
```

Pascal:
```
P2P=Enabled Latency Matrix (us)
   D\D     0      1      2      3      4      5      6      7 
     0   3.39  20.00  14.53  19.57  19.73  16.15  19.17  17.48 
     1  16.02  11.21  14.42  19.54  19.75  16.20  19.11  17.55 
     2  16.07  19.93   3.79  19.58  19.72  16.48  19.18  17.56 
     3  16.03  19.85  14.43   4.35  19.72  16.25  19.10  17.47 
     4  16.21  19.81  14.58  19.88  11.34  16.06  19.09  17.39 
     5  16.28  19.76  14.62  19.63  19.61   3.27  19.14  17.31 
     6  16.07  19.95  14.55  19.70  19.62  16.18   4.03  17.36 
     7  16.08  20.03  14.62  19.89  19.78  16.05  19.27  11.23 
```

We see similar slowdowns when training large models in tensorflow (which is how this came to our attention).  Your tool seemed like a good way to probe this issue.  Is there a more appropriate place to submit this bug?

**Comment by scott-gray** [comment]
So I just had the driver on the machine update to 370.  I think this may have fixed the issue.  I'll keep you posted.

A related question is do you know if anyone is working on nccl/tensorflow integration?

**Comment by scott-gray** [comment]
It appears the issue is completely resolved in the 370 driver.  I'd close the issue but I'm curious on the answer to my tensorflow question.

**Comment by ajtulloch** [comment]
@scott-gray adding NCCL to an existing computation-graph framework is pretty clean,  e.g. https://github.com/caffe2/caffe2/tree/master/caffe2/contrib/nccl
