### ISSUE TITLE
Large allReduce size, better NCCL bandwidth

### ISSUE THREAD

**Issue by pro-panda** [NVIDIA/nccl#445]
Following is a nccl-tests run on 1 node-4 GPU setting, with NCCL running over PCIe
```
#
#                                                     out-of-place                       in-place          
#       size         count    type   redop     time   algbw   busbw  error     time   algbw   busbw  error
#        (B)    (elements)                     (us)  (GB/s)  (GB/s)            (us)  (GB/s)  (GB/s)       
      262144         65536   float     sum    122.3    2.14    3.22    N/A
      524288        131072   float     sum    198.8    2.64    3.96    N/A
     1048576        262144   float     sum    349.1    3.00    4.51    N/A
     2097152        524288   float     sum    670.8    3.13    4.69    N/A
     4194304       1048576   float     sum   1312.7    3.20    4.79    N/A
     8388608       2097152   float     sum   2605.3    3.22    4.83    N/A
    16777216       4194304   float     sum   5183.1    3.24    4.86    N/A
    33554432       8388608   float     sum    10339    3.25    4.87    N/A
    67108864      16777216   float     sum    20653    3.25    4.87    N/A
   134217728      33554432   float     sum    41278    3.25    4.88    N/A
   268435456      67108864   float     sum    82503    3.25    4.88    N/A
   536870912     134217728   float     sum   164854    3.26    4.88    N/A
  1073741824     268435456   float     sum   328867    3.26    4.90    N/A
```

Why do larger sizes have better bandwidths?

**Comment by kwen2501** [comment]
The time to execute a collective consists of, roughly, latency overhead and the time to transmit data. When the data size is small, the latency overhead has a bigger weight in the execution time, i.e. the collective is spending bigger portion of time dealing with the latency overhead rather than transmitting data, hence the **effective** bandwidth is smaller.

**Comment by pro-panda** [comment]
While running on multi-node over TCP, I've seen that the drop in effective bandwidth is even higher. 
How much of it is likely due to latency introduced by NCCL vs by TCP?

**Comment by kwen2501** [comment]
I would expect the TCP latency to be much larger than the intra-node GPU-to-GPU latency. I don't have detailed numbers though.

**Comment by pro-panda** [comment]
Sorry, I'll rephrase. How much of the latency do you expect is introduced by NCCL CPU proxy architecture?
Or is most of the latency only due to TCP?

**Comment by kwen2501** [comment]
Most due to TCP I would say.

**Comment by AddyLaddy** [comment]
I just did a quick experiment comparing NCCL AllReduce latency over IB (verbs) verses IPoIB on the same pair of nodes and NIC. The IB latency was around 30us verses 65us with IPoIB on a single NIC. Peak BW was also severly limited with TCP.
