### ISSUE TITLE
Questions on Collnet and Iallreduce

### ISSUE THREAD

**Issue by changlan** [NVIDIA/nccl#449]
Hello, I am trying to understand how allreduce in `collnet` works. As far as I understand, data in sendbuff is sliced into multiple slots, and then we post an Iallreduce request for each slot. However, I have a few questions:

1. How does NCCL determine the size of each slot? Is it an adjustable parameter? 
2. How many concurrent Iallreduce requests are possible?

Any reference to the source code would be greatly appreciated. Thanks!

**Comment by kwen2501** [comment]
> How does NCCL determine the size of each slot? Is it an adjustable parameter?

There are `NCCL_STEPS` slots in the transmission buffer, where `NCCL_STEPS`=8. Take the Simple protocol for example, the default buffer size is 4MB, hence the slot size if 512KB. The actual size used out of a slot can be smaller (particularly when sending the last chunk of data) and depends on the size of the message chunk given by the upstream GPU, see `sizesFifo` in coll_net.cc.

> How many concurrent Iallreduce requests are possible?

That depends on (a) the processing time of the reduction network, (b) the CPU processing speed of the CollNet code, and (c) the speed of the GPU pipeline. I would think of (a) as a consumer (with an average response time h), and the minimum of (b) and (c) as a producer (with a rate lambda), then the average number of outstanding requests may be roughly lambda*h.

**Comment by changlan** [comment]
Thanks. Is the number of outstanding requests also bounded by `NCCL_STEPS`? I was thinking if `h` is large enough, then `NCCL_STEPS=8` might not be sufficient to saturate the network.

**Comment by kwen2501** [comment]
Yes, the number of outstanding requests is also bounded by `NCCL_STEPS`. 

But in reality we don't see so many outstanding requests, unless the network is way too slow.
