### ISSUE TITLE
does ready flag work for LL128?

### ISSUE THREAD

**Issue by dearsxx0918** [NVIDIA/nccl#456]
We have a [ready ](https://github.com/NVIDIA/nccl/blob/399656269027c1818fc999ccf8ec4dd838cec50d/src/transport/net.cc#L295) flag here.
And we also redefined ready  [here](https://github.com/NVIDIA/nccl/blob/399656269027c1818fc999ccf8ec4dd838cec50d/src/transport/net.cc#L297).
The first one do not work any more for LL128. And the flag check for LL128 is no meaning?

**Comment by kwen2501** [comment]
The flag check for LL128 is effective when we don't have GPUDirect RDMA (read) on the send side.

**Comment by dearsxx0918** [comment]
> The flag check for LL128 is effective when we don't have GPUDirect RDMA (read) on the send side.

Thanks for your reply.
Take a look at the code, the ready flag defined twice here. Which means the first defined ready is not work in the scope of second ready. See the code block copied from master branch:
        int ready = 1;      // **First ready defined here.**
        if (args->protocol == NCCL_PROTO_LL128) {
          int ready = resources->useGdr;  //**Second ready defined here.**
          if (!ready) {
            // When data is in sysmem, we need to wait until all flags are correct since the GPU only
            // called threadfence()
            uint64_t flag = args->transmitted + 1;
            int nFifoLines = DIVUP(sizesFifo[buffSlot], sizeof(uint64_t)*NCCL_LL128_LINEELEMS);
            volatile uint64_t* lines = (volatile uint64_t*)buff;
            ready = 1;
            for (int i=0; i<nFifoLines; i++) {
              if (lines[i*NCCL_LL128_LINEELEMS+NCCL_LL128_DATAELEMS] != flag) { ready = 0; break; } // **change second ready here won't affect the first defined ready.**
            }
          }
        } else if (args->protocol == NCCL_PROTO_LL) {
          uint32_t flag = NCCL_LL_FLAG(args->transmitted + 1);
          int nFifoLines = DIVUP(size, sizeof(union ncclLLFifoLine));
          union ncclLLFifoLine* lines = (union ncclLLFifoLine*)buff;
          for (int i=0; i<nFifoLines; i++) {
            volatile uint32_t *f1 = &lines[i].flag1;
            volatile uint32_t *f2 = &lines[i].flag2;
            if (f1[0] != flag || f2[0] != flag) { ready = 0; break; }
          }
        }
        if (ready) // **ready will always be 1 for LL128 protocol**

**Comment by dearsxx0918** [comment]
Could you please take a detailed look at this?

**Comment by sjeaugey** [comment]
Right, good catch, we probably have a bug here.

Now given that we currently disable LL128 when we don't have GPU Direct RDMA, we'll probably never see a problem unless we force `NCCL_PROTO=LL128`, and even forcing it, the probability that one such error happens is low as we're still flushing data (but not all the way to CPU memory so in theory data corruption could happen).

Thanks for the report, we'll fix the bug.

**Comment by dearsxx0918** [comment]
Thanks for your reply.
