### ISSUE TITLE
How does NCCL decide which algorithm to use?

### ISSUE THREAD

**Issue by mabdullahsoyturk** [NVIDIA/nccl#457]
Hello everyone,

I have three questions:

- How does NCCL decide to use Ring or Tree on intranode communication?
- Does it decide on the algorithm at the begining and stick with that algorithm or does it change automatically during runtime? 
- Is it possible to get how much data a GPU receives and sends in total? I am asking this because as far as I understand with ring algorithm, for example, if we execute allReduce with 100MB sendbuffer and 4 GPUs, each GPU sends (N/P) * 2 * (P-1/P) bytes which is (100/4) * 2 * (3/4) 150MB. Is my calculation correct? How can I do a similar calculation for the Tree algorithm?

**Comment by firejq** [comment]
#256 may help.

**Comment by sjeaugey** [comment]
Actually the ring/tree tuning answer is outdated on #256. We now have up to 9 choices for Algorithm x Protocol ({Ring,Tree,CollNet}x{LL,LL128,Simple}) so we have models of each combination and for each size, we estimate how much time each would take, then take the lowest.

How much data a GPU sends and receives in total is a complicated question. Without going into the details and corner cases, for an allreduce of size S on N GPUs, each GPU on a ring would send and receive 2(N-1)*S/N; for tree it would be 2*S (except for the root which is just S); and for collnet (network-accelerated allreduce) it would be 2*S intra-node and S inter-node.

**Comment by mabdullahsoyturk** [comment]
@firejq Thanks for pointing to the issue. 

@sjeaugey Thanks a lot for the answer. How do you do the estimation and how can I learn more about the details and corner cases? Since I am trying to record the communication between each GPU, I need to be aware of the details and the corner cases.

**Comment by sjeaugey** [comment]
Everything is in `src/graph/tuning.cc` but it's unfortunately very complicated and based on experiments (the reality doesn't always match the theory), and it would take a lot of time to document all of that.

**Comment by mabdullahsoyturk** [comment]
I understand. Thanks for the quick reply.

**Comment by zhangmenghao** [comment]
> Actually the ring/tree tuning answer is outdated on #256. We now have up to 9 choices for Algorithm x Protocol ({Ring,Tree,CollNet}x{LL,LL128,Simple}) so we have models of each combination and for each size, we estimate how much time each would take, then take the lowest.
> 
> How much data a GPU sends and receives in total is a complicated question. Without going into the details and corner cases, for an allreduce of size S on N GPUs, each GPU on a ring would send and receive 2(N-1) * S/N; for tree it would be 2 * S (except for the root which is just S); and for collnet (network-accelerated allreduce) it would be 2 * S intra-node and S inter-node.

@sjeaugey Hi, Sylvain, regarding this reply, I have some questions. For an all-reduce of size $S$ on $N$ GPUs, in the tree algorithm, I guess the data a GPU sends/receives should also be $2(N-1) * S/N$. The tree algorithm consists of a $log_2N$ number of reduce-scatter and a  $log_2N$ number of all-gather. In the reduce-scatter procedure, the data a GPU sends/receive in each data transfer is $S/2, S/4 ... S/N$ respectively, thus the total data a GPU sends/receives is $(N-1) * S/N$. Similarly, in the all-gather procedure, the data a GPU sends/receive in each data transfer is $S/N ...  S/4, S/2$ respectively, thus the total data a GPU sends/receives is also $(N-1) * S/N$. Therefore, the total data a GPU sends/receives in tree-based all-reduce should be $2(N-1) * S/N$, instead of $2 * S$. Do I understand correctly?

**Comment by sjeaugey** [comment]
> In the reduce-scatter procedure, the data a GPU sends/receive in each data transfer is $S/2,S/4,S/8$ respectively, 

No that would be a totally different algorithm. We send the whole data through the trees (up then down), in a pipelined manner so that there is always data in and data out. It's not done through $log_2(n)$ consecutive stages of different sizes.

**Comment by sjeaugey** [comment]
There is a blog post about it: 
https://developer.nvidia.com/blog/massively-scale-deep-learning-training-nccl-2-4/

Before you ask, there are many reasons why we preferred that algorithms to others, e.g. recursive doubling:
 - Dual binary trees have a fixed number of peers we communicate with (up to 2 down and 1 up) . That means when compiling CUDA code, the compiler can make assumptions about loop depth and properly unroll loops.
  - Binary trees do not work better with number of ranks being a power-of-two. They work equally well on any number of ranks.
  - Binary trees do not create a lot of flows on higher levels in the fabric, contrary to algorithms which need N/2 ranks to talk to N/2 ranks at each step and require perfect bisection bandwidth at all levels.

**Comment by JingxinPan** [comment]
> Actually the ring/tree tuning answer is outdated on #256. We now have up to 9 choices for Algorithm x Protocol ({Ring,Tree,CollNet}x{LL,LL128,Simple}) so we have models of each combination and for each size, we estimate how much time each would take, then take the lowest.
> 
> How much data a GPU sends and receives in total is a complicated question. Without going into the details and corner cases, for an allreduce of size S on N GPUs, each GPU on a ring would send and receive 2(N-1) * S/N; for tree it would be 2 * S (except for the root which is just S); and for collnet (network-accelerated allreduce) it would be 2 * S intra-node and S inter-node.

@sjeaugey if the answer is outdated in #256, could you let us know which algorithms the allreduce is using in latest version? reduce+broadcast/reducescatter+allgather in ring/treesplit. Thanks.

**Comment by lyppg** [comment]
> Actually the ring/tree tuning answer is outdated on #256. We now have up to 9 choices for Algorithm x Protocol ({Ring,Tree,CollNet}x{LL,LL128,Simple}) so we have models of each combination and for each size, we estimate how much time each would take, then take the lowest.
> 
> How much data a GPU sends and receives in total is a complicated question. Without going into the details and corner cases, for an allreduce of size S on N GPUs, each GPU on a ring would send and receive 2(N-1) * S/N; for tree it would be 2 * S (except for the root which is just S); and for collnet (network-accelerated allreduce) it would be 2 * S intra-node and S inter-node.

@sjeaugey if the answer is outdated in #256, could you let us know which algorithms the allreduce is using in latest version? reduce+broadcast/reducescatter+allgather in ring/treesplit. Thanks.
