### ISSUE TITLE
cudaFree collectiveArgs

### ISSUE THREAD

**Issue by hamid-ramezani** [NVIDIA/nccl#461]
Hello, 

I've added a field (an array) to [collectiveArgs](https://github.com/NVIDIA/nccl/blob/033d799524fb97629af5ac2f609de367472b2696/src/include/devcomm.h#L135) and allocated memory for it. After using that array inside the kernel, I plan to free its memory. 

I was wondering what is the best place to free that memory? is [here](https://github.com/NVIDIA/nccl/blob/033d799524fb97629af5ac2f609de367472b2696/src/group.cc#L292) (after the call to ncclEnqueueEvents) a safe place to free the memory of some buffers used in kernel?

**Comment by kwen2501** [comment]
Hi, we do not free `collectiveArgs` until the end of life of the NCCL communicator, i.e. when user calls `ncclCommDestroy`. 

As for your allocated memory, it is hard for the CPU side of NCCL to know when the CUDA kernel finishes consuming the memory. At the user level, users can call `cudaStreamSynchronize(stream)` or record a CUDA event to determine that. Not sure if that's easily doable from within NCCL. Can that memory be free at the end of life of the communicator like `collectiveArgs`?

**Comment by hamid-ramezani** [comment]
@kwen2501 Hi Ke, 
Thank you very much for the reply. 

> Can that memory be free at the end of life of the communicator like collectiveArgs?

Unfortunately no. Because I allocate that memory in the CPU side of ncclAllReduce. The allocated memory would be added up in a scenario when multiple calls to ncclAllReduce are made (like in nccl_tests) and it causes memory issues.

> At the user level, users can call cudaStreamSynchronize(stream)

I tried to free the memory in the nccl-tests. I did it above [this](https://github.com/NVIDIA/nccl-tests/blob/master/src/common.cu#L861-L865) and my snippet is as follows: 
`  for(int i=0; i<nGpus*nThreads; ++i) {
    cudaFree(comms[i]->args.args.my_buffer);
  }
`

I keep getting this compilation error: `pointer to incomplete class type is not allowed`,  I was wondering if by any chance you have idea about this?

**Comment by kwen2501** [comment]
I am not sure how you can pass a buffer other than the input and output buffers from user code all the way down to NCCL kernels because the NCCL APIs does not take extra arguments. 

As for the compilation error, did you check the definition of `my_buffer`? Could there be something that's declared but not defined?

**Comment by hamid-ramezani** [comment]
@kwen2501 Thanks Ke. 

> As for the compilation error, did you check the definition of my_buffer? Could there be something that's declared but not defined?
Yes, I've already added that to the CollectiveArgs. 

But, no worry. Now, I've added that memory in the init.cc file which allocates the memory only once for multiple calls and that saved me :).
