### ISSUE TITLE
Question about profiling nccl kernels with Nsight Compute

### ISSUE THREAD

**Issue by zarzen** [NVIDIA/nccl#466]
Hi,
I was trying to use Nsight Compute `ncu` to profile a python script. Because I would like to see get some metric data of ncclSend, ncclRecv kernels. But, the profiler hangs when it profiles `ncclKernelBoardcast`. I suspect the reason for such hanging is due to the profiler, which treats nccl-kernel as individual components, without considering the cooperation among kernels.
So how do you guys profiling ncclKernels? or in other words, how to get performance insights of current nccl implementation? 

* update: I tried setting `--replay-mode application` which does not help.

**Comment by gbxu** [comment]
hi @zarzen ,  I meet the same problem with you. Do you know how to profile the metrics of nccl operators with nvprof or ncu?

**Comment by zarzen** [comment]
no, I didn't find way to do that.

**Comment by gbxu** [comment]
> no, I didn't find way to do that.

thank you anyway.

**Comment by Zjhzzzzz** [comment]
> no, I didn't find way to do that.

hey bro, do you know how to profile nccl operators now?

**Comment by Zjhzzzzz** [comment]
> > no, I didn't find way to do that.
> 
> thank you anyway.

hey bro, do you know how to profile nccl operators now?

**Comment by bikekiller** [comment]
@zarzen I got the same problem, do you fix this?
