### ISSUE TITLE
Questions about ring and tree algorithms in NCCL

### ISSUE THREAD

**Issue by haihai-00** [NVIDIA/nccl#471]
Hi,community 
I m reading NCCL codes recently, and have some questions about algorithm slections:
There are 3 algorithms and 3 protocols can be selected in NCCL
1. NCCL constructs all 3 structures when init. How does NCCL constructs rings and trees? My understanding is like this: it find paths of all gpus, and constructs a small ring in single node. And small rings are connected into one big flat ring. As for tree, NCCL first constructs small trees for single node, and connect these trees into a big tree. Is my understanding correct?

2. When inter node communication is involved, what kind of ring it uses? Flat ring or 2d ring? Or it’s being selected for different scenarios? So far I just found the log of flat ring.
3. When connecting multi nodes, only ring struct is used to connect small rings? Or small rings can also be connected by trees? As I found in code, only rings for rings and trees for trees, just to confirm.

Would be vary grateful if you can answer my question!

**Comment by sjeaugey** [comment]
1. Yes that is correct.
2. Indeed we only build flat rings, no 2D ring.
3. We don't mix rings and trees, as you saw in the code.
So basically we have 2 algorithms: a flat ring (high latency, best bandwidth) and a tree (low latency, ok bandwidth). On top of that we have collnet, but that's only if you have a plugin that supports network-based collectives (like SHARP).

**Comment by haihai-00** [comment]
Thank you for your quick response.
And I have other questions about ring:
1. In NCCL2.3，2D ring is used. And in NCCL2.4 double binary tree is used. But now in the latest version 2D ring is deprecated. Is it because 2D ring has a lower performance than double binary tree?

**Comment by sjeaugey** [comment]
I'm not sure why you think that we had 2D rings in NCCL 2.3... we never used 2D rings, only 1D. It is true that some users experimented with 2D rings in the NCCL 2.3 time frame when running at scale (manually writing their 2D ring), but we preferred the tree approach as it was giving better performance at scale, which we released in 2.4.

**Comment by haihai-00** [comment]
> I'm not sure why you think that we had 2D rings in NCCL 2.3... we never used 2D rings, only 1D. 
I thought Nccl uses 2d ring from this link: http://developer.nvidia.com/blog/massively-scale-deep-learning-training-nccl-2-4/, it says that 2d ring is used with 2.3 and tree is used in 2.4. So that only means 2d ring is used in this experiment not officially in NCCL, right?

**Comment by sjeaugey** [comment]
Yes, the "hierarchical rings" number is achieved using two NCCL communicators and doing a manual 2D ring pipeline (intra-node reduce_scatter -> inter-node allreduce -> intra-node allgather).

**Comment by haihai-00** [comment]
Thank you very much for the explanation.
But I meet another question about NIC.
I have two nodes and each node have 8gpus and 4 mellanox cards. When I running examples I noticed that mlx_0 is always used for inter nodes communication, so I want to figure out if other nic is used, will the tree and ring graph be changed.
 But when I specified NCCL_IB_HCA=mlx5_1, the log shows nccl can only detect mlx5_0 so no ib can be used. So socket is used for inter node communication. 
 But I have tried with “ibv_get_device_list” API to get rdma device and it do can detect 4 nic. 
So I’m confused, is there anything I missed with my nccl configuration to result this?

**Comment by sjeaugey** [comment]
Can you check all your interfaces are in ACTIVE mode running `ibv_devinfo` ?

**Comment by haihai-00** [comment]
Yes, I’ve run ibv_devinfo on server and 4 nics are active.

**Comment by sjeaugey** [comment]
Can you post the NCCL log and the output of ibv_devinfo ? I don't see why ibv_devinfo would show 4 active interfaces and NCCL would only list one. There can be many reasons for NCCL to only use one interface, but falling back to sockets when NCCL_IB_HCA=mlx5_1 is set means mlx5_1 was not "usable". The only other test is that the `link_layer` is either Infiniband or Ethernet, which I assume is the case here as well?

**Comment by haihai-00** [comment]
I d like to post the logs but due to the some network issues I cannot copy it to my PC. I will try to post the log later if the network issue is solved. 
But I m pretty sure that linker layer of all 4 nics goes to infiniband not Ethernet.

**Comment by haihai-00** [comment]
Hi,
sorry that I cannot paste the log still because of the network issue. But I really need to figure out why Nccl can only use mlx5_0.
For the nic status, mlx5_0 to mlx5_3 all use ifiniband in link layer and are all active.
 I add some information when run ibhosts(it part of the output since I have to type all this by hand:( )
would you please help check why Nccl can only detect mlx5_0 for rdma?  Or is there any information you may need?


#ibhosts  
Node1 mlx5_1
“Mellanox technologys aggregation node”
Node1 mlx5_0
Node2 HCA-1
Node2 HCA-2
Node3 mlx5_0
Node3 HCA-2
Node4 HCA-2
Node4 mlx5_0
Swat7-06 mlx5_0
Swat7_03 mlx5_0
Swat7_01 HCA-1
Swat7_02 mlx5_0
Node2 HCA-3
Node2 HCA-4
Node3 HCA-4
Node1 mlx5_3
Node1 mlx5_2
Node4 HCA-3
Node4 HCA-4
Node3 HCA-3

**Comment by sjeaugey** [comment]
At this point this is a mystery to me, I've never experienced that before; which is why I was asking for the log in case anything would catch my eye.

Alternatively, you could put some printf in https://github.com/NVIDIA/nccl/blob/master/src/transport/net_ib.cc#L144-L147 to print what IB device NCCL finds and why it doesn't consider them.

**Comment by haihai-00** [comment]
That s what I ve done before and turns out nccl just find mlx5_0 by ibv_get_device_list. And I forgot to say that there are 4 nodes and 4 mlx card in total number in my cluster. And I’m using node 3 4 to test. Node 1 and 2 are being use to do other tests at the same time. It these may be related with my issue?

**Comment by sjeaugey** [comment]
Ok, so it looks like something is preventing NCCL from "seeing" all 4 IBV interfaces. Could it be a container/VM issue, only showing one NIC? `ibv_devinfo` and NCCL should use the exact same API, so if you run `ibv_devinfo` with the same environment as NCCL, you should not see different results.

**Comment by haihai-00** [comment]
> Ok, so it looks like something is preventing NCCL from "seeing" all 4 IBV interfaces. Could it be a container/VM issue, only showing one NIC?

That may be the point, so how should I confirm it is related with container?

**Comment by sjeaugey** [comment]
> That may be the point, so how should I confirm it is related with container?
Did you run `ibv_devinfo` from within the container ?

**Comment by haihai-00** [comment]
Thank you soooo much. It is exactly the issue of container. Only mlx5_0 is added when start container, so other mlx device can be detected when I add them in the docket run command.

**Comment by zfy3000163** [comment]
> 是的，“分层环”数量是使用两个 NCCL 通信器并执行手动 2D 环管道（节点内 reduce_scatter -> 节点间 allreduce -> 节点内 allgather）实现的。
Is the construction of the two communicators implemented by calling the nccl API? Is it implemented outside nccl? Looking forward to your reply, thank you!

**Comment by vutrung96** [comment]
@sjeaugey Sorry to dig up an old thread, but

> Yes, the "hierarchical rings" number is achieved using two NCCL communicators and doing a manual 2D ring pipeline (intra-node reduce_scatter -> inter-node allreduce -> intra-node allgather).

So this overlaps inter-node / intra-node communication? Is there any documentation of this algorithm?

Thanks!

**Comment by sjeaugey** [comment]
Again, NCCL does not implement 2D rings, as you still end up with a linear number of chunks, hence very small transfers at scale.

But the original article compared the Tree performance with 3rd-party attempts using 2D rings, see references [3] [4] and [5] in the article:
https://developer.nvidia.com/blog/massively-scale-deep-learning-training-nccl-2-4/#ref3

**Comment by vutrung96** [comment]
@sjeaugey gotcha, thank you!
