### ISSUE TITLE
don't support bfloat16 ? so how to use nccl on A100 for BF16?

### ISSUE THREAD

**Issue by guolinke** [NVIDIA/nccl#476]
RuntimeError: Input tensor data type is not supported for NCCL process group: BFloat16
How to run distributed training with bf16 in A100?

Also refer to https://github.com/pytorch/pytorch/issues/53439

**Comment by AddyLaddy** [comment]
We have support for bfloat16 on an internal branch. I'll try and make a PR against github soon.

**Comment by xutianming** [comment]
Looking forward to bfloat16 support !

**Comment by chr1sj0nes** [comment]
Hi. Any updates on when bfloat16 support might land. We are also eager to use this feature. Thanks!

**Comment by AddyLaddy** [comment]
Have you been able to test my PR ? https://github.com/NVIDIA/nccl/pull/485

Or are you looking for a timeline for support in the official NCCL releases?

**Comment by chr1sj0nes** [comment]
@AddyLaddy I was wondering about the timeline for an official release.

**Comment by AddyLaddy** [comment]
NCCL 2.10.3 is now released with bfloat16 support
