### ISSUE TITLE
Will the sequence of send and recv cause a deadlock?

### ISSUE THREAD

**Issue by JF-D** [NVIDIA/nccl#479]
Hi, @sjeaugey, I am trying to use send and recv to do distributed training.
From my experiments (I use tesla V100 and nccl 2.7.8), I found out that the order of send and recv can lead to stuck.
For example, with two gpus (rank 0 and rank 1):
```
rank 0: 
1. send tensor x0 to rank 1
2. recv tensor x1 from rank 1
rank 1: 
1. send tensor x1 to rank 0
2. recv tensor x0 from rank 0
```
Then, it will be stuck. I didn't find the order rules, is this a deadlock due to blocking send and recv? Does this mean that I have to carefully arrange the send and recv pairs to avoid waiting (send waiting for recv, or, recv waiting for send) and deadlock?

Thanks a lot!

**Comment by zarzen** [comment]
Once they are in the same ncclGroup it should be fine, I have tested it.

**Comment by sjeaugey** [comment]
Indeed. You should group the send and recv calls so that they form a single sendrecv operation.
```
ncclGroupStart();
if (rank == 0) {
  ncclSend(x0, count0, type, 1, comm, stream);
  ncclRecv(x1, count1, type, 1, comm, stream);
} else if (rank == 1) {
  ncclSend(x1, count1, type, 0, comm, stream);
  ncclRecv(x0, count0, type, 0, comm, stream);
}
ncclGroupEnd();
```

**Comment by JF-D** [comment]
@zarzen @sjeaugey Got it! Thanks a lot~
