### ISSUE TITLE
Is there any possibility  to use gdasync in NCCL? Why?

### ISSUE THREAD

**Issue by dearsxx0918** [NVIDIA/nccl#483]
I found that gdasync can trigger PCIE door bell in GPU kernel. And this will reduce CPU usage and make async more smooth. But this haven't been used by NCCL. Is there any possibility to enable this in NCCL in future?

**Comment by sjeaugey** [comment]
Yes this is something NCCL will try to leverage in the future. We don't have precise plans however, that would require significant changes in the network plugin API.

**Comment by dearsxx0918** [comment]
Thanks for you reply.
