### ISSUE TITLE
Does NCCL have the custom datatype?

### ISSUE THREAD

**Issue by jiangxiaobin96** [NVIDIA/nccl#488]
If i have customize a struct named box, can i ncclBcast the datatype box?
```
ncclResult_tncclBcast(void* buff, size_t count, ncclDataType_t datatype, int root, ncclComm_t comm, cudaStream_t stream);
```
i can not find the match ncclDataType_t. Is there any solution to new custom datatype?

**Comment by sjeaugey** [comment]
Yes you can, all you need to do is use the ncclChar datatype and the size of the struct as count:
```
struct struct_type my_struct;
ncclBcast(&my_struct, sizeof(struct struct_type), ncclChar, root, comm, stream);
```

**Comment by jiangxiaobin96** [comment]
Thanks for your information.
