### ISSUE TITLE
Is NCCL available in CUDA 8.0 ?

### ISSUE THREAD

**Issue by fmana** [NVIDIA/nccl#49]
Not really an issue.
In the perspective to move toward CUDA 8.0 and Pascal (PCIe/NVlink) architecture, is Nickel already available in CUDA 8.0 ?
Do I need to download it from GitHub site ?
Is Nickel already optimized for NVlink ?

Thanks,
Franco

**Comment by cliffwoolley** [comment]
Hi Franco,

NCCL is not included in the CUDA Toolkit; you can get it from GitHub.  That said, no, the GitHub version is not optimized for NVLink.

Thanks for inquiring!

Best,
Cliff
