### ISSUE TITLE
Some questions about ncclBroadcast.

### ISSUE THREAD

**Issue by jiangxiaobin96** [NVIDIA/nccl#490]
Some questions about ncclBroadcast.
If each GPU has a sendbuff to broadcast.
```
// ncclGroupStart(); ----first place
for(int i=0;i<numGPUs;i++) {
        ncclGroupStart();   // ---- second place
        for(int j=0;j<numGPUs;j++) {
            ncclBroadcast(send[i],recv[j]+off,datasize,ncclInt,i,comms[j],s[j]);
        }
        
        off+=datasize;
        ncclGroupEnd();
}
//ncclGroupEnd();
```
Is there any problem? **I am not sure the placement of ncclGroupStart and ncclGroupEnd**. Is there any difference?
And the **stream** is also my question. If each GPU has a sendbuff to broadcast, how does the stream in each GPU work?

**Comment by sjeaugey** [comment]
Each GPU doing a broadcast is equivalent to a ncclAllGather, so this would probably be more efficient:
```
ncclGroupStart();
for(int j=0;j<numGPUs;j++) {
  ncclAllGather(send[j], recv[j], datasize, ncclInt, comms[j], s[j]);
}
ncclGroupStart();
```

**Comment by jiangxiaobin96** [comment]
I have tried allgather, but the datasize of allgather is fixed. I have to broadcast different size of sendbuff in each GPU like allgatherv operation.

**Comment by sjeaugey** [comment]
Ah, then it's fine. `datasize` was not `datasize[i]` so I assumed it was a fixed size.

And yes you should uncomment the groupStart/groupEnd on the outer loop to have all operations merged as one, which is quite important if your sizes are small.

**Comment by jiangxiaobin96** [comment]
So how to achieve the function of allgatherv? Whether i can change the datasize to datasize[i] to achieve. I look over the previous  issues which says that allgatherv can be approximated by doing a batch of ncclbroadcast. And in fact it works.
```
ncclGroupStart();
int a[4] = {1,2,3,4};
for(int i=0;i<numGPUs;i++) {
    for(int j=0;j<numGPUs;j++) {
        ncclBroadcast(send[i],recv[j]+off,a[i],ncclInt,i,comms[j],s[j]);
    }
    off+=a[i];
}
ncclGroupEnd();
```
but if my send[i] needs to calculate for a long time in kernel in s[i] stream. Will the stream j wait the stream i or stream j will send the null first?
**I want to know how the different streams work in ncclbroadcast.**

**Comment by jiangxiaobin96** [comment]
OK. I have solved the problem of simulating allgatherv by ncclbroadcast. However, the  performance is not very well. Is there any other solution to achieve the allgatherv operation.

**Comment by sjeaugey** [comment]
The allgatherv call will effectively wait on each GPU `i` until the stream `s[i]` is ready, just like it would for an allreduce operation.

It is a bit more complicated given we are also grouping across GPUs but if you were to run one GPU per process, the code would be simpler and you would only use one stream per GPU (and all operations within a group for a given GPU have to use the same stream).

Regarding performance, we did not optimize this case much so far, but ideally if you have 4 operations and 4 channels, each operation should map to a different channel and performance should be pretty good. The number of channels is platform-dependent but you could try setting `NCCL_MIN_NCHANNELS=4` to make sure all 4 operations can execute concurrently.

**Comment by jiangxiaobin96** [comment]
Can omp support ncclbroadcast?
Instead of using "for" loop to cudasetdevice, using opm like "devid=omp_get_thread_num(n)" to cudasetdevice. Can the ncclbroadcast function still work?

**Comment by sjeaugey** [comment]
I'm not sure I understand exactly what you want to do. And I was not saying you should run multi-process (or multi-thread), just that the logic would be simpler to understand.

I don't have experience mixing OpenMP and NCCL; if OpenMP can guarantee to launch one thread per GPU, then it should work.

**Comment by jiangxiaobin96** [comment]
like the following code
```
ncclGroupStart();
int off[3] = {0,1,3};
int a[3] = {1,2,3};
omp_set_num_threads(numGPUs);
#pragma omp parallel
{   
        int i=omp_get_thread_num();
        cudaSetDevice(i);
        for(int j=0;j<numGPUs;j++) { 
            ncclBroadcast(send[i],recv[j]+off[i],a[i],ncclInt,i,comms[j],s[j]);
        }
}
ncclGroupEnd();
```
I tried that it can not work. But i launch one thread for each GPU.

**Comment by jiangxiaobin96** [comment]
I also add `#pragma omp critical` between cudasetdevice and for loop. Critical is used to define a critical section to ensure that only one thread accesses the critical section at the same time. I think the processing is similar with two for loop(the code i post four days ago), but in fact the code still can not work. The program will block in ncclBroadcast function.

**Comment by sjeaugey** [comment]
You need to use the threads for the **multi-GPU** dimension, and keep the for loop for the operation aggregation, making sure to call ncclGroupStart/ncclGroupEnd within the threaded code. Therefore we need to reverse the loop.

So this:
```
ncclGroupStart();
for(int root=0; root<numGPUs; root++) {
    for(int gpu=0; gpu<numGPUs; gpu++) {
        ncclBroadcast(send[root], recv[gpu]+offset, sizes[root], ncclInt, root, comms[gpu], stream[gpu]);
    }
    offset += sizes[root];
}
ncclGroupEnd();
```
would become:
```
omp_set_num_threads(numGPUs);
#pragma omp parallel
{   
        int gpu = omp_get_thread_num();
        ncclGroupStart();
        size_t offset = 0;
        for (int root=0; root<numGpus; root++) {
            ncclBroadcast(send[root], recv[gpu]+offset, sizes[root], ncclInt, root, comms[gpu], stream[gpu]);
            offset += sizes[root];
        }
        ncclGroupEnd();
}
```

**Comment by jiangxiaobin96** [comment]
Thank you for answer, it helps me a lot.

**Comment by jiangxiaobin96** [comment]
Oh, forget to ask what's the different between these two ways of codes.

> You need to use the threads for the **multi-GPU** dimension, and keep the for loop for the operation aggregation, making sure to call ncclGroupStart/ncclGroupEnd within the threaded code. Therefore we need to reverse the loop.
> 
> So this:
> 
> ```
> ncclGroupStart();
> for(int root=0; root<numGPUs; root++) {
>     for(int gpu=0; gpu<numGPUs; gpu++) {
>         ncclBroadcast(send[root], recv[gpu]+offset, sizes[root], ncclInt, root, comms[gpu], stream[gpu]);
>     }
>     offset += sizes[root];
> }
> ncclGroupEnd();
> ```
> 
> would become:
> 
> ```
> omp_set_num_threads(numGPUs);
> #pragma omp parallel
> {   
>         int gpu = omp_get_thread_num();
>         ncclGroupStart();
>         size_t offset = 0;
>         for (int root=0; root<numGpus; root++) {
>             ncclBroadcast(send[root], recv[gpu]+offset, sizes[root], ncclInt, root, comms[gpu], stream[gpu]);
>             offset += sizes[root];
>         }
>         ncclGroupEnd();
> }
> ```

**Comment by sjeaugey** [comment]
There is no fundamental difference here, aside from using multiple threads to launch operations which could have a better latency, provided you set NCCL_LAUNCH_MODE=PARALLEL when using NCCL 2.8 or earlier.

**Comment by jiangxiaobin96** [comment]
I referred to the ring-base collectives like the following picture. 
> Does the ncclBroadcast function transfer data in this way?
> Like the code above, I set send buffer and recv buffer. So when I broadcast GPU0's send buffer to other GPU's recv buffer, in first step GPU0's send buffer to GPU1's recv buffer and which operation will happen in next step:1) GPU0's send buffer to GPU2's recv buffer;2) GPU1's recv buffer to GPU2's recv buffer. I prefer to the second way. Is it true?
![image](https://user-images.githubusercontent.com/26225317/114990766-6f6e9580-9ecb-11eb-99b5-3260ebf363bb.png)

**Comment by sjeaugey** [comment]
1. Yes, broadcast is a pipeline starting from the root and only sending to a single peer (at the moment at least).
2. Indeed it is the second option.
