### ISSUE TITLE
GPU occupation during model training

### ISSUE THREAD

**Issue by elevenxiang** [NVIDIA/nccl#491]
Hi,

Do you have any profiling result about GPU occupation during training ?

Because I found that NCCL communication overhead arrived 75%, does it normal ?

<img width="909" alt="check_gpu_utilization" src="https://user-images.githubusercontent.com/19565381/113819860-7c450800-97ac-11eb-8197-99343d4310b5.png">

Thanks

**Comment by elevenxiang** [comment]
BTW, I just run one epoch

**Comment by elevenxiang** [comment]
Hardware : 2 GPU of RTX3090 with NVLINK connected
Model: Resnet50

**Comment by elevenxiang** [comment]
<img width="909" alt="check_gpu_utilization" src="https://user-images.githubusercontent.com/19565381/113817826-83b6e200-97a9-11eb-9c06-25002d7f809f.png">

**Comment by jiangxiaobin96** [comment]
I think you can try the command `nvprof --export-profile xxx.nvvp`. In the first time of use, nccl function has a long time for cudaLaunchCooperativeKernelMultiDevice.

**Comment by elevenxiang** [comment]
> I think you can try the command `nvprof --export-profile xxx.nvvp`. In the first time of use, nccl function has a long time for cudaLaunchCooperativeKernelMultiDevice.

Thanks, but from the Nsight system, it shows the detail kernel functions, which really occupy the GPU
And they aren't in launch stage

**Comment by sjeaugey** [comment]
It seems indeed your computation time / communication time ratio is too low. When training on multiple GPUs, the scaling always depends on two factors:

1. The compute time (forward/backward). This is dependent on your neural network but also your batch size. Increasing your batch size will usually make your scaling better but having a large batch size can impact convergence.

2. The communication time (NCCL). This is dependent on your platform. Between a simple PCI system and a DGX A100, NCCL performance can vary from 6GB/s to more than 200GB/s. You should check how much time your NCCL operation takes in your application, check that it is consistent with what you see running the NCCL perf tests, and see whether that performance is consistent with what you would expect from your platform.

**Comment by elevenxiang** [comment]
> It seems indeed your computation time / communication time ratio is too low. When training on multiple GPUs, the scaling always depends on two factors:
> 
> 1. The compute time (forward/backward). This is dependent on your neural network but also your batch size. Increasing your batch size will usually make your scaling better but having a large batch size can impact convergence.
> 2. The communication time (NCCL). This is dependent on your platform. Between a simple PCI system and a DGX A100, NCCL performance can vary from 6GB/s to more than 200GB/s. You should check how much time your NCCL operation takes in your application, check that it is consistent with what you see running the NCCL perf tests, and see whether that performance is consistent with what you would expect from your platform.

Thank you so much, I got your point
And I will try to change the model and batch size to verify it
Also try to run the pccl-tests to check if it is consistent

**Comment by elevenxiang** [comment]
@sjeaugey 

As you said, when I changed the batch size from 128 to 256, the communication rate will decrease to about 60%

And when use NCCL perf test to check if it is consistent, I found it is hard to meet below conditions:
1. kernel execution configuration, perf test and train application has different configurations
2. reduce data size

so could you share the way to how to check if it is consistent ?

Thanks

**Comment by sjeaugey** [comment]
The goal with the NCCL perf test was to see how much time your allreduce operations are taking and check what BusBW that corresponds to.

If you don't know on what sizes NCCL is called in the training, you can set `NCCL_DEBUG=INFO NCCL_DEBUG_SUBSYS=COLL` to get traces.

So if for example you launched your training on 2 GPUs and you see that allreduce is called on 240,000 elements of type float, then you can run:
```
all_reduce_perf -t 2 -t float -n 240000
```
then check what bandwidth you get. You should also probably run:
```
all_reduce_perf -t 2 -b 8 -e 1G -f 2
```
to see whether the performance you get is because your peak performance is not what it should be (e.g. NVLink is not properly detected and you're going through PCI) or whether it's because the size of the allreduce operation is too small to fill the NVLinks and it's mostly driven by latency.

**Comment by elevenxiang** [comment]
> NCCL_DEBUG_SUBSYS=COLL

**Comment by elevenxiang** [comment]
@sjeaugey 
Here I try your commands to verify, and I found that they are not consistent:
**Reduce data size as blow, 128 count, float**
<img width="1553" alt="all_reduce_size" src="https://user-images.githubusercontent.com/19565381/114121625-41181580-9921-11eb-8d3e-896858fc82f2.png">


**For nsys performance as blow, each all_reduce will take about 2ms:**
<img width="1418" alt="nsys_all_reduce_time" src="https://user-images.githubusercontent.com/19565381/114121709-6b69d300-9921-11eb-9c5a-20d3311377cd.png">

**But when I use the all_reduce_perf with the same count, it just took about 17us and this delta is huge**
<img width="880" alt="all_reduce_perf_time" src="https://user-images.githubusercontent.com/19565381/114121778-93f1cd00-9921-11eb-898e-ea42a286d7a7.png">

I am confused, is it related with kernel execution configuration ?

Thanks

**Comment by elevenxiang** [comment]
And I was wondering the AllReduce data size is too small, right ?
From the trace log, the count, 128 or 64 or 256, and only once is 559184

<img width="1389" alt="different_data_count" src="https://user-images.githubusercontent.com/19565381/114125106-62c8cb00-9928-11eb-968b-de298b6dcc78.png">

**Comment by sjeaugey** [comment]
I agree; the time you see is not consistent with the sizes, and the sizes are really small. Are you using a framework which does aggregate the buffers before calling NCCL? Are you sure the 2ms allreduce calls really correspond to a 128 element allreduce?

**Comment by elevenxiang** [comment]
> I agree; the time you see is not consistent with the sizes, and the sizes are really small. Are you using a framework which does aggregate the buffers before calling NCCL? Are you sure the 2ms allreduce calls really correspond to a 128 element allreduce?

I have no idea why this issue was closed, can we continue to discuss in this loop ? or should I open another one ?
Thanks

**Comment by sjeaugey** [comment]
You might have close it when posting, clicking on the wrong button. Reopening.

**Comment by elevenxiang** [comment]
@sjeaugey 
About the small size reduce, it turns out that they are from SyncBatchNorm.
The real backward reduce size is interspersed in the SyncBatchNorm, so it is not easy to notice them

And I also did the below tests:
1. Use the Nvidia Docker(pytorch:20.11-py3) with pytorch 1.8 built-in, the NCCL communication ratio will decrease to 52.5%
2. Disalbe SyncBatchNorm, it will decrease to 38.2%
3. Same docker but runs on 2 A100 GPUs(NVLINK connected), the ratio will be 29.7%

So about these ratios, they should be normal, right ? if so I think we can then finish this discuss

Thanks

**Comment by sjeaugey** [comment]
This seems to confirm that you are communication-bound indeed. I would still verify that NVLink works as expected on your setup by running NCCL perf tests on large sizes.

**Comment by elevenxiang** [comment]
> This seems to confirm that you are communication-bound indeed. I would still verify that NVLink works as expected on your setup by running NCCL perf tests on large sizes.

About the NCCL Perf test  not consistent issue, I found that even the same size, the kernel will be launched with different execution configuration, for example:

**Model Training:**
grid:  <<<1, 1, 1>>>
block: <<<64, 1, 1>>>

**NCCL Perf Test:**
grid:  <<<4, 1, 1>>>
block: <<<544, 1, 1>>>

so the AllReduce time should have big difference, right ?

Thanks

**Comment by elevenxiang** [comment]
@sjeaugey 
I think I have found the root cause of the consistent between model training and NCCL perf test

1. This the normal reduce time(~100us, which is consistent with NCCL perf test),  obviously there is no overlap kernel execution
<img width="1248" alt="no_conflict_nccl_kernel_time" src="https://user-images.githubusercontent.com/19565381/114676139-9007e580-9d3b-11eb-961b-cd97d23e41f2.png">


2. Below is the abnormal reduce time, it tooks about 188ms to finish. And there are many overlap kernel
<img width="946" alt="conflict_nccl_kernel" src="https://user-images.githubusercontent.com/19565381/114676290-bc236680-9d3b-11eb-8fd9-9ae7a123f51c.png">


So can we now make the conclusion that high communication ratio is caused by overlap kernel during model training ?

Thanks

**Comment by elevenxiang** [comment]
Is there any way to disable the kernel overlap to verify my conclusion ?

Thanks

**Comment by elevenxiang** [comment]
I have also tried to set "export CUDA_LAUNCH_BLOCKING=1" to disable overlap.
And yes after set this, the communication ratio will decrease again, but from the nsys, there are still some execution time over 100ms, Is it caused by Sync and wait between GPUs ?

Thanks

**Comment by elevenxiang** [comment]
@sjeaugey 

Finally I found the prove why sometimes kernel executed over 100ms, it is the **launch wait** !!!

<img width="1634" alt="launch_wait" src="https://user-images.githubusercontent.com/19565381/114850672-9c5f7180-9e13-11eb-8d00-3650e95bf1e8.png">


Thanks

**Comment by sjeaugey** [comment]
Makes sense. Indeed GPU de-sync is the main cause of NCCL operations taking more time in real applications than in benchmarks. If GPU 0 does more work than GPU 1, or for some reasons do things in a different order, then we can end up in this situation where ranks have to wait until the last GPU enters the collective operation.

**Comment by elevenxiang** [comment]
> Makes sense. Indeed GPU de-sync is the main cause of NCCL operations taking more time in real applications than in benchmarks. If GPU 0 does more work than GPU 1, or for some reasons do things in a different order, then we can end up in this situation where ranks have to wait until the last GPU enters the collective operation.

So is there any improvement method for this de-sync ?
Thanks

**Comment by sjeaugey** [comment]
If GPU 0 needs to do more work than GPU 1 then there is nothing to improve. GPU 1 is waiting for a long time but may have nothing else useful to do.

The solution would be to better balance the workload between GPU 0 and GPU 1 but that is outside of NCCL.

**Comment by elevenxiang** [comment]
> If GPU 0 needs to do more work than GPU 1 then there is nothing to improve. GPU 1 is waiting for a long time but may have nothing else useful to do.
> 
> The solution would be to better balance the workload between GPU 0 and GPU 1 but that is outside of NCCL.

Okay, Thank you

**Comment by elevenxiang** [comment]
Close this issue now, Thanks
