### ISSUE TITLE
gcc version

### ISSUE THREAD

**Issue by hqy200714813** [NVIDIA/nccl#50]
which gcc version needed by NCCL?
/usr/bin/make64 MAC=64 CUDA_HOME=/home/work/cuda-7.5/ test
Compiling src/libwrap.cu            > build/obj/libwrap.o  
nvcc warning : The -c++11 flag is not supported with the configured host compiler. Flag will be ignored.
src/core.h(47): error: expected an identifier

src/core.h(61): warning: parsing restarts here after previous syntax error

src/core.h(111): error: DevRing is not a template

2 errors detected in the compilation of "/tmp/tmpxft_00004dea_00000000-13_libwrap.compute_52.cpp1.ii".
make64: **\* [build/obj/libwrap.o] Error 2

when I compile this project , an ERROR occured as above.

**Comment by nluehr** [comment]
I'm not sure what the absolute minimum version would be. GCC 4.8 is certainly a sufficient version. For older gcc versions (e.g. 4.6), you can try substituting the -std=c++11 flag with -std=c++0x.

**Comment by baiyancheng20** [comment]
When I change the -std=c++11 flag with -std=c++0x in the Makefile, I meet the following problem:
`nvcc fatal   : Value 'c++0x' is not defined for option 'std'.`
Could anyone give me a help?
