### ISSUE TITLE
Internode Data Transfer

### ISSUE THREAD

**Issue by mabdullahsoyturk** [NVIDIA/nccl#504]
> The NCCL CUDA kernels always just store/load to memory either GPU memory or host memory. For inter-node communication Linux proxy threads poll host memory and then transfer the data using the network making us of GDRDMA when available. Hence the NCCL CUDA kernels are unaware of the network hops or proxies.

I have seen this reply in this issue: #213 but I couldn't find where Linux proxy threads do this host memory polling in the code. Can anyone give me a few pointers?

**Comment by sjeaugey** [comment]
The code is in `src/proxy.cc` for the main thread and operation management, then the progress function will call to the network code in `src/transport/net.cc`.

**Comment by mabdullahsoyturk** [comment]
Thnaks a lot.

**Comment by eric-haibin-lin** [comment]
Hi @sjeaugey , does the cuda kernel also check the state of the proxy? I tried to search in the code, but could not figure out how nccl cuda kernels (e.g. nccl_ring_allreduce) know when the network operations is completed. Thanks!

**Comment by sjeaugey** [comment]
The proxy-gpu synchronization is using the same head/tail as gpu-gpu communication, so the kernel code does not have any proxy-specific polling.
