### ISSUE TITLE
[Ampere/NVLink] [P2P] why choose read not write ?

### ISSUE THREAD

**Issue by elevenxiang** [NVIDIA/nccl#512]
Hi ,

I am reading the source code, and also did some profiling with p2pBandwidthLatencyTest on A100 machine.

And I found that obviously p2p write is faster than read, and also with better bandwidth.
But why the code logic still choose to enable read ?

_static ncclResult_t p2pGetInfo(struct ncclTopoSystem* topo, struct ncclPeerInfo* info1, struct ncclPeerInfo* info2, int* read, int* intermediateRank) {
  int p2p;
  // Queries the topology to see if the GPUs are Ampere and
  // connected via NVLink, if so we enable P2P Read by default
  NCCLCHECK(ncclTopoCheckP2p(topo, info1->busId, info2->busId, &p2p, read, intermediateRank));

  int readEnable = ncclParamP2pReadEnable();
  if (readEnable != -2) *read = readEnable;
  return ncclSuccess;
}_

Thanks

**Comment by AddyLaddy** [comment]
On NVLink connected machines such as the DGX A100 we have found that P2P reads give better peak BW when benchmarking the NCCL AllReduce operation on all 8 GPUs.

Do your benchmarks show different behaviour?
What system are you benchmarking on?

**Comment by elevenxiang** [comment]
> On NVLink connected machines such as the DGX A100 we have found that P2P reads give better peak BW when benchmarking the NCCL AllReduce operation on all 8 GPUs.
> 
> Do your benchmarks show different behaviour?
> What system are you benchmarking on?

I did the benchmark with tool "p2pBandwidthLatencyTest" , not all_reduce_perf
![1](https://user-images.githubusercontent.com/19565381/119758646-7250a300-bed9-11eb-8eb5-9886f877b1dd.png)

![2](https://user-images.githubusercontent.com/19565381/119758673-7b417480-bed9-11eb-84a0-93ad427a2c9b.png)

From above benchmark test, write should be a better choice, right. ?

Thanks

**Comment by elevenxiang** [comment]
@AddyLaddy  by the way, our system is : DGX-1 A100

**Comment by sjeaugey** [comment]
The p2pBandwidthLatencyTest uses the copy engine of the GPU by default, which indeed has slightly better performance using writes compared to reads. However, NCCL uses SMs to communicate, and if you add --sm_copy to `p2pBandiwdthLatencyTest`, you should see performance with reads being better than writes.

**Comment by AddyLaddy** [comment]
You can also toggle P2P Read vs Write in NCCL using the env var; `NCCL_P2P_READ_ENABLE=[0|1]` and measure the effect using the `all_reduce_perf` benchmark

**Comment by elevenxiang** [comment]
@sjeaugey @AddyLaddy 
Got it, Thank you so much ~

**Comment by shanleo1986** [comment]
Hi, what is the end result? And can you help to explan what is the P2P read and P2P write? What is the difference between them?
Thank you.

**Comment by AddyLaddy** [comment]
There were architectural reasons that P2P Reads performed better on NVLink A100 systems. That is no longer the case on H100.
