### ISSUE TITLE
nccl in OpenPOWER P8NVLink system with P100 GPU

### ISSUE THREAD

**Issue by alvintpwang** [NVIDIA/nccl#52]
Does this tool support the P8NVLink system with P100 GPU?  From the blog below, this tool need the GPUDirect but OpenPOWER system doesn't have GPUDirect. That is why I ask if this tool is ready for OpenPOWER P8NVLink system with P100 GPU.

Nvidia blog
=========
https://devblogs.nvidia.com/parallelforall/fast-multi-gpu-collectives-nccl/
"NCCL makes extensive use of GPUDirect Peer-to-Peer direct access to push data between processors."

**Comment by spotluri** [comment]
NCCL should work on all power platforms and uses GPUDirect P2P or copies through system memory to get the best performance out of the platform.
