### ISSUE TITLE
NCCL Buffer was in Cache or Memory?

### ISSUE THREAD

**Issue by iamshlee** [NVIDIA/nccl#521]
Hi, 

As I know,  AllReduce in NCCL was running a unit of NCCL_BUFFER_SIZE. 

During running the AllReduce on GPU, NCCL Buffer space was in cache or memory? In pytorch, high priority stream allocates the NCCL Buffer, so in processing Allreduce, I think intermediate data was going through only cache not memory. is it right?

Thanks.

**Comment by kwen2501** [comment]
NCCL allocates the intermediate buffers in GPUs' global memory, or when GPU P2P is not available or preferred, the host memory. Whether that piece of memory is mapped in cache is up to the hardware's scheduling, NCCL has no control on that. I don't think CUDA stream has any knob for that either, if you know there is, any pointer would be appreciated.

**Comment by iamshlee** [comment]
Thanks!
