### ISSUE TITLE
encountered NCCL WARN NET/IB : Got completion with error 4, opcode 0, len 32694, vendor err 81 - ACS disabled on Bios & OS kernel 

### ISSUE THREAD

**Issue by dobiup** [NVIDIA/nccl#523]
We encountered below error when we run the torch-flower with GDR infiniband.
It was run on K8s and docker, same error occured every time

intra-node GPU job works well and inter-node GPU job works well without GDR via infiniband

Error code on NCCL
[0] transport/net_ib.cc:818 NCCL WARN NET/IB : Got completion with error 4, opcode 0, len 32694, vendor err 81

ACS disabled on bios/OS kernel
lspci -s a8:0c.0 -vvvv | grep ACS
                UESta:  DLP- SDES- TLP- FCP- CmpltTO- CmpltAbrt- UnxCmplt- RxOF- MalfTLP- ECRC- UnsupReq- ACSViol-
                UEMsk:  DLP- SDES- TLP- FCP- CmpltTO- CmpltAbrt- UnxCmplt- RxOF- MalfTLP- ECRC- UnsupReq- ACSViol-
                UESvrt: DLP- SDES- TLP+ FCP+ CmpltTO- CmpltAbrt- UnxCmplt- RxOF- MalfTLP- ECRC- UnsupReq- ACSViol-
                ACSCap: SrcValid+ TransBlk+ ReqRedir+ CmpltRedir+ UpstreamFwd+ EgressCtrl- DirectTrans+
                ACSCtl: SrcValid- TransBlk- ReqRedir- CmpltRedir- UpstreamFwd- EgressCtrl- DirectTrans-

ib_send test succeed via infiniband
 Dual-port       : OFF          Device         : mlx5_0
 Number of qps   : 1            Transport type : IB
 Connection type : RC           Using SRQ      : OFF
 PCIe relax order: ON
 ibv_wr* API     : ON
 TX depth        : 128
 CQ Moderation   : 1
 Mtu             : 4096[B]
 Link type       : IB
 Max inline data : 0[B]
 rdma_cm QPs     : OFF
 Data ex. method : Ethernet

debug log on NCCL

ytorch-flower-rdma-master-0:156:156 [7] NCCL INFO Broadcast: opCount 0 sendbuff 0x7f3402400000 recvbuff 0x7f3402400000 count 69069572 datatype 0 op 0 ro ot 0 comm 0x7f33b4008dd0 [nranks=16] stream 0x55f346ed4c10pytorch-flower-rdma-master-0:155:306 [6] NCCL INFO comm 0x7efd88008dd0 rank 6 nranks 16 cudaDev 6 busId c8000 - Init COMPLETEpytorch-flower-rdma-master-0:155:155 [6] NCCL INFO Broadcast: opCount 0 sendbuff 0x7efddea00000 recvbuff 0x7efddea00000 count 69069572 datatype 0 op 0 ro ot 0 comm 0x7efd88008dd0 [nranks=16] stream 0x564367753580mlx5: pytorch-flower-rdma-master-0: got completion with error:00000000 00000000 00000000 0000000000000000 00000000 00000000 0000000000000003 00000000 00000000 0000000000000000 04005104 08000046 000031d2pytorch-flower-rdma-master-0:152:313 [0] transport/net_ib.cc:818 NCCL WARN NET/IB : Got completion with error 4, opcode 0, len 32741, vendor err 81pytorch-flower-rdma-master-0:152:313 [0] NCCL INFO include/net.h:28 -&gt; 2pytorch-flower-rdma-master-0:152:313 [0] NCCL INFO transport/net.cc:310 -&gt; 2pytorch-flower-rdma-master-0:152:313 [0] NCCL INFO proxy.cc:198 -&gt; 2 [Proxy Thread]mlx5: pytorch-flower-rdma-master-0: got completion with error:00000000 00000000 00000000 0000000000000000 00000000 00000000 0000000000000003 00000000 00000000 00000000 | ytorch-flower-rdma-master-0:156:156 [7] NCCL INFO Broadcast: opCount 0 sendbuff 0x7f3402400000 recvbuff 0x7f3402400000 count 69069572 datatype 0 op 0 ro ot 0 comm 0x7f33b4008dd0 [nranks=16] stream 0x55f346ed4c10pytorch-flower-rdma-master-0:155:306 [6] NCCL INFO comm 0x7efd88008dd0 rank 6 nranks 16 cudaDev 6 busId c8000 - Init COMPLETEpytorch-flower-rdma-master-0:155:155 [6] NCCL INFO Broadcast: opCount 0 sendbuff 0x7efddea00000 recvbuff 0x7efddea00000 count 69069572 datatype 0 op 0 ro ot 0 comm 0x7efd88008dd0 [nranks=16] stream 0x564367753580mlx5: pytorch-flower-rdma-master-0: got completion with error:00000000 00000000 00000000 0000000000000000 00000000 00000000 0000000000000003 00000000 00000000 0000000000000000 04005104 08000046 000031d2pytorch-flower-rdma-master-0:152:313 [0] transport/net_ib.cc:818 NCCL WARN NET/IB : Got completion with error 4, opcode 0, len 32741, vendor err 81pytorch-flower-rdma-master-0:152:313 [0] NCCL INFO include/net.h:28 -&gt; 2pytorch-flower-rdma-master-0:152:313 [0] NCCL INFO transport/net.cc:310 -&gt; 2pytorch-flower-rdma-master-0:152:313 [0] NCCL INFO proxy.cc:198 -&gt; 2 [Proxy Thread]mlx5: pytorch-flower-rdma-master-0: got completion with error:00000000 00000000 00000000 0000000000000000 00000000 00000000 0000000000000003 00000000 00000000 00000000
-- | --
ytorch-flower-rdma-master-0:156:156 [7] NCCL INFO Broadcast: opCount 0 sendbuff 0x7f3402400000 recvbuff 0x7f3402400000 count 69069572 datatype 0 op 0 ro ot 0 comm 0x7f33b4008dd0 [nranks=16] stream 0x55f346ed4c10pytorch-flower-rdma-master-0:155:306 [6] NCCL INFO comm 0x7efd88008dd0 rank 6 nranks 16 cudaDev 6 busId c8000 - Init COMPLETEpytorch-flower-rdma-master-0:155:155 [6] NCCL INFO Broadcast: opCount 0 sendbuff 0x7efddea00000 recvbuff 0x7efddea00000 count 69069572 datatype 0 op 0 ro ot 0 comm 0x7efd88008dd0 [nranks=16] stream 0x564367753580mlx5: pytorch-flower-rdma-master-0: got completion with error:00000000 00000000 00000000 0000000000000000 00000000 00000000 0000000000000003 00000000 00000000 0000000000000000 04005104 08000046 000031d2pytorch-flower-rdma-master-0:152:313 [0] transport/net_ib.cc:818 NCCL WARN NET/IB : Got completion with error 4, opcode 0, len 32741, vendor err 81pytorch-flower-rdma-master-0:152:313 [0] NCCL INFO include/net.h:28 -&gt; 2pytorch-flower-rdma-master-0:152:313 [0] NCCL INFO transport/net.cc:310 -&gt; 2pytorch-flower-rdma-master-0:152:313 [0] NCCL INFO proxy.cc:198 -&gt; 2 [Proxy Thread]mlx5: pytorch-flower-rdma-master-0: got completion with error:00000000 00000000 00000000 0000000000000000 00000000 00000000 0000000000000003 00000000 00000000 00000000

Environment Information
Server HPE Gen 10 Plus - A100 HGX 8 
IB HDR
OS Ubuntu 20.04.1 LTS
nv_peer_mem 1.1.0
MLNX_OFED_LINUX-5.3-1.0.0.1 (OFED-5.3-1.0.0)
GPU Driver : Driver Version: 455.45.01
docker 19.3.5
K8s 1.117.3

**Comment by dobiup** [comment]
NCCL Version : 2.7.8
Just filter it, because too many information was printed, it is also same with other PLX pci bridge ID.

applied it to all PLX with IB HCA according to NVIDIA ACS guidance on NCCL

**Comment by dobiup** [comment]
We excluded NIC(RoCE) on NCCL in order to use IB RDMA for GDR.

**Comment by sjeaugey** [comment]
Would you be able to quickly try with NCCL 2.8 or later? If not can you retrieve the relaxed ordering setting of your NICs with:
```
sudo service mst start
for nic in /dev/mst/*; do
  sudo mlxconfig -d $nic q PCI_WR_ORDERING
done
```

Also, can you post the full output of `lspci -vvv | grep ACSCtl` ?

**Comment by dobiup** [comment]
> Would you be able to quickly try with NCCL 2.8 or later? If not can you retrieve the relaxed ordering setting of your NICs with:
> 
> ```
> sudo service mst start
> for nic in /dev/mst/*; do
>   sudo mlxconfig -d $nic q PCI_WR_ORDERING
> done
> ```
> 
> Also, can you post the full output of `lspci -vvv | grep ACSCtl` ?

**Comment by dobiup** [comment]
# lspci -vvv | grep -i acsctl
                ACSCtl: SrcValid+ TransBlk- ReqRedir+ CmpltRedir+ UpstreamFwd+ EgressCtrl- DirectTrans-
                ACSCtl: SrcValid+ TransBlk- ReqRedir- CmpltRedir- UpstreamFwd- EgressCtrl- DirectTrans-
                ACSCtl: SrcValid+ TransBlk- ReqRedir- CmpltRedir- UpstreamFwd- EgressCtrl- DirectTrans-
                ACSCtl: SrcValid- TransBlk- ReqRedir- CmpltRedir- UpstreamFwd- EgressCtrl- DirectTrans-
                ACSCtl: SrcValid- TransBlk- ReqRedir- CmpltRedir- UpstreamFwd- EgressCtrl- DirectTrans-
                ACSCtl: SrcValid- TransBlk- ReqRedir- CmpltRedir- UpstreamFwd- EgressCtrl- DirectTrans-
                ACSCtl: SrcValid- TransBlk- ReqRedir- CmpltRedir- UpstreamFwd- EgressCtrl- DirectTrans-
                ACSCtl: SrcValid- TransBlk- ReqRedir- CmpltRedir- UpstreamFwd- EgressCtrl- DirectTrans-
                ACSCtl: SrcValid- TransBlk- ReqRedir+ CmpltRedir+ UpstreamFwd- EgressCtrl- DirectTrans-
                ACSCtl: SrcValid- TransBlk- ReqRedir+ CmpltRedir+ UpstreamFwd- EgressCtrl- DirectTrans-
                ACSCtl: SrcValid+ TransBlk- ReqRedir+ CmpltRedir+ UpstreamFwd+ EgressCtrl- DirectTrans-
                ACSCtl: SrcValid+ TransBlk- ReqRedir+ CmpltRedir+ UpstreamFwd+ EgressCtrl- DirectTrans-
                ACSCtl: SrcValid+ TransBlk- ReqRedir+ CmpltRedir+ UpstreamFwd+ EgressCtrl- DirectTrans-
                ACSCtl: SrcValid+ TransBlk- ReqRedir+ CmpltRedir+ UpstreamFwd+ EgressCtrl- DirectTrans-
                ACSCtl: SrcValid+ TransBlk- ReqRedir+ CmpltRedir+ UpstreamFwd+ EgressCtrl- DirectTrans-
                ACSCtl: SrcValid+ TransBlk- ReqRedir+ CmpltRedir+ UpstreamFwd+ EgressCtrl- DirectTrans-
                ACSCtl: SrcValid+ TransBlk- ReqRedir+ CmpltRedir+ UpstreamFwd+ EgressCtrl- DirectTrans-
                ACSCtl: SrcValid+ TransBlk- ReqRedir+ CmpltRedir+ UpstreamFwd+ EgressCtrl- DirectTrans-
                ACSCtl: SrcValid- TransBlk- ReqRedir+ CmpltRedir+ UpstreamFwd+ EgressCtrl- DirectTrans-
                ACSCtl: SrcValid- TransBlk- ReqRedir+ CmpltRedir+ UpstreamFwd+ EgressCtrl- DirectTrans-
                ACSCtl: SrcValid- TransBlk- ReqRedir+ CmpltRedir+ UpstreamFwd+ EgressCtrl- DirectTrans-
                ACSCtl: SrcValid- TransBlk- ReqRedir+ CmpltRedir+ UpstreamFwd+ EgressCtrl- DirectTrans-
                ACSCtl: SrcValid+ TransBlk- ReqRedir- CmpltRedir- UpstreamFwd- EgressCtrl- DirectTrans-
                ACSCtl: SrcValid+ TransBlk- ReqRedir- CmpltRedir- UpstreamFwd- EgressCtrl- DirectTrans-
                ACSCtl: SrcValid- TransBlk- ReqRedir- CmpltRedir- UpstreamFwd- EgressCtrl- DirectTrans-
                ACSCtl: SrcValid- TransBlk- ReqRedir- CmpltRedir- UpstreamFwd- EgressCtrl- DirectTrans-
                ACSCtl: SrcValid- TransBlk- ReqRedir- CmpltRedir- UpstreamFwd- EgressCtrl- DirectTrans-
                ACSCtl: SrcValid- TransBlk- ReqRedir- CmpltRedir- UpstreamFwd- EgressCtrl- DirectTrans-
                ACSCtl: SrcValid- TransBlk- ReqRedir- CmpltRedir- UpstreamFwd- EgressCtrl- DirectTrans-
                ACSCtl: SrcValid+ TransBlk- ReqRedir+ CmpltRedir+ UpstreamFwd+ EgressCtrl- DirectTrans-
                ACSCtl: SrcValid+ TransBlk- ReqRedir- CmpltRedir- UpstreamFwd- EgressCtrl- DirectTrans-
                ACSCtl: SrcValid+ TransBlk- ReqRedir- CmpltRedir- UpstreamFwd- EgressCtrl- DirectTrans-
                ACSCtl: SrcValid- TransBlk- ReqRedir- CmpltRedir- UpstreamFwd- EgressCtrl- DirectTrans-
                ACSCtl: SrcValid- TransBlk- ReqRedir- CmpltRedir- UpstreamFwd- EgressCtrl- DirectTrans-
                ACSCtl: SrcValid- TransBlk- ReqRedir- CmpltRedir- UpstreamFwd- EgressCtrl- DirectTrans-
                ACSCtl: SrcValid- TransBlk- ReqRedir- CmpltRedir- UpstreamFwd- EgressCtrl- DirectTrans-
                ACSCtl: SrcValid- TransBlk- ReqRedir+ CmpltRedir+ UpstreamFwd- EgressCtrl- DirectTrans-
                ACSCtl: SrcValid- TransBlk- ReqRedir+ CmpltRedir+ UpstreamFwd- EgressCtrl- DirectTrans-
                ACSCtl: SrcValid+ TransBlk- ReqRedir+ CmpltRedir+ UpstreamFwd+ EgressCtrl- DirectTrans-
                ACSCtl: SrcValid+ TransBlk- ReqRedir+ CmpltRedir+ UpstreamFwd+ EgressCtrl- DirectTrans-
                ACSCtl: SrcValid+ TransBlk- ReqRedir+ CmpltRedir+ UpstreamFwd+ EgressCtrl- DirectTrans-
                ACSCtl: SrcValid+ TransBlk- ReqRedir+ CmpltRedir+ UpstreamFwd+ EgressCtrl- DirectTrans-
                ACSCtl: SrcValid+ TransBlk- ReqRedir+ CmpltRedir+ UpstreamFwd+ EgressCtrl- DirectTrans-
                ACSCtl: SrcValid+ TransBlk- ReqRedir+ CmpltRedir+ UpstreamFwd+ EgressCtrl- DirectTrans-
                ACSCtl: SrcValid+ TransBlk- ReqRedir+ CmpltRedir+ UpstreamFwd+ EgressCtrl- DirectTrans-
                ACSCtl: SrcValid+ TransBlk- ReqRedir+ CmpltRedir+ UpstreamFwd+ EgressCtrl- DirectTrans-
                ACSCtl: SrcValid+ TransBlk- ReqRedir+ CmpltRedir+ UpstreamFwd+ EgressCtrl- DirectTrans-
                ACSCtl: SrcValid+ TransBlk- ReqRedir- CmpltRedir- UpstreamFwd- EgressCtrl- DirectTrans-
                ACSCtl: SrcValid+ TransBlk- ReqRedir- CmpltRedir- UpstreamFwd- EgressCtrl- DirectTrans-
                ACSCtl: SrcValid- TransBlk- ReqRedir- CmpltRedir- UpstreamFwd- EgressCtrl- DirectTrans-
                ACSCtl: SrcValid- TransBlk- ReqRedir- CmpltRedir- UpstreamFwd- EgressCtrl- DirectTrans-
                ACSCtl: SrcValid- TransBlk- ReqRedir- CmpltRedir- UpstreamFwd- EgressCtrl- DirectTrans-
                ACSCtl: SrcValid- TransBlk- ReqRedir- CmpltRedir- UpstreamFwd- EgressCtrl- DirectTrans-
                ACSCtl: SrcValid+ TransBlk- ReqRedir+ CmpltRedir+ UpstreamFwd+ EgressCtrl- DirectTrans-
                ACSCtl: SrcValid+ TransBlk- ReqRedir- CmpltRedir- UpstreamFwd- EgressCtrl- DirectTrans-
                ACSCtl: SrcValid+ TransBlk- ReqRedir- CmpltRedir- UpstreamFwd- EgressCtrl- DirectTrans-
                ACSCtl: SrcValid- TransBlk- ReqRedir- CmpltRedir- UpstreamFwd- EgressCtrl- DirectTrans-
                ACSCtl: SrcValid- TransBlk- ReqRedir- CmpltRedir- UpstreamFwd- EgressCtrl- DirectTrans-
                ACSCtl: SrcValid- TransBlk- ReqRedir- CmpltRedir- UpstreamFwd- EgressCtrl- DirectTrans-
                ACSCtl: SrcValid- TransBlk- ReqRedir- CmpltRedir- UpstreamFwd- EgressCtrl- DirectTrans-
                ACSCtl: SrcValid- TransBlk- ReqRedir+ CmpltRedir+ UpstreamFwd- EgressCtrl- DirectTrans-
                ACSCtl: SrcValid- TransBlk- ReqRedir+ CmpltRedir+ UpstreamFwd- EgressCtrl- DirectTrans-
                ACSCtl: SrcValid+ TransBlk- ReqRedir+ CmpltRedir+ UpstreamFwd+ EgressCtrl- DirectTrans-
                ACSCtl: SrcValid+ TransBlk- ReqRedir+ CmpltRedir+ UpstreamFwd+ EgressCtrl- DirectTrans-
                ACSCtl: SrcValid+ TransBlk- ReqRedir+ CmpltRedir+ UpstreamFwd+ EgressCtrl- DirectTrans-
                ACSCtl: SrcValid+ TransBlk- ReqRedir+ CmpltRedir+ UpstreamFwd+ EgressCtrl- DirectTrans-
                ACSCtl: SrcValid+ TransBlk- ReqRedir+ CmpltRedir+ UpstreamFwd+ EgressCtrl- DirectTrans-
                ACSCtl: SrcValid+ TransBlk- ReqRedir+ CmpltRedir+ UpstreamFwd+ EgressCtrl- DirectTrans-
                ACSCtl: SrcValid+ TransBlk- ReqRedir+ CmpltRedir+ UpstreamFwd+ EgressCtrl- DirectTrans-
                ACSCtl: SrcValid+ TransBlk- ReqRedir+ CmpltRedir+ UpstreamFwd+ EgressCtrl- DirectTrans-
                ACSCtl: SrcValid+ TransBlk- ReqRedir+ CmpltRedir+ UpstreamFwd+ EgressCtrl- DirectTrans-
                ACSCtl: SrcValid+ TransBlk- ReqRedir- CmpltRedir- UpstreamFwd- EgressCtrl- DirectTrans-
                ACSCtl: SrcValid+ TransBlk- ReqRedir- CmpltRedir- UpstreamFwd- EgressCtrl- DirectTrans-
                ACSCtl: SrcValid- TransBlk- ReqRedir- CmpltRedir- UpstreamFwd- EgressCtrl- DirectTrans-
                ACSCtl: SrcValid- TransBlk- ReqRedir- CmpltRedir- UpstreamFwd- EgressCtrl- DirectTrans-
                ACSCtl: SrcValid- TransBlk- ReqRedir- CmpltRedir- UpstreamFwd- EgressCtrl- DirectTrans-
                ACSCtl: SrcValid- TransBlk- ReqRedir- CmpltRedir- UpstreamFwd- EgressCtrl- DirectTrans-
                ACSCtl: SrcValid- TransBlk- ReqRedir- CmpltRedir- UpstreamFwd- EgressCtrl- DirectTrans-
                ACSCtl: SrcValid- TransBlk- ReqRedir+ CmpltRedir+ UpstreamFwd- EgressCtrl- DirectTrans-
                ACSCtl: SrcValid- TransBlk- ReqRedir+ CmpltRedir+ UpstreamFwd- EgressCtrl- DirectTrans-
                ACSCtl: SrcValid+ TransBlk- ReqRedir+ CmpltRedir+ UpstreamFwd+ EgressCtrl- DirectTrans-
                ACSCtl: SrcValid+ TransBlk- ReqRedir+ CmpltRedir+ UpstreamFwd+ EgressCtrl- DirectTrans-
                ACSCtl: SrcValid+ TransBlk- ReqRedir+ CmpltRedir+ UpstreamFwd+ EgressCtrl- DirectTrans-
                ACSCtl: SrcValid+ TransBlk- ReqRedir+ CmpltRedir+ UpstreamFwd+ EgressCtrl- DirectTrans-
                ACSCtl: SrcValid- TransBlk- ReqRedir- CmpltRedir- UpstreamFwd- EgressCtrl- DirectTrans-
                ACSCtl: SrcValid- TransBlk- ReqRedir- CmpltRedir- UpstreamFwd- EgressCtrl- DirectTrans-
                ACSCtl: SrcValid- TransBlk- ReqRedir- CmpltRedir- UpstreamFwd- EgressCtrl- DirectTrans-
                ACSCtl: SrcValid- TransBlk- ReqRedir- CmpltRedir- UpstreamFwd- EgressCtrl- DirectTrans-
                ACSCtl: SrcValid- TransBlk- ReqRedir- CmpltRedir- UpstreamFwd- EgressCtrl- DirectTrans-
                ACSCtl: SrcValid- TransBlk- ReqRedir- CmpltRedir- UpstreamFwd- EgressCtrl- DirectTrans-
                ACSCtl: SrcValid- TransBlk- ReqRedir- CmpltRedir- UpstreamFwd- EgressCtrl- DirectTrans-
                ACSCtl: SrcValid- TransBlk- ReqRedir- CmpltRedir- UpstreamFwd- EgressCtrl- DirectTrans-
                ACSCtl: SrcValid- TransBlk- ReqRedir- CmpltRedir- UpstreamFwd- EgressCtrl- DirectTrans-
                ACSCtl: SrcValid- TransBlk- ReqRedir- CmpltRedir- UpstreamFwd- EgressCtrl- DirectTrans-
                ACSCtl: SrcValid+ TransBlk- ReqRedir+ CmpltRedir+ UpstreamFwd+ EgressCtrl- DirectTrans-
                ACSCtl: SrcValid- TransBlk- ReqRedir+ CmpltRedir+ UpstreamFwd+ EgressCtrl- DirectTrans-
                ACSCtl: SrcValid- TransBlk- ReqRedir+ CmpltRedir+ UpstreamFwd+ EgressCtrl- DirectTrans-
                ACSCtl: SrcValid- TransBlk- ReqRedir+ CmpltRedir+ UpstreamFwd+ EgressCtrl- DirectTrans-
                ACSCtl: SrcValid- TransBlk- ReqRedir+ CmpltRedir+ UpstreamFwd+ EgressCtrl- DirectTrans-
                ACSCtl: SrcValid+ TransBlk- ReqRedir- CmpltRedir- UpstreamFwd- EgressCtrl- DirectTrans-
                ACSCtl: SrcValid+ TransBlk- ReqRedir- CmpltRedir- UpstreamFwd- EgressCtrl- DirectTrans-
                ACSCtl: SrcValid- TransBlk- ReqRedir- CmpltRedir- UpstreamFwd- EgressCtrl- DirectTrans-
                ACSCtl: SrcValid- TransBlk- ReqRedir- CmpltRedir- UpstreamFwd- EgressCtrl- DirectTrans-
                ACSCtl: SrcValid- TransBlk- ReqRedir- CmpltRedir- UpstreamFwd- EgressCtrl- DirectTrans-
                ACSCtl: SrcValid- TransBlk- ReqRedir- CmpltRedir- UpstreamFwd- EgressCtrl- DirectTrans-
                ACSCtl: SrcValid- TransBlk- ReqRedir+ CmpltRedir+ UpstreamFwd- EgressCtrl- DirectTrans-
                ACSCtl: SrcValid- TransBlk- ReqRedir+ CmpltRedir+ UpstreamFwd- EgressCtrl- DirectTrans-
                ACSCtl: SrcValid+ TransBlk- ReqRedir+ CmpltRedir+ UpstreamFwd+ EgressCtrl- DirectTrans-
                ACSCtl: SrcValid+ TransBlk- ReqRedir+ CmpltRedir+ UpstreamFwd+ EgressCtrl- DirectTrans-
                ACSCtl: SrcValid+ TransBlk- ReqRedir+ CmpltRedir+ UpstreamFwd+ EgressCtrl- DirectTrans-
                ACSCtl: SrcValid+ TransBlk- ReqRedir+ CmpltRedir+ UpstreamFwd+ EgressCtrl- DirectTrans-
                ACSCtl: SrcValid+ TransBlk- ReqRedir+ CmpltRedir+ UpstreamFwd+ EgressCtrl- DirectTrans-
                ACSCtl: SrcValid+ TransBlk- ReqRedir+ CmpltRedir+ UpstreamFwd+ EgressCtrl- DirectTrans-
                ACSCtl: SrcValid+ TransBlk- ReqRedir+ CmpltRedir+ UpstreamFwd+ EgressCtrl- DirectTrans-
                ACSCtl: SrcValid+ TransBlk- ReqRedir+ CmpltRedir+ UpstreamFwd+ EgressCtrl- DirectTrans-
                ACSCtl: SrcValid+ TransBlk- ReqRedir- CmpltRedir- UpstreamFwd- EgressCtrl- DirectTrans-
                ACSCtl: SrcValid+ TransBlk- ReqRedir- CmpltRedir- UpstreamFwd- EgressCtrl- DirectTrans-
                ACSCtl: SrcValid- TransBlk- ReqRedir- CmpltRedir- UpstreamFwd- EgressCtrl- DirectTrans-
                ACSCtl: SrcValid- TransBlk- ReqRedir- CmpltRedir- UpstreamFwd- EgressCtrl- DirectTrans-
                ACSCtl: SrcValid- TransBlk- ReqRedir- CmpltRedir- UpstreamFwd- EgressCtrl- DirectTrans-
                ACSCtl: SrcValid- TransBlk- ReqRedir- CmpltRedir- UpstreamFwd- EgressCtrl- DirectTrans-

**Comment by sjeaugey** [comment]
It seems you still have a lot of `SrcValid+`. Now, those could be on the CPU or on devices not used by CPU-NIC communication, but I would still double check that the ACS disabling worked. In particular, you mentioned ACS was disabled in the BIOS, which I believe should cause all `SrcValid-`. Disabling ACS from the OS requires to identify all PCI switches used by GPU-NIC communication and call the correct `setpci` command for each PCI switch.

**Comment by dobiup** [comment]
Yeah~ I know there are some SrcValid+, furthermore also still remained on PCI Bridge that is assigned to AMD CPU.
When disable it on Bios, it doesn’t changed to SrcValid so I disable it on OS command.
setpci with ecap option.
Should I disable SrcValid regading PCI Bridge for CPU?
when I issued lspci - -nn, there are too many device related with SrcValid+

**Comment by dobiup** [comment]
I just disabled SrcValid+ for PLX PCI bridge for HCA or NIC
