### ISSUE TITLE
[P2P][NVB] why enable p2p transport for PATH_NVB ?

### ISSUE THREAD

**Issue by elevenxiang** [NVIDIA/nccl#528]
Hi, 

Recently, I found that it enabled p2p for PATH_NVB, will it speed up collective communication ?

From the code, it was added after connected all Rings & Trees, it should not affect the Ring or Tree.

So I wonder why should enable p2p transport for PATH_NVB ?

Thanks

**Comment by sjeaugey** [comment]
Can you point to the part of the code you are referring to? I'm not sure I understand your question.

**Comment by elevenxiang** [comment]
> Can you point to the part of the code you are referring to? I'm not sure I understand your question.

  if (ncclParamNvbPreconnect()) {
    // Connect p2p when using NVB path
    int nvbNpeers;
    int* nvbPeers;
    NCCLCHECK(ncclTopoGetNvbGpus(comm->topo, comm->rank, &nvbNpeers, &nvbPeers));
    for (int r=0; r<nvbNpeers; r++) {
      int peer = nvbPeers[r];
      int delta = (comm->nRanks + (comm->rank-peer)) % comm->nRanks;
      for (int c=0; c<comm->p2pnChannelsPerPeer; c++) {
        int channelId = (delta+comm->p2pChannels[c]) % comm->p2pnChannels;
        if (comm->channels[channelId].peers[peer].recv[0].connected == 0) { // P2P uses only 1 connector
          comm->connectRecv[peer] |= (1<<channelId);
        }
      }
      delta = (comm->nRanks - (comm->rank-peer)) % comm->nRanks;
      for (int c=0; c<comm->p2pnChannelsPerPeer; c++) {
        int channelId = (delta+comm->p2pChannels[c]) % comm->p2pnChannels;
        if (comm->channels[channelId].peers[peer].send[0].connected == 0) { // P2P uses only 1 connector
          comm->connectSend[peer] |= (1<<channelId);
        }
      }
    }
    NCCLCHECK(ncclTransportP2pSetup(comm, NULL, 0));
    free(nvbPeers);
  }

**Comment by elevenxiang** [comment]
> Can you point to the part of the code you are referring to? I'm not sure I understand your question.
  if (ncclParamNvbPreconnect()) {
    // Connect p2p when using NVB path
    int nvbNpeers;
    int* nvbPeers;
    NCCLCHECK(ncclTopoGetNvbGpus(comm->topo, comm->rank, &nvbNpeers, &nvbPeers));
    for (int r=0; r<nvbNpeers; r++) {
      int peer = nvbPeers[r];
      int delta = (comm->nRanks + (comm->rank-peer)) % comm->nRanks;
      for (int c=0; c<comm->p2pnChannelsPerPeer; c++) {
        int channelId = (delta+comm->p2pChannels[c]) % comm->p2pnChannels;
        if (comm->channels[channelId].peers[peer].recv[0].connected == 0) { // P2P uses only 1 connector
          comm->connectRecv[peer] |= (1<<channelId);
        }
      }
      delta = (comm->nRanks - (comm->rank-peer)) % comm->nRanks;
      for (int c=0; c<comm->p2pnChannelsPerPeer; c++) {
        int channelId = (delta+comm->p2pChannels[c]) % comm->p2pnChannels;
        if (comm->channels[channelId].peers[peer].send[0].connected == 0) { // P2P uses only 1 connector
          comm->connectSend[peer] |= (1<<channelId);
        }
      }
    }
    NCCLCHECK(ncclTransportP2pSetup(comm, NULL, 0));
    free(nvbPeers);
  }

**Comment by elevenxiang** [comment]
> Can you point to the part of the code you are referring to? I'm not sure I understand your question.

https://github.com/NVIDIA/nccl/blob/3fec2fa5eea34917f09e2282afc38863b454eae1/src/init.cc#L814

**Comment by AddyLaddy** [comment]
The NVB connections are an optimization for non-NVSwitch systems where we use the memory of intermediate GPUs for P2P communications between GPUs that are not directly connected to each other via NVLink.

**Comment by elevenxiang** [comment]
> The NVB connections are an optimization for non-NVSwitch systems where we use the memory of intermediate GPUs for P2P communications between GPUs that are not directly connected to each other via NVLink.

Yes, this is a good ides, but from the code, these indirectly connected GPUs p2p setup after connected all rings and trees, so they should not increase the ring number or improve the bandwidth, right ? if so, is it really helpful for communication performance ?

Thanks

**Comment by sjeaugey** [comment]
The NVB paths will be connected during the ring and tree setup. What you see in the "nvbPreconnect" section located after the ring and tree setup is the connection of all NVB paths for alltoall, which we preconnect to avoid a hang later on during alltoall.

**Comment by elevenxiang** [comment]
> The NVB paths will be connected during the ring and tree setup. What you see in the "nvbPreconnect" section located after the ring and tree setup is the connection of all NVB paths for alltoall, which we preconnect to avoid a hang later on during alltoall.

ok, got it
Thank you ~
