### ISSUE TITLE
make failed

### ISSUE THREAD

**Issue by TonyZihao** [NVIDIA/nccl#53]
hi all
i miss a error ,i cant make the nccl
```
user@user-ProLiant-DL380-Gen9:~/nccl$ make CUDA_HOME=</usr/local/cuda-7.5> test
-bash: test: Is a directory
user@user-ProLiant-DL380-Gen9:~/nccl$ ls
debian  fortran  LICENSE.txt  Makefile  Makefile~  README.md  src  test  

```
test is a existed file, i dont know where is my false

**Comment by cliffwoolley** [comment]
Remove the < and > off of your CUDA_HOME.  Those are confusing your shell.

**Comment by TonyZihao** [comment]
what a foolish mistake! 
thank you very much ! @cliffwoolley

**Comment by cliffwoolley** [comment]
Glad it was a quick one to resolve for you.

Best,
Cliff
