### ISSUE TITLE
Is there any document/explanation for the magic numbers in tuning.cc?

### ISSUE THREAD

**Issue by dearsxx0918** [NVIDIA/nccl#535]
I've been learning nccl source code for about three months.
I saw a lot of magic number in tuning.cc, it's very hard to understand. List as below(the double/integer using bold font):
busBw*1.0/**3.8**:https://github.com/NVIDIA/nccl/blob/7e515921295adaab72adf56ea71a0fafb0ecb5f3/src/graph/tuning.cc#L131
1.0/**4.0** : 1.0/**3.0**:https://github.com/NVIDIA/nccl/blob/7e515921295adaab72adf56ea71a0fafb0ecb5f3/src/graph/tuning.cc#L128
intraLat *= **1.8**:https://github.com/NVIDIA/nccl/blob/7e515921295adaab72adf56ea71a0fafb0ecb5f3/src/graph/tuning.cc#L142

So are these just the tuning result? Or they have some special meaning?

**Comment by sjeaugey** [comment]
Indeed, tuning.cc is full of empirical corrections because, unfortunately, performance is not always following the ideal formula.
In any case, there isn't much to understand here; it's mostly about tuning for all platforms.

**Comment by dearsxx0918** [comment]
thank you! Another question is, do you build many systems with different configurations to tune performance? Or did you do it with a simulator? Simulators don't seem to help much in performance tuning.

**Comment by sjeaugey** [comment]
All tuning is done on real systems, to correct for the difference between the model and reality.

**Comment by dearsxx0918** [comment]
Thank you for your quick reply！
