### ISSUE TITLE
How send/recv is implemented?

### ISSUE THREAD

**Issue by pwrliang** [NVIDIA/nccl#540]
I'm implementing a graph analytical framework that leverages nccl as the communication framework. Most of the operations that I use are ncclSend/ncclRecv. I'm curious about that how these primitives are implemented. 

As far as I know from the official documents, a dedicated kernel is used for memory copy, and the data flows within a ring topology. However, I'm not sure about how P2P operations are implemented. I have the following questions about the design:

1. Why a dedicated kernel is used instead of the cudaMempy? Since a GPU has a specific copy engine, using cudaMempy allows the application to use SMs fully.

2. What topology is used for P2P operations? The data flows as a ring, or a kernel copies the data directly?

3. When a pair of ncclSend/ncclRecv operations are issued between two GPUs that are not directly connected with NVLINK, will the data be transited by a third GPU to speed up the communication?

**Comment by sjeaugey** [comment]
1. There are many reasons for that: using the CE would require to map the destination buffer to the source process address space using CUDA IPCs which can have a high overhead; CEs have a pretty high latency which means that one send/recv would be ok but an alltoall operation could have a significant overhead and using all NVLinks simultaneously could be challenging; and there are also the cases where we need to pipeline data through a FIFO (Shared memory or Cubemesh, see 3.) in which case using the SMs allows to synchronize very quickly and have efficient communication through a circular FIFO.
2. Rings/Trees are only for Allreduce, Reduce, Broadcast, AllGather and ReduceScatter, not for Send/Recv. Send/Recv is done directly through NVLink or PCIe when CUDA provides peer access. Otherwise it can be done through shared memory, or through an intermediate GPU (see 3). And for inter-node communication NCCL can also use its network capabilities to pipeline data through the NIC.
3. On a cubemesh topology, NCCL will allocate memory on an intermediate GPU which will be accessed by both the source and destination directly (the source writing to the buffer, and the destination reading from the buffer).

**Comment by pwrliang** [comment]
> 1. There are many reasons for that: using the CE would require to map the destination buffer to the source process address space using CUDA IPCs which can have a high overhead; CEs have a pretty high latency which means that one send/recv would be ok but an alltoall operation could have a significant overhead and using all NVLinks simultaneously could be challenging; and there are also the cases where we need to pipeline data through a FIFO (Shared memory or Cubemesh, see 3.) in which case using the SMs allows to synchronize very quickly and have efficient communication through a circular FIFO.
> 2. Rings/Trees are only for Allreduce, Reduce, Broadcast, AllGather and ReduceScatter, not for Send/Recv. Send/Recv is done directly through NVLink or PCIe when CUDA provides peer access. Otherwise it can be done through shared memory, or through an intermediate GPU (see 3). And for inter-node communication NCCL can also use its network capabilities to pipeline data through the NIC.
> 3. On a cubemesh topology, NCCL will allocate memory on an intermediate GPU which will be accessed by both the source and destination directly (the source writing to the buffer, and the destination reading from the buffer).

Hi Sylvain, thanks for your explanations, but I still have a question about answer 3. 

I wrote a program to analyze the behavior behind the NCCL, which tries to send and receive an array between devices.

```
  int src_dev = 0;
  std::vector<int> dst_devs;

  for (int i = 1; i < argc; i++) {
    auto dst = std::string(argv[i]);
    dst_devs.push_back(std::stoi(dst));
  }

  std::vector<std::thread> ths;
  ncclUniqueId id;
  int nDevs = dst_devs.size() + 1;
  int nElem = 1000 * 1000 * 100;

  CHECK_NCCL(ncclGetUniqueId(&id));

  ths.emplace_back([&]() {
    groute::Stream stream(src_dev);
    thrust::device_vector<int> src_data(nElem);
    ncclComm_t comm;

    CHECK_NCCL(ncclCommInitRank(&comm, nDevs, id, src_dev));
    CHECK_NCCL(ncclGroupStart());

    for (int rank = 1; rank < nDevs; rank++) {
      CHECK_NCCL(ncclSend(thrust::raw_pointer_cast(src_data.data()),
                          src_data.size(), ncclInt, rank, comm,
                          stream.cuda_stream));
    }
    CHECK_NCCL(ncclGroupEnd());
    stream.Sync();
    CHECK_NCCL(ncclCommDestroy(comm));
  });

  for (int rank = 1; rank < nDevs; rank++) {
    ths.emplace_back([&, rank]() {
      int dst = dst_devs[rank - 1];
      groute::Stream stream(dst);
      thrust::device_vector<int> dst_data(nElem);
      ncclComm_t comm;

      CHECK_NCCL(ncclCommInitRank(&comm, nDevs, id, rank));
      Stopwatch sw(true);

      CHECK_NCCL(ncclGroupStart());
      CHECK_NCCL(ncclRecv(thrust::raw_pointer_cast(dst_data.data()),
                          dst_data.size(), ncclInt, src_dev, comm,
                          stream.cuda_stream));
      CHECK_NCCL(ncclGroupEnd());
      stream.Sync();
      sw.stop();
      std::cout << "Dev: " << dst << " time: " << sw.ms() << " Bandwidth: "
                << ((double) dst_data.size() * sizeof(int) / 1024 / 1024 /
                    1024) /
                       (sw.ms() / 1000)
                << " GB/s" << std::endl;

      CHECK_NCCL(ncclCommDestroy(comm));
    });
  }

  for (auto& th : ths) {
    th.join();
  }
```

I run the program that sends an integer array from device 0 and receives it from device 7. According to your explanation, an intermediate GPU will be used to transfer the buffer because there is no direct link between device 0 and device 7. My program reports the bandwidth was about 10.1901 GB/s, and that looks very close to PCI-E bandwidth. I run the program again with nvprof and import the profiling log into NVIDIA Visual Profiler. The diagram shows that there is no intermediate device that participates in the computation. The version of nccl is 2.9.9.

![Screen Shot 2021-08-05 at 17 25 10](https://user-images.githubusercontent.com/14839342/128326990-696fd22f-15cc-4f91-b69a-af2200879f68.png)


Here is the configuration of a machine I'm using:
```
<system version="1">
  <cpu numaid="0" affinity="ffffffff,ffffffff,ffffffff" arch="x86_64" vendor="GenuineIntel" familyid="6" modelid="85">
    <pci busid="0000:18:00.0" class="0x060400" link_speed="8 GT/s" link_width="16">
      <pci busid="0000:4f:00.0" class="0x030200" link_speed="8 GT/s" link_width="16">
        <gpu dev="0" sm="70" rank="0" gdr="0">
          <nvlink target="0000:50:00.0" count="1" tclass="0x030200"/>
          <nvlink target="0000:60:00.0" count="2" tclass="0x030200"/>
          <nvlink target="0000:db:00.0" count="2" tclass="0x030200"/>
          <nvlink target="0000:5f:00.0" count="1" tclass="0x030200"/>
        </gpu>
      </pci>
      <pci busid="0000:50:00.0" class="0x030200" link_speed="8 GT/s" link_width="16">
        <gpu dev="1" sm="70" rank="1" gdr="0">
          <nvlink target="0000:dc:00.0" count="2" tclass="0x030200"/>
          <nvlink target="0000:5f:00.0" count="2" tclass="0x030200"/>
          <nvlink target="0000:4f:00.0" count="1" tclass="0x030200"/>
          <nvlink target="0000:60:00.0" count="1" tclass="0x030200"/>
        </gpu>
      </pci>
    </pci>
    <pci busid="0000:5d:00.0" class="0x060400" link_speed="8 GT/s" link_width="16">
      <pci busid="0000:5f:00.0" class="0x030200" link_speed="8 GT/s" link_width="16">
        <gpu dev="2" sm="70" rank="2" gdr="0">
          <nvlink target="0000:60:00.0" count="2" tclass="0x030200"/>
          <nvlink target="0000:b1:00.0" count="1" tclass="0x030200"/>
          <nvlink target="0000:50:00.0" count="2" tclass="0x030200"/>
          <nvlink target="0000:4f:00.0" count="1" tclass="0x030200"/>
        </gpu>
      </pci>
      <pci busid="0000:60:00.0" class="0x030200" link_speed="8 GT/s" link_width="16">
        <gpu dev="3" sm="70" rank="3" gdr="0">
          <nvlink target="0000:4f:00.0" count="2" tclass="0x030200"/>
          <nvlink target="0000:50:00.0" count="1" tclass="0x030200"/>
          <nvlink target="0000:5f:00.0" count="2" tclass="0x030200"/>
          <nvlink target="0000:b2:00.0" count="1" tclass="0x030200"/>
        </gpu>
      </pci>
    </pci>
    <nic>
      <net name="eth0" dev="0" speed="10000" port="0" guid="0x0" maxconn="65536" gdr="0"/>
    </nic>
  </cpu>
  <cpu numaid="-1" arch="x86_64" vendor="GenuineIntel" familyid="6" modelid="85">
    <pci busid="0000:af:00.0" class="0x060400" link_speed="8 GT/s" link_width="16">
      <pci busid="0000:b1:00.0" class="0x030200" link_speed="8 GT/s" link_width="16">
        <gpu dev="4" sm="70" rank="4" gdr="0">
          <nvlink target="0000:dc:00.0" count="2" tclass="0x030200"/>
          <nvlink target="0000:b2:00.0" count="2" tclass="0x030200"/>
          <nvlink target="0000:5f:00.0" count="1" tclass="0x030200"/>
          <nvlink target="0000:db:00.0" count="1" tclass="0x030200"/>
        </gpu>
      </pci>
      <pci busid="0000:b2:00.0" class="0x030200" link_speed="8 GT/s" link_width="16">
        <gpu dev="5" sm="70" rank="5" gdr="0">
          <nvlink target="0000:60:00.0" count="1" tclass="0x030200"/>
          <nvlink target="0000:db:00.0" count="2" tclass="0x030200"/>
          <nvlink target="0000:b1:00.0" count="2" tclass="0x030200"/>
          <nvlink target="0000:dc:00.0" count="1" tclass="0x030200"/>
        </gpu>
      </pci>
    </pci>
    <pci busid="0000:d8:00.0" class="0x060400" link_speed="8 GT/s" link_width="16">
      <pci busid="0000:db:00.0" class="0x030200" link_speed="8 GT/s" link_width="16">
        <gpu dev="6" sm="70" rank="6" gdr="0">
          <nvlink target="0000:4f:00.0" count="2" tclass="0x030200"/>
          <nvlink target="0000:dc:00.0" count="1" tclass="0x030200"/>
          <nvlink target="0000:b1:00.0" count="1" tclass="0x030200"/>
          <nvlink target="0000:b2:00.0" count="2" tclass="0x030200"/>
        </gpu>
      </pci>
      <pci busid="0000:dc:00.0" class="0x030200" link_speed="8 GT/s" link_width="16">
        <gpu dev="7" sm="70" rank="7" gdr="0">
          <nvlink target="0000:b1:00.0" count="2" tclass="0x030200"/>
          <nvlink target="0000:b2:00.0" count="1" tclass="0x030200"/>
          <nvlink target="0000:db:00.0" count="1" tclass="0x030200"/>
          <nvlink target="0000:50:00.0" count="2" tclass="0x030200"/>
        </gpu>
      </pci>
    </pci>
  </cpu>
</system>
```

**Comment by sjeaugey** [comment]
It is expected that you don't see anything on the intermediate GPU: it is a passive target for both the sender and receiver. There is no kernel running on it.

Regarding the performance you see, it is lower than it should be. Keep in mind though that we will only use an intermediate GPU which is part of the NCCL communicator. So if you create a communicator with only GPU 0 and GPU 7, send/recv communication will go back to the CPU. You would need to have at least GPU 3 or GPU 4 to be able to use NVLink between 0 and 7.

**Comment by pwrliang** [comment]
Thanks again, all my questions are perfectly answered.

**Comment by heavyrain-lzy** [comment]
> I'm implementing a graph analytical framework that leverages nccl as the communication framework. Most of the operations that I use are ncclSend/ncclRecv. I'm curious about that how these primitives are implemented.
> 
> As far as I know from the official documents, a dedicated kernel is used for memory copy, and the data flows within a ring topology. However, I'm not sure about how P2P operations are implemented. I have the following questions about the design:
> 
> 1. Why a dedicated kernel is used instead of the cudaMempy? Since a GPU has a specific copy engine, using cudaMempy allows the application to use SMs fully.
> 2. What topology is used for P2P operations? The data flows as a ring, or a kernel copies the data directly?
> 3. When a pair of ncclSend/ncclRecv operations are issued between two GPUs that are not directly connected with NVLINK, will the data be transited by a third GPU to speed up the communication?

I wonder where I can find more information about NCCL such as how to impement the ncclSend. I can only get the reference from [Overview of NCCL](https://docs.nvidia.com/deeplearning/nccl/user-guide/docs/overview.html). How do you know the "As far as I know from the official documents, a dedicated kernel is used for memory copy, and the data flows within a ring topology."? Can you give the website?
