### ISSUE TITLE
Why do some kernels only get invoked with int8_t as data type?

### ISSUE THREAD

**Issue by hy00nc** [NVIDIA/nccl#542]
Hi, I've got a question on NCCL's source code.

Just as the title says, **why do some kernels only get invoked with int8_t data type?**
These kernels include `SendRecv`, `Broadcast`, `Gather`, etc. I suspect these are the ones that do not need computation using the buffer values during the kernel execution.

I have been assuming that all the kernels are invoked with the data type of the values that we actually communicate. Why is `int8_t` sufficient or necessary for these kernels? Am I missing something? How are the data transferred using `int8_t` when the actual values to transfer have a different type?

I would appreciate any help :)

**Comment by sjeaugey** [comment]
Allgather, Broadcast and Send/Recv perform simple copies; there is no difference between a broadcast of 1 Million floats and a broadcast of 4 Millions int8. To reduce binary size, we only generate the code for int8, and multiply the count by the datatype size in bytes.

**Comment by hy00nc** [comment]
I see. Thanks for the quick response!
