### ISSUE TITLE
What is Direct in NCCL code?

### ISSUE THREAD

**Issue by void-main** [NVIDIA/nccl#547]
What's the difference between Send and DirectSend? Is it related to GDR stuff?

**Comment by sjeaugey** [comment]
DirectSend allows to optimize the case where the sender and receiver are in the same process, hence the sender is able to write the data directly to the final user buffer instead of using the FIFO, with the receiver doing an extra copy.

**Comment by void-main** [comment]
Got it, thank you very much!
