### ISSUE TITLE
NCCL test failed of initialization error

### ISSUE THREAD

**Issue by lujx1024** [NVIDIA/nccl#554]
## What I was Trying to do

I have a 4 NVIDIA GPU machine  and I tried to parallel train a deep learning model with all GPU participanted. So I install NCCL as I was told in  tutorial  step by step , and I used the [nccl_tests](https://github.com/NVIDIA/nccl-tests) to test the environment. and the test  failed. Here is the detail information.

## Environment

- OS : CentOS 7 64bit
- CUDA : Version 10.1.243
- chDNN : 7.6.5
- GPU : GeForce RTX 2080 Ti
- NCCL Version : NCCL 2.8.3 for CUDA 10.1

## What I have done

1. I double checked the NCCL version that corresponded with the CUDA version and cuDNN version to make sure I installed the right version。
2. I downloaded the Local installation package （RPM）to make sure I don't have an internet issue.
3. After  installation , I added the environment variable to `~./bashrc` 

## Something may need to know about environment variable

1. NCCL library files in the system 

   I run this command to make sure I can find all the file that related to NCCL: `find / -name libnccl* `,and I got results like bellow:
  ```
    /var/nccl-repo-2.8.3-ga-cuda10.1/libnccl-2.8.3-1+cuda10.1.x86_64.rpm
    /var/nccl-repo-2.8.3-ga-cuda10.1/libnccl-devel-2.8.3-1+cuda10.1.x86_64.rpm
    /var/nccl-repo-2.8.3-ga-cuda10.1/libnccl-static-2.8.3-1+cuda10.1.x86_64.rpm
    /usr/lib64/libnccl.so.2.9.9
    /usr/lib64/libnccl.so.2
    /usr/lib64/libnccl.so
    /usr/lib64/libnccl_static.a
    /usr/share/doc/libnccl-2.9.9
    /usr/share/doc/libnccl-devel-2.9.9
    /usr/share/doc/libnccl-static-2.9.9
  ```

2. Added `usr/lib64` to environment variable `LD_LIBRARY_PATH`:
  I wrote `export LD_LIBRARY_PATH=/usr/lib64:$LD_LIBRARY_PATH` to the bottom of the file `~/.bashrc` to make sure it's set up permanently, and using `echo $LD_LIBRARY_PATH` to double check。and I got results like bellow:
```
  [root@centos nccl-tests]# echo $LD_LIBRARY_PATH
  /usr/lib64:/usr/local/cuda/lib64:/usr/local/cuda-10.1/lib64:/usr/local/cuda/lib64:/usr/local/cuda-10.1/lib64:
```
## The error log

```
[root@centos nccl-tests]# ./build/all_reduce_perf -b 8 -e 128M -f 2 -g 3         
# nThread 1 nGpus 3 minBytes 8 maxBytes 134217728 step: 2(factor) warmup iters: 5 iters: 20 validation: 1                                                                                                     
#                                                                                                      
#   Using devices                                                                                        
#   Rank  0 Pid  44621 on centos_aoto device  0 [0x03] GeForce RTX 2080 Ti                             
#   Rank  1 Pid  44621 on centos_aoto device  1 [0x82] GeForce RTX 2080 Ti                             
#   Rank  2 Pid  44621 on centos_aoto device  2 [0x83] GeForce RTX 2080 Ti                             
                                                                                                       
centos_aoto:44621:44621 [0] enqueue.cc:74 NCCL WARN Cuda failure 'initialization error'                
centos_aoto:44621:44621 [-596340352] NCCL INFO Bootstrap : Using eno1:172.16.210.212<0>                
centos_aoto:44621:44621 [64768] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation                                                                                        
centos_aoto:44621:44621 [0] NCCL INFO NET/IB : No device found.                                        
centos_aoto:44621:44621 [-596346187] NCCL INFO NET/Socket : Using [0] eno1:172.16.210.212<0> [1] eno2:192.168.1.127<0> [2]virbr0:192.168.122.1<0> [3]veth26556bd:fe80::a423:dbff:fe8f:b378%veth26556bd<0>       
centos_aoto:44621:44621 [4096] NCCL INFO Using network Socket  NCCL version 2.9.9+cuda11.3                                                                            
                                                                                                       
centos_aoto:44621:44621 [0] init.cc:891 NCCL WARN Cuda failure 'initialization error'                                                                                                         
centos_aoto:44621:44621 [0] init.cc:891 NCCL WARN Cuda failure 'initialization error'                                                                                                        
centos_aoto:44621:44621 [0] init.cc:891 NCCL WARN Cuda failure 'initialization error'                                                                                                         
centos_aoto:44621:44621 [0] group.cc:161 NCCL WARN Cuda failure 'initialization error'      
centos_aoto:44621:44621 [0] NCCL INFO init.cc:936 -> 1                                                 
centos_aoto: Test NCCL failure common.cu:1017 'unhandled cuda error'                                   
 .. centos_aoto pid 44621: Test failure common.cu:925                                                  
```
## I need your help
I have looked up issues in the github page and tutorials and I couldn't fix this problem , So what should I do now to push forward my troubleshooting ? Any suggestion will be appreciated .

**Comment by sjeaugey** [comment]
From the log, it seems you are actually using `NCCL version 2.9.9+cuda11.3`.

That might explain why the first call to CUDA fails. Note that in /usr/lib64 the library is called `libnccl.so.2.9.9`, not `2.8.4` as mentioned. How did you install the NCCL library?

**Comment by lujx1024** [comment]
I installed this NCCL library via RPM package, and I downloaded the specific version 2.8.3 for CUDA 10.1 and the file name is `nccl-repo-rhel7-2.8.3-ga-cuda10.1-1-1.x86_64.rpm`, Honestly I don't know this `libnccl.so.2.9.9` files came from , what should I do ? shuold I just delete all files that contain 2.9.9 or else? because I couldn't find a way to uninstall it .

**Comment by lujx1024** [comment]
@sjeaugey Yes , you are right  that is the reason the nccl tests failed, I didn't realize that I actually call the `libnccl.so.2.9.9`, not `2.8.3`. I did see the log, I just didn't observer, That's My bad.

So , the thing is I did download the RPM file and I executed the command `rpm -ivh nccl-repo-rhel7-2.8.3-ga-cuda10.1-1-1.x86_64.rpm `, but instead of install the nccl library, it seems this command just splited this package into three independent packages（maybe I need to install them separately I assum）. As someone else may install another version of NCCL and my installation is not effected caused the incompatible cuda and nccl version, and that leads to the `initialization error`.

## Solution : uninstall the incompatible version and reinstall the compatible one
```
[root@centos home]# rpm -qa | grep nccl
libnccl-2.9.9-1+cuda11.3.x86_64
libnccl-static-2.9.9-1+cuda11.3.x86_64
libnccl-devel-2.9.9-1+cuda11.3.x86_64

[root@centos home]# rpm -e libnccl-devel-2.9.9-1+cuda11.3.x86_64
/sbin/ldconfig: /usr/local/cuda-10.1/targets/x86_64-linux/lib/libcudnn.so.7 is not a symbolic link

[root@centos home]# rpm -e libnccl-2.9.9-1+cuda11.3.x86_64
/sbin/ldconfig: /usr/local/cuda-10.1/targets/x86_64-linux/lib/libcudnn.so.7 is not a symbolic link

[root@centos home]# rpm -e libnccl-static-2.9.9-1+cuda11.3.x86_64

[root@centos home]# yum install libnccl-2.8.3-1+cuda10.1 libnccl-devel-2.8.3-1+cuda10.1 libn ccl-static-2.8.3-1+cuda10.1
Loaded plugins: fastestmirror, langpacks
Loading mirror speeds from cached hostfile
 * base: mirrors.aliyun.com
 * epel: mirrors.bfsu.edu.cn
 * extras: mirrors.aliyun.com
 * updates: mirrors.aliyun.com
Resolving Dependencies
--> Running transaction check
---> Package libnccl.x86_64 0:2.8.3-1+cuda10.1 will be installed
---> Package libnccl-devel.x86_64 0:2.8.3-1+cuda10.1 will be installed
---> Package libnccl-static.x86_64 0:2.8.3-1+cuda10.1 will be installed
--> Finished Dependency Resolution

Dependencies Resolved

========================================================================================================================= 
Package                     Arch                Version                       Repository                           Size 
=========================================================================================================================
Installing:
 libnccl                     x86_64              2.8.3-1+cuda10.1              nccl-2.8.3-ga-cuda10.1               32 M  
 libnccl-devel               x86_64              2.8.3-1+cuda10.1              nccl-2.8.3-ga-cuda10.1              7.7 k  
 libnccl-static              x86_64              2.8.3-1+cuda10.1              nccl-2.8.3-ga-cuda10.1               37 M

Transaction Summary
=========================================================================================================================
Install  3 Packages

Total download size: 69 M
Installed size: 181 M
Is this ok [y/d/N]: y
Downloading packages:
-------------------------------------------------------------------------------------------------------------------------
Total                                                                                    418 MB/s |  69 MB  00:00:00
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
Warning: RPMDB altered outside of yum.
  Installing : libnccl-2.8.3-1+cuda10.1.x86_64                                                                       
  1/3 /sbin/ldconfig: /usr/local/cuda-10.1/targets/x86_64-linux/lib/libcudnn.so.7 is not a symbolic link

  Installing : libnccl-devel-2.8.3-1+cuda10.1.x86_64                                                                 
  2/3 /sbin/ldconfig: /usr/local/cuda-10.1/targets/x86_64-linux/lib/libcudnn.so.7 is not a symbolic link

  Installing : libnccl-static-2.8.3-1+cuda10.1.x86_64                                                                3/3
  Verifying  : libnccl-static-2.8.3-1+cuda10.1.x86_64                                                                1/3
  Verifying  : libnccl-devel-2.8.3-1+cuda10.1.x86_64                                                                 2/3
  Verifying  : libnccl-2.8.3-1+cuda10.1.x86_64                                                                       3/3

Installed:
  libnccl.x86_64 0:2.8.3-1+cuda10.1  libnccl-devel.x86_64 0:2.8.3-1+cuda10.1  libnccl-static.x86_64 0:2.8.3-1+cuda10.1

Complete!
```
Now the environment is settled and nccl tests past too.

@sjeaugey Thannk you for your time, you've been very helpful and I really appreciate that.

**Comment by sjeaugey** [comment]
@lujx1024 did you follow the [NCCL install guide]( https://docs.nvidia.com/deeplearning/nccl/install-guide/index.html#rhel_centos) ?

Copy/pasting the relevant lines for a local repo:

1. Install the repo 
```
sudo rpm -i nccl-repo-<version>.rpm
```
2. Update yum database
```
sudo yum update
```
3. Install NCCL
```
sudo yum install libnccl libnccl-devel libnccl-static
```
Was the documentation unclear, erroneous, or it was just you didn't find the documentation? I'm realizing the link to that installation guide is pretty hard to find; I'll see if we can get a link added close to the RHEL download link.

Thanks for your feedback!

**Comment by lujx1024** [comment]
Thank you for claritying it , and now I'm sure it was me didn't get what the documentation tells me to do.  

After I jump to the download page and log on my account , chose a right version and download the local installer, I subconsciously use the command `rpm -ihv package` to install them and totally forget about the documentation.

And to be fair,I feel waht the documentation says is pretty clearly after  I look through it . it's just a little bit complicated for people like me who use English as a sencond language. 

I should pay more attention on this documentation before I executed the installation command.

Thank you  very much for your remind, I really appreciate your effort .
