### ISSUE TITLE
CollNet causes CUDA_ERROR_ILLEGAL_ADDRESS events 

### ISSUE THREAD

**Issue by changlan** [NVIDIA/nccl#556]
After upgrading NCCL from 2.7 to 2.10, I started to encounter crashes with `CUDA_ERROR_ILLEGAL_ADDRESS` events when using CollNet for all-reduce in TensorFlow:

![image](https://user-images.githubusercontent.com/603293/130311794-a67ed84a-ec2b-4fab-8a25-463c86b2c55a.png)

The issue seems to be first introduced by recent CollNet changes in 2.10.3. Observations so far:
* NCCL 2.7.3 CollNet: no error
* NCCL 2.9.6 CollNet: no error
* NCCL 2.10.3 CollNet: `CUDA_ERROR_ILLEGAL_ADDRESS`
* NCCL 2.10.3 CollNet with `NCCL_PROTO=LL`: no error, but much slower training.

The issue is not tied to the specific CollNet transport implementation, as I can reproduce the same issue with a dummy transport: https://gist.github.com/changlan/5a879487058ff1500861458ca3c0b0c9.

/cc @sjeaugey @kwen2501

**Comment by kwen2501** [comment]
Thanks for reporting this. We have a few questions:
(1) What machine are you using? How many GPUs per node? Are the machines connected to a switch capable of reduction?
(2) Can you share the NCCL log with setting `NCCL_DEBUG=INFO NCCL_DEBUG_SUBSYS=INIT,GRAPH,ENV,TUNING,COLL`? It would help us identify the problem.
(3) Do you have a simple reproducer?

Ps: there is no combination of CollNet + LL since NCCL 2.9.

**Comment by changlan** [comment]
Hi Ke, thanks for the reply. We were using `n1-highmem-96` machines with 8 V100 per host. We had the issue even with a dummy transport that does not rely on a SHARP-capable switch so it is unlikely related to specific CollNet transports. Please find the NCCL log in the attached [train.log](https://github.com/NVIDIA/nccl/files/7069611/train.log) file.

So far the easiest reproducer I have is this [notebook](https://github.com/changlan/ai-platform-samples/blob/cmle-rs/ai-platform/notebooks/unofficial/reduction_server/distributed-training-reduction-server.ipynb) using `gcr.io/deeplearning-platform-release/tf2-gpu.2-5:m76` as the base image (**m73** has NCCL 2.9 while **m76** has NCCL 2.10).

**Comment by changlan** [comment]
Any updates? I wonder if there is any easy way to use CollNet on a single node (e.g. letting two GPUs on the same host use CollNet instead of doing all-reduce locally), which could simplify reproducing the issue.
