### ISSUE TITLE
How can I scale with nccl addoption?

### ISSUE THREAD

**Issue by archenroot** [NVIDIA/nccl#56]
Hi, 

I have single GPU application which I am now trying to extend to work on multiple GPUs, which is offloading data in segments and I would like to let it scale both horizontally and vertically.

Q1: I am considering adopting nccl for single node multi-gpu task distribution. I think this is the way to go in the moment. Is this where nccl will help me?

Q2: When it comes to multigpu clusters distribution(for example I have 2x 8GPU systems), is there also work for nccl or better to look into frameworks like rCUDA MPI?

Q3: Does nccl try to aspirate to become a generic layer into which I could potentially connect any system with any number of GPUs and distribute tasks? 

Thanks for suggestions/answers.

Ladislav

**Comment by nluehr** [comment]
NCCL is strictly a collective communication library. It provides optimized routines for operations such as broadcast or all-reduce among multiple GPUs, but not any mechanisms for task distribution or control. If you are just starting out with multi-GPU programming, CUDA-aware MPI might be a good place to start. [Here](http://on-demand-gtc.gputechconf.com/gtc-quicklink/6Pg15P1) is a presentation from last year's GTC that may be helpful.

**Comment by archenroot** [comment]
Thx for article and explanation, and yes, I am exploring this world of "beyond single gpu" in the moment.
