### ISSUE TITLE
Why not use command mode to do data transfer ?

### ISSUE THREAD

**Issue by elevenxiang** [NVIDIA/nccl#567]
I have a simple question about the data transfer inside the NCCL.

From the code, NCCL use kernels to do all coll or p2p communication, but from the bandwidth test, cudaMemcpy  has higher bandwidth. so why use kernel mode  ?

is it because command mode has poor and low efficiency synchronize method ?

Thanks

**Comment by elevenxiang** [comment]
or the reduce op, like SUM/MIN/MAX ... they are easy to combined with kernel ?

**Comment by jbachan** [comment]
Consider reductions: kernels allow us to read from multiple remote buffers, sum their contents with the local buffer, and write the results out to another remote buffer. cudaMemcpy cannot do that. cudaMemcpy also has high latency. By using a kernel we only pay the latency once to launch the kernel and then time between transfers done in that kernel is minimal.
