### ISSUE TITLE
How to use memory allocated by cudaMallocPitch?

### ISSUE THREAD

**Issue by pranavladkat** [NVIDIA/nccl#57]
I could follow this library easily for memories allocated by cudaMalloc since I know the exact number of count/datatype I requested. How can I use memory allocated by cudaMallocPitch?

Thanks,
Pranav

**Comment by nluehr** [comment]
You can use the pitch value returned by cudaMallocPitch to compute the total allocation size. E.g.,
```
cudaMallocPitch(&ptr, &pitch, width, height);
ncclCount = pitch * height / sizeof(Type);
```

**Comment by pranavladkat** [comment]
Thanks! It worked :) Closing this issue
