### ISSUE TITLE
Compile error in enqueue.cc: error: 'memcpy' is not a member of 'std'

### ISSUE THREAD

**Issue by HongmingHUANG** [NVIDIA/nccl#571]
Environment: Ubuntu 18.04 LTS, gcc 7.5.0.

When I just cloned the repo and follows the building operation using 'make -j src.build' to build, it occurs an error:

enqueue.cc: In function 'ncclResult_t ncclRedOpCreatePreMulSum(ncclRedOp_t*, void*, ncclDataType_t, ncclScalarResidence_t, ncclComm_t)':
enqueue.cc:1285:10: error: 'memcpy' is not a member of 'std'
     std::memcpy(ops, comm->userRedOps, comm->userRedOpCapacity*sizeof(ncclUserRedOp));

Does anyone meet the same issue? In the last month, I can build NCCL successfully.

**Comment by jbachan** [comment]
It does not repro for me on my more modern ubuntu+gcc. Does adding `#include <cstring>` to the top of `src/enqueue.cc` resolve this issue?

**Comment by HongmingHUANG** [comment]
> It does not repro for me on my more modern ubuntu+gcc. Does adding `#include <cstring>` to the top of `src/enqueue.cc` resolve this issue?

Yes, it can solve the problem and compile the enqueue.cc now. So this is a compatible issue for older version of gcc?

**Comment by jbachan** [comment]
My guess is that this is the fault of NCCL for not having that include there, and that it just happens to work on newer GCC's. I will merge this fix.

**Comment by jbachan** [comment]
Fixed in 30ca3fcacf8a73c48d7b8f7aaa54ae8bff89e884
