### ISSUE TITLE
Why Simple proto need an extra warp to do system fence?

### ISSUE THREAD

**Issue by manofmountain** [NVIDIA/nccl#572]
Just found nccl use an extra warp to do system fence on Simple proto. Will the system fence be executed with next round of ReduceCopyStore by other 16 warps in a parallel way? Could you guys help elaborate the optimization mechanism here?

**Comment by sjeaugey** [comment]
Yes, that's indeed the purpose of that extra side thread calling threadfence_system: letting the other 512 threads copy the next chunk while we wait for the fence to complete and post the flag to the next GPU. Not doing so would cause significant bubbles and lower efficiency.

**Comment by manofmountain** [comment]
@sjeaugey  thanks for your quick response.

So two more questions here.

1. As the 17th warp can be executed with the other 16 worker warps independently, how could we ensure 'threadfence_system' being executed earlier than next chunk ReduceCopyStore?  As  the system fence should be a barrier for the whole blocks'  remote peer memory (or system host memory) store,  we should ensure it being executed before next chunk's remote store actions, right? please correct me if have misunderstandings here.

2. Even if we have a way to ensure system fence being issued before next chunk's ReduceCopyStore,  how could we ensure next chunk of data arrived later than current sent chunk, as the 1st chunk's system fence might not be finished yet.  So do we have a way to use many issued 'system fence' to guard different batches of peer memory store, and each of them have a sequential way to be executed sequentially to abide for the semantics of 'system fence'?

**Comment by sjeaugey** [comment]
1. We don't need the threadfence_system to complete before the next chunk starts being written. Our goal is only to make sure the **previous** chunk is visible to the next GPU before we update the FIFO tail. The next chunk can be written in parallel.
2. I'm not sure I understand why we need to worry about the ordering in that direction. The only sequence we want to enforce is: 1. write chunk (512 workers) 2. inter-process sync (all threads) 3. threadfence (sync warp) 4. remote flag update (sync warp). We do that sequence for every chunk, in a pipelined manner.

**Comment by manofmountain** [comment]
> 1. We don't need the threadfence_system to complete before the next chunk starts being written. Our goal is only to make sure the **previous** chunk is visible to the next GPU before we update the FIFO tail. The next chunk can be written in parallel.
> 2. I'm not sure I understand why we need to worry about the ordering in that direction. The only sequence we want to enforce is: 1. write chunk (512 workers) 2. inter-process sync (all threads) 3. threadfence (sync warp) 4. remote flag update (sync warp). We do that sequence for every chunk, in a pipelined manner.

@sjeaugey  Many thanks for your clarification, that's clear enough for me.
