### ISSUE TITLE
Cannot install nccl

### ISSUE THREAD

**Issue by saix47** [NVIDIA/nccl#58]
I was trying to install nccl on my PC:
Ubuntu 16.04 LTS
GTX 1080
CUDA 8.0
CUDNN 5.1
but got errors:

> minedl@minedl-machine:~/nccl$ make install 
> Compiling src/core.cu                         > /home/minedl/nccl/build/obj/core.o
> src/common_coll.h(96): error: class "ncclComm" has no member "buffSizePerRing"
> 
> src/common_coll.h(100): error: class "ncclMem" has no member "doneCount"
> 
> src/common_coll.h(105): error: class "ncclComm" has no member "nRings"
> 
> 3 errors detected in the compilation of "/tmp/tmpxft_000037f6_00000000-5_core.cpp4.ii".
> Makefile:109: recipe for target '/home/minedl/nccl/build/obj/core.o' failed
> make: *** [/home/minedl/nccl/build/obj/core.o] Error 2

Did anyone get the same error and solve it before?

**Comment by iN1k1** [comment]
Same here on similar PC configuration. It seems that the referred fields are indeed not a part of the ncclComm object..

**Comment by sjeaugey** [comment]
Should be fixed. Sorry about that. Let me know if that works for you now.

**Comment by dvector89** [comment]
I also can't install nccl. What i did was this:

>  [@nmyjs_1 nccl-master]$ make CUDA_HOME=/usr/local/cuda test
> Compiling src/libwrap.cu                      > /search/odin/shiliangliang/tools/nccl-master/build/obj/libwrap.o
> nvcc fatal   : Value 'gnu++0x' is not defined for option 'std'
> make: *** [/search/odin/shiliangliang/tools/nccl-master/build/obj/libwrap.o] Error 1

Is there anyone can figure it out? Thanks.

**Comment by sjeaugey** [comment]
Closing.
