### ISSUE TITLE
AllReduce bandwidth change curve with respect to data size

### ISSUE THREAD

**Issue by elevenxiang** [NVIDIA/nccl#583]
Hi

Currently, I found that all reduce bandwidth is still too low compared to NVLink physical bandwidth limitation:

As you know the reduce size during model training usually will not exceed 32M, so I think we should improve the little size bandwidth as possible as we can. Below is the test result on my A100 8-GPU environment

So Is that any ways to improve the bandwidth even on little reduce size ? or is there any formula to calculate the reduce size to archive best bandwidth ?

Thanks

```
nThread 1 nGpus 2 minBytes 32 maxBytes 1073741824 step: 2(factor) warmup iters: 5 iters: 20 validation: 1

Using devices
  Rank  0 Pid 1533050 on AI-A100-Beethoven01 device  0 [0x00] NVIDIA A100-SXM4-40GB
  Rank  1 Pid 1533050 on AI-A100-Beethoven01 device  1 [0x00] NVIDIA A100-SXM4-40GB

                                                       out-of-place                       in-place
       size         count      type   redop     time   algbw   busbw  error     time   algbw   busbw  error
        (B)    (elements)                       (us)  (GB/s)  (GB/s)            (us)  (GB/s)  (GB/s)
          32             8     float     sum    10.14    0.00    0.00  0e+00    10.21    0.00    0.00  0e+00
          64            16     float     sum    10.14    0.01    0.01  0e+00    10.31    0.01    0.01  0e+00
         128            32     float     sum    10.26    0.01    0.01  0e+00     9.98    0.01    0.01  0e+00
         256            64     float     sum    10.17    0.03    0.03  0e+00     9.99    0.03    0.03  0e+00
         512           128     float     sum    10.14    0.05    0.05  0e+00    10.26    0.05    0.05  0e+00
        1024           256     float     sum    10.60    0.10    0.10  0e+00    10.42    0.10    0.10  0e+00
        2048           512     float     sum    10.83    0.19    0.19  0e+00    10.53    0.19    0.19  0e+00
        4096          1024     float     sum    11.21    0.37    0.37  0e+00    10.99    0.37    0.37  0e+00
        8192          2048     float     sum    12.62    0.65    0.65  0e+00    12.37    0.66    0.66  0e+00
       16384          4096     float     sum    17.53    0.93    0.93  0e+00    17.36    0.94    0.94  0e+00
       32768          8192     float     sum    20.35    1.61    1.61  0e+00    19.95    1.64    1.64  0e+00
       65536         16384     float     sum    25.76    2.54    2.54  0e+00    26.00    2.52    2.52  0e+00
      131072         32768     float     sum    37.54    3.49    3.49  0e+00    37.15    3.53    3.53  0e+00
      262144         65536     float     sum    50.71    5.17    5.17  0e+00    49.82    5.26    5.26  0e+00
      524288        131072     float     sum    53.59    9.78    9.78  0e+00    53.04    9.88    9.88  0e+00
     1048576        262144     float     sum    69.77   15.03   15.03  0e+00    69.33   15.12   15.12  0e+00
     2097152        524288     float     sum    80.85   25.94   25.94  0e+00    78.86   26.59   26.59  0e+00
     4194304       1048576     float     sum    87.56   47.90   47.90  0e+00    87.45   47.96   47.96  0e+00
     8388608       2097152     float     sum    119.6   70.15   70.15  0e+00    119.4   70.24   70.24  0e+00
    16777216       4194304     float     sum    161.3  104.02  104.02  0e+00    158.9  105.61  105.61  0e+00
    33554432       8388608     float     sum    266.9  125.73  125.73  0e+00    264.8  126.71  126.71  0e+00
    67108864      16777216     float     sum    449.3  149.38  149.38  0e+00    449.9  149.17  149.17  0e+00
   134217728      33554432     float     sum    846.0  158.66  158.66  0e+00    844.2  158.99  158.99  0e+00
   268435456      67108864     float     sum   1603.9  167.36  167.36  0e+00   1599.6  167.81  167.81  0e+00
   536870912     134217728     float     sum   3118.6  172.15  172.15  0e+00   3111.5  172.55  172.55  0e+00
  1073741824     268435456     float     sum   6002.4  178.89  178.89  0e+00   5992.9  179.17  179.17  0e+00
Out of bounds values : 0 OK
Avg bus bandwidth    : 47.7939
```

**Comment by sjeaugey** [comment]
Performance on 2 GPUs can be a bit lower compared to 4 or 8, hence my request.

Can you copy here what command line you are using to launch the test? The performance you're getting seems a bit low to me and I want to be able to compare with my numbers.

Aside from that, given a given bandwidth and a given latency, there will always be a transition from latency-bound to bandwidth-bound as sizes increase. The "best" bandwidth is achieved at an infinite size.

And the higher the bandwidth, the larger sizes you would need to achieve peak bandwidth. The formula can be a bit complex though given we have multiple protocols with different latency/bandwidth tradeoffs. Basically, a ring works well (>95% efficiency) when each channel has 2 MB*ngpus. We have 2 channels per NVLink, hence 24 Channels*8 GPUs*2MB = 384MB. Internode, we have two channels per NIC so numbers would be different (because the peak bandwidth would be different too).

**Comment by elevenxiang** [comment]
> Ok, thanks. Do you get better performance when compiling the tests with MPI (`make ... MPI=1`) and running with `mpirun -np 8 all_reduce_perf -b 32 -f 2 -e 8G` (no `-g`)?

It seemed that mpirun test didn't get better .


mpirun -np 8 all_reduce_perf -b 32 -f 2 -e 8G
 nThread 1 nGpus 1 minBytes 32 maxBytes 8589934592 step: 2(factor) warmup iters: 5       iters: 20 validation: 1 single_test: 0 test_buffer_kind: 2

 Using devices
   Rank  0 Pid 1821213 on AI-A100-Beethoven01 device  0 [0x00] NVIDIA A100-SXM4-40GB
   Rank  1 Pid 1821214 on AI-A100-Beethoven01 device  1 [0x00] NVIDIA A100-SXM4-40GB
   Rank  2 Pid 1821215 on AI-A100-Beethoven01 device  2 [0x00] NVIDIA A100-SXM4-40GB
   Rank  3 Pid 1821216 on AI-A100-Beethoven01 device  3 [0x00] NVIDIA A100-SXM4-40GB
   Rank  4 Pid 1821217 on AI-A100-Beethoven01 device  4 [0x00] NVIDIA A100-SXM4-40GB
   Rank  5 Pid 1821218 on AI-A100-Beethoven01 device  5 [0x00] NVIDIA A100-SXM4-40GB
   Rank  6 Pid 1821219 on AI-A100-Beethoven01 device  6 [0x00] NVIDIA A100-SXM4-40GB
   Rank  7 Pid 1821223 on AI-A100-Beethoven01 device  7 [0x00] NVIDIA A100-SXM4-40GB

                                                     out-of-place                       in-place
       size         count    type   redop     time   algbw   busbw  error     time   algbw   busbw  error
        (B)    (elements)                     (us)  (GB/s)  (GB/s)            (us)  (GB/s)  (GB/s)
          32             8   float     sum    16.87    0.00    0.00  1e-07    16.54    0.00    0.00  1e-07
          64            16   float     sum    16.74    0.00    0.01  1e-07    16.51    0.00    0.01  1e-07
         128            32   float     sum    16.63    0.01    0.01  6e-08    16.70    0.01    0.01  6e-08
         256            64   float     sum    17.05    0.02    0.03  6e-08    16.81    0.02    0.03  6e-08
         512           128   float     sum    16.97    0.03    0.05  6e-08    16.85    0.03    0.05  6e-08
        1024           256   float     sum    17.59    0.06    0.10  1e-07    17.34    0.06    0.10  1e-07
        2048           512   float     sum    19.56    0.10    0.18  2e-07    19.14    0.11    0.19  2e-07
        4096          1024   float     sum    23.76    0.17    0.30  2e-07    22.55    0.18    0.32  2e-07
        8192          2048   float     sum    24.40    0.34    0.59  2e-07    25.79    0.32    0.56  2e-07
       16384          4096   float     sum    29.35    0.56    0.98  2e-07    25.89    0.63    1.11  2e-07
       32768          8192   float     sum    34.23    0.96    1.68  2e-07    33.04    0.99    1.74  2e-07
       65536         16384   float     sum    39.17    1.67    2.93  2e-07    37.55    1.75    3.05  2e-07
      131072         32768   float     sum    41.81    3.14    5.49  2e-07    40.58    3.23    5.65  2e-07
      262144         65536   float     sum    47.12    5.56    9.74  2e-07    45.85    5.72   10.01  2e-07
      524288        131072   float     sum    58.69    8.93   15.63  2e-07    62.11    8.44   14.77  2e-07
     1048576        262144   float     sum    75.53   13.88   24.29  2e-07    76.42   13.72   24.01  2e-07
     2097152        524288   float     sum    119.8   17.50   30.62  2e-07    119.1   17.60   30.80  2e-07
     4194304       1048576   float     sum    147.0   28.54   49.94  2e-07    146.5   28.63   50.10  2e-07
     8388608       2097152   float     sum    215.0   39.02   68.29  2e-07    214.2   39.17   68.55  2e-07
    16777216       4194304   float     sum    270.0   62.14  108.75  2e-07    269.1   62.36  109.12  2e-07
    33554432       8388608   float     sum    466.2   71.97  125.94  2e-07    465.5   72.08  126.13  2e-07
    67108864      16777216   float     sum    701.1   95.72  167.51  2e-07    700.0   95.86  167.76  2e-07
   134217728      33554432   float     sum   1369.9   97.98  171.46  2e-07   1367.9   98.12  171.71  2e-07
   268435456      67108864   float     sum   2432.9  110.33  193.09  2e-07   2435.4  110.22  192.89  2e-07
   536870912     134217728   float     sum   4847.8  110.75  193.80  2e-07   4843.5  110.84  193.98  2e-07
  1073741824     268435456   float     sum   9397.6  114.26  199.95  2e-07   9397.6  114.26  199.95  2e-07
  2147483648     536870912   float     sum    18715  114.75  200.81  2e-07    18718  114.73  200.77  2e-07
  4294967296    1073741824   float     sum    37069  115.86  202.76  2e-07    37195  115.47  202.07  2e-07
  8589934592    2147483648   float     sum    73972  116.12  203.22  2e-07    74501  115.30  201.77  2e-07

 Out of bounds values : 0 OK
 Avg bus bandwidth    : 68.1961

**Comment by elevenxiang** [comment]
> Ok, thanks. That's under what I'd expect by ~15% but in any case, you won't be much faster than that. You get close to peak at 256MB and that is consistent with my formula above.

okay ~

Thank you so much

**Comment by Macsim2** [comment]
@elevenxiang  
Hi I'm troubling with nccl bandwidth and I achieved lower band width using A100 80GB.
You gave a 40-70 GB/s bandwidth which use a NVlink right?
So. I trying check other people's computers setting compare to my setting
Can I get a your CPU and main Memory model name and main board etc by any chance..?

**Comment by cliffwoolley** [comment]
@Macsim2 Please file a new issue instead of tacking on to possibly unrelated older ones.  Thanks!
