### ISSUE TITLE
About function runRing(ncclWorkElem *args) in all_reduce.h

### ISSUE THREAD

**Issue by JoeyYoung** [NVIDIA/nccl#589]
Hi all, 

I am a little confused about the implementation of the ring all_reduce procedure. 
I found that when I call nccl communication for one tensor:
`NCCLCHECK(ncclAllReduce((const void *) sendbuff, (void *) recvbuff,size, ncclFloat, ncclSum,comm, s));`
The function `runRing(ncclWorkElem *args)` in all_reduce.h is triggered for multiple times. As far as I understand, this function contains the complete 2(k-1) steps to all-reduce chunks. Why we need repeat `runRing()` for one tensor?

Looking forward your kind suggestions

**Comment by JoeyYoung** [comment]
Is that because default nccl buffer size is 4MB, if the source tensor to be transmitted is larger than 4MB, nccl will split the tensor into multiple sections and transmit each section one-by-one?

**Comment by sjeaugey** [comment]
NCCL launches the allreduce operation on multiple CUDA blocks (one per channel), each running multiple threads. I'm not sure where you put your printf and how many you see, but CUDA being heavily parallel, it's not surprising to see runRun called multiple times.

**Comment by JoeyYoung** [comment]
I see. 
One more question related to #391. It said "one loop of the ring will process 1MB x nranks", does it mean (1MB x nranks) data is all-reduced within one loop? Sinec the FIFO size is 4MB, what if (1MB x nranks) > 4MB?

Thanks

**Comment by sjeaugey** [comment]
> what if (1MB x nranks) > 4MB?
Then the FIFO will rotate more than once during those 2*(nranks-1) steps.
