### ISSUE TITLE
Analysis nccl using Nsight Systems

### ISSUE THREAD

**Issue by rainyfly** [NVIDIA/nccl#591]
Hi, I try to use Nsight Systems to analysis a pytorch distributed training program. 
I use 'nsys profile python train.py', the output has nothing about nccl collective op information. 
And I found in nccl, nvtx marks are inserted in each collective op calling. And in this https://www.youtube.com/watch?v=bda5Er27jqo video, I can see the nccl item. So I am confused why  my nsys can not capture this information. I am so grateful to get the answer, thanks.

**Comment by rainyfly** [comment]
NCCL version 2.7.8+cuda10.2

**Comment by sjeaugey** [comment]
NVTX markings were aded in [2.8.3](https://github.com/NVIDIA/nccl/commit/920dbe5b359fe5817b8ba874476ca4ba2dc5f1ef).

```
2.8.3-1
...
Add NVTX profiling hooks.
...
```

**Comment by rainyfly** [comment]
Cool, thanks.
