### ISSUE TITLE
Is there any posibility to use warp_reduce intrinsic to implement kernel reduce functions?

### ISSUE THREAD

**Issue by dearsxx0918** [NVIDIA/nccl#594]
Hi, as title, I found that cuda tensor core support warp reduce function, why NCCL do not use this intrinsic to implement the kernel side code? Any performance consideration or implementation consideration?

**Comment by jbachan** [comment]
Our reduction algorithms are data parallel in that each thread is responsible for computing results destined to a different index of the final result vector since this is the access pattern GPUs are designed to handle best. Summing across threads is thus non productive.

**Comment by dearsxx0918** [comment]
Thanks for you reply!
