### ISSUE TITLE
Install error: [nvcc fatal   : Value 'gnu++0x' is not defined for option 'std']

### ISSUE THREAD

**Issue by dvector89** [NVIDIA/nccl#60]
Some information:
1. Red Hat Enterprise Linux Server release 6.6 (Santiago)
2. cuda7.5
3. nccl-1.2.3-1-cuda7.5

I installed by below command:
> [@ppk_02 nccl-1.2.3-1-cuda7.5]$ make CUDA_HOME=/usr/local/cuda test
> Compiling src/libwrap.cu            > build/obj/libwrap.o      
> nvcc fatal   : Value 'gnu++0x' is not defined for option 'std'
> make: *** [build/obj/libwrap.o] Error 1

Is there anyone who can help me figure it out? Thanks very much.

**Comment by sjeaugey** [comment]
According to https://access.redhat.com/solutions/19458 the GCC version in RHEL 6.6 is GCC 4.4. You need to use GCC 4.8 to compile NCCL. Compiling GCC 4.8.2 on RHEL 6.6 should be rather straightforward.

**Comment by dvector89** [comment]
@sjeaugey Thanks for your reply.
The version of gcc seems to be 4.4.7：

> [@ppk_02 nccl-1.2.3-1-cuda7.5]$ gcc --version
> gcc (GCC) 4.4.7 20120313 (Red Hat 4.4.7-11)
> Copyright (C) 2010 Free Software Foundation, Inc.
> This is free software; see the source for copying conditions.  There is NO
> warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
> 
> [@ppk_02 nccl-1.2.3-1-cuda7.5]$ g++ --version
> g++ (GCC) 4.4.7 20120313 (Red Hat 4.4.7-11)
> Copyright (C) 2010 Free Software Foundation, Inc.
> This is free software; see the source for copying conditions.  There is NO
> warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Do I need to change the version to 4.82?

**Comment by dvector89** [comment]
After installed GCC 4.9.2, I get the same error when I compile the NCCL. (I did not compile the GCC 4.8.2 successfully)

**Comment by LitLeo** [comment]
I also encountered the same problem. How did you solve the problem?
Thanks very much.

**Comment by LitLeo** [comment]
Hi， I have solved this problem.
I successfully installed NCCL on Ubuntu 14.04. I debugged the Makefile and found the $CXX is different in Ubuntu 14.04 and 
In Ubuntu 14.04, $CXX=g++, in $CXX=g++ std=gnu++0x.
So I run 
`export CXX=g++`
It works.
