### ISSUE TITLE
NCCL fails to build on mac

### ISSUE THREAD

**Issue by Yangqing** [NVIDIA/nccl#61]
I am building the master version (at commit 2a974f5ca2aa12b178046b2206b43f1fd69d9fae), with Mac OS 10.12 and got the following error:

> jiayq-mbp:nccl jiayq$ make
> ls: /usr/local/cuda/lib64/libcudart.so.*: No such file or directory
> ls: /usr/local/cuda/lib64/libcudart.so.*: No such file or directory
> ls: /usr/local/cuda/lib64/libcudart.so.*: No such file or directory
> ls: /usr/local/cuda/lib64/libcudart.so.*: No such file or directory
> Grabbing  src/nccl.h                          > /Users/jiayq/Research/nccl/build/include/nccl.h
> ls: /usr/local/cuda/lib64/libcudart.so.*: No such file or directory
> ls: /usr/local/cuda/lib64/libcudart.so.*: No such file or directory
> Compiling src/libwrap.cu                      > /Users/jiayq/Research/nccl/build/obj/libwrap.o
> ls: /usr/local/cuda/lib64/libcudart.so.*: No such file or directory
> ls: /usr/local/cuda/lib64/libcudart.so.*: No such file or directory
> Compiling src/core.cu                         > /Users/jiayq/Research/nccl/build/obj/core.o
> src/core.cu(717): error: expected an expression
> 
> src/core.cu(717): error: expected an expression
> 
> 2 errors detected in the compilation of "/var/folders/4x/jpsdl58x643dsgw7tbq1zs5clp6v5p/T//tmpxft_00013b6e_00000000-11_core.compute_52.cpp1.ii".
> make: *** [/Users/jiayq/Research/nccl/build/obj/core.o] Error 2

@slayton58 recommended me opening an issue - happy to provide more details :)

My build environment is nvcc 8.0.54 and Apple LLVM version 8.0.0 (clang-800.0.42.1).

**Comment by sjeaugey** [comment]
That usually means that your CUDA_HOME is not set properly. CUDA_HOME defaults to /usr/local/cuda ; you should set it to your CUDA installation path. Agreed, we could return a more explicit message.

Let me know if that fixes the problem.

**Comment by Yangqing** [comment]
Thanks @sjeaugey!

I tried adding

export CUDA_HOME=/usr/local/cuda; make

and it seems to not work either.

**Comment by sjeaugey** [comment]
Setting CUDA_HOME to /usr/local/cuda should not change anything (it is already the default value). Given the output, it looks like "ls /usr/local/cuda/lib64/libcudart.so.*" fails. If you are sure the path is correct, then it may be a mac-specific issue.

Be aware that you may be the first person trying to compile NCCL on mac, so you are in unknown territory here.

**Comment by maddyscientist** [comment]
I think the problem is that on mac the directory should be lib not lib64.

**Comment by Yangqing** [comment]
Thanks guys for the pointers - I think I have a solution by fixing the Makefile, will send a PR.

**Comment by Yangqing** [comment]
#62 filed.
