### ISSUE TITLE
testbed question

### ISSUE THREAD

**Issue by jkhourybbn** [NVIDIA/nccl#611]
Hi @sjeaugey, I am putting together a testbed comprising a set of DGXA100 servers  (each server has 8 A100s with NVSwitch), interconnected over IB cards to a switch (8 cards per server). I want to be able to force all inter-GPU collective communications to go over the IB cards/switch even among the GPUs within the server, this is mainly to test some networking effect at the largest GPU scale. Is there a recommended way to force inter-GPU comms to go over IB cards within a server (bypass the internal NVLInk and PCI)?

Thank you.

**Comment by AddyLaddy** [comment]
`NCCL_P2P_DISABLE=1` `NCCL_SHM_DISBALE=1`

**Comment by jkhourybbn** [comment]
Thanks @AddyLaddy!
