### ISSUE TITLE
Rail Local Feature Schedule

### ISSUE THREAD

**Issue by f2hkop** [NVIDIA/nccl#619]
Dear NCCL Team, Happy New Year!
Is any progress updated on the rail local feature mentioned in GTC 21 Spring? 
We plan to evaluate it on our cluster under construction，as it may bring some performance gains in all-to-all communication.
![image](https://user-images.githubusercontent.com/45728083/148171337-274fd70d-2ccc-4b15-9d91-8303deba8d64.png)

**Comment by sjeaugey** [comment]
Hi,

It's imminent. We wanted to push the preview of 2.12 this week, but we found some serious bug and want to fix it first.

**Comment by f2hkop** [comment]
Got it, thanks for reply!

**Comment by f2hkop** [comment]
Thanks for update! We will test it when the resources are available.
