### ISSUE TITLE
Is there any need to upgrade nccl library to latest for my pytorch ?

### ISSUE THREAD

**Issue by elevenxiang** [NVIDIA/nccl#620]
Hi,

As the title's description, do I need to upgrade nccl library to latest ?

I noticed that sometimes there are some optimization commit, but also some bug fix patch, so I wonder if we need to upgrade our nccl library version ?

or which version do you suggest ?

Thanks

**Comment by sjeaugey** [comment]
That's a pretty general question. To upgrade or not to upgrade.

Generally, customers tend to not upgrade unless they experience performance issues or bugs. On large systems, given upgrading is a costly process, they usually experiment with the latest version on the side and if they see a great improvement (either with bugs or performance) then they decide to upgrade everything.

So I'd say feel free to try the latest version (especially if you run the latest GPU generations), but if everything works fine with the one you have you may not need to bother.

**Comment by elevenxiang** [comment]
> 

Ok, Thank you ~
