### ISSUE TITLE
NCCL WARN NET/Socket : message truncated  in PyTorch multiple machines and multiple GPUs

### ISSUE THREAD

**Issue by shanguanma** [NVIDIA/nccl#626]
I also meet same issue,My compute environment is as follows:
NCCL version 2.10.3+cuda11.1, ubuntu20.04, I am using multiple machines and multiple GPUs of pytorch to train model.
The detail is as follows:

transport/net_socket.cc:424 NCCL WARN NET/Socket : peer 192.168.161.30<59210> message truncated :
receiving 1048576 bytes instead of 65536
I don't konw how to slove it.

**Comment by sjeaugey** [comment]
That could be due to mostly two things:
 1. You're not calling NCCL consistently between ranks. NCCL_DEBUG_SUBSYS=COLL NCCL_DEBUG=INFO will dump all calls from all ranks and let you compare them ... if it happens quickly and not after hours or computing.
 2. NCCL is not using the same protocol on all ranks due to some environment not being consistent.

If it works with `NCCL_PROTO=SIMPLE` then it's probably 2. otherwise I'd chase 1.

**Comment by shanguanma** [comment]
@sjeaugey ,thanks for your reply, I have tried your two method, 
1. `You're not calling NCCL consistently between ranks. NCCL_DEBUG_SUBSYS=COLL NCCL_DEBUG=INFO will dump all calls from all ranks and let you compare them ... if it happens quickly and not after hours or computing.`
its output is
 ```
ype 2 op 0 root 0 comm 0x7f5a4c002f70 [nranks=2] stream 0x56411fb3cad0
dell-PowerEdge-T640:342239:342239 [0] NCCL INFO AllReduce: opCount 4e0 sendbuff 0x7f5a181ffe00 recvbuff 0x7f5a181ffe00 count 1 datatype 7 op 0 root 0 comm 0x7f5a4c002f70 [nranks=2] stream 0x56411fb3cad0
dell-PowerEdge-T640:342239:342239 [0] NCCL INFO AllReduce: opCount 4e1 sendbuff 0x7f5a1fbf0000 recvbuff 0x7f5a1fbf0000 count 1 datatype 4 op 2 root 0 comm 0x7f5a4c002f70 [nranks=2] stream 0x56411fb3cad0
dell-PowerEdge-T640:342239:342239 [0] NCCL INFO Broadcast: opCount 4e2 sendbuff 0x7f59ffd57800 recvbuff 0x7f59ffd57800 count 640 datatype 0 op 0 root 1 comm 0x7f5a4c002f70 [nranks=2] stream 0x56411fb3cad0
dell-PowerEdge-T640:342239:342239 [0] NCCL INFO AllReduce: opCount 4e3 sendbuff 0x7f5a015ffa00 recvbuff 0x7f5a015ffa00 count 1 datatype 7 op 0 root 0 comm 0x7f5a4c002f70 [nranks=2] stream 0x56411fb3cad0
dell-PowerEdge-T640:342239:348713 [0] NCCL INFO AllReduce: opCount 4e4 sendbuff 0x7f5a42400000 recvbuff 0x7f5a42400000 count 4310409 datatype 7 op 0 root 0 comm 0x7f5a4c002f70 [nranks=2] stream 0x56411fb3cad0
dell-PowerEdge-T640:342239:348713 [0] NCCL INFO AllReduce: opCount 4e5 sendbuff 0x7f5a64600000 recvbuff 0x7f5a64600000 count 6579593 datatype 7 op 0 root 0 comm 0x7f5a4c002f70 [nranks=2] stream 0x56411fb3cad0
dell-PowerEdge-T640:342239:348713 [0] NCCL INFO AllReduce: opCount 4e6 sendbuff 0x7f5a30000000 recvbuff 0x7f5a30000000 count 6975625 datatype 7 op 0 root 0 comm 0x7f5a4c002f70 [nranks=2] stream 0x56411fb3cad0
dell-PowerEdge-T640:342239:348713 [0] NCCL INFO AllReduce: opCount 4e7 sendbuff 0x7f5a66000000 recvbuff 0x7f5a66000000 count 6712320 datatype 7 op 0 root 0 comm 0x7f5a4c002f70 [nranks=2] stream 0x56411fb3cad0
dell-PowerEdge-T640:342239:348713 [0] NCCL INFO AllReduce: opCount 4e8 sendbuff 0x7f5a2e000000 recvbuff 0x7f5a2e000000 count 6588416 datatype 7 op 0 root 0 comm 0x7f5a4c002f70 [nranks=2] stream 0x56411fb3cad0
dell-PowerEdge-T640:342239:348713 [0] NCCL INFO AllReduce: opCount 4e9 sendbuff 0x7f5a2c000000 recvbuff 0x7f5a2c000000 count 6580992 datatype 7 op 0 root 0 comm 0x7f5a4c002f70 [nranks=2] stream 0x56411fb3cad0
dell-PowerEdge-T640:342239:348713 [0] NCCL INFO AllReduce: opCount 4ea sendbuff 0x7f5a2a000000 recvbuff 0x7f5a2a000000 count 6586624 datatype 7 op 0 root 0 comm 0x7f5a4c002f70 [nranks=2] stream 0x56411fb3cad0
dell-PowerEdge-T640:342239:348713 [0] NCCL INFO AllReduce: opCount 4eb sendbuff 0x7f5a28000000 recvbuff 0x7f5a28000000 count 6573312 datatype 7 op 0 root 0 comm 0x7f5a4c002f70 [nranks=2] stream 0x56411fb3cad0
dell-PowerEdge-T640:342239:348713 [0] NCCL INFO AllReduce: opCount 4ec sendbuff 0x7f5aa7022400 recvbuff 0x7f5aa7022400 count 592384 datatype 7 op 0 root 0 comm 0x7f5a4c002f70 [nranks=2] stream 0x56411fb3cad0
dell-PowerEdge-T640:342239:348713 [0] NCCL INFO AllReduce: opCount 4ed sendbuff 0x7f5aa7fca000 recvbuff 0x7f5aa7fca000 count 668 datatype 2 op 0 root 0 comm 0x7f5a4c002f70 [nranks=2] stream 0x56411fb3cad0
```
2. `NCCL is not using the same protocol on all ranks due to some environment not being consistent. I using export NCCL_PROTO=Simple`
After running one epoch, the next epoch is not continuing running. it is stucking there.

I'll elaborate more on my problem here.
I used NFS method to launch pytorch multi-machine and multi-GPUs training model.
Now， The network cable used between the machines instead of the IB card so I set `export NCCL_IB_DISABLE=1`
I get network name from ifconfig command, so I set `export NCCL_SOCKET_IFNAME="eno1np0"`
I used debug mode, so I set `export NCCL_DEBUG=INFO`
After completing  the above environment variables setting, Multi-machine and multi-GPUs can run one epoch, but when it comes to the next epoch, it keeps hovering there.
Could you  help me to solve it?

**Comment by sjeaugey** [comment]
Actually, I forgot to ask, did you run the NCCL perf tests first to make sure your environment/hardware setup was working fine? That would always be the first thing to do when experiencing issues with NCCL in a new environment.

Regarding 1. the log you're showing seems to be for rank 0. You need to also dump the log for all ranks and make sure the last allreduce(s) before the hang are consistent between ranks.

Also, one thing I didn't mention is to ensure the environment variables between all ranks are set consistently.  For example, when running with mpirun and launching tasks through SSH, all ranks on the same node as the mpirun command will inherit the environment, but ranks on remote nodes will not, so you need to pass those environment variables with the "-x" option of mpirun. When running in a SLURM environment, that's not necessary as SLURM replicates the environment in remote tasks.

**Comment by shanguanma** [comment]
@sjeaugey ，Thanks  a lot . I find my issue for my question. Machine-to-machine The network bandwidth is too low, causing part of the machine-to-machine synchronization information to be lost.
