### ISSUE TITLE
Why we need ld.volatile in NCCL?

### ISSUE THREAD

**Issue by dearsxx0918** [NVIDIA/nccl#628]
Hi, I'm reading NCCL code now, and I'm confused that there are many ASM code in NCCL. Typically the load/store operation.
I'm not a professionnal in this aspect, anyone can explain why we need ASM in NCCL? And why we need ld.volatile and st.volatile?
See https://github.com/NVIDIA/nccl/blob/014407367347d9a14fff072c6fb9a4d55e657d60/src/collectives/device/prims_ll.h#L97

**Comment by sjeaugey** [comment]
This is mostly to perform 16B load/stores. We could use `int4` datatypes but IIRC those don't like being marked as volatile and we need that as well.

The reason for volatile is simply that we read data from a GPU which was written by another GPU. The compiler cannot know that an external entity will write to that data, so we need to mark it as volatile to avoid compiler optimization which could break the code. In particular, LL protocols poll the data until the value of the flag is what they expect. So we need to compiler to reload that data from memory always, not keep the value from a register.

**Comment by dearsxx0918** [comment]
Hi sjeaugey, thanks for you quickly reply. I think I get your point for ld.volatile, but it doesn't explain why we need st.volatile?
See https://github.com/NVIDIA/nccl/blob/014407367347d9a14fff072c6fb9a4d55e657d60/src/collectives/device/prims_ll.h#L127

**Comment by dearsxx0918** [comment]
Thanks! Colse it now.
