### ISSUE TITLE
NCCL Installation Fetching Keys Step Resulted With: Unable to Fetch URI No Data

### ISSUE THREAD

**Issue by senanursahin** [NVIDIA/nccl#630]
Hello everyone,

My system is running on Ubuntu 20.04, x86_64 architecture, RTX3080 GPU.
I was trying to download NCCL and following from Installation Guide https://docs.nvidia.com/deeplearning/nccl/install-guide/index.html  I runned the command

  sudo apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/7fa2af80.pub

But this site is empty, not fetchable and from the first step of installation I got the following error,

    Executing: /tmp/apt-key-gpghome.y0ADTcv871/gpg.1.sh --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x84_64/7fa2af80.pub
    gpg: requesting key from ‘https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x84_64/7fa2af80.pub’
    gpg: WARNING: unable to fetch URI https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x84_64/7fa2af80.pub: No data

Are there any links provided for NCCL installation keys to work on Ubuntu x86_64

**Comment by sjeaugey** [comment]
I just tried to download the file with `wget` and it seemed to work fine. Could it be a transient error?

**Comment by senanursahin** [comment]
I think so! 
It worked fine after another try, thank you for your answer
