### ISSUE TITLE
Maybe duplicated when meeting unknown cpu?

### ISSUE THREAD

**Issue by ShrimpLau** [NVIDIA/nccl#632]
When I was reading src code, find this might occur double call, but don't see any bad effect :)

https://github.com/NVIDIA/nccl/blob/014407367347d9a14fff072c6fb9a4d55e657d60/src/graph/xml.cc#L575 seems duplicated with https://github.com/NVIDIA/nccl/blob/014407367347d9a14fff072c6fb9a4d55e657d60/src/graph/xml.cc#L584

**Comment by sjeaugey** [comment]
Good point, we could probably remove the first call on line 575, as the second one at 584 would probably do it as well. We'd need to try.

**Comment by ShrimpLau** [comment]
BTW I'm keeping an eye on whether it is possible to manually inject the whole topology to containers in one node with different visible GPUs to make use of NVLink instead of NET. In [this comment](https://github.com/NVIDIA/nccl/issues/324#issuecomment-616632252) last year, it seems difficult to make it, is there any update maybe?

**Comment by sjeaugey** [comment]
Not that I know of. Last time I tried, if the driver didn't see the GPU in question it wouldn't allow you to enable P2P.

**Comment by ShrimpLau** [comment]
Thanks for your information :)
