### ISSUE TITLE
Makefile does not install static library if only make install is called

### ISSUE THREAD

**Issue by aavbsouza** [NVIDIA/nccl#662]
Hello, some libraries for instance HPCCM (https://github.com/NVIDIA/hpc-container-maker/blob/6c984440702525624b71f827d4f5126ce174ab2f/hpccm/building_blocks/nccl.py#L156) only calls `make install`, but since the `install` target only depends on the `lib` target the static library is not created. A possible solution is to make install depends on the `build` target.

**Comment by sjeaugey** [comment]
That sounds like a good idea. I made a PR for that.
