### ISSUE TITLE
About the functionality of ncclWorkElem

### ISSUE THREAD

**Issue by JoeyYoung** [NVIDIA/nccl#665]
Hi all, 

I'm looking into the device implementation of nccl send/recv in sendrecv.h, and I fail to catch some details in the `function __device__ __forceinline__ void run(ncclWork *work)`:
1. Why we need at most 8 work elements to do the send/recv tasks? What does the work element actually do in the communication?
2. I read two lines of code `int nThreadsSegment = args->p2p.nThreads;`, `int nThreadsSplit = (nThreadsSegment - (nThreadsSegment > 128 ? WARP_SIZE : 0))/2;`, and I'm very confused that how threads are managed here, can you kindly give more explanations?

Any suggestions will be helpful, thanks!

**Comment by sjeaugey** [comment]
1. Each CUDA Block = Channel = GPU SM can process send/recv operations from at most 8 peers at once. In that configuration, we split the 512 threads into 16 warps of 32 threads, each warp handling a send or recv from a different peer. If we don't have to communicate with that many peers, we'll use more threads per peer.
2. For send operations we benefit from having an extra warp to perform synchronization while the other warps perform copies. So if we have only 4 peers, i.e. 64 threads (or more) per send, we'll also add 32 threads (1 warp) to the send task.
nThreadsSegment is the number of threads to perform a given send/recv. It can be 64 (32+32), 160 (32+64), 288 (128+160) or 544 (256+288). nThreadsSplit is equal to 32, 64, 128 or 256.

**Comment by JoeyYoung** [comment]
I see, thanks for your detailed explanation!
