### ISSUE TITLE
How to detect the bandwidth when using nccl transfer pytorch tensor?

### ISSUE THREAD

**Issue by timmywanttolearn** [NVIDIA/nccl#669]
Hi.
I am using a linux server and pytorch nccl to transfer pytorch tensor.
I use 'tcp://127.0.0.1:9000' as my init_method and nccl as my backend.
And I use
```
sudo iftop -i lo -n -P
```
to detect bandwidth. lo is the network interface used for loop back address.
How ever I can not detect the bandwidth, what should I do?

**Comment by sjeaugey** [comment]
NCCL communicates through CUDA directly within a system, or through shared memory if direct P2P beween GPUs is not possible. It would not use TCP/IP which has a high latency, a low bandwidth and a high CPU usage.

**Comment by timmywanttolearn** [comment]
> NCCL communicates through CUDA directly within a system, or through shared memory if direct P2P beween GPUs is not possible. It would not use TCP/IP which has a high latency, a low bandwidth and a high CPU usage.

Thank you!
And is there any way to detect nccl transfer bandwidth, please?

**Comment by sjeaugey** [comment]
Those transfers are done fully in hardware (no software involved like for TCP/IP) so unless there are hardware counters on PCI I'm not sure how to see that.

We usually just run the NCCL perf tests to see what performance we're getting out of the hardware.

**Comment by timmywanttolearn** [comment]
> Those transfers are done fully in hardware (no software involved like for TCP/IP) so unless there are hardware counters on PCI I'm not sure how to see that.
> 
> We usually just run the NCCL perf tests to see what performance we're getting out of the hardware.

Thank you very much!
