### ISSUE TITLE
scatter support

### ISSUE THREAD

**Issue by hiyijian** [NVIDIA/nccl#67]
I noticed that there is only ncclReduceScatter, but no ncclSctter(it was commented in header file).

Why is that?

**Comment by sjeaugey** [comment]
NCCL's focus has been on operations where getting the best performance is hard. Scatter, gather and alltoall can all be implemented with a simple for loop of cudaMemcpy and NCCL wouldn't be able to provide better performance. So aside from the convenience of having those operations in NCCL, it brings little value to developers, hence the low priority.

**Comment by hiyijian** [comment]
Thanks
