### ISSUE TITLE
Tree in intra-node comm

### ISSUE THREAD

**Issue by XiaoSong9905** [NVIDIA/nccl#672]
After reading this issue https://github.com/NVIDIA/nccl/issues/448, I'm kind of confused. Can we use tree based collective communication for intra-node ( e.g. within a DGX-1 ) ?  GPU0,1,2,3 subset of DGX-1 ?

**Comment by sjeaugey** [comment]
No, the tree structure is only inter-node. Intra-node it's always a chain.
