### ISSUE TITLE
NCCL Broadcast is much slower than expected

### ISSUE THREAD

**Issue by TarzanZhao** [NVIDIA/nccl#674]
I did some experiments and found that NCCL broadcast is too slower than expected. 

Some experiments results:

- NCCL broadcast transfers 4GB data from (host 0, gpu0)
1. to (host 1, gpu0): 3.3s
2. to (host 1, gpu0~1): 3.7s
3. to (host 1, gpu0~3): 5.7s

- NCCL send/recv transfers 4GB data from (host 0, gpu0)
1. to (host 1, gpu0): 1.4s
2. to (host 1, gpu0~1): 2.8s
3. to (host 1, gpu0~3): 5.6s

- NCCL broadcast transfers 4MB data from (host 0, gpu0) to (host 1, gpu0~3): 4s
- NCCL send/recv transfers 4MB data from (host 0, gpu0) to (host 1, gpu0~3): 0.01s

I compare the speed of NCCL send/recv and broadcast. I use two AWS p3.16xlarge instances, each contains 8 GPUs and NVlink to connect these GPUs.  I use NCCL_ALGO=Ring, NCCL_PROTO=Simple. From the above statistics, we found broadcast is too slow in two cases, one is when transferred data is small, the other is when broadcast group is small(like only two devices)

Something weird that may be useful information: 
1. I open NCCL_DEBUG_SUBSYS=ALL and see "GPU Direct RDMA Disabled for GPU 81000 / HCA 0 (distance 6 > 4)" in log, that means NCCL_NET_GDR_LEVEL=4. But if I set NCCL_NET_GDR_LEVEL=5, the program will become so slow or actually get stuck somewhere. 
2. NCCL_PROTO=Simple gives better speed. I also tested NCCL_PROTO=LL and NCCL_PROTO=LL128, they are even slower.

**Comment by sjeaugey** [comment]
Can you run the broadcast_perf test from the [NCCL perf tests](https://github.com/nvidia/nccl-tests) and provide the output with `NCCL_DEBUG=INFO` ?
```
mpirun -x NCCL_DEBUG=INFO -np 5 -H host0:1,host1:4 ./build/broadcast_test -b 8 -e 4G -f 2
```

That would help us figure out what's going on.
Thanks!

**Comment by TarzanZhao** [comment]
Thanks! Let me try. And I just update the issue, FYI.

**Comment by sjeaugey** [comment]
One more thing actually, make sure to run the test twice. There could be extra time in the first call to any operation when finalizing connections which could make the time look much larger than it would be throughout the life of an application.

**Comment by TarzanZhao** [comment]
That is the problem. Thanks a lot!

> One more thing actually, make sure to run the test twice in your experiments. There could be extra time in the first call to any operation when finalizing connections which could make the time look much larger than it would be throughout the life of an application.
> 
> NCCL perf tests should not suffer from that as they are doing the warmup before benchmarking performance.
