### ISSUE TITLE
NCCL AlltoAll hang at first step, guess caused by zero byte send/recv

### ISSUE THREAD

**Issue by g-ziyan** [NVIDIA/nccl#696]
hi @sjeaugey, 

I noticed that you mentioned "Fix bug with zero-bytes send/recv operations" in [2.12.10](https://github.com/NVIDIA/nccl/commit/353e8ba446cdaadfa730c56d23328b6b912faac9) commit. Could you please clarify how to fix it in 2.11.4 version? This problem may cause my program hangs at alltoall process, and since some other issues I can't update to 2.12.10 directly.

I guess the key fix is in src/group.cc 

![middle_img_v2_28498ef0-eb8a-4162-b194-9915c084a41g](https://user-images.githubusercontent.com/31973481/175874327-f0d9dc06-b643-4b01-bd06-accbe556ddec.jpg)

and tried to patch  
```
 if (sendbytes < 0 || (sendbytes == 0 && totSendBytes != 0)) sendbytes = -1;
 if (recvbytes < 0 || (recvbytes == 0 && totRecvBytes != 0)) recvbytes = -1;
```
in 2.11.4 version. However, it doesn't work. 

I attached my nccl log here. Any suggestion would be grateful. 
[rank0_nccl.log](https://github.com/NVIDIA/nccl/files/8989240/rank0_nccl.log)

**Comment by sjeaugey** [comment]
Can you try this patch instead:
```
diff --git a/src/proxy.cc b/src/proxy.cc
index e5d2eaba..b8725c1d 100644
--- a/src/proxy.cc
+++ b/src/proxy.cc
@@ -386,7 +386,7 @@ ncclResult_t ncclProxyAppendPosted(struct ncclProxyState* state) {
   int commOpCount = op->commOpCount;
   while (op && op->commOpCount == commOpCount) {
     next = op->next;
-    if (op->subs[0].sendbytes) {
+    if (op->subs[0].sendChunkSize) {
       if (prev) prev->next = next;
       else state->postedOps = next;
       op->next = NULL;
```
