### ISSUE TITLE
Self-adaptive datatype in `ncclrecv()`

### ISSUE THREAD

**Issue by AdorableJiang** [NVIDIA/nccl#703]
## Description
In the last few days I suffered from `torch.distributed.recv()` getting the wrong tensor values from `torch.distributed.send()`. And it turns out to be caused by the mismatch tensor `dtype` between `send()` and `recv()`. Please see [#pytorch/pytorch/issues/81545](https://github.com/pytorch/pytorch/issues/81545). Although `nccl` has introduced this feature in its [doc](https://docs.nvidia.com/deeplearning/nccl/user-guide/docs/usage/p2p.html#point-to-point-communication):

> Any point-to-point communication needs two NCCL calls : a call to [ncclSend()](https://docs.nvidia.com/deeplearning/nccl/user-guide/docs/api/p2p.html#c.ncclSend) on one rank and a corresponding [ncclRecv()](https://docs.nvidia.com/deeplearning/nccl/user-guide/docs/api/p2p.html#c.ncclRecv) on the other rank, ___with the same count and data type___.

`PyTorch` says nothing about this in its [doc](https://pytorch.org/docs/stable/distributed.html#torch.distributed.send).

Besides, I am not the only one who encontered this problem.

> Got wrong tensor when using dist.send to send tensors - distributed - PyTorch Forums
> https://discuss.pytorch.org/t/got-wrong-tensor-when-using-dist-send-to-send-tensors/151812

## Expectation

In practice, the users may be aware of that they are going to tansfer a e.g. `float` type data, but can be hard or just inconvenient to know exactly the data type is `float16`, `float32`, or `float64`. 

Is it possible to implement an overloading of
```c++
ncclRecv(recvbuff, recvcount, recvtype, peer, comm, stream)
```
that looks like 
```c++
ncclRecv(recvbuff, recvcount, peer, comm, stream)
```
which does not require `recvtype` but acquire it from `sendtype` of `ncclSend()`. And cast `recvbuff` to `sendtype` automatically.

**Comment by sjeaugey** [comment]
The NCCL API is currently a C API, not C++. So we can't do overloading.

Now, from what you describe, this is a compile-time issue, not a runtime issue. So you should be able to implement those very easily; something like:
```
// Automatic datatype based on buffer type
ncclResult_t ncclRecv(float* recvbuff, float* recvcount, int peer, ncclComm_t comm, cudaStream_t stream) {
  return ncclRecv(recvbuff, recvcount, ncclFloat, peer, comm, stream);
}
ncclResult_t ncclRecv(half* recvbuff, half* recvcount, int peer, ncclComm_t comm, cudaStream_t stream) {
  return ncclRecv(recvbuff, recvcount, ncclHalf, peer, comm, stream);
}
ncclResult_t ncclRecv(double* recvbuff, double* recvcount, int peer, ncclComm_t comm, cudaStream_t stream) {
  return ncclRecv(recvbuff, recvcount, ncclDouble, peer, comm, stream);
}
```

**Comment by AdorableJiang** [comment]
Thanks for your suggestion.
