### ISSUE TITLE
Unexpected use of SIGUSR1

### ISSUE THREAD

**Issue by jrapin** [NVIDIA/nccl#704]
Hi,
Latest version of NCCL catches SIGUR1:
https://github.com/NVIDIA/nccl/blob/19ab67d1727d337d10d0a48cbaf5cd119b8d88f1/src/proxy.cc#L655

This is unexpected as a user. For instance, in our case many training pipelines rely on slurm cluster sending a usr1 signal as a preemption notification, but with the latest version the signal is caught and therefore hidden by NCCL. Fortunately we could trace it back thanks to the `ACTIVE OPS` print that appends when catching the signal, otherwise it would have been hard to figure out what was hiding it from us.

Would it be possible to avoid catching the signal as a default behavior, since this is monopolizing 1 of the only 2 user signals available and can easily interfere with other tools?

Thank you!

**Comment by AddyLaddy** [comment]
Thanks for reporting this issue. A fix has already been applied in the next release of NCCL:
```
diff --git a/src/proxy.cc b/src/proxy.cc
index c35efe5f..26b732b5 100644
--- a/src/proxy.cc
+++ b/src/proxy.cc
@@ -641,6 +641,9 @@ ncclResult_t ncclSetThreadContext(struct ncclComm* comm) {
   return ncclSuccess;
 }
 
+// Set to SIGUSR1 or SIGUSR2 to help debug proxy state during hangs
+NCCL_PARAM(ProxyDumpSignal, "PROXY_DUMP_SIGNAL", -1);
+
 void* ncclProxyProgress(void *comm_) {
   struct ncclComm* comm = (struct ncclComm*)comm_;
   if (ncclSetThreadContext(comm) != ncclSuccess) {
@@ -652,7 +655,8 @@ void* ncclProxyProgress(void *comm_) {
 
   struct ncclProxyProgressState* state = &comm->proxyState.progressState;
   state->nextOps = -1;
-  signal(SIGUSR1, ncclDumpProxyState);
+  const int sig = ncclParamProxyDumpSignal();
+  if (sig != -1) signal(sig, ncclDumpProxyState);
   ncclLastProxyState = state;
   char threadName[NCCL_THREAD_NAMELEN];
   snprintf(threadName, NCCL_THREAD_NAMELEN, "NCCL Progress%2d", comm->cudaDev);
```

**Comment by jrapin** [comment]
Thanks for solving this!
