### ISSUE TITLE
Nsight profiling shows Send&Recv Kernel called for Allreduce with NCCL 2.13

### ISSUE THREAD

**Issue by szhengac** [NVIDIA/nccl#714]
When I used nsys to profile my pytorch job, I found all the NCCL kernels are send and recv, while allgather, reduce-scatter, and allreduce all disappear. So I did profiling again for nccl-test too, and I obtained the same result. Are all the NCCL kernels replaced with send and recv in NCCL 2.13? I am using CUDA 11.7.

<img width="1023" alt="Screen Shot 2022-08-17 at 1 34 21 PM" src="https://user-images.githubusercontent.com/3960020/185237840-e43eb6d0-e366-4cc2-81d6-8fb33defedb0.png">

**Comment by AddyLaddy** [comment]
The kernel names in NCCL 2.13 are not related to the actual collective function being called.
This has been partially resolved in the next release of NCCL, but in general it is unreliable to use the NCCL kernel name to understand what operation NCCL is running as each kernel could execute multiple difference functions e.g. when operations are grouped together.

**Comment by szhengac** [comment]
@AddyLaddy Thanks for your prompt response. Do you know when will the next release be out?

**Comment by AddyLaddy** [comment]
It's undergoing final QA currently. Hopefully we'll be able to release it very shortly

**Comment by AddyLaddy** [comment]
A preview branch of NCCL 2.14.3 has just been pushed here.

**Comment by szhengac** [comment]
@AddyLaddy thanks! is there any doc describing the new features of this release?

**Comment by AddyLaddy** [comment]
So no, there will be release notes and documentation updates with the official NCCL 2.14.3 release on the Nvidia download site.
The commit comments are all that you have at the moment.

-Addy

**Comment by sjeaugey** [comment]
The PR also has a brief description of the new features.
