### ISSUE TITLE
NCCL data corruption with GPUDirect RDMA on EFA

### ISSUE THREAD

**Issue by crowsonkb** [NVIDIA/nccl#716]
We are seeing data corruption similar to https://github.com/NVIDIA/nccl/issues/133 with GPUDirect RDMA on EFA. We have 8x A100 instances (AWS p4d.24xlarge) connected with Amazon EFA and we are seeing the following problem:

- Data corruption (Inf/NaN) during PyTorch model training
- The data corruption does not happen when training on a single p4d.24xlarge instance.
- The data corruption happens during an allreduce, there are no Inf/NaN on any GPUs before the allreduce, but often there will be Inf/NaN after an allreduce.
- The data corruption does not happen when EFA is disabled and the traffic goes over TCP instead.
- The data corruption does not happen when `NCCL_NET_GDR_LEVEL=LOC` is set.

Here are our library versions:

From `nvidia-smi`: `NVIDIA-SMI 470.129.06   Driver Version: 470.129.06   CUDA Version: 11.4`
PyTorch version: `1.12.0+cu113`
PyTorch NCCL version: `(2, 10, 3)`
`LD_PRELOAD` NCCL version (we `LD_PRELOAD` this custom Amazon NCCL to make EFA work): 2.12.7
PyTorch CUDA version: 11.3

**Comment by rashikakheria** [comment]
@crowsonkb Could you share your command line with us? If you haven't gone through our official documentation: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/efa-start-nccl-base.html#nccl-start-base-test, we only recommend using `-x NCCL_PROTO=simple` with EFA in order to avoid data corruption.

**Comment by crowsonkb** [comment]
> @crowsonkb Could you share your command line with us? If you haven't gone through our official documentation: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/efa-start-nccl-base.html#nccl-start-base-test, we only recommend using `-x NCCL_PROTO=simple` with EFA in order to avoid data corruption.

Thank you, that worked!

**Comment by david-macleod** [comment]
@crowsonkb could I just ask whether this issue happened every time all_reduce was called, or only intermittently? (trying to figure out if we are seeing the same issue)

**Comment by Quentin-Anthony** [comment]
> @crowsonkb could I just ask whether this issue happened every time all_reduce was called, or only intermittently? (trying to figure out if we are seeing the same issue)

@crowsonkb and I faced this intermittently, but very often.

**Comment by rderp** [comment]
@bwbarrett is there a reference for the performance to expect with P4de for smaller size nccl ops?. We are seeing what we think is bad performance with 16 nodes (128 GPUs) for all gathers (512 bytes per rank). Did the fact that the hardware doesn't support anything but SIMPLE severely limit the performance here?
