### ISSUE TITLE
How the memory copy works between node？

### ISSUE THREAD

**Issue by Dominic-ZZ** [NVIDIA/nccl#717]
I have been studying the NCCL source code recently and have some questions about how NCCL implements communication between different nodes. I saw the collectives/device/common.h and broadcast.h, there is a topology (ring or tree) for the realization of communication. But it looks like it's only in one node, and I didn't find any GDR-related variables or APIs in it. Where is the communication between different nodes implemented? How does data get from one node to another?

**Comment by sjeaugey** [comment]
The network communication is done thanks to the network send proxy which mimics the next GPU but instead sends the data in the FIFO through the network, towards a network receive proxy which will receive data in the next GPU's FIFO. The next GPU will also not "know" that the data was not written directly by the previous GPU but by the NIC.

The network code is in src/transport/net.cc.

**Comment by Dominic-ZZ** [comment]
I found it, thanks a lot
