### ISSUE TITLE
Can NCCL auto-detect correct IB_GID_INDEX?

### ISSUE THREAD

**Issue by void-main** [NVIDIA/nccl#718]
In our environment (k8s + rdma_device_plugin), we ran into a case where different pods have different `IB_GID_INDEX`. For example, in our 4 node training job, 2 machines have INDEX set to `4` and `5`, however,  for the other machines, the INDEX are `6` and `7`. 
In our training job, we set `NCCL_IB_GID_INDEX` to `5` for all the machines, which caused machines with `6` and `7` index to report error: `[0] misc/ibvwrap.cc:284 NCCL WARN Call to ibv_modify_qp failed with error No such device` (because of the wrong `IB_GID_INDEX`).

Our question is: 
1. Does nccl assume same `IB_GID_INDEX` for processes in the same node?
2. Are there any environment variables that we could set to let nccl auto-detect the correct IB_GID_INDEX?

**Comment by sjeaugey** [comment]
No we don't have a way to autodetect the GID. One solution is to run a script at startup to write "NCCL_GID_INDEX=X" in /etc/nccl.conf, using show_gids to find which gid has the IP address you want to use.

**Comment by void-main** [comment]
@sjeaugey got it, thanks!
