### ISSUE TITLE
double gtx680 cuda8.0 ubuntu14.04LTS

### ISSUE THREAD

**Issue by zengraoli** [NVIDIA/nccl#72]
I followed the instructions from the readme, but I can't get the tests to run.
Is someone help me?

my options:
1、git clone https://github.com/NVIDIA/nccl.git
2、cd nccl
3、sudo make CUDA_HOME=/usr/local/cuda-8.0 test
4、sudo make install
4、export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:./build/lib

and then：
sudo ./build/test/single/all_reduce_test 10000000

tips：
./build/test/single/all_reduce_test: error while loading shared libraries: libnccl.so.1: cannot open shared object file: No such file or directory

but：
zengraoli@zengraoli-desktop:~/dl/nccl$ ll /usr/local/lib/libnccl.so*
lrwxrwxrwx 1 root root       12  3月  4 18:51 /usr/local/lib/libnccl.so -> libnccl.so.1*
lrwxrwxrwx 1 root root       16  3月  4 18:51 /usr/local/lib/libnccl.so.1 -> libnccl.so.1.3.3*
-rwxr-xr-x 1 root root 23126897  3月  4 18:51 /usr/local/lib/libnccl.so.1.3.3*
zengraoli@zengraoli-desktop:~/dl/nccl$

**Comment by zengraoli** [comment]
oh my carelessness！

**Comment by zengraoli** [comment]
The message you get ("invalid device function") means that one of the GPU cannot execute the compiled code.

Indeed, the GTX760 has a compute capability of 3.0 (https://developer.nvidia.com/cuda-gpus), and the default NVCC_GENCODE in the Makefile only compiles for 3.5 and later.

In the Makefile recompile with :
NVCC_GENCODE="-gencode=arch=compute_30,code=sm_30 -gencode=arch=compute_52,code=sm_52"

then copy build lib to /usr/lib

It work!

**Comment by sjeaugey** [comment]
You can also set your LD_LIBRARY_PATH instead of installing in /usr/lib :
```
export LD_LIBRARY_PATH=$PWD/build/lib:$LD_LIBRARY_PATH
./build/test/single/all_reduce_test <size>
```
