### ISSUE TITLE
In single node with 8*3090，why the performance of nccl 2.8.3 is around 10% slower than 2.7.8.

### ISSUE THREAD

**Issue by TonyWu199** [NVIDIA/nccl#721]
I use the **nccl-tests** for testing the performance of **nccl 2.7.8** and **nccl 2.8.3** in 8*3090 of single machine. 
But **nccl 2.8.3** is 10% slower than **nccl 2.7.8**.

My running command is 
```
mpirun --allow-run-as-root -np 8 -npernode 8 -hostfile <path-to-hostfile> -mca btl_tcp_if_include eth0 -x LD_PRELOAD=<path-to-libnccl.so> -x PATH ./build/all_reduce_perf -b 16M -e 20M -w 10 -n 100 -g 1
``` 

The nccl 2.7.8 in nccl-tests
![image](https://user-images.githubusercontent.com/22834799/190141412-b82b6ed5-466a-4f43-a896-3cc4a5fbc44e.png)

The nccl 2.8.3 in nccl-tests
![image](https://user-images.githubusercontent.com/22834799/190141517-36b562df-61ab-4a11-9a6d-6ccc63e3bc21.png)

**Comment by sjeaugey** [comment]
Can you try with NCCL 2.14.3? Also the difference I see in your trace seems to be just over 5%. Not sure it's going to make any visible difference on a real application.

In any case, your performance is pretty low overall, but I guess this is with all GPUs connected directly to the CPUs, meaning that with 8 GPUs you have 5 bidirectional flows in and out of each CPU, so it could be normal.

Do you know what your NPS(Numa Per Socket) setting is in your BIOS? Could be worth trying setting it to 4 if not already.

**Comment by TonyWu199** [comment]
@sjeaugey, first thanks for such a quick reply. 
I tried NCCL 2.14.3 and got the below result in the same settings as before.
![image](https://user-images.githubusercontent.com/22834799/190157161-4624e7fb-9fa6-4e8c-a32e-e0ac9d480af1.png)

I use `lscpu` command and get the NUMA info as 
![image](https://user-images.githubusercontent.com/22834799/190157307-bf77ae48-46b4-4448-851b-9019d89a16b3.png)
Is the NUMA setting normal? It seems to be 4 in my machine as your comment.

**Comment by sjeaugey** [comment]
Thanks, so no big change.

How many sockets do you have on your system? I would imagine 2 if you have 8 GPUs (unless there are PCI switches?) in which case 4 NUMA nodes may mean you are in NPS=2 mode.

**Comment by sjeaugey** [comment]
Yes probably we made a change in 2.8 which was better in most situations but slightly worse in your case. It's a small regression though.

I would still try to set NPS=4. Also, are you running with `mpirun --bind-to numa`? That can help quite a lot.

**Comment by TonyWu199** [comment]
I tried the same code in `V100`, and **NCCL 2.8.3** surpasses **NCCL 2.7.8** with no doubt (5% gain).
Besides, I also tried to use `mpirun --bind-to numa` in 3090 and got nearly the same results as before.

**Comment by TonyWu199** [comment]
I read the patch from 2.7.8 to 2.8.3, is the problem caused by  `Use shared buffers for inter-node send/recv.` in 3090？

**Comment by sjeaugey** [comment]
> I read the patch from 2.7.8 to 2.8.3, is the problem caused by Use shared buffers for inter-node send/recv. in 3090？

I doubt it; shared buffers is for send/recv, and you are running all_reduce.
