### ISSUE TITLE
Does NCCL populate the L2 cache?

### ISSUE THREAD

**Issue by jaywonchung** [NVIDIA/nccl#729]
Hi,

I was wondering if NCCL P2P communication (received with `ncclRecv`) immediately populates the L2 cache together with VRAM, just like how [`cudaMemcpy` from host to device goes through the L2 cache](https://forums.developer.nvidia.com/t/cudamemcpy-and-l2-cache/42817).

Also, when one `ncclRecv` and one `ncclSend` are grouped with `ncclGroupStart` and `ncclGroupEnd` to exchange data in different buffers between two devices, will the received data for both ranks reside in the L2 cache, assuming that it will fit?

Thanks a lot.

**Comment by sjeaugey** [comment]
I would think so, given NCCL uses the SM to copy data to the user buffer; data should be in L2 (unless other concurrent work empties it). I don't see why performing a concurrent sendrecv would make any difference, so I'd think it's also the case for a symmetric sendrecv.

**Comment by jaywonchung** [comment]
Thanks for the quick reply! For grouped sendrecv, I was thinking of a situation like this:

1. NCCL kernel receives data from the other rank. Received data is in L2.
2. NCCL kernel reads in data to send to the other rank. Received data is evicted from L2 and replaced with data to send.
3. NCCL kernel sends data to the other rank.

Would this happen?

**Comment by sjeaugey** [comment]
Send and receive happen concurrently. Now indeed if the receive happens early (because the sender is ready) but the send is blocked and starts later, then the send operation would evict data from L2.

That said, the question is only relevant if the send size is equal to the size of the L2 Cache. If the size is smaller and both fit, then both will be in L2. If they are larger then in any case you won't have all the data in L2.

**Comment by jaywonchung** [comment]
That makes a lot of sense. Thanks a lot for the great answer!

**Comment by Graham1025** [comment]
> Send and receive happen concurrently. Now indeed if the receive happens early (because the sender is ready) but the send is blocked and starts later, then the send operation would evict data from L2.
> 
> That said, the question is only relevant if the send size is equal to the size of the L2 Cache. If the size is smaller and both fit, then both will be in L2. If they are larger then in any case you won't have all the data in L2.

@sjeaugey I am wondering if there are any environment variables that can be used to control skipping L2

**Comment by jbachan** [comment]
No env cars exist. NCCL could play with using non-evicting load instructions. It isn't convenient for me to check at the moment, but that could be the behavior already with how the SM handles the volatile loads we issue. Ideally ncclSend should read the user data to send using non-evicting loads that only populate registers.

**Comment by Graham1025** [comment]
> No env cars exist. NCCL could play with using non-evicting load instructions. It isn't convenient for me to check at the moment, but that could be the behavior already with how the SM handles the volatile loads we issue. Ideally ncclSend should read the user data to send using non-evicting loads that only populate registers.

Thanks a lot for your reply. By the way，if I want to skip L2 cache when doing communications with nccl，should I use PTX in nccl device kernel function ?
