### ISSUE TITLE
nonblocking group call gives incorrect result (possible user error)

### ISSUE THREAD

**Issue by manauref** [NVIDIA/nccl#732]
Dear NCCL team,

I'm trying to test the nonblocking group call option in a simple test that assumes 2 MPI processes with a GPU each, and I simply want to send an 8-element array (0,1,2,...,7) from rank 0 to rank 1. The communicator is created as indicated in the docs:
```
  ncclComm_t d_comm;
  ncclResult_t state;
  ncclConfig_t config = NCCL_CONFIG_INITIALIZER;
  config.blocking = 0;
  NCCLCHECK(ncclCommInitRankConfig(&d_comm, nRanks, id, myRank, &config));
  if (config.blocking == 0) {
    do {
      NCCLCHECK(ncclCommGetAsyncError(d_comm, &state));
    } while(state == ncclSuccess);
  }
```
and the communication is done as follows

```
  ncclGroupStart();

  if (myRank == 0)
    ncclSend(sendbuff, size, ncclInt, 1, d_comm, d_stream);
  if (myRank == 1)
    ncclRecv(recvbuff, size, ncclInt, 0, d_comm, d_stream);

  ncclResult_t group_state = ncclGroupEnd();

  if (config.blocking == 0) {
    if (group_state == ncclInProgress) {
      do {
        ncclCommGetAsyncError(d_comm, &state);
      } while (state == ncclInProgress);
    }
  }

  cudaStreamSynchronize(d_stream);

  cudaMemcpy(host, recvbuff, size * sizeof(int),cudaMemcpyDeviceToHost);
```

The full code is attached below. At the end of the program I print out the ranks and the host array. The expected answer is
```
myRank:1 | host after=0,1,2,3,4,5,6,7,
```
but instead the resulting host array in rank 1 is all zeros, i.e.
```
myRank:1 | host after=0,0,0,0,0,0,0,0,
```

If one instead creates a blocking communicator by using 
```
  config.blocking = 1;
```
the produces the expected result.

***Questions:***
1. Am I using the nonblocking group call option correctly?
2. Are nonblocking group calls actually available? I find no examples online and the nccl-tests repo doesn't have a test for them.
3. Could it have something to do with my NCCL installation?

Setting ```export NCCL_DEBUG=VERSION``` I get ```NCCL version 2.14.3+cuda11.7```.
TIA

[ncclSendRecv.cpp.zip](https://github.com/NVIDIA/nccl/files/9771247/ncclSendRecv.cpp.zip)

**Comment by sjeaugey** [comment]
There is a bug here:
```
if (config.blocking == 0) {
  do {
    NCCLCHECK(ncclCommGetAsyncError(d_comm, &state));
  } while(state == ncclSuccess);
}
```
You should poll while state is `ncclInProgress`, not `ncclSuccess`.

If you check the return code of `ncclGroupStart`/`ncclSend`/`ncclRecv` you'll get `ncclInvalidUsage` and the NCCL call will have no effect. Running with `NCCL_DEBUG=WARN` also prints errors like:
```
WARN Attempt to use communicator before the previous operation returned ncclSuccess
```

To make sure it is clear, the non-blocking option is only about preventing NCCL calls from blocking on the **CPU side**. It has no impact on the NCCL communication execution on the GPU side. Not blocking on the CPU side is important for fault tolerance, as it allows to cancel/abort any operation which could hang or which we just want to abort as we're tearing down a communicator.

**Comment by sjeaugey** [comment]
> If I may, I suggest making this change in the docs as well
:facepalm: apologies for that. Thanks for pointing it out.

>  Is it ok to place the send and recv in separate group calls
In this case, each rank only performs one operation (either a send or a recv). So group calls serve no purpose. If you needed to perform a sendrecv between the two ranks, i.e. each rank performs a send and a recv, exchanging data, then you would need to group them as a single operation progressing both the send and recv at the same time.

**Comment by manauref** [comment]
Thank you for your time.
