### ISSUE TITLE
sendbuff logged as nil for P2P send

### ISSUE THREAD

**Issue by kwen2501** [NVIDIA/nccl#734]
Hi team, I notice that the `sendbuff` is logged as nil while the actual address could have been logged as `recvbuff`, for a send operation.
```
NCCL INFO Send: opCount 0 sendbuff (nil) recvbuff 0x7ff818efb800 count 257536 datatype 7 op 0 root 1 comm 0x7ff73c00d690 [nranks=2] stream 0x7ff8e08f07d0
```
I believe this is due to the following block of code:
https://github.com/NVIDIA/nccl/blob/master/src/enqueue.cc#L342-L347

Although, I tend to think that there may be specific reason for setting the `sendbuff` to `nullptr` while creating `ncclInfo`. 

The log is from NCCL 2.14.3.

**Comment by sjeaugey** [comment]
Indeed, for send/recv operations, we use only recvbuff as "buff". We just didn't add a send/recv specific INFO format (that can also help with parsing).

**Comment by kwen2501** [comment]
I see, thanks! Closing.
