### ISSUE TITLE
Questions on NCCL optimized for NVLink

### ISSUE THREAD

**Issue by roywei** [NVIDIA/nccl#735]
Hi NCCL community,

I was doing some benchmark using PyTorch and found out that PyTorch using NCCL in  Nvidia NGC container is faster than PyTorch using open source NCCL on intra-node comm.
I noticed in the release note, NGC container is using NCCL optimized for NVLink
https://docs.nvidia.com/deeplearning/frameworks/pytorch-release-notes/rel_22-03.html#rel_22-03

When I train Megatron LM and compare the performance,
NGC NCCL is around 5% faster than PyTorch compiled with OSS NCCL of same version on single node.

This this a closed source implementation of NCCL? Is is possible we utilize this NCCL outside of NGC?
Or is my configuration wrong and the perf diff come from something else?

Any insights are helpful, thanks!

**Comment by sjeaugey** [comment]
That's not expected. The NCCL version in NGC should be the exact same as the open-source version.

Now maybe the container has other settings (/etc/nccl.conf?) or some other PyTorch patches which are not upstreamed yet? 

It's the first time I hear that, but on the other hand, the point of NGC containers is to bring the best performance without the hassle of putting everything together correctly.

**Comment by roywei** [comment]
Thank for the info! After some profiling and running nccl-tests, I can confirm the nccl speed and allreduce speed is the same as open source version. (I got confused by the optimized for NVLink statement in the release note).
The speed advantage seems to come from forward and backward time diff, collective comm speed are the same. Thanks!

```
iteration      600/     800 | consumed samples:         4800 | elapsed time per iteration (ms): 437.3 | learning rate: 2.733E-05 | global batch size:     8 | lm loss: 6.766993E+00 | loss scale: 65536.0 | grad norm: 1.671 | number of skipped iterations:   0 | nu
mber of nan iterations:   0 |
7: time (ms) | forward-compute: 117.89 | backward-compute: 278.99 | backward-params-all-reduce: 1.87 | backward-layernorm-all-reduce: 0.01 | backward-embedding-all-reduce: 0.02 | backward-reduce-model-grads: 1.94 | backward-gather-model-params: 0.01 | optimizer-cop


iteration      600/     800 | consumed samples:         4800 | elapsed time per iteration (ms): 451.7 | learning rate: 2.733E-05 | global batch size:     8 | lm loss: 6.767890E+00 | loss scale: 65536.0 | grad norm: 1.687 | number of skipped iterations:   0 | number of nan iterations:   0 |
7: time (ms) | forward-compute: 120.25 | backward-compute: 290.83 | backward-params-all-reduce: 1.87 | backward-layernorm-all-reduce: 0.01 | backward-embedding-all-reduce: 0.02 | backward-reduce-model-grads: 1.94 | backward-gather-model-params: 0.01 | optimizer-copy-to-main-grad: 4.85 | optimizer-unscale-and-check-inf: 4.91 | optimizer-clip-main-grad: 7.58 | optimizer-count-zeros: 0.01 | optimizer-inner-step: 14.71 | optimizer-copy-main-to-model-params: 5.20 | optimizer: 37.35 | batch-generator: 1.44
```
