### ISSUE TITLE
Any reason not setting NCCL_GRAPH_REGISTER=1 as default?

### ISSUE THREAD

**Issue by janilbols-w** [NVIDIA/nccl#738]
Hi team, 
The question, as title, pop up when i read the description in doc. 

From my point of view, NCCL_GRAPH_REGISTER=1 is an optimization to reduce memory copy.
Is there any reason for not using this optimizaion?

It is mentioned, "user buffers will be automatically de-registered when the CUDA Graphs are destroyed", which is buffer safty 
 the biggest concern? How bad will it cause?

Cheers

**Comment by jbachan** [comment]
We have no reason to believe this shouldn't be set to as enabled by default and are looking into making it so.

**Comment by janilbols-w** [comment]
thanks for the reply, got my answer

Cheers
