### ISSUE TITLE
ncclKernel_SendRecv_RING is profiled when training models from torchvision.models

### ISSUE THREAD

**Issue by JoeyYoung** [NVIDIA/nccl#739]
Hi All,

I found something weird.
I have a standard script as follows, which uses models from torchvision module. The testbed is one server with 4 GPUs. Latest nccl is used.

``` python
import torchvision.models as models

def init_processes(backend):
    dist.init_process_group(backend, rank=WORLD_RANK, world_size=WORLD_SIZE)
    torch.cuda.set_device(LOCAL_RANK)
    model = models.resnet18().to(LOCAL_RANK)
    ddp_model = DDP(model, device_ids=[LOCAL_RANK], output_device=LOCAL_RANK) 
    loss_fn = nn.CrossEntropyLoss()
    optimizer = optim.SGD(ddp_model.parameters(), lr=0.001)

    with torch.profiler.profile(
        on_trace_ready=torch.profiler.tensorboard_trace_handler("./proflog_naive"),
    ) as profiler:
        for i in range(2):
            inputs = torch.randn(64, 3, 224, 224).to(LOCAL_RANK)
            labels = torch.randint(0, 1, [64]).to(LOCAL_RANK)
            outputs = ddp_model(inputs)
            loss = loss_fn(outputs, labels)

            optimizer.zero_grad()
            loss.backward()
            optimizer.step()
            profiler.step()

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--backend", type=str, default="nccl", choices=['nccl', 'gloo'])
    args = parser.parse_args()

    init_processes(backend=args.backend)
```

When I profile its running timeline (with nvprofiler, torch profiler), the GPU timeline showing `ncclKernel_SendRecv_RING_SIMPLE_Sum_int8_t(ncclDevComm*, unsigned long, ncclWork*) ` kernels instead of allreduce kernels as expected:

<img width="846" alt="image" src="https://user-images.githubusercontent.com/28895626/197817644-55a52f66-7447-4e7f-b2a7-3706c5fb18af.png">
preceding events are:
<img width="561" alt="image" src="https://user-images.githubusercontent.com/28895626/197817834-f0aa76dc-f563-4fe9-b9da-a9a3a2cc5640.png">

However, the nccl trace, which I print out with `NCCL_DEBUG=INFO NCCL_DEBUG_SUBSYS=INIT,COLL,P2P,NET,ENV` enabled, shows that:
```
net-g16:461179:461302 [0] NCCL INFO AllReduce: opCount b sendbuff 0x7fc390240000 recvbuff 0x7fc390240000 count 513000 datatype 7 op 0 root 0 comm 0x7fc4bc004c70 [nranks=4] stream 0x5577b986dcf0
net-g16:461179:461302 [0] NCCL INFO AllReduce: opCount c sendbuff 0x7fc394000000 recvbuff 0x7fc394000000 count 7213056 datatype 7 op 0 root 0 comm 0x7fc4bc004c70 [nranks=4] stream 0x5577b986dcf0
net-g16:461179:461302 [0] NCCL INFO AllReduce: opCount d sendbuff 0x7fc36a000000 recvbuff 0x7fc36a000000 count 3963456 datatype 7 op 0 root 0 comm 0x7fc4bc004c70 [nranks=4] stream 0x5577b986dcf0
net-g16:461180:461180 [1] NCCL INFO Broadcast: opCount 7 sendbuff 0x7f9269db0c00 recvbuff 0x7f9269db0c00 count 252 datatype 0 op 0 root 0 comm 0x7f921c004c70 [nranks=4] stream 0x55fc3f400c80
net-g16:461182:461182 [3] NCCL INFO Broadcast: opCount 7 sendbuff 0x7f87c5db0c00 recvbuff 0x7f87c5db0c00 count 252 datatype 0 op 0 root 0 comm 0x7f8778004c70 [nranks=4] stream 0x55d585d60500
net-g16:461181:461181 [2] NCCL INFO Broadcast: opCount 8 sendbuff 0x7fd259db0e00 recvbuff 0x7fd259db0e00 count 12 datatype 0 op 0 root 0 comm 0x7fd208004c70 [nranks=4] stream 0x5573ed419430
net-g16:461180:461180 [1] NCCL INFO Broadcast: opCount 8 sendbuff 0x7f9269db0e00 recvbuff 0x7f9269db0e00 count 12 datatype 0 op 0 root 0 comm 0x7f921c004c70 [nranks=4] stream 0x55fc3f400c80
net-g16:461182:461182 [3] NCCL INFO Broadcast: opCount 8 sendbuff 0x7f87c5db0e00 recvbuff 0x7f87c5db0e00 count 12 datatype 0 op 0 root 0 comm 0x7f8778004c70 [nranks=4] stream 0x55d585d60500
net-g16:461181:461181 [2] NCCL INFO Broadcast: opCount 9 sendbuff 0x7fd0d1fe8000 recvbuff 0x7fd0d1fe8000 count 38400 datatype 0 op 0 root 0 comm 0x7fd208004c70 [nranks=4] stream 0x5573ed419430
net-g16:461180:461180 [1] NCCL INFO Broadcast: opCount 9 sendbuff 0x7f90ddfe8000 recvbuff 0x7f90ddfe8000 count 38400 datatype 0 op 0 root 0 comm 0x7f921c004c70 [nranks=4] stream 0x55fc3f400c80
net-g16:461180:461180 [1] NCCL INFO Broadcast: opCount a sendbuff 0x7f9269db0c00 recvbuff 0x7f9269db0c00 count 160 datatype 0 op 0 root 0 comm 0x7f921c004c70 [nranks=4] stream 0x55fc3f400c80
net-g16:461181:461181 [2] NCCL INFO Broadcast: opCount a sendbuff 0x7fd259db0c00 recvbuff 0x7fd259db0c00 count 160 datatype 0 op 0 root 0 comm 0x7fd208004c70 [nranks=4] stream 0x5573ed419430
net-g16:461182:461182 [3] NCCL INFO Broadcast: opCount 9 sendbuff 0x7f8645fe8000 recvbuff 0x7f8645fe8000 count 38400 datatype 0 op 0 root 0 comm 0x7f8778004c70 [nranks=4] stream 0x55d585d60500
net-g16:461182:461182 [3] NCCL INFO Broadcast: opCount a sendbuff 0x7f87c5db0c00 recvbuff 0x7f87c5db0c00 count 160 datatype 0 op 0 root 0 comm 0x7f8778004c70 [nranks=4] stream 0x55d585d60500
net-g16:461181:461311 [2] NCCL INFO AllReduce: opCount b sendbuff 0x7fd0d2240000 recvbuff 0x7fd0d2240000 count 513000 datatype 7 op 0 root 0 comm 0x7fd208004c70 [nranks=4] stream 0x5573ed419430
net-g16:461180:461317 [1] NCCL INFO AllReduce: opCount b sendbuff 0x7f90de240000 recvbuff 0x7f90de240000 count 513000 datatype 7 op 0 root 0 comm 0x7f921c004c70 [nranks=4] stream 0x55fc3f400c80
net-g16:461182:461323 [3] NCCL INFO AllReduce: opCount b sendbuff 0x7f8644240000 recvbuff 0x7f8644240000 count 513000 datatype 7 op 0 root 0 comm 0x7f8778004c70 [nranks=4] stream 0x55d585d60500
net-g16:461181:461311 [2] NCCL INFO AllReduce: opCount c sendbuff 0x7fd0d6000000 recvbuff 0x7fd0d6000000 count 7213056 datatype 7 op 0 root 0 comm 0x7fd208004c70 [nranks=4] stream 0x5573ed419430
net-g16:461182:461323 [3] NCCL INFO AllReduce: opCount c sendbuff 0x7f8648000000 recvbuff 0x7f8648000000 count 7213056 datatype 7 op 0 root 0 comm 0x7f8778004c70 [nranks=4] stream 0x55d585d60500
net-g16:461180:461317 [1] NCCL INFO AllReduce: opCount c sendbuff 0x7f90e2000000 recvbuff 0x7f90e2000000 count 7213056 datatype 7 op 0 root 0 comm 0x7f921c004c70 [nranks=4] stream 0x55fc3f400c80
net-g16:461182:461323 [3] NCCL INFO AllReduce: opCount d sendbuff 0x7f861e000000 recvbuff 0x7f861e000000 count 3963456 datatype 7 op 0 root 0 comm 0x7f8778004c70 [nranks=4] stream 0x55d585d60500
net-g16:461181:461311 [2] NCCL INFO AllReduce: opCount d sendbuff 0x7fd0be000000 recvbuff 0x7fd0be000000 count 3963456 datatype 7 op 0 root 0 comm 0x7fd208004c70 [nranks=4] stream 0x5573ed419430
net-g16:461180:461317 [1] NCCL INFO AllReduce: opCount d sendbuff 0x7f90ca000000 recvbuff 0x7f90ca000000 count 3963456 datatype 7 op 0 root 0 comm 0x7f921c004c70 [nranks=4] stream 0x55fc3f400c80
```
Seems clearly allreduce() is triggered, so why only sendrecv kernels are profiled in the timeline?

What's more, when I use a self-defined model (like below) to train instead of models imported from torchvision, allreduce kernels can be profiled as expected. 
``` python
class ToyModel(nn.Module):
    def __init__(self):
        super(ToyModel, self).__init__()
        self.net1 = nn.Linear(10, 10)
        self.relu = nn.ReLU()
        self.net2 = nn.Linear(10, 5)

    def forward(self, x):
        return self.net2(self.relu(self.net1(x)))
```
It's very weird and troubles me a lot since I don't think the way of how we define a model will affect the behavior of the communication backend. Are there any suggestions?

Thanks in advance!

**Comment by AddyLaddy** [comment]
The misnaming of the NCCL kernels has now been fixed in the newer releases

**Comment by JoeyYoung** [comment]
Thanks for your reminder @AddyLaddy. Just wonder whether it is only a misnaming problem, other profiling results, e.g., grid size, kernel duration, triggered time are all correct?

**Comment by sjeaugey** [comment]
Yes all the rest is correct. And in fact, it was not really a bug, just a change we reverted because it was confusing for users. This `ncclKernel_SendRecv_RING` kernel can be seen as `ncclGenericKernel_For_Non-Inlined_Operations`. Most operations are not inlined, so we just launch any nccl kernel, which will read a `workElem` struct to know what operation(s) to perform and will call the appropriate nccl function.

Hence, since NCCL 2.2, a single kernel can run multiple operations within the same kernel launch, and therefore looking at the kernel name no longer reflects what is actually run by NCCL. It just gives a hint as to what the first NCCL operation might be.

**Comment by JoeyYoung** [comment]
> Yes all the rest is correct. And in fact, it was not really a bug, just a change we reverted because it was confusing for users. This `ncclKernel_SendRecv_RING` kernel can be seen as `ncclGenericKernel_For_Non-Inlined_Operations`. Most operations are not inlined, so we just launch any nccl kernel, which will read a `workElem` struct to know what operation(s) to perform and will call the appropriate nccl function.
> 
> Hence, since NCCL 2.2, a single kernel can run multiple operations within the same kernel launch, and therefore looking at the kernel name no longer reflects what is actually run by NCCL. It just gives a hint as to what the first NCCL operation might be.

I see. Thanks for your explanation.

**Comment by sjeaugey** [comment]
For completeness, the reason why you were seeing the right name when running your `ToyModel` example was because the sizes were small, and for small operations we use the LL protocol + inlined code, so those calls would end up launching the kernel with the corresponding name.

**Comment by terU3760** [comment]
@AddyLaddy Hi, could you please also point out which commit fixed the misnaming problem specified in this post by [JoeyYoung](https://github.com/JoeyYoung)?

**Comment by AddyLaddy** [comment]
We don't push individual commits to github, so there is no specific commit. 
But I believe the changes were made to `src/enqueue.c` in NCCL 2.14.2 and later; look for the `specialized` kernel function attribute handling.
