### ISSUE TITLE
Reduce_scatter limitations?

### ISSUE THREAD

**Issue by minsikcho** [NVIDIA/nccl#74]
I found ncclReduceScatter is not compatible with MPI_Reduce_scatter, because recvcount is one scalar in nccl while MPI accepts as a vector. If it is one scalar, how can a user access each partially reduced output? 

For example, there are 4 processes and 73 numbers to reduce. In MPI, I can pass a vector {18,19,18,18} and access 4 partitioned results from each process. How does nccl handle this case? I can see that we need to pass 19*4=76 to the recvcount in ncclReduceScatter, but not sure how to access each partition on each process. 

The same goes to AllGather. MPI has AllGather"V" to handle this, but there is no ncclAllGatherV, and not sure how I use ncclAllGather for this purpose. 

Any comments would be appreciated.

**Comment by sjeaugey** [comment]
Indeed, NCCL reduce scatter is actually similar to MPI_Reduce_scatter_block. The count you pass is the receive count, so the send buffer should be of size nranks*(receive count).

In your precise case, that means passing recvcount=19, a sendbuffer of 76 elements and recvbuffer of 19 elements.

For allgather, it is the same principle, but with send/recv inverted. NCCL asks for the sendcount (=19) and the recvcount will be equal to sendcount*nranks = 76, so the sendbuffer should have 19 elements, and the recvbuffer 76.

**Comment by minsikcho** [comment]
OK, I see so NCCL reduce scatter follows in fact MPI_Reduce_scatter_block, not MPI_Reduce_scatter, in terms of functionality. 

So, for my example, by somehow I need to increase the sendbuffer size from 73 to 76 (e.g., by adding dummy values). Then, I can access each partition with regular interval 19 with the last 3 values ignored.

**Comment by sjeaugey** [comment]
That's correct. MPI_Reduce_scatter should be named MPI_Reduce_scatterv and MPI_Reduce_scatter_block should be the real MPI_Reduce_scatter. This has been raised before in this MPI Forum issue :
https://github.com/mpi-forum/mpi-forum-historic/issues/257

**Comment by minsikcho** [comment]
That makes sense. Thanks for the clarification.
