### ISSUE TITLE
How to make nccl operations progress concurrently in single process multiple GPUs setting?

### ISSUE THREAD

**Issue by kingder** [NVIDIA/nccl#744]
I have two processes with two GPUs each,  p0-gpu0 will use group ncclsend / ncclreceive with p1-gpu0, the same for p0-gpu1 and p1-gpu1. A dedicated thread for each gpu, the nccl operations will be issued into the default stream of each gpu. The send / receive in each gpu pair will be matched while maybe interleaved between the other pair because of threading. We observed hangs if there‘s cuda memory operations like cudaFree / cudaMalloc somewhere.
I know that gpu memory operations will case a implicit sync, my questions:
- Whether the sync only block the current gpu or both gpus of the same process?
-  Is there any change to avoid hang by this setting?

**Comment by sjeaugey** [comment]
Unfortunately this is indeed a tricky case, where CUDA memory operations can cause a device sync on the local GPU, but also on all GPUs which have P2P enabled with the local GPU (which is usually the case if there is a NCCL communicator with all GPUs).

Setting `NCCL_LAUNCH_MODE=GROUP` can help alleviate the issue. Another solution could be to use memory management functions which do not cause implicit inter-GPU synchronization, like the [low-level memory management API](https://developer.nvidia.com/blog/introducing-low-level-gpu-virtual-memory-management/), but that is much more complex to use than cudaMalloc/cudaFree.

Finally, moving to a one process per GPU model seems to be the preferred option these days, as it does not suffer from such issues and makes the GPU management simpler and more regular.

**Comment by kingder** [comment]
Thanks for the advice, very helpful!
