### ISSUE TITLE
Does NCCL support MPI derived datatypes?

### ISSUE THREAD

**Issue by manauref** [NVIDIA/nccl#746]
I have communications with MPI that use derived data types, e.g.

MPI_Type_contiguous
MPI_Type_vector
MPI_Type_indexed

Is there a way to use NCCL Send/Recv with these types or something like them? For example, they facilitate communicating non-contiguous chunks of data.

I saw a closed issue about using user-custom data types:
https://github.com/NVIDIA/nccl/issues/488
could something like that work?

**Comment by sjeaugey** [comment]
No we don't support derived datatypes.

In MPI, non-contiguous datatypes ended up being implemented almost always with a pack/unpack function before and after. We could do the same in NCCL but it's not hard to append a packing kernel before the NCCL send kernel, or an unpacking one after the receive. Plus, you can vary the number of CUDA blocks/threads independently of NCCL choices, or even use cudaMemcpy* functions which will not use SMs.

So, while it might be beneficial to add that support in NCCL for some cases, my impression was that we already had lots of decently optimized options to compose NCCL with packing/unpacking primitives.

**Comment by manauref** [comment]
Roger that. Thanks. Yes, packing/unpacking then using NCCL send/recv is something we can do. I've been told MPI derived datatypes, although they may pack/unpack as you said, also reduce the amount of memory needed (perhaps because of the way they pack/unpack?), which is important for higher dimensional problems we focus on.

**Comment by sjeaugey** [comment]
Fair point, since there is some pipelining, I guess we only pack/unpack one chunk at a time.

Application should do that as well though, benefiting from both the memory reduction and the pipelining. But I agree it's a bit more work. Something like (pseudo code):
```
  for (int offset = 0; offset < size; offset += chunk_size) {
     pack<<<..., pack_stream>>>(buffer, chunk_size);
     cudaEventRecord(pack_done);
     cudaStreamWaitEvent(nccl_stream, pack_done);
     ncclOperation(buffer, chunk_size, nccl_stream);
     cudaEventRecord(nccl_done);
     cudaStreamWaitEvent(unpack_stream, nccl_done);
     unpack<<<..., unpack_stream>>>(buffer, chunk_size);
  }
```
