### ISSUE TITLE
Questions about GDRDMA path in SR-IOV env.  

### ISSUE THREAD

**Issue by susol-hjkim** [NVIDIA/nccl#748]
Hello there. ~

I have two Supermicro servers like dgx A100.
Now just test SR-IOV enviorments.
And mlx5_8~11 is mlx5_2's VF. 

When I nccl tests, added two options.
-x CUDA_VISIBLE_DEVICES=0  (gpu0)
-x NCCL_IB_HCA=mlx5_8,mlx5_9,mlx5_10,mlx5_11 (mlx5_2's VF)

And I saw use only two path.

dgx-100a54:38430:38441 [0] NCCL INFO Channel 00 : 0[7000] -> 1[7000] [receive] via NET/IB/0/GDRDMA
dgx-100a49:45731:45742 [0] NCCL INFO Channel 00 : 1[7000] -> 0[7000] [receive] via NET/IB/0/GDRDMA
dgx-100a54:38430:38441 [0] NCCL INFO Channel 01 : 0[7000] -> 1[7000] [receive] via NET/IB/1/GDRDMA
dgx-100a49:45731:45742 [0] NCCL INFO Channel 01 : 1[7000] -> 0[7000] [receive] via NET/IB/1/GDRDMA
dgx-100a54:38430:38441 [0] NCCL INFO Channel 02 : 0[7000] -> 1[7000] [receive] via NET/IB/0/GDRDMA
dgx-100a49:45731:45742 [0] NCCL INFO Channel 02 : 1[7000] -> 0[7000] [receive] via NET/IB/0/GDRDMA
dgx-100a54:38430:38441 [0] NCCL INFO Channel 03 : 0[7000] -> 1[7000] [receive] via NET/IB/1/GDRDMA
dgx-100a49:45731:45742 [0] NCCL INFO Channel 03 : 1[7000] -> 0[7000] [receive] via NET/IB/1/GDRDMA
dgx-100a54:38430:38441 [0] NCCL INFO Channel 00 : 1[7000] -> 0[7000] [send] via NET/IB/0/GDRDMA
dgx-100a49:45731:45742 [0] NCCL INFO Channel 00 : 0[7000] -> 1[7000] [send] via NET/IB/0/GDRDMA
dgx-100a54:38430:38441 [0] NCCL INFO Channel 01 : 1[7000] -> 0[7000] [send] via NET/IB/1/GDRDMA
dgx100a49:45731:45742 [0] NCCL INFO Channel 01 : 0[7000] -> 1[7000] [send] via NET/IB/1/GDRDMA
dgx-100a54:38430:38441 [0] NCCL INFO Channel 02 : 1[7000] -> 0[7000] [send] via NET/IB/0/GDRDMA
dgx-100a49:45731:45742 [0] NCCL INFO Channel 02 : 0[7000] -> 1[7000] [send] via NET/IB/0/GDRDMA
dgx-100a54:38430:38441 [0] NCCL INFO Channel 03 : 1[7000] -> 0[7000] [send] via NET/IB/1/GDRDMA
dgx-100a49:45731:45742 [0] NCCL INFO Channel 03 : 0[7000] -> 1[7000] [send] via NET/IB/1/GDRDMA

**[Question]**
Q1. Why used only 2 path ?? 
      Not 4 path? GPU0 has same distance mlx5_8~11.
        
I attached file. 
If you need more please tell me.
Thank you so much.

**[NCCL CMD]**
mpirun -H 192.168.191.13,192.168.191.14  -map-by slot --mca btl ^openib --mca btl_tcp_if_include eth2 \
-x NCCL_DEBUG=INFO  -x NCCL_SOCKET_IFNAME=eth2 -x CUDA_VISIBLE_DEVICES=0 -x NCCL_IB_HCA=mlx5_8,mlx5_9,mlx5_10,mlx5_11  \
/home/admin/workspace/nccl-tests/build/all_reduce_perf -b 1G -e 2G -f 2 -c 0 -n 10 -w 5 -g 1
[nvidia-smi-topo_nccl-debug-info_v1.txt](https://github.com/NVIDIA/nccl/files/9978973/nvidia-smi-topo_nccl-debug-info_v1.txt)

**Comment by sjeaugey** [comment]
> Q1. Why used only 2 path ?? Not 4 path? GPU0 has same distance mlx5_8~11.

Please see this comment:
https://github.com/NVIDIA/nccl/issues/687#issuecomment-1308819860
Let me know if it doesn't answer the question.

**Comment by susol-hjkim** [comment]
Hello ~ sjeaugey.
It really helped me a lot.
Thank you so much again.
