### ISSUE TITLE
How a GPU send/recv data to/from other GPUs in NCCL?

### ISSUE THREAD

**Issue by ConnollyLeon** [NVIDIA/nccl#752]
Currently I am reading codes of NCCL. I notice that in my nccl-tests experiments, NCCL uses LL protocol to communicate within a DGX V100 server.

Then I start  to check how LL protocol works, and find out that all data transfers uses the template class LLGenericOp. To dive in  deeper,  I find out that all data transfers use `storeLL` and `readLL` to send and recv data from other GPUs.  But I don't understand how an asm instruction like 
```cpp
asm("ld.volatile.global.v4.u32 {%0,%1,%2,%3}, [%4];" : "=r"(data1), "=r"(flag1), "=r"(data2), "=r"(flag2) : "l"(&src->i4));
```
handle the data transfers between GPUs. 

It seems to store data to global memory. Is the global memory shared between GPU devices?

Could you please help me out?

**Comment by ConnollyLeon** [comment]
I think the logic is in `transport` directory, and NCCL bind the communication proxy to the address that used by the instruction 
```cpp
asm("ld.volatile.global.v4.u32 {%0,%1,%2,%3}, [%4];" : "=r"(data1), "=r"(flag1), "=r"(data2), "=r"(flag2) : "l"(&src->i4));
```

Could you please check whether I have a right understanding?

**Comment by jbachan** [comment]
All communication in NCCL happens with loads and stores against global memory that is "shared" between the GPU and its peer GPU or host CPUs. The shared memory is organized into circular buffers. CUDA P2P is one way we achieve that sharing: https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__PEER.html

The instructions you've found move data into/out-of that shared memory.

**Comment by ConnollyLeon** [comment]
> All communication in NCCL happens with loads and stores against global memory that is "shared" between the GPU and its peer GPU or host CPUs. The shared memory is organized into circular buffers. CUDA P2P is one way we achieve that sharing: https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__PEER.html
> 
> The instructions you've found move data into/out-of that shared memory.

@jbachan Thanks for your reply! I have another question. I notice that `ncclCollNets[3]={nullptr, nullptr, nullptr}`, and `ncclCollNets[0]` will only be available when `libnccl-net.so` plugin is given. Is this mean by default we don't use collnet or ncclNet when selecting ncclNets?

**Comment by AddyLaddy** [comment]
CollNet is how we enable SHARP via the external plugin: https://github.com/Mellanox/nccl-rdma-sharp-plugins
Unless CollNet is available in the plugin and NCCL_COLLNET_ENABLE=1 then NCCL won't attempt to use that Algo.
