### ISSUE TITLE
Is there any indicator or flag indicating the algorithm of a communication is using?

### ISSUE THREAD

**Issue by mozizhao** [NVIDIA/nccl#754]
Hi,

I know there are three types of algorithms that NCCL could use to communicate among ranks under the all-reduce scenario (ring, tree, and another), depending on the environment setting of the cluster. But in this case, I cannot know the exact algorithm is using. Is there any indicator or flags that can tell user which algorithm is using in the log?

**Comment by mozizhao** [comment]
@sjeaugey Could you please help answer this question?

**Comment by sjeaugey** [comment]
Short answer is no, there is no such log. You can uncomment this line to see it:
https://github.com/NVIDIA/nccl/blob/master/src/enqueue.cc#L1158

As for why, it's because we can't print a line on every call (that would have a perf impact) and we can't also deduce which algorithm we're using easily.
There are 4 algorithms now (Ring, Tree, CollnetChain and CollnetDirect) × 3 protocols (LL, LL128, Simple). Restricting to Ring and Tree, that's still 6 combinations.

The internal tuning model will switch from one to the other depending on the number of nodes, number of GPUs per node, and size of the operation, but also the intra-node and inter-node bandwidth. NCCL will move from one combination to another depending on the size, for example it could do: tree/LL -> ring/LL -> tree/LL128 -> ring/LL128 -> tree/simple -> ring/simple. Or any other combination. So there is no easy rule to determine which algorithm/protocol is used.

**Comment by mozizhao** [comment]
Hi,


thanks for your response. According to my survey, in the tuner file, the algorithm is determined. Is it possible to output the selected algorithm by adding a line of code in this file? I am not familiar with nccl code, so I am not sure about that.&nbsp;



---Original---
From: "Sylvain ***@***.***&gt;
Date: Mon, Dec 12, 2022 17:33 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [NVIDIA/nccl] Is there any indicator or flag indicating thealgorithm of a communication is using? (Issue #754)




 
Short answer is no, there is no such log. You can uncomment this line to see it:
 https://github.com/NVIDIA/nccl/blob/master/src/enqueue.cc#L1158
 
As for why, it's because we can't print a line on every call (that would have a perf impact) and we can't also deduce which algorithm we're using easily.
 There are 4 algorithms now (Ring, Tree, CollnetChain and CollnetDirect) × 3 protocols (LL, LL128, Simple). Restricting to Ring and Tree, that's still 6 combinations.
 
The internal tuning model will switch from one to the other depending on the number of nodes, number of GPUs per node, and size of the operation, but also the intra-node and inter-node bandwidth. NCCL will move from one combination to another depending on the size, for example it could do: tree/LL -&gt; ring/LL -&gt; tree/LL128 -&gt; ring/LL128 -&gt; tree/simple -&gt; ring/simple. Or any other combination. So there is no easy rule to determine which algorithm/protocol is used.

**Comment by sjeaugey** [comment]
I'm not sure what you mean. Yes, for each size, the algorithm/protocol is deterministic. But it's still dependent on the size.

**Comment by mozizhao** [comment]
> I'm not sure what you mean. Yes, for each size, the algorithm/protocol is deterministic. But it's still dependent on the size.

Hi Sylvain Jeaugey,

Sorry for my unclear expression. I will try to express myself more clearly about my thought. In the code https://github.com/NVIDIA/nccl/blob/master/src/graph/tuning.cc, the algorithm (ring, tree and etc.) is somehow determined and never changed after executing this initiation according to the environment and data. Is it convenient for me to add some logs in this file to determine what algorithm is selected, given the environment and data? To my knowledge, the algorithm in this file is one-shot and may not incur much performance degradation. 

The reason why I am curious about the selected algorithm is that I want to build up a prediction model, to forecast the mini-batch time spent on multi-GPU multi-node training for my research idea. Sometimes the overhead is linear with the number of workers/nodes and sometimes it's not. I guess this is susceptible to algorithm selection. So awareness of the algorithm may be important for my prediction. If you found I go astray, could you please give me some idea?

Thanks a lot.

**Comment by sjeaugey** [comment]
Sure, you could add traces and extracting the settings.

You can also set NCCL_DEBUG=INFO NCCL_DEBUG_SUBSYS=TUNING to get the numbers, and then run ncclTopoGetAlgoTime() on the size you care about.

**Comment by mozizhao** [comment]
> Sure, you could add traces and extracting the settings.
> 
> You can also set NCCL_DEBUG=INFO NCCL_DEBUG_SUBSYS=TUNING to get the numbers, and then run ncclTopoGetAlgoTime() on the size you care about.

Hi, I download the source code from GitHub and uncomment the line https://github.com/NVIDIA/nccl/blob/master/src/enqueue.cc#L1178, to check the algorithm it uses. Then I build and reinstall the NCCL according to https://github.com/NVIDIA/nccl/blob/master/README.md. However, it didn't output any log as expected. Should I clean the original NCCL in my host first?

**Comment by sjeaugey** [comment]
You may want to modify `makefiles/version.mk` to set the suffix to e.g. `debug`. Then rebuild, install and when you run, set `NCCL_DEBUG=VERSION` to print which version you're using. You should see `2.16.2debug`.

**Comment by sjeaugey** [comment]
Did you install the deb packages with `dpkg -i build/pkg/deb/*.deb`?

Now you may just want to try that version without installing it. In that case you can just set:
```
export LD_LIBRARY_PATH=$NCCL_HOME/build/lib:$LDL_LIBRARY_PATH
```
And then run again.

**Comment by mozizhao** [comment]
> 



> Did you install the deb packages with `dpkg -i build/pkg/deb/*.deb`?
> 
> Now you may just want to try that version without installing it. In that case you can just set:
> 
> ```
> export LD_LIBRARY_PATH=$NCCL_HOME/build/lib:$LDL_LIBRARY_PATH
> ```
> 
> And then run again.

Hi,

Since I test the NCCL under PyTorch, I found that maybe I should rebuild PyTorch with a customized NCCL path as discussed in https://discuss.pytorch.org/t/how-can-i-change-nccl-version-in-pytorch/143942. I will try to rebuild them to see if it will work or not. Anyway, thank you for your advice.

**Comment by mozizhao** [comment]
> Sure, you could add traces and extracting the settings.
> 
> You can also set NCCL_DEBUG=INFO NCCL_DEBUG_SUBSYS=TUNING to get the numbers, and then run ncclTopoGetAlgoTime() on the size you care about.

Hi, I want to know if NCCL always picks the algorithm yielding the minimum value in the last row when using the AllReduce? In this case, is CollNet/ LL128 selected to be the runtime algorithm?

```
autodl-container-035011a13c-c17b1392:9373:9456 [0] NCCL INFO Latency/AlgBw |    Tree/    LL |    Tree/ LL128 |    Tree/Simple |    Ring/    LL |    Ring/ LL128 |    Ring/Simple | CollNet/    LL | CollNet/ LL128 | CollNet/Simple |
autodl-container-035011a13c-c17b1392:9373:9456 [0] NCCL INFO  Max NThreads |            512 |            640 |            512 |            512 |            640 |            256 |            512 |            640 |            512 |
autodl-container-035011a13c-c17b1392:9373:9456 [0] NCCL INFO     Broadcast |     0.0/   0.0 |     0.0/   0.0 |     0.0/   0.0 |     6.3/   0.8 |    14.0/   0.0 |    18.0/   3.0 |     0.0/   0.0 |     0.0/   0.0 |     0.0/   0.0 |
autodl-container-035011a13c-c17b1392:9373:9456 [0] NCCL INFO        Reduce |     0.0/   0.0 |     0.0/   0.0 |     0.0/   0.0 |     6.3/   0.8 |    14.0/   0.0 |    18.0/   3.0 |     0.0/   0.0 |     0.0/   0.0 |     0.0/   0.0 |
autodl-container-035011a13c-c17b1392:9373:9456 [0] NCCL INFO     AllGather |     0.0/   0.0 |     0.0/   0.0 |     0.0/   0.0 |    33.3/   0.8 |    52.0/   0.0 |   105.6/   3.2 |     0.0/   0.0 |     0.0/   0.0 |     0.0/   0.0 |
autodl-container-035011a13c-c17b1392:9373:9456 [0] NCCL INFO ReduceScatter |     0.0/   0.0 |     0.0/   0.0 |     0.0/   0.0 |    33.3/   0.8 |    52.0/   0.0 |   105.6/   3.2 |     0.0/   0.0 |     0.0/   0.0 |     0.0/   0.0 |
autodl-container-035011a13c-c17b1392:9373:9456 [0] NCCL INFO     AllReduce |    35.2/   0.4 |    49.8/   0.0 |   280.0/   1.4 |    63.0/   0.4 |    94.0/   0.0 |   202.8/   1.6 |    14.2/   0.0 |    14.8/   0.0 |    29.7/   0.0 |
```

**Comment by sjeaugey** [comment]
The first number is the latency and the second is the bandwidth. Anything with 0 bandwidth will be dismissed (infinite time). LL has low latency but low bandwidth. LL128 more latency more bandwidth, Simple even more latency and more bandwidth...

The formula is not always just latency + size/bandwidth, for Tree we have a correction factor to apply (it's ugly but that's what we have at the moment).

**Comment by mozizhao** [comment]
> The first number is the latency and the second is the bandwidth. Anything with 0 bandwidth will be dismissed (infinite time). LL has low latency but low bandwidth. LL128 more latency more bandwidth, Simple even more latency and more bandwidth...
> 
> The formula is not always just latency + size/bandwidth, for Tree we have a correction factor to apply (it's ugly but that's what we have at the moment).

Thanks!

**Comment by BitCalSaul** [comment]
@mozizhao @sjeaugey Hi, I was wondering — is this table specifically showing the latency and bandwidth of communication primitives on your server, under different methods and protocols? I’m really interested in how you generated these results. Would you mind sharing a bit about your setup or process? I’d love to try running similar measurements on my side.

Thanks!

**Comment by sjeaugey** [comment]
Those represent what the NCCL internal model computed as base numbers for the different algorithms, in order to hopefully select the right combination at any size.

The computation of those numbers is pretty complicated and the result of a lot of empirical adjustments. Even the computation of the expected time doesn't follow a simple latency + size / bandwidth formula; there are further adjustments in the computation code as well.

**Comment by BitCalSaul** [comment]
Hi @sjeaugey , I’ve shared some related details in another issue here: https://github.com/NVIDIA/nccl/issues/1123#issuecomment-3013393929

My nccl version is (2,20,5) with cuda 12.4, pytorch 2.3.0.

In my case, I’ve already enabled:
```
NCCL_DEBUG=INFO
NCCL_DEBUG_SUBSYS=TUNING
```
With this, I successfully got the latency and bandwidth metrics under different protocols and algorithms from the NCCL internal tuning model.

![Image](https://github.com/user-attachments/assets/e3998dff-f99b-4fcc-8207-6acbb14e1b5a)

Now to my specific experiment:
	•	I have 6 Ada 6000 GPUs on a single host connected via PCIe only.
	•	I’m performing AllGather on a large tensor of shape [5, 2048, 2048], which is about 80 MB per GPU (assuming float32).
	•	The AllGather takes roughly 20 milliseconds, and Nsight Systems shows it consistently uses the LL protocol.
	•	However, according to the TUNING output table, the Simple protocol offers 3× higher bandwidth than LL for this message size.

So ideally, I want to force the use of the Simple protocol to potentially reduce the AllGather time to around 6 ms.

But I’ve tried setting environment variables like:
`NCCL_PROTO=Simple
NCCL_PROTO=^LL,^LL128 `
and even combinations with NCCL_ALGO, yet LL protocol is always selected.

My questions are:
	1.	For a tensor of this size, does ~20 ms on 6 PCIe-connected Ada 6000 GPUs sound reasonable?
	2.	Is there any way to force the Simple protocol reliably in this scenario?
	3.	Could the fact that it’s intra-node communication (single host) be affecting the protocol selection in a non-obvious way?

Thanks a lot for your insight!
