### ISSUE TITLE
Create tag for v2.16.2

### ISSUE THREAD

**Issue by robogast** [NVIDIA/nccl#755]
Hi! It seems the v2.16.2 release has its dedicated commit https://github.com/NVIDIA/nccl/commit/28189e2df85885b78bf20384cefc3cedab023bf5, but no corresponding tag was made.

Could you add the v.2.16.2 release as a tag? :)

**Comment by sjeaugey** [comment]
Sure, I didn't merge v2.16.2 to master yet, that's why the tag isn't there.

I'll do it soon.

**Comment by sjeaugey** [comment]
Done.
