### ISSUE TITLE
Why doesn't use GDR for LL protocol ?

### ISSUE THREAD

**Issue by elevenxiang** [NVIDIA/nccl#756]
Hi,

From the below code, I found that LL protocol doesn't use GDR, so why ?

https://github.com/NVIDIA/nccl/blob/28189e2df85885b78bf20384cefc3cedab023bf5/src/transport/net.cc#L540-L544

Thanks

**Comment by sjeaugey** [comment]
That's because in the current implementation, to reduce latency, the CPU polls the flag inside the data to know when data is ready to send, rather than having the GPU perform a `threadfence_system()` then set a flag.

Since the CPU has to access the data directly, it needs to be in CPU memory.

**Comment by elevenxiang** [comment]
Hi sjeaugey,

So glad to see your comment, yes LL protocol really needs CPU polls the data flag.

But LL128 protocol also need CPU polls the flag, why it choose to use GDR like Simple ?

Thanks

**Comment by elevenxiang** [comment]
@sjeaugey 

So glad to see your comment, totally understood now

LL128 performs a __threadfence() inside postSend(), and Simple also performs a __threadfence_system()
So they don't need CPU poll the data flag.

Thanks

**Comment by sjeaugey** [comment]
Not using GPU Direct RDMA means bandwidth will be heavily reduced in most platform. The goal of LL128 is to achieve high bandwidth with better latency than Simple. So for LL128 we lose a bit of latency to avoid dividing bandwidth by 2 or even 4 (CPU memory bandwidth from/to GPUs isn't very good).

So while we considered for LL we wanted to keep latency to the minimum (at the expense of bandwidth which was already low anyway), for LL128 we chose to favor bandwidth.

**Comment by elevenxiang** [comment]
> Not using GPU Direct RDMA means bandwidth will be heavily reduced in most platform. The goal of LL128 is to achieve high bandwidth with better latency than Simple. So for LL128 we lose a bit of latency to avoid dividing bandwidth by 2 or even 4 (CPU memory bandwidth from/to GPUs isn't very good).
> 
> So while we considered for LL we wanted to keep latency to the minimum (at the expense of bandwidth which was already low anyway), for LL128 we chose to favor bandwidth.

got it, thanks
