### ISSUE TITLE
2 questions about nccl kernel

### ISSUE THREAD

**Issue by hongbilu** [NVIDIA/nccl#761]
1. Why an extra warp need to do post_send/recv in SIMPLE protocol kernel? in theory, it can be done within worker threads also, is there a special scenario here?
2. does NVCC support 128-bit data type?(PTX seems support ld/st 128bit) if true, why not load/store 128-bit when loadLL/StoreLL?

**Comment by jbachan** [comment]
1. It gives a performance boost. The worker warps can move on to processing the next chunk of work while one warp stays behind waiting for the threadfence_system (which has significant latency).
2. We do use 128-bit load/store everywhere we can. LL uses it via `{ld|st}.volatile.global.v4.u32`

**Comment by hongbilu** [comment]
1.  thanks！I'm not getting it why only PostSend thread need to do threadfence_system here? What issue does it fix？
2.  sorry, maybe I gave wrong information, it seems support {ld|st}.volatile.global.v4.u64 which can be used？

**Comment by jbachan** [comment]
1. The fence is necessary for correctness to order the stores of the data before the store of the credit that data has arrived (this goes into the head or tail step counter of the fifo). All workers and extra warp enter barrier after which the extra warp knows the data stores have been issued so it fences and then issues the credit store.
2. `v4.u64` would be 256 bits which is not supported. The ptx assembler will fail.

**Comment by hongbilu** [comment]
got it， thanks very much
