### ISSUE TITLE
Why some GID index doesn't work for cross node communication ?

### ISSUE THREAD

**Issue by elevenxiang** [NVIDIA/nccl#769]
Hi,

Here we found that some GID Index will cause QP connection timeout as below:

// on our A100 platform, when set GID Index to 1 to run all_reduce_perf
_ibvwrap.cc: NCCL WARN Call to ibv_modify_qp failed with error Connection timed out_

and if we change the GID Index to 3, it will works normally !

then we use below command to check GID index:
_ibv_devinfo -d mlx5_bond_0 -v_

			phys_state:		LINK_UP (5)
			GID[  0]:		fe80:0000:0000:0000:0ac0:ebff:feda:1cfb, RoCE v1
			GID[  1]:		fe80::ac0:ebff:feda:1cfb, RoCE v2
			GID[  2]:		0000:0000:0000:0000:0000:ffff:c800:d106, RoCE v1
			GID[  3]:		::ffff:200.0.209.6, RoCE v2

So I wonder why only GID Index 3 could work, but GID Index 1 failed ? How could we choose the right GID index ?

Thanks

**Comment by sjeaugey** [comment]
The `fe80::ac0:ebff:feda:1cfb` IPv6 address is probably the link-local address so it isn't properly routed and fails.

GIDs correspond to IP addresses configured on the system. For each IP address there are 2 GIDs (one for RoCEv1 and one for RoCEv2). So I guess you could check which GID corresponds to the IP address you want to use or just use GID 3 if all nodes are configured the same.

**Comment by sjeaugey** [comment]
I don't think IPv6 is the problem here, just that that precise IPv6 address is not functional.

**Comment by elevenxiang** [comment]
> I don't think IPv6 is the problem here, just that that precise IPv6 address is not functional.

👌 Thanks, it seemed that it will be ok to choose IP4 based GPD index.
