### ISSUE TITLE
[Question] Can Inter-Node Graph be Customized?

### ISSUE THREAD

**Issue by bailiumit** [NVIDIA/nccl#776]
Dear Developers,

Hope you are doing well!

I have been studying the NCCL Tree algorithm recently. It seems that we can customize the intra-node chains via `NCCL_GRAPH_FILE`. 

But the inter-node connections are determined by the double binary tree algorithm. I would greatly appreciate it if I could get some insight in two questions:
1. Can inter-node graph be customized via file(s)?
2. If the answer to the first question is "no", is there any workaround? For example, re-ranking devices to create a different double binary tree etc.

Thank you!

**Comment by sjeaugey** [comment]
> Can inter-node graph be customized via file(s)?
No, the graph file is only for intra-node paths.
> is there any workaround?
Not really. The easiest I could think of would be to set the up/down[0]/down[1]/down[2] for each rank. For example with an environment variable like `NCCL_TREE_RANKS=4 1 -1 -1`. Then you could set it differently for each rank and build custom trees.
