### ISSUE TITLE
How to specify the device of P2P communication?

### ISSUE THREAD

**Issue by Codle** [NVIDIA/nccl#777]
I have both NVLink and PCI on the machine, and I want to test the pure **PCI** speed. NCCL_P2P_LEVEL seems to only determine which GPUs to use P2P, but does not specify the communication device.

**Comment by sjeaugey** [comment]
We cannot use PCI if NVLink is present between GPUs. NCCL relies on mapping remote GPU memory through CUDA, and CUDA will automatically use NVLink when it is present.

**Comment by Codle** [comment]
> We cannot use PCI if NVLink is present between GPUs. NCCL relies on mapping remote GPU memory through CUDA, and CUDA will automatically use NVLink when it is present.

OK, thanks. I will try to find a machine without NVLink to do this test.
