### ISSUE TITLE
ibv_reg_dmabuf_mr failed with error Operation not supported

### ISSUE THREAD

**Issue by NHZlX** [NVIDIA/nccl#778]
When I run nccl-tests （nccl 2.13）on two nodes, I meet this problem

```
misc/ibvwrap.cc:288 NCCL WARN Call to ibv_reg_dmabuf_mr failed with error Operation not supported
```

nccl 2.11 runs ok.

Help welcome.

**Comment by AddyLaddy** [comment]
Perhaps your IB driver version is too old to support DMABUF?
NCCL does try to backoff to nvidia-peermem for issues like that, but it doesn't appear to have worked for you.
Try running with `NCCL_DMABUF_ENABLE=0`

**Comment by AddyLaddy** [comment]
There were fixes to the DMABUF backoff in later versions of NCCL too. Perhaps you can also try with a newer version? We're up to NCCL 2.16.x now.

**Comment by NHZlX** [comment]
Many Thanks! BTW, what is the impact of DMABUF on performance, Do NV experts have similar test data？

**Comment by AddyLaddy** [comment]
nvidia-peermem and DMA-BUF both provide a mechanism for GPUDirect RDMA between the NIC and GPU memory.
On PCI topologies where the NIC and GPU can communicate with each other without using the CPU memory, this can dramatically improve communication performance.

On our DGX-A100 systems with 8x IB HDR NICs, we achieve a peak NCCL AllReduce BusBW of ~192GB/s.
