### ISSUE TITLE
Multi-send&recv is out of order execution， how to make sure the result is correct?

### ISSUE THREAD

**Issue by raninbowlalala** [NVIDIA/nccl#781]
My nccl version is 2.708.
GPU 0(send) -> GPU 1(recv) will execute many times, about 300. 
I use multi-thread and one-thread control one GPU.
I have two question:
1. send will execute in one thread and recv will  execute in another thread, how to make sure the result is correct?
2. send &  recv execute in one thread, there are many times execution, can I use same communicator?

Is it possible if I create a ncclUniqueId for each one send&recv？

Or one send & recv should execute in one thread?

**Comment by sjeaugey** [comment]
The receive operations are guaranteed to receive data in the same order it has been sent. So if one thread sends data and one thread receives data, you should not have any problem.

If you have multiple threads sending data (and/or multiple threads receiving data), then indeed it would be trickier to know in which order they've been sent (hence received) and creating multiple communicators could help.

**Comment by raninbowlalala** [comment]
> , then indeed it would be trickier to know in which order they've been sent (hence received) and creating multiple communicators could help

Thanks for your reply.
If I create 300 ncclUniqueIds for 300 times send&recv， is this OK？

**Comment by sjeaugey** [comment]
1. I'm not sure I understand. Would you create one communicator for each send&recv? That would mean each send/recv would take multiple seconds. That's not what communicator creation/destruction is designed for.
2. What do you use ncclGroupStart/End for? To merge multiple send/recv on a GPU or to launch send/recv operations on multiple GPUs at once?

**Comment by raninbowlalala** [comment]
> 2\. at do you use ncclGroupStart/End for? To merge multiple send/recv on a GPU or to launch send/recv

1. I can't call send&recv in order, the following situations may occur:
GPU0: send0
GPU0: send1
GPU1: recv1
GPU1: recv0
So I think I need one communicator for one send&recv. Is it right?
2. I mean this:
 ncclGroupStart
 ncclSend(rank0->rank1)
 ncclRecv(rank1)
 ncclGroupEnd
Does send and recv need to wrapped by start/end?

**Comment by raninbowlalala** [comment]
And I create three comminicator for three send&recv, I am hung in first send, my log is here:

> 2c1605972966:36073:36180 [0] NCCL INFO Bootstrap : Using eth0:172.17.0.5<0>
2c1605972966:36073:36180 [0] NCCL INFO Plugin Path : /opt/hpcx/nccl_rdma_sharp_plugin/lib/libnccl-net.so
2c1605972966:36073:36180 [0] NCCL INFO P2P plugin IBext
2c1605972966:36073:36180 [0] NCCL INFO NET/IB : No device found.
2c1605972966:36073:36180 [0] NCCL INFO NET/IB : No device found.
2c1605972966:36073:36180 [0] NCCL INFO NET/Socket : Using [0]eth0:172.17.0.5<0>
2c1605972966:36073:36180 [0] NCCL INFO Using network Socket
NCCL version 2.9.9+cuda11.3
2c1605972966:36073:36258 [0] NCCL INFO Channel 00/04 :    0   1
2c1605972966:36073:36258 [0] NCCL INFO Channel 01/04 :    0   1
2c1605972966:36073:36258 [0] NCCL INFO Channel 02/04 :    0   1
2c1605972966:36073:36258 [0] NCCL INFO Channel 03/04 :    0   1
2c1605972966:36073:36261 [1] NCCL INFO Trees [0] -1/-1/-1->1->0 [1] -1/-1/-1->1->0 [2] -1/-1/-1->1->0 [3] -1/-1/-1->1->0
2c1605972966:36073:36258 [0] NCCL INFO Trees [0] 1/-1/-1->0->-1 [1] 1/-1/-1->0->-1 [2] 1/-1/-1->0->-1 [3] 1/-1/-1->0->-1
2c1605972966:36073:36261 [1] NCCL INFO Setting affinity for GPU 1 to ff,ffff0000,00ffffff
2c1605972966:36073:36258 [0] NCCL INFO Setting affinity for GPU 0 to ff,ffff0000,00ffffff
2c1605972966:36073:36256 [0] NCCL INFO Channel 00/04 :    0   1
2c1605972966:36073:36256 [0] NCCL INFO Channel 01/04 :    0   1
2c1605972966:36073:36256 [0] NCCL INFO Channel 02/04 :    0   1
2c1605972966:36073:36256 [0] NCCL INFO Channel 03/04 :    0   1
2c1605972966:36073:36263 [1] NCCL INFO Trees [0] -1/-1/-1->1->0 [1] -1/-1/-1->1->0 [2] -1/-1/-1->1->0 [3] -1/-1/-1->1->0
2c1605972966:36073:36256 [0] NCCL INFO Trees [0] 1/-1/-1->0->-1 [1] 1/-1/-1->0->-1 [2] 1/-1/-1->0->-1 [3] 1/-1/-1->0->-1
2c1605972966:36073:36263 [1] NCCL INFO Setting affinity for GPU 1 to ff,ffff0000,00ffffff
2c1605972966:36073:36256 [0] NCCL INFO Setting affinity for GPU 0 to ff,ffff0000,00ffffff
2c1605972966:36073:36257 [0] NCCL INFO Channel 00/04 :    0   1
2c1605972966:36073:36257 [0] NCCL INFO Channel 01/04 :    0   1
2c1605972966:36073:36257 [0] NCCL INFO Channel 02/04 :    0   1
2c1605972966:36073:36257 [0] NCCL INFO Channel 03/04 :    0   1
2c1605972966:36073:36264 [1] NCCL INFO Trees [0] -1/-1/-1->1->0 [1] -1/-1/-1->1->0 [2] -1/-1/-1->1->0 [3] -1/-1/-1->1->0
2c1605972966:36073:36257 [0] NCCL INFO Trees [0] 1/-1/-1->0->-1 [1] 1/-1/-1->0->-1 [2] 1/-1/-1->0->-1 [3] 1/-1/-1->0->-1
2c1605972966:36073:36264 [1] NCCL INFO Setting affinity for GPU 1 to ff,ffff0000,00ffffff
2c1605972966:36073:36257 [0] NCCL INFO Setting affinity for GPU 0 to ff,ffff0000,00ffffff
2c1605972966:36073:36260 [0] NCCL INFO Channel 00/04 :    0   1
2c1605972966:36073:36260 [0] NCCL INFO Channel 01/04 :    0   1
2c1605972966:36073:36260 [0] NCCL INFO Channel 02/04 :    0   1
2c1605972966:36073:36260 [0] NCCL INFO Channel 03/04 :    0   1
2c1605972966:36073:36262 [1] NCCL INFO Trees [0] -1/-1/-1->1->0 [1] -1/-1/-1->1->0 [2] -1/-1/-1->1->0 [3] -1/-1/-1->1->0
2c1605972966:36073:36260 [0] NCCL INFO Trees [0] 1/-1/-1->0->-1 [1] 1/-1/-1->0->-1 [2] 1/-1/-1->0->-1 [3] 1/-1/-1->0->-1
2c1605972966:36073:36262 [1] NCCL INFO Setting affinity for GPU 1 to ff,ffff0000,00ffffff
2c1605972966:36073:36260 [0] NCCL INFO Setting affinity for GPU 0 to ff,ffff0000,00ffffff
2c1605972966:36073:36258 [0] NCCL INFO Channel 00 : 0[1a000] -> 1[3d000] via P2P/direct pointer
2c1605972966:36073:36258 [0] NCCL INFO Channel 01 : 0[1a000] -> 1[3d000] via P2P/direct pointer
2c1605972966:36073:36258 [0] NCCL INFO Channel 02 : 0[1a000] -> 1[3d000] via P2P/direct pointer
2c1605972966:36073:36261 [1] NCCL INFO Channel 00 : 1[3d000] -> 0[1a000] via P2P/direct pointer
2c1605972966:36073:36256 [0] NCCL INFO Channel 00 : 0[1a000] -> 1[3d000] via P2P/direct pointer
2c1605972966:36073:36258 [0] NCCL INFO Channel 03 : 0[1a000] -> 1[3d000] via P2P/direct pointer
2c1605972966:36073:36261 [1] NCCL INFO Channel 01 : 1[3d000] -> 0[1a000] via P2P/direct pointer
2c1605972966:36073:36256 [0] NCCL INFO Channel 01 : 0[1a000] -> 1[3d000] via P2P/direct pointer
2c1605972966:36073:36264 [1] NCCL INFO Channel 00 : 1[3d000] -> 0[1a000] via P2P/direct pointer
2c1605972966:36073:36261 [1] NCCL INFO Channel 02 : 1[3d000] -> 0[1a000] via P2P/direct pointer
2c1605972966:36073:36256 [0] NCCL INFO Channel 02 : 0[1a000] -> 1[3d000] via P2P/direct pointer
2c1605972966:36073:36257 [0] NCCL INFO Channel 00 : 0[1a000] -> 1[3d000] via P2P/direct pointer
2c1605972966:36073:36256 [0] NCCL INFO Channel 03 : 0[1a000] -> 1[3d000] via P2P/direct pointer
2c1605972966:36073:36261 [1] NCCL INFO Channel 03 : 1[3d000] -> 0[1a000] via P2P/direct pointer
2c1605972966:36073:36264 [1] NCCL INFO Channel 01 : 1[3d000] -> 0[1a000] via P2P/direct pointer
2c1605972966:36073:36257 [0] NCCL INFO Channel 01 : 0[1a000] -> 1[3d000] via P2P/direct pointer
2c1605972966:36073:36263 [1] NCCL INFO Channel 00 : 1[3d000] -> 0[1a000] via P2P/direct pointer
2c1605972966:36073:36264 [1] NCCL INFO Channel 02 : 1[3d000] -> 0[1a000] via P2P/direct pointer
2c1605972966:36073:36257 [0] NCCL INFO Channel 02 : 0[1a000] -> 1[3d000] via P2P/direct pointer
2c1605972966:36073:36260 [0] NCCL INFO Channel 00 : 0[1a000] -> 1[3d000] via P2P/direct pointer
2c1605972966:36073:36263 [1] NCCL INFO Channel 01 : 1[3d000] -> 0[1a000] via P2P/direct pointer
2c1605972966:36073:36257 [0] NCCL INFO Channel 03 : 0[1a000] -> 1[3d000] via P2P/direct pointer
2c1605972966:36073:36264 [1] NCCL INFO Channel 03 : 1[3d000] -> 0[1a000] via P2P/direct pointer
2c1605972966:36073:36262 [1] NCCL INFO Channel 00 : 1[3d000] -> 0[1a000] via P2P/direct pointer
2c1605972966:36073:36260 [0] NCCL INFO Channel 01 : 0[1a000] -> 1[3d000] via P2P/direct pointer
2c1605972966:36073:36258 [0] NCCL INFO Connected all rings
2c1605972966:36073:36263 [1] NCCL INFO Channel 02 : 1[3d000] -> 0[1a000] via P2P/direct pointer
2c1605972966:36073:36258 [0] NCCL INFO Connected all trees
2c1605972966:36073:36258 [0] NCCL INFO threadThresholds 8/8/64 | 16/8/64 | 8/8/512
2c1605972966:36073:36258 [0] NCCL INFO 4 coll channels, 4 p2p channels, 4 p2p channels per peer
2c1605972966:36073:36262 [1] NCCL INFO Channel 01 : 1[3d000] -> 0[1a000] via P2P/direct pointer
2c1605972966:36073:36260 [0] NCCL INFO Channel 02 : 0[1a000] -> 1[3d000] via P2P/direct pointer
2c1605972966:36073:36263 [1] NCCL INFO Channel 03 : 1[3d000] -> 0[1a000] via P2P/direct pointer
2c1605972966:36073:36262 [1] NCCL INFO Channel 02 : 1[3d000] -> 0[1a000] via P2P/direct pointer
2c1605972966:36073:36260 [0] NCCL INFO Channel 03 : 0[1a000] -> 1[3d000] via P2P/direct pointer
2c1605972966:36073:36258 [0] NCCL INFO comm 0x7fdafc009120 rank 0 nranks 2 cudaDev 0 busId 1a000 - Init COMPLETE
########### create 0 comm:0x7fdafc009120 (CUDA)2c1605972966:36073:36257 [0] NCCL INFO Connected all rings

2c1605972966:36073:36257 [0] NCCL INFO Connected all trees
2c1605972966:36073:36256 [0] NCCL INFO Connected all rings
2c1605972966:36073:36257 [0] NCCL INFO threadThresholds 8/8/64 | 16/8/64 | 8/8/512
2c1605972966:36073:36257 [0] NCCL INFO 4 coll channels, 4 p2p channels, 4 p2p channels per peer
2c1605972966:36073:36256 [0] NCCL INFO Connected all trees
2c1605972966:36073:36261 [1] NCCL INFO Connected all rings
########### exec comm:0x7fdafc009120 (CUDA)
2c1605972966:36073:36256 [0] NCCL INFO threadThresholds 8/8/64 | 16/8/64 | 8/8/512
2c1605972966:36073:36256 [0] NCCL INFO 4 coll channels, 4 p2p channels, 4 p2p channels per peer
2c1605972966:36073:36261 [1] NCCL INFO Connected all trees
2c1605972966:36073:36274 [0] NCCL INFO Launch mode Parallel
2c1605972966:36073:36261 [1] NCCL INFO threadThresholds 8/8/64 | 16/8/64 | 8/8/512
2c1605972966:36073:36261 [1] NCCL INFO 4 coll channels, 4 p2p channels, 4 p2p channels per peer
2c1605972966:36073:36262 [1] NCCL INFO Channel 03 : 1[3d000] -> 0[1a000] via P2P/direct pointer
2c1605972966:36073:36264 [1] NCCL INFO Connected all rings
2c1605972966:36073:36264 [1] NCCL INFO Connected all trees
2c1605972966:36073:36264 [1] NCCL INFO threadThresholds 8/8/64 | 16/8/64 | 8/8/512
2c1605972966:36073:36264 [1] NCCL INFO 4 coll channels, 4 p2p channels, 4 p2p channels per peer
2c1605972966:36073:36263 [1] NCCL INFO Connected all rings
2c1605972966:36073:36263 [1] NCCL INFO Connected all trees
2c1605972966:36073:36263 [1] NCCL INFO threadThresholds 8/8/64 | 16/8/64 | 8/8/512
2c1605972966:36073:36263 [1] NCCL INFO 4 coll channels, 4 p2p channels, 4 p2p channels per peer

**Comment by raninbowlalala** [comment]
And after I set NCCL_LAUNCH_MODE=GROUP， I will got correct result as below:

> 2c1605972966:38716:38825 [0] NCCL INFO Bootstrap : Using eth0:172.17.0.5<0>
2c1605972966:38716:38825 [0] NCCL INFO Plugin Path : /opt/hpcx/nccl_rdma_sharp_plugin/lib/libnccl-net.so
2c1605972966:38716:38825 [0] NCCL INFO P2P plugin IBext
2c1605972966:38716:38825 [0] NCCL INFO NET/IB : No device found.
2c1605972966:38716:38825 [0] NCCL INFO NET/IB : No device found.
2c1605972966:38716:38825 [0] NCCL INFO NET/Socket : Using [0]eth0:172.17.0.5<0>
2c1605972966:38716:38825 [0] NCCL INFO Using network Socket
NCCL version 2.9.9+cuda11.3
2c1605972966:38716:38903 [0] NCCL INFO Channel 00/04 :    0   1
2c1605972966:38716:38903 [0] NCCL INFO Channel 01/04 :    0   1
2c1605972966:38716:38903 [0] NCCL INFO Channel 02/04 :    0   1
2c1605972966:38716:38903 [0] NCCL INFO Channel 03/04 :    0   1
2c1605972966:38716:38904 [1] NCCL INFO Trees [0] -1/-1/-1->1->0 [1] -1/-1/-1->1->0 [2] -1/-1/-1->1->0 [3] -1/-1/-1->1->0
2c1605972966:38716:38903 [0] NCCL INFO Trees [0] 1/-1/-1->0->-1 [1] 1/-1/-1->0->-1 [2] 1/-1/-1->0->-1 [3] 1/-1/-1->0->-1
2c1605972966:38716:38904 [1] NCCL INFO Setting affinity for GPU 1 to ff,ffff0000,00ffffff
2c1605972966:38716:38903 [0] NCCL INFO Setting affinity for GPU 0 to ff,ffff0000,00ffffff
2c1605972966:38716:38899 [0] NCCL INFO Channel 00/04 :    0   1
2c1605972966:38716:38899 [0] NCCL INFO Channel 01/04 :    0   1
2c1605972966:38716:38899 [0] NCCL INFO Channel 02/04 :    0   1
2c1605972966:38716:38899 [0] NCCL INFO Channel 03/04 :    0   1
2c1605972966:38716:38905 [1] NCCL INFO Trees [0] -1/-1/-1->1->0 [1] -1/-1/-1->1->0 [2] -1/-1/-1->1->0 [3] -1/-1/-1->1->0
2c1605972966:38716:38899 [0] NCCL INFO Trees [0] 1/-1/-1->0->-1 [1] 1/-1/-1->0->-1 [2] 1/-1/-1->0->-1 [3] 1/-1/-1->0->-1
2c1605972966:38716:38905 [1] NCCL INFO Setting affinity for GPU 1 to ff,ffff0000,00ffffff
2c1605972966:38716:38899 [0] NCCL INFO Setting affinity for GPU 0 to ff,ffff0000,00ffffff
2c1605972966:38716:38902 [0] NCCL INFO Channel 00/04 :    0   1
2c1605972966:38716:38902 [0] NCCL INFO Channel 01/04 :    0   1
2c1605972966:38716:38902 [0] NCCL INFO Channel 02/04 :    0   1
2c1605972966:38716:38902 [0] NCCL INFO Channel 03/04 :    0   1
2c1605972966:38716:38906 [1] NCCL INFO Trees [0] -1/-1/-1->1->0 [1] -1/-1/-1->1->0 [2] -1/-1/-1->1->0 [3] -1/-1/-1->1->0
2c1605972966:38716:38902 [0] NCCL INFO Trees [0] 1/-1/-1->0->-1 [1] 1/-1/-1->0->-1 [2] 1/-1/-1->0->-1 [3] 1/-1/-1->0->-1
2c1605972966:38716:38906 [1] NCCL INFO Setting affinity for GPU 1 to ff,ffff0000,00ffffff
2c1605972966:38716:38902 [0] NCCL INFO Setting affinity for GPU 0 to ff,ffff0000,00ffffff
2c1605972966:38716:38904 [1] NCCL INFO Channel 00 : 1[3d000] -> 0[1a000] via P2P/direct pointer
2c1605972966:38716:38903 [0] NCCL INFO Channel 00 : 0[1a000] -> 1[3d000] via P2P/direct pointer
2c1605972966:38716:38901 [0] NCCL INFO Channel 00/04 :    0   1
2c1605972966:38716:38901 [0] NCCL INFO Channel 01/04 :    0   1
2c1605972966:38716:38901 [0] NCCL INFO Channel 02/04 :    0   1
2c1605972966:38716:38901 [0] NCCL INFO Channel 03/04 :    0   1
2c1605972966:38716:38907 [1] NCCL INFO Trees [0] -1/-1/-1->1->0 [1] -1/-1/-1->1->0 [2] -1/-1/-1->1->0 [3] -1/-1/-1->1->0
2c1605972966:38716:38901 [0] NCCL INFO Trees [0] 1/-1/-1->0->-1 [1] 1/-1/-1->0->-1 [2] 1/-1/-1->0->-1 [3] 1/-1/-1->0->-1
2c1605972966:38716:38907 [1] NCCL INFO Setting affinity for GPU 1 to ff,ffff0000,00ffffff
2c1605972966:38716:38901 [0] NCCL INFO Setting affinity for GPU 0 to ff,ffff0000,00ffffff
2c1605972966:38716:38904 [1] NCCL INFO Channel 01 : 1[3d000] -> 0[1a000] via P2P/direct pointer
2c1605972966:38716:38903 [0] NCCL INFO Channel 01 : 0[1a000] -> 1[3d000] via P2P/direct pointer
2c1605972966:38716:38904 [1] NCCL INFO Channel 02 : 1[3d000] -> 0[1a000] via P2P/direct pointer
2c1605972966:38716:38903 [0] NCCL INFO Channel 02 : 0[1a000] -> 1[3d000] via P2P/direct pointer
2c1605972966:38716:38904 [1] NCCL INFO Channel 03 : 1[3d000] -> 0[1a000] via P2P/direct pointer
2c1605972966:38716:38903 [0] NCCL INFO Channel 03 : 0[1a000] -> 1[3d000] via P2P/direct pointer
2c1605972966:38716:38904 [1] NCCL INFO Connected all rings
2c1605972966:38716:38899 [0] NCCL INFO Channel 00 : 0[1a000] -> 1[3d000] via P2P/direct pointer
2c1605972966:38716:38903 [0] NCCL INFO Connected all rings
2c1605972966:38716:38904 [1] NCCL INFO Connected all trees
2c1605972966:38716:38905 [1] NCCL INFO Channel 00 : 1[3d000] -> 0[1a000] via P2P/direct pointer
2c1605972966:38716:38904 [1] NCCL INFO threadThresholds 8/8/64 | 16/8/64 | 8/8/512
2c1605972966:38716:38903 [0] NCCL INFO Connected all trees
2c1605972966:38716:38904 [1] NCCL INFO 4 coll channels, 4 p2p channels, 4 p2p channels per peer
2c1605972966:38716:38903 [0] NCCL INFO threadThresholds 8/8/64 | 16/8/64 | 8/8/512
2c1605972966:38716:38903 [0] NCCL INFO 4 coll channels, 4 p2p channels, 4 p2p channels per peer
2c1605972966:38716:38899 [0] NCCL INFO Channel 01 : 0[1a000] -> 1[3d000] via P2P/direct pointer
2c1605972966:38716:38905 [1] NCCL INFO Channel 01 : 1[3d000] -> 0[1a000] via P2P/direct pointer
2c1605972966:38716:38899 [0] NCCL INFO Channel 02 : 0[1a000] -> 1[3d000] via P2P/direct pointer
2c1605972966:38716:38904 [1] NCCL INFO comm 0x7fb6e184d4b0 rank 1 nranks 2 cudaDev 1 busId 3d000 - Init COMPLETE
########### create 1 comm:0x7fb6e184d4b0 (CUDA)
########### exec comm:0x7fb6e184d4b0 (CUDA)
2c1605972966:38716:38905 [1] NCCL INFO Channel 02 : 1[3d000] -> 0[1a000] via P2P/direct pointer
2c1605972966:38716:38903 [0] NCCL INFO comm 0x7fb6fc009120 rank 0 nranks 2 cudaDev 0 busId 1a000 - Init COMPLETE
########### create 0 comm:0x7fb6fc009120 (CUDA)
########### exec comm:0x7fb6fc009120 (CUDA)
2c1605972966:38716:38919 [0] NCCL INFO Launch mode Group/CGMD
2c1605972966:38716:38899 [0] NCCL INFO Channel 03 : 0[1a000] -> 1[3d000] via P2P/direct pointer
2c1605972966:38716:38906 [1] NCCL INFO Channel 00 : 1[3d000] -> 0[1a000] via P2P/direct pointer
2c1605972966:38716:38905 [1] NCCL INFO Channel 03 : 1[3d000] -> 0[1a000] via P2P/direct pointer
2c1605972966:38716:38902 [0] NCCL INFO Channel 00 : 0[1a000] -> 1[3d000] via P2P/direct pointer
2c1605972966:38716:38906 [1] NCCL INFO Channel 01 : 1[3d000] -> 0[1a000] via P2P/direct pointer
2c1605972966:38716:38902 [0] NCCL INFO Channel 01 : 0[1a000] -> 1[3d000] via P2P/direct pointer
2c1605972966:38716:38907 [1] NCCL INFO Channel 00 : 1[3d000] -> 0[1a000] via P2P/direct pointer
2c1605972966:38716:38906 [1] NCCL INFO Channel 02 : 1[3d000] -> 0[1a000] via P2P/direct pointer
2c1605972966:38716:38902 [0] NCCL INFO Channel 02 : 0[1a000] -> 1[3d000] via P2P/direct pointer
2c1605972966:38716:38907 [1] NCCL INFO Channel 01 : 1[3d000] -> 0[1a000] via P2P/direct pointer
2c1605972966:38716:38901 [0] NCCL INFO Channel 00 : 0[1a000] -> 1[3d000] via P2P/direct pointer
2c1605972966:38716:38906 [1] NCCL INFO Channel 03 : 1[3d000] -> 0[1a000] via P2P/direct pointer
2c1605972966:38716:38902 [0] NCCL INFO Channel 03 : 0[1a000] -> 1[3d000] via P2P/direct pointer
2c1605972966:38716:38907 [1] NCCL INFO Channel 02 : 1[3d000] -> 0[1a000] via P2P/direct pointer
2c1605972966:38716:38901 [0] NCCL INFO Channel 01 : 0[1a000] -> 1[3d000] via P2P/direct pointer
2c1605972966:38716:38899 [0] NCCL INFO Connected all rings
2c1605972966:38716:38899 [0] NCCL INFO Connected all trees
2c1605972966:38716:38907 [1] NCCL INFO Channel 03 : 1[3d000] -> 0[1a000] via P2P/direct pointer
2c1605972966:38716:38899 [0] NCCL INFO threadThresholds 8/8/64 | 16/8/64 | 8/8/512
2c1605972966:38716:38899 [0] NCCL INFO 4 coll channels, 4 p2p channels, 4 p2p channels per peer
2c1605972966:38716:38901 [0] NCCL INFO Channel 02 : 0[1a000] -> 1[3d000] via P2P/direct pointer
2c1605972966:38716:38905 [1] NCCL INFO Connected all rings
2c1605972966:38716:38905 [1] NCCL INFO Connected all trees
2c1605972966:38716:38905 [1] NCCL INFO threadThresholds 8/8/64 | 16/8/64 | 8/8/512
2c1605972966:38716:38905 [1] NCCL INFO 4 coll channels, 4 p2p channels, 4 p2p channels per peer
2c1605972966:38716:38901 [0] NCCL INFO Channel 03 : 0[1a000] -> 1[3d000] via P2P/direct pointer
2c1605972966:38716:38906 [1] NCCL INFO Connected all rings
2c1605972966:38716:38905 [1] NCCL INFO comm 0x7fb6e4009120 rank 1 nranks 2 cudaDev 1 busId 3d000 - Init COMPLETE
########### create 1 comm:0x7fb6e4009120 (CUDA2c1605972966:38716:38899 [0] NCCL INFO comm 0x7fb70c009150 rank 0 nranks 2 cudaDev 0 busId 1a000 - Init COMPLETE
)
########### create 0 comm:0x7fb70c009150 (2c1605972966:38716:38906 [1] NCCL INFO Connected all trees
CUDA)
2c1605972966:38716:38906 [1] NCCL INFO threadThresholds 8/8/64 | 16/8/64 | 8/8/512
2c1605972966:38716:38906 [1] NCCL INFO 4 coll channels, 4 p2p channels, 4 p2p channels per peer
########### exec comm:0x7fb6e4009120 (CUDA)
########### exec comm:0x7fb70c009150 (CUDA)
2c1605972966:38716:38923 [0] NCCL INFO Launch mode Group/CGMD
2c1605972966:38716:38902 [0] NCCL INFO Connected all rings
2c1605972966:38716:38902 [0] NCCL INFO Connected all trees
2c1605972966:38716:38902 [0] NCCL INFO threadThresholds 8/8/64 | 16/8/64 | 8/8/512
2c1605972966:38716:38902 [0] NCCL INFO 4 coll channels, 4 p2p channels, 4 p2p channels per peer
2c1605972966:38716:38907 [1] NCCL INFO Connected all rings
2c1605972966:38716:38907 [1] NCCL INFO Connected all trees
2c1605972966:38716:38907 [1] NCCL INFO threadThresholds 8/8/64 | 16/8/64 | 8/8/512
2c1605972966:38716:38907 [1] NCCL INFO 4 coll channels, 4 p2p channels, 4 p2p channels per peer
2c1605972966:38716:38901 [0] NCCL INFO Connected all rings
2c1605972966:38716:38901 [0] NCCL INFO Connected all trees
2c1605972966:38716:38901 [0] NCCL INFO threadThresholds 8/8/64 | 16/8/64 | 8/8/512
2c1605972966:38716:38901 [0] NCCL INFO 4 coll channels, 4 p2p channels, 4 p2p channels per peer
2c1605972966:38716:38902 [0] NCCL INFO comm 0x7fb6f8009120 rank 0 nranks 2 cudaDev 0 busId 1a000 - Init COMPLETE
########### create 0 comm:0x7fb6f8009120 (CUDA)
########### exec comm:0x7fb6f8009120 (CUDA)
2c1605972966:38716:38928 [0] NCCL INFO Launch mode Group/CGMD
2c1605972966:38716:38906 [1] NCCL INFO comm 0x7fb6d8009120 rank 1 nranks 2 cudaDev 1 busId 3d000 - Init COMPLETE
########### create 1 comm:0x7fb6d8009120 (CUDA)
########### exec comm:0x7fb6d8009120 (CUDA)
2c1605972966:38716:38901 [0] NCCL INFO comm 0x7fb704009120 rank 0 nranks 2 cudaDev 0 busId 1a000 - Init COMPLETE
########### create 0 comm:0x7fb704009120 (CUDA)
########### exec comm:0x7fb704009120 (CUDA)
2c1605972966:38716:38930 [0] NCCL INFO Launch mode Group/CGMD
2c1605972966:38716:38907 [1] NCCL INFO comm 0x7fb6dc009120 rank 1 nranks 2 cudaDev 1 busId 3d000 - Init COMPLETE
########### create 1 comm:0x7fb6dc009120 (CUDA)
########### exec comm:0x7fb6dc009120 (CUDA)
DenseHostTensor dtype = i32, shape = [1], values = [4]
DenseHostTensor dtype = i32, shape = [1], values = [3]
DenseHostTensor dtype = i32, shape = [1], values = [2]
DenseHostTensor dtype = i32, shape = [1], values = [5]


Do you know the reason?

**Comment by sjeaugey** [comment]
> I can't call send&recv in order, the following situations may occur:
> GPU0: send0
> GPU0: send1
> GPU1: recv1
> GPU1: recv0
> So I think I need one communicator for one send&recv. Is it right?

That could make sense; unfortunately communicating concurrently on multiple communicators is not supported by CUDA because CUDA does not give you guarantees that the two send/recv operations on the two NCCL communicators using two different streams will not block each other. Using non-blocking streams is a requirement to get concurrency but not a guarantee.

> I mean this:
> ncclGroupStart
> ncclSend(rank0->rank1)
> ncclRecv(rank1)
> ncclGroupEnd
> Does send and recv need to wrapped by start/end?

Can you be more precise as to which NCCL operation is running on which GPU? Is ncclSend running on rank 0 and ncclRecv running on rank 1? If so, then you're using grouping to launch on multiple GPUs at once, rather than fusing multiple operations on the same GPU. When launching on multiple GPUs from the same process, NCCL_LAUNCH_MODE=GROUP can indeed help avoid hangs, although it's not guaranteed, just less likely to happen.

**Comment by raninbowlalala** [comment]
> Can you be more precise as to which NCCL operation is running on which GPU? Is ncclSend running on rank 0 and ncclRecv running on rank 1? If so, then you're using grouping to launch on multiple GPUs at once, rather than fusing multiple operations on the same GPU. When launching on multiple GPUs from the same process, NCCL_LAUNCH_MODE=GROUP can indeed help avoid hangs, although it's not guaranteed, just less likely to happen.

Yes， ncclSend running on rank 0 and ncclRecv running on rank 1. Thank you for your patience and quick response！It helps me alot！
