### ISSUE TITLE
[Question]  About ncclAllReduceCollNetKernel decision

### ISSUE THREAD

**Issue by Shangwei-Li** [NVIDIA/nccl#793]
I am trying to modify some older(2.7.6-1, precisely) NCCL code for other usage, and to understand the code in src/collective/device. 
I notice that in older version(2.7.6-1), ncclAllReduceCollNetKernel decides whether it should do reduce or broadcast based on blockIdx, while in newer version(2.16.5-1) it is based on threadIdx. To my knowledge, blocks can be executed in any order, so there could be deadlock if those broadcast blocks are executed before reduce blocks. Is my understanding right or NCCL used some techniques to avoid deadlock? Is this one of the reasons the code has been changed?
Thanks!

**Comment by sjeaugey** [comment]
You are right, having different CTAs run as different roles but tied together was a risk of deadlock. On top of that, it was much more complex to manage as we could not longer launch any number of CTAs, we needed to make sure we launched the ones which were working together.

For all those reasons, we were happy to get rid of that early design and move to independent channels.

**Comment by Shangwei-Li** [comment]
Thank you for your detailed explanation!
