### ISSUE TITLE
Question about alignas(long long)

### ISSUE THREAD

**Issue by PeiqinZhuang** [NVIDIA/nccl#80]
I have tried the method on web-site to compile to source code.When I did " make CUDA_HOME=/usr/local/cuda-7.5 test ",something with error happened.After querying a lot of information,I still can't get the idea to deal with the problem.So I come to for help.The errors are listed as followed:![](https://ooo.0o0.ooo/2017/03/26/58d69f4053eff.png)

**Comment by sjeaugey** [comment]
Hi @PeiqinZhuang,
Which version of g++ are you using ?  It seems indeed the alignas directive is not understood. This is a c++11 keyword, which is why you need gcc 4.8.

**Comment by PeiqinZhuang** [comment]
Thank you for implying the gcc version.Indeed,my gcc version 4.7.I delete "alignas(long long)",then it make it works

**Comment by sjeaugey** [comment]
Oh, that's good to know, and can be helpful to others. Please close the bug when you feel your issue is resolved.

Thanks !
