### ISSUE TITLE
Why does NCCL not support one GPU multiple NICs in all2all collective communication?

### ISSUE THREAD

**Issue by zhangmenghao** [NVIDIA/nccl#804]
I was testing NCCL between two node, and each node has one GPU and two NICs in the same NUMA, connecting directing with one switch. Each NIC is assigned with a different IP address.
I found that in all_reduce, NCCL already support one GPU two NICs, and the bandwidth of these two NICs can be fully utilized. 
However, in all2all, only one NIC is used, and the other NIC is left used. 

Therefore, my question is, why does NCCL not support one GPU two NICs in alltoall? Is there some difficulty that prevent you from supporting such a feature?

**Comment by sjeaugey** [comment]
What version are you using? We had that issue on old versions but it was supposed to be fixed now.

**Comment by zhangmenghao** [comment]
We used NCCL 2.14.3.

**Comment by zhangmenghao** [comment]
Hi, Sylvain, could you please answer this question for us? @sjeaugey

**Comment by sjeaugey** [comment]
Sorry for the delay. Turns out I was wrong and it wasn't fixed. We're working on a fix right now, we'll post updates here when ready.

**Comment by zhangmenghao** [comment]
Really great news! We are looking forward to your new NCCL version.

In NCCL 2.14.3, we have hacked the function `ncclTopoGetLocalNet()` in `topo.cc`, and make alltoall support one GPU two NICs finally. Especially, we assigned `netDev` based on not only `rr`, but also on `channelId`. However, such a change only uses half of these channels, i.e., half of channels are assigned to these two NICs equally. And we are confused by such a phenomenon. Could you please explain a few words about how the setting-up channels are used in latter all2all communication?
