### ISSUE TITLE
the installed version is inconsistent with the queried version

### ISSUE THREAD

**Issue by jiahui1688** [NVIDIA/nccl#809]
Before, I installed nccl-2.10.3, after that I removed it.
Now, I installed nccl-2.15.5.
Now, I input `dpkg --list` in Terminal,I can see nccl 2.15.5-1
![nccl_04](https://user-images.githubusercontent.com/95198346/227720514-b50aa6c0-dbbc-475c-8c24-f7ba4ee0c8f7.png)

But,When I input `python -c "import torch;print(torch.cuda.nccl.version())"`  in Terminal, I can see (2, 10, 3).
![nccl_02](https://user-images.githubusercontent.com/95198346/227719103-e84483c4-8e0d-4c13-82e5-e6263c720ff7.png)
I want to use nccl-2.15.5, but I don't know how to slove this problem.

**Comment by sjeaugey** [comment]
It looks like you are using a version of PyTorch which is compiled statically against a fixed version of NCCL. To update NCCL, you'd need to update PyTorch or use a version of PyTorch compiled dynamically against NCCL.

**Comment by jiahui1688** [comment]
Big thanks
