### ISSUE TITLE
indentifier issue in line 35 

### ISSUE THREAD

**Issue by csktan** [NVIDIA/nccl#81]
when i tried to compile, with cuda 8.0 and also tried with 7 and 7.5 it gives me an error in  **core.h** in line 35 saying that "expected an identifier",
please need help :)

**Comment by nluehr** [comment]
What version of gcc are you using?

**Comment by csktan** [comment]
gcc (GCC) 4.4.7 20120313 (Red Hat 4.4.7-16)

**Comment by cliffwoolley** [comment]
See https://github.com/NVIDIA/nccl/issues/50 .

**Comment by csktan** [comment]
thank you  so much
