### ISSUE TITLE
Why Tree has better bandwidth performance than Ring on only 2 DGX-A100 ?

### ISSUE THREAD

**Issue by elevenxiang** [NVIDIA/nccl#812]
Hi, 

I have 2 DGX A100 with RDMA network connection, and when I run all_reduce_perf, I found that Tree has better bandwidth, why ? I thought we only have 2 nodes, and Ring should be better.

Thanks

// Ring
NCCL version 2.16.5+cuda11.0
```
                                                             out-of-place                       in-place
       size         count      type   redop    root     time   algbw   busbw #wrong     time   algbw   busbw #wrong
        (B)    (elements)                               (us)  (GB/s)  (GB/s)            (us)  (GB/s)  (GB/s)
           8             2     float     sum      -1    93.12    0.00    0.00      0    92.93    0.00    0.00      0
          16             4     float     sum      -1    93.30    0.00    0.00      0    93.24    0.00    0.00      0
          32             8     float     sum      -1    92.96    0.00    0.00      0    93.10    0.00    0.00      0
          64            16     float     sum      -1    93.05    0.00    0.00      0    93.06    0.00    0.00      0
         128            32     float     sum      -1    93.62    0.00    0.00      0    93.33    0.00    0.00      0
         256            64     float     sum      -1    93.99    0.00    0.01      0    93.85    0.00    0.01      0
         512           128     float     sum      -1    93.96    0.01    0.01      0    93.94    0.01    0.01      0
        1024           256     float     sum      -1    95.44    0.01    0.02      0    95.08    0.01    0.02      0
        2048           512     float     sum      -1    96.01    0.02    0.04      0    96.14    0.02    0.04      0
        4096          1024     float     sum      -1    100.5    0.04    0.08      0    99.93    0.04    0.08      0
        8192          2048     float     sum      -1    105.6    0.08    0.15      0    105.3    0.08    0.15      0
       16384          4096     float     sum      -1    111.1    0.15    0.28      0    110.7    0.15    0.28      0
       32768          8192     float     sum      -1    116.0    0.28    0.53      0    114.3    0.29    0.54      0
       65536         16384     float     sum      -1    122.8    0.53    1.00      0    122.5    0.53    1.00      0
      131072         32768     float     sum      -1    124.1    1.06    1.98      0    123.8    1.06    1.99      0
      262144         65536     float     sum      -1    131.9    1.99    3.73      0    135.1    1.94    3.64      0
      524288        131072     float     sum      -1    131.7    3.98    7.46      0    129.6    4.05    7.59      0
     1048576        262144     float     sum      -1    150.5    6.97   13.07      0    146.3    7.17   13.44      0
     2097152        524288     float     sum      -1    179.3   11.70   21.93      0    186.0   11.28   21.14      0
     4194304       1048576     float     sum      -1    223.6   18.76   35.17      0    222.6   18.85   35.34      0
     8388608       2097152     float     sum      -1    343.3   24.44   45.82      0    337.9   24.82   46.55      0
    16777216       4194304     float     sum      -1    579.3   28.96   54.30      0    573.5   29.26   54.86      0
    33554432       8388608     float     sum      -1   1132.7   29.62   55.54      0   1127.6   29.76   55.80      0
    67108864      16777216     float     sum      -1   2258.9   29.71   55.70      0   2240.2   29.96   56.17      0
   134217728      33554432     float     sum      -1   4340.6   30.92   57.98      0   4346.3   30.88   57.90      0
   268435456      67108864     float     sum      -1   8471.8   31.69   59.41      0   8484.4   31.64   59.32      0
   536870912     134217728     float     sum      -1    16904   31.76   59.55      0    16962   31.65   59.35      0
  1073741824     268435456     float     sum      -1    33876   31.70   59.43      0    33798   31.77   59.57      0
Out of bounds values : 0 OK
Avg bus bandwidth    : 19.0703
```
// Tree
NCCL version 2.16.5+cuda11.0
```
                                                              out-of-place                       in-place
       size         count      type   redop    root     time   algbw   busbw #wrong     time   algbw   busbw #wrong
        (B)    (elements)                               (us)  (GB/s)  (GB/s)            (us)  (GB/s)  (GB/s)
           8             2     float     sum      -1    38.12    0.00    0.00      0    36.71    0.00    0.00      0
          16             4     float     sum      -1    37.94    0.00    0.00      0    36.71    0.00    0.00      0
          32             8     float     sum      -1    37.13    0.00    0.00      0    37.29    0.00    0.00      0
          64            16     float     sum      -1    38.00    0.00    0.00      0    37.61    0.00    0.00      0
         128            32     float     sum      -1    38.45    0.00    0.01      0    38.13    0.00    0.01      0
         256            64     float     sum      -1    40.28    0.01    0.01      0    38.53    0.01    0.01      0
         512           128     float     sum      -1    39.55    0.01    0.02      0    40.32    0.01    0.02      0
        1024           256     float     sum      -1    41.28    0.02    0.05      0    40.85    0.03    0.05      0
        2048           512     float     sum      -1    42.61    0.05    0.09      0    41.89    0.05    0.09      0
        4096          1024     float     sum      -1    44.93    0.09    0.17      0    42.83    0.10    0.18      0
        8192          2048     float     sum      -1    46.56    0.18    0.33      0    43.78    0.19    0.35      0
       16384          4096     float     sum      -1    47.63    0.34    0.65      0    44.88    0.37    0.68      0
       32768          8192     float     sum      -1    48.50    0.68    1.27      0    45.32    0.72    1.36      0
       65536         16384     float     sum      -1    50.77    1.29    2.42      0    49.04    1.34    2.51      0
      131072         32768     float     sum      -1    63.93    2.05    3.84      0    63.20    2.07    3.89      0
      262144         65536     float     sum      -1    75.85    3.46    6.48      0    74.93    3.50    6.56      0
      524288        131072     float     sum      -1    86.50    6.06   11.36      0    85.45    6.14   11.50      0
     1048576        262144     float     sum      -1    108.5    9.67   18.13      0    107.0    9.80   18.38      0
     2097152        524288     float     sum      -1    134.7   15.57   29.19      0    133.8   15.68   29.40      0
     4194304       1048576     float     sum      -1    193.0   21.74   40.76      0    194.4   21.58   40.46      0
     8388608       2097152     float     sum      -1    298.2   28.13   52.74      0    293.9   28.55   53.53      0
    16777216       4194304     float     sum      -1    520.7   32.22   60.42      0    514.3   32.62   61.16      0
    33554432       8388608     float     sum      -1    906.3   37.03   69.42      0    899.7   37.30   69.93      0
    67108864      16777216     float     sum      -1   1729.8   38.80   72.74      0   1724.3   38.92   72.97      0
   134217728      33554432     float     sum      -1   3795.8   35.36   66.30      0   4740.0   28.32   53.09      0
   268435456      67108864     float     sum      -1   8627.4   31.11   58.34      0   7662.0   35.03   65.69      0
   536870912     134217728     float     sum      -1    11038   48.64   91.19      0    10549   50.90   95.43      0
  1073741824     268435456     float     sum      -1    20810   51.60   96.74      0    20557   52.23   97.94      0
Out of bounds values : 0 OK
Avg bus bandwidth    : 24.4264
```

**Comment by AddyLaddy** [comment]
Tree performs better on two nodes as there are fewer inter-node data transmissions for that particular case. As you scale out beyond two nodes, the same effect will not be present. Forcing `NCCL_ALGO=RING` when using two nodes will give you a better representation of the scale out data if that's what you're interested in?

How many NICs and what speed are they on your system?

**Comment by elevenxiang** [comment]
> 

Hi AddyLaddy,

They are standard DGX A100 platform, each node has 8 x 100Gbps NICs.

The perf data I showed before is exactly tested under NCCL_ALGO=Ring and NCCL_ALGO=Tree, and obviously Tree algorithm has higher peak bandwidth.

And I think you are right, for only 2 nodes, Ring algorithm has more data transmissions

Ring: (S / N) x 2 (N - 1), N = 16
Tree: S

Thanks

**Comment by AddyLaddy** [comment]
Ok thanks. We often see two nodes Tree BusBW figures that exceed the theoretical limit of the network cards due to way it's calculated. But you're only getting 60GB/s from Ring - that seems a little low for 8x100Gbit/s NICs. 
On an Nvidia DGX-A100 system we have 8x200Gbit/s IB cards and we measure 192GB/s AllReduce BusBW.

Do you have GDRDMA enabled? Is this RoCE or InfiniBand? Does this system have NVSwitches ?

Do you want to share a `NCCL_DEBUG=INFO` log and a `NCCL_TOPO_DUMP_FILE=system.xml` for us to check the configuration?

**Comment by elevenxiang** [comment]
> Ok thanks. We often see two nodes Tree BusBW figures that exceed the theoretical limit of the network cards due to way it's calculated. But you're only getting 60GB/s from Ring - that seems a little low for 8x100Gbit/s NICs. On an Nvidia DGX-A100 system we have 8x200Gbit/s IB cards and we measure 192GB/s AllReduce BusBW.
> 
> Do you have GDRDMA enabled? Is this RoCE or InfiniBand? Does this system have NVSwitches ?
> 
> Do you want to share a `NCCL_DEBUG=INFO` log and a `NCCL_TOPO_DUMP_FILE=system.xml` for us to check the configuration?

Yes, from the log we found GDRDMA was enabled, and we are using RoCEv2, not InfiniBand.
for intra-node connection, we use NV12 switch

**Comment by elevenxiang** [comment]
any suggested QPN number for each connection ? we found QPN number will affect the bandwidth.
Thanks

**Comment by sjeaugey** [comment]
That's a common issue on fabrics which do not have separate switches for each NIC, and where the fabric does not efficiently balance the 8 flows on 8 different network links.

Increasing the number of QPs per connection can somewhat mitigate that issue, as you would have more flows, so they might spread better, but it has consequences. The more you increase the number of QPs, the more you increase your network overhead (you need to post N commands to the NIC instead of 1) and the smaller the network packets are, as we post 1/Nth of the chunk on each QP.

The best is therefore to ensure the fabric is capable of guaranteeing each of the 8 flows will use a different link, either through physical separation of flows, or some adaptive routing technology which will automatically move flows to idle links when the link has a high load. Increasing QPN is only a workaround and not a great one.

**Comment by elevenxiang** [comment]
> That's a common issue on fabrics which do not have separate switches for each NIC, and where the fabric does not efficiently balance the 8 flows on 8 different network links.
> 
> Increasing the number of QPs per connection can somewhat mitigate that issue, as you would have more flows, so they might spread better, but it has consequences. The more you increase the number of QPs, the more you increase your network overhead (you need to post N commands to the NIC instead of 1) and the smaller the network packets are, as we post 1/Nth of the chunk on each QP.
> 
> The best is therefore to ensure the fabric is capable of guaranteeing each of the 8 flows will use a different link, either through physical separation of flows, or some adaptive routing technology which will automatically move flows to idle links when the link has a high load. Increasing QPN is only a workaround and not a great one.

Thank you so much, I will confirm the network configuration ~
