### ISSUE TITLE
why do we need barrierReduceAny

### ISSUE THREAD

**Issue by MonroeD** [NVIDIA/nccl#815]

**Comment by jbachan** [comment]
One thread (tid=0) loads the abort flag (which is in host mem) and submits that to barrierReduceAny so that it is returned to all of threads so they know together that its time to end the kernel.

**Comment by MonroeD** [comment]
I know what barrierReduceAny  does. I want to know why there is two brak in while (true);
`while (true) {
    if (ncclShmem.work.header.isLast) break;

    { // Check whether the last operation was aborted and make sure all threads exit
      int aborted = tid == 0 ? *comm->abortFlag : 0;
      if (barrierReduceAny(aborted)) // publish ncclShmem.work
        break;
    }
}`
I think the first break（ncclShmem.work.header.isLast） can work well ?

**Comment by MonroeD** [comment]
> If we just executed the last operation of the list of operations to perform, then we exit immediately to avoid the extra cost of barrierReduceAny.
> 
> The call to barrierReduceAny is only for cases where we have more than one operation to execute, for example when using ncclGroupStart/ncclGroupEnd to aggregate multiple operations into a single kernel launch.

I think so too, but if i add a printf  before barrierReduceAny as follows
`if (barrierReduceAny(aborted)) {
  printf("");
  break;
}`

the testcase is as followed.
`ncclGroupStart()
ncclAllReduce(sendbuff2, recvbuff2, count2, datatype, comm, stream);
ncclReduce(sendbuff1, recvbuff1, count1, datatype, root, comm, stream);
ncclGroupEnd()`

but I can't see any printf in the result. I think the process is as followed. 
1. we aggeragate ncclAllReduce and ncclReduce into a single kernel launch
2. the two request are pushed into channel.workFifo, and the last op（reduce） is set ncclShmem.work.header.isLast;
3. the kernel while (ture) may first process all_reduce op, then process reduce op and check ncclShmem.work.header.isLast ; and then exit the while;

Please show me my mistake. Thanks!

**Comment by jbachan** [comment]
If these operations are small enough then they may be sent to different channels. You won't see "hello" unless some channel has multiple ncclWork's to run. Consider adding the following before the loop exit check on isLast:
```
printf("rank=%d chan=%d isLast=%d\n", ncclShmem.comm.rank, blockIdx.x, ncclShmem.work.header.isLast);
```
