### ISSUE TITLE
Proto LL relies on 8 Bytes atomic read/write or 16 Bytes atomic read/write?

### ISSUE THREAD

**Issue by MonroeD** [NVIDIA/nccl#824]
```
  __device__ uint64_t readLLFinish(int offset, ncclLLFifoLine(&line)[MaxRecv], int i) {
    union ncclLLFifoLine* src = recvPtr(i) + offset;
    uint32_t flag = recvFlag(i);
    int spins = 0;
    while (line[i].flag1 != flag || line[i].flag2 != flag) {
      asm("ld.volatile.global.v4.u32 {%0,%1,%2,%3}, [%4];" : "=r"(line[i].data1), "=r"(line[i].flag1), "=r"(line[i].data2), "=r"(line[i].flag2) : "l"(&src->i4));
      if (checkAbort(spins, 0)) break;
    }
    uint64_t val64 = line[i].data1 + (((uint64_t)line[i].data2) << 32);
    return val64;
  }

  __device__ void storeLL(union ncclLLFifoLine* dst, uint64_t val, uint32_t flag) {
    asm volatile("st.volatile.global.v4.u32 [%0], {%1,%2,%3,%4};" :: "l"(&dst->i4), "r"((uint32_t)val), "r"(flag), "r"((uint32_t)(val >> 32)), "r"(flag));
  }
```

1. is this st.volatile.global.v4.u32/ld.volatile.global.v4.u32 atomic? i mean that it can store/load data 16Bytes?
2. if it relies on 8 bytes atomic read/write, we split the st.volatile.global.v4.u32 into twice load 8 bytes, and the load does too. is it right?
3. I see in the issue that answers LL relies  on 8 Bytes atomic read/write? [https://github.com/NVIDIA/nccl/issues/281](url)

**Comment by MonroeD** [comment]
If in single node, not IB/RDMA, can i say it relies on 16 bytes？

**Comment by jbachan** [comment]
We only assume 8-byte atomicity. Using a single 16-byte instruction means we are getting two atomic accesses at once. But the whole 16-byte access itself is not atomic.
