### ISSUE TITLE
A little bit confuse about the implementation compared with NVSwitch presentation

### ISSUE THREAD

**Issue by dearsxx0918** [NVIDIA/nccl#828]
![image](https://user-images.githubusercontent.com/4445405/233529368-c98d1740-95ae-412c-9f37-2ead3d31efa9.png)
Hi sjeaugey，
    I've read the latest code 2.17.1, the new algorithm NVLS is so powerful. But I'm a little bit confused by the code.
    We do multimem.ld_reduce on a multicast address on switch and store the final result on H100's local register.  But in the presentation, there are only three partial data sent out.
    Seems that we do 3 partial data reduce on NVSwitch and then do the last reduce on H100?
Best regards,
-Edda

**Comment by dearsxx0918** [comment]
@sjeaugey  Could you please educate me on this?

**Comment by sjeaugey** [comment]
Sorry I missed this.

You are right, this slide isn't accurately reflecting the reality. When we call multimem.ld_reduce, it would pull data from all 4 GPUs and give us the final result.

**Comment by dearsxx0918** [comment]
Thanks for you reply!
