### ISSUE TITLE
NCCL build error: expected unqualified-id before 'long'

### ISSUE THREAD

**Issue by kilasuelika** [NVIDIA/nccl#83]
NCCl is required when building caffe with multi-GPUs. But error occurs when I build NCCL. It's something like:
`make CUDA_HOME=/usr/local/cuda
Grabbing  src/nccl.h                          > /home/li/Downloads/nccl-master/build/include/nccl.h
Compiling src/libwrap.cu                      > /home/li/Downloads/nccl-master/build/obj/libwrap.o
src/core.h:35:16: error: expected unqualified-id before ‘long’
src/core.h:35:16: error: expected ‘)’ before ‘long’
src/core.h:99:1: error: ‘DevRing’ does not name a type
make: *** [/home/li/Downloads/nccl-master/build/obj/libwrap.o] Error 1
`

**Comment by cliffwoolley** [comment]
This is likely due to the version of gcc you are running; see #50.

**Comment by cliffwoolley** [comment]
Did the GCC version resolve your issue?

**Comment by kilasuelika** [comment]
It's too difficult to change the default GCC version of Ubuntu. So I download the pre-built NVCC package in Debian system and install it.
Thank you for your patience.

**Comment by Amostanlee** [comment]
Thanks
