### ISSUE TITLE
cross node nccl-tests with LL128 protocol failed on nccl 2.10.3

### ISSUE THREAD

**Issue by elevenxiang** [NVIDIA/nccl#831]
HI,

When I test socket path with LL128 protocol cross 2 nodes, and I found that data check failed randomly.
Is it a known issue on nccl 2.10.3 ?

Test Command:
mpirun --allow-run-as-root -np 2 -npernode 1 -x NCCL_DEBUG=WARN -x NCCL_PROTO=LL128 -x NCCL_IB_DISABLE=1 -x NCCL_IB_GID_INDEX=3 -H ai001_ip:8,ai002_ip:8 all_reduce_perf -t 1 -g 1 -d float -b 8388608 -e 8388608 -n 1 -w 0

Using devices
Rank  0 Pid 2304899 on a100-01 device  0 [0x54] NVIDIA A100-SXM4-80GB
Rank  1 Pid 161129 on a100-02 device  0 [0x54] NVIDIA A100-SXM4-80GB
NCCL version 2.10.3+cuda11.6

                                                       out-of-place                       in-place
       size         count      type   redop     time   algbw   busbw  error     time   algbw   busbw  error
        (B)    (elements)                       (us)  (GB/s)  (GB/s)            (us)  (GB/s)  (GB/s)
     8388608       2097152     float     sum   5729.5    1.46    1.46  0e+00   5477.3    1.53    1.53  1e+00
Out of bounds values : 2 FAILED
Avg bus bandwidth    : 1.49781

Thanks

**Comment by elevenxiang** [comment]
@sjeaugey from your comment "The LL128 protocol requires a lot of conditions to be met or it can cause data corruption. "
Can I understand that NCCL doesn't guarantee LL128 works under all data path, for example both socket, cuda host memory and GDR mode ?

I would appreciate that if could you share condition that the LL128 protocol must meet.

Thanks

**Comment by AddyLaddy** [comment]
For the LL128 protocol to operate correctly we need 128-byte writes to be delivered "atomically" as the NCCL kernels poll the last 8-byte flag. Once that flag becomes set the kernels assume the preceding 120-bytes is correct.
We have found that some networks and PCI-E switches can split these 128-byte write into multiple blocks and then re-order them, especially when Relaxed Ordering is enabled at points along the data path between the NIC and GPU memory.
Splitting into multiple blocks can be OK as long as the sequential memory order of the writes is not broken.

**Comment by elevenxiang** [comment]
> For the LL128 protocol to operate correctly we need 128-byte writes to be delivered "atomically" as the NCCL kernels poll the last 8-byte flag. Once that flag becomes set the kernels assume the preceding 120-bytes is correct. We have found that some networks and PCI-E switches can split these 128-byte write into multiple blocks and then re-order them, especially when Relaxed Ordering is enabled at points along the data path between the NIC and GPU memory. Splitting into multiple blocks can be OK as long as the sequential memory order of the writes is not broken.

Thank your so much for this detail explanation.
Yes, 128-byte atomic writing  is the base of LL128 protocol
And I also did many tests for this case, and found small size is hard to reproduce, but big size(MB level) will easy to hit it.
socket network is easy to reproduce it, but GDR is hard to hit it

so
1. how could judge if disable LL128 for cross node case ?
2. in NCCL 2.17.1, I found you add once more loading operation after checking the flag, is this a workaround for this issue ?

Thanks

**Comment by elevenxiang** [comment]
@AddyLaddy 

Add one more question:
3. I remembered that older version(before NCCL 2.10.3, which skip the shared memory when 16-byte align address) didn't have this issue. if this means using shared memory as the intermediated buffer isn't affected by re-order behavior ?

Thanks

**Comment by elevenxiang** [comment]
For question 1, I think I found the judgement from the code:

  for (int c=0; c<NCCL_NUM_FUNCTIONS; c++) for (int a=0; a<NCCL_NUM_ALGORITHMS; a++) for (int p=0; p<NCCL_NUM_PROTOCOLS; p++) {
    int pEnable = protoEnable[p];
    if (pEnable == 2 && p == NCCL_PROTO_LL128) {
      // Enable LL128 by default only on Volta/Ampere+NVLink. Other cases are not tested and may cause silent data corruption.
      pEnable = (graphs[a]->typeInter <= PATH_PXB) && graphs[a]->typeIntra <= PATH_NVL &&
        ((minCompCap == 70 && maxCompCap == 70) || (minCompCap == 80 && maxCompCap == 80)) ? 1 : 0;
    }
    if (pEnable == 0) comm->bandwidths[c][a][p] = 0;

**Comment by elevenxiang** [comment]
@AddyLaddy 
I also checked the PCIE spec, and its max payload size is 128 bytes at least which means the smallest split size.
and if so, how could it break the 128-byte writing atomic ?

Thanks

**Comment by elevenxiang** [comment]
> CPUs often break 128B PCI TLPs into 2x64B (because cache line size is 64B). Then the 64B TLPs can be reordered, and it break LL128.
> 
> LL128 is therefore not supported on sockets, as those go through the CPU. Only on NICs with GPU Direct and PCI Switches connecting NICs directly to GPUs (or intranode through NVLink).

got it, understand now.

and I still have last two questions, hope you could help explain
1. older version(before NCCL 2.10.3, which skip the shared memory when 16-byte align address) didn't hit this issue. does it mean using shared memory as the intermediated buffer isn't affected by re-order behavior ? or just lower the hit rate ?
2. in NCCL 2.17.1, I found you add once more loading operation after checking the flag, what does it for ? is looks like a workaround for this issue ?

Thanks
