### ISSUE TITLE
What is the corner case of 'cross-rail communication' when NCCL_CROSS_NIC=0?

### ISSUE THREAD

**Issue by xial-thu** [NVIDIA/nccl#836]
Dear developers:

  I'm investigating on the possibility of not connecting rails at the top for potential cost reduction. The cluster consists of nodes with 2 NICs and 8 GPUs. I notice at document saying

> Note there are corner cases for which NCCL may still cause cross-rail communication, so rails still need to be connected at the top.

  I wonder what is the corner case?

Thx!

**Comment by sjeaugey** [comment]
That is when users create a communicator which contains GPUs on disjoint rails. For example, if the user creates a communicator with GPU 0 on one node and GPU 6 on another node. In that case, the communicator does not include GPU 0 on the other node nor GPU 6 on the first node, so we don't have "relays" between those two GPUs and whey won't be able to communicate with each other.

A variation of this is when we have a set of GPUs which are not rail-aligned, for example with 9 GPUs, 8 on the first node and 1 on the second node. In that case, the sole GPU on the second node won't be able to send data to the 7 other GPUs which are not on its rail.

Finally, NCCL does not provide strong guarantees of not crossing rails. We can try to avoid it, or fix bugs after the fact (when possible), but this is not something we test systematically.

Not connecting rails at the top is taking a significant risk of having applications crash with some test cases, and spend lots of time debugging why the applications is trying to communicate across rails.

**Comment by xial-thu** [comment]
Now my understanding is that if the scenario is limited to homogeneous cluster + LLM training + cabling is all correct, ideally there's no cross-rail communication. ring/tree/collNet topology also helps debugging.

Thanks for the advise, I'll carefully re-consider the case.
