### ISSUE TITLE
Why does NCCL force to post 0-byte work request when enable adaptive routing in Infiniband?

### ISSUE THREAD

**Issue by Tuvie** [NVIDIA/nccl#850]
I am reading the codes of NCCL to understand what happens in NCCL when adaptive routing is enabled in IB network. I notice NCCL forces to post a 0-byte RDMA_WRITE_WITH_IMM after the work request which contains the data as follows:

https://github.com/NVIDIA/nccl/blob/master/src/transport/net_ib.cc#L1008

```C
  struct ibv_send_wr* lastWr = comm->wrs+nreqs-1;
  if (nreqs > 1 || (comm->ar && reqs[0]->send.size > ncclParamIbArThreshold())) {
    // When using ADAPTIVE_ROUTING, send the bulk of the data first as an
    // RDMA_WRITE, then a 0-byte RDMA_WRITE_WITH_IMM to trigger a remote
    // completion.
    lastWr++;
    memset(lastWr, 0, sizeof(struct ibv_send_wr));
  }
  lastWr->wr_id = wr_id;
  lastWr->opcode = IBV_WR_RDMA_WRITE_WITH_IMM;
  lastWr->imm_data = immData;
  lastWr->next = NULL;
  lastWr->send_flags = IBV_SEND_SIGNALED;
```

Why do we need to do this? What if I just post the data work request with imm_data?

**Comment by sjeaugey** [comment]
RDMA_WRITE_WITH_IMM messages do not use adaptive routing. Hence we replace it by an RDMA_WRITE (which can use adaptive routing), followed by a 0-byte RDMA_WRITE_WITH_IMM to force ordering and generate the completion on the receiver side.

**Comment by Tuvie** [comment]
I see. Thanks a lot

**Comment by mohanjiao** [comment]
If the 0-byte RDMA_WRITE_WITH_IMM package arrives first, will it cause the retransmission of the write package?
