### ISSUE TITLE
some questions about workFifo and workFifoDev

### ISSUE THREAD

**Issue by MonroeD** [NVIDIA/nccl#868]
```c++
  // Per-channel operation list.
  NCCLCHECK(ncclCudaHostCalloc(&channel->workFifo, NCCL_MAX_OPS));
  if (ncclGdrCopy != NULL && ncclParamGdrCopyFifoEnable() == 1) {
    // GDRCOPY support
    // We allocate a workFifo in GDR mapped CUDA memory
    // But we still allocate the Host workFifo so that we
    // can copy the work elements to CUDA memory on kernel launch
    NCCLCHECK(ncclGdrCudaCalloc(&channel->workFifoGdr, &channel->workFifoDev, NCCL_MAX_OPS, &channel->gdrMemDesc));
  } else {
    // The device workFifo is the Host one
    channel->workFifoDev = channel->workFifo;
  }
```
I noticed that workFifoDev is directly pointing to workFifo (allocated by cudaHostAlloc). I would like to ask if this is necessary to do this? Can I use cudaMalloc for workFifo and then use cudaMemcpy to transfer data?  So is workFifo used for host-device interaction during kernel execution? (just like abortFlag?)

tag v2.12.12-1

**Comment by jbachan** [comment]
You could upload the fifo data via cudaMemcpy but that's usually higher latency than having the kernel read from host memory. There is no interaction while the kernel is running, by that time the memory is read only.
