### ISSUE TITLE
Will the channel in same Graph use NVlink as well as PCIe to transport?

### ISSUE THREAD

**Issue by uubs** [NVIDIA/nccl#869]
hi, 
   I have some doubt about search Graph process.

  1. Will the channel in same Graph use NVlink as well as PCIe to transport?
     eg: intra[0] as channel 0 use  NVLink as P2p transport, intra[1] use PCIe as P2p transport

  2. if so, how can I config to use NVllink as P2p only?

Thanks.

**Comment by sjeaugey** [comment]
If there is an NVLink connection between two GPUs, then CUDA will only use NVLink, not PCI. So NCCL will never assume a PCI path between GPUs which are NVLink-connected.

**Comment by uubs** [comment]
thanks for your reply.

I still have some double about the search channel result.

say, I have the following paths get from computePaths

```
    GPU0  GPU1  GPU2  GPU3  GPU4  GPU5  GPU6  GPU7  CPU Affinity  NUMA Affinity
GPU0   X    NV1   NV2   NV1   SYS   SYS   SYS   NV2   0-17,36-53        0
GPU1  NV1    X    NV1   NV2   SYS   SYS   NV2   SYS   0-17,36-53        0
GPU2  NV2   NV1    X    NV2   SYS   NV1   SYS   SYS   0-17,36-53        0
GPU3  NV1   NV2   NV2    X    NV1   SYS   SYS   SYS   0-17,36-53        0
GPU4  SYS   SYS   SYS   NV1    X    NV2   NV2   NV1   18-35,54-71       1
GPU5  SYS   SYS   NV1   SYS   NV2    X    NV1   NV2   18-35,54-71       1
GPU6  SYS   NV2   SYS   SYS   NV2   NV1    X    NV1   18-35,54-71       1
GPU7  NV2   SYS   SYS   SYS   NV1   NV2   NV1    X    18-35,54-71       1
```

Is there a chance that channel(0->1->2->3->4->5->6->7) and channel(0->4->5->6->7->1->2) both exist in graph?

here,

channel(0->1->2->3->4->5->6->7) is all connected by NVLink,

some rank of  channel(0->4->5->6->7->1->2) connected by PCIe+QPI， while other connected by NVLink.

**Comment by uubs** [comment]
thanks for your tips. I finally almost figure it out.

what I figure out is that,
channel(0->4->5->6->7->1->2) will only exist during the recursive search process, but it will never show up(for my instance) at the saved Graph(prior Graph).
Cause the Graph including the channel don't have the maximum (nChannel*bwIntra).

if it is wrong, could you correct me?
