### ISSUE TITLE
src/core.cu(717): error: identifier "so" is undefined

### ISSUE THREAD

**Issue by whu-zhangz** [NVIDIA/nccl#87]
When I am building the nccl with cuda 8.0, I meet these errors.
```
Compiling src/core.cu                         > /home/dell/caffe2/third_party/nccl/build/obj/core.o
src/core.cu(717): error: identifier "so" is undefined

1 error detected in the compilation of "/tmp/tmpxft_00001ee3_00000000-11_core.compute_52.cpp1.ii". 
'''

Is there anyone who can help me figure it out? Thanks very much.

**Comment by cliffwoolley** [comment]
This is likely due to the GCC version you're using.
See #50 #81 #83 
Please reopen if this does not resolve your issue.

**Comment by vahidn83** [comment]
I get the same error (src/core.cu(719): error: identifier "so" is undefined) using GCC 4.8.5 on CentOS 7. Should I still upgrade GCC?
