### ISSUE TITLE
what's the differences between ALGO collnetChain and collnetDirect

### ISSUE THREAD

**Issue by tyronfong** [NVIDIA/nccl#873]
hi, may i know what's the differences between ALGO collnetChain and collnetDirect? nothing found in google or nvidia document TAT.

**Comment by sjeaugey** [comment]
NCCL implementation details are explained during GTC talks. Here is the talk from this year:
https://www.nvidia.com/en-us/on-demand/session/gtcspring23-s51111/

The difference between collnetChain and collnetDirect is explained slides 21-23, or you can watch the video starting at 19:58.
