### ISSUE TITLE
Does the NCCL library support automatic selection of different types of network cards, such as Ethernet and high-speed IB network cards?

### ISSUE THREAD

**Issue by pengshuang** [NVIDIA/nccl#878]
Our scenario involves two heterogeneous GPU clusters, Cluster A and Cluster B, each consisting of 20 GPU machines (A100-80G). Cluster A is internally equipped with both high-speed IB cards and regular Ethernet cards, while Cluster B is internally equipped with high-speed RoCE cards and regular Ethernet cards. Due to the inability to establish a high-speed IB network between Cluster A and Cluster B, communication between them can only be done via Ethernet using TCP/IP (Socket).

Our objective is to have machines within Cluster A and Cluster B connected through high-speed cards, while machines between Cluster A and Cluster B are connected through regular Ethernet networking. I would like to inquire whether NCCL supports automatic card detection and configuration to enable distributed training between the heterogeneous clusters. If it doesn't support it, is it possible to achieve this by modifying the source code?

I am unsure of the feasibility and would greatly appreciate your response. Thank you very much!

**Comment by sjeaugey** [comment]
NCCL cannot use both the IB/RoCE network and TCP/IP in the same communicator. But with recent versions, you can create different communicators (an intra-domain group and and inter-domain group), then for each communicator you can select which network to use.

To do that, you need to create your communicators with ncclCommInitRankConfig, and pass `config.netName="IB"` on the ones using IB/RoCE and `config.netName="Socket"` on the one communicating between clusters.

**Comment by pengshuang** [comment]
Thank you for your prompt response, and I apologize for my lack of familiarity with the relationship between NCCL and PyTorch. In our current setup, we are using the [Megatron-LM](https://github.com/NVIDIA/Megatron-LM) repository based on PyTorch. I would like to inquire whether we need to modify the corresponding PyTorch code or directly modify the NCCL code.

For example, regarding the `ncclCommInitRankConfig` you mentioned, which file do I need to edit?

 I am looking forward to your response. Thank you very much!

**Comment by pengshuang** [comment]
Thank you for your answer.
