### ISSUE TITLE
How to use nccl to complier my code?

### ISSUE THREAD

**Issue by FaceOP** [NVIDIA/nccl#88]
I want to add nccl function on my code.
I reference many .pdf .
like : [nccl 2016](http://on-demand.gputechconf.com/gtc/2016/presentation/s6616-nathan-luehr-nccl.pdf)

Here is my part of code

> int nGPUs;
    //Get "How many GPUs d you have"
    cudaGetDeviceCount(&nGPUs);
    ncclComm_t* comms = (ncclComm_t*)malloc(sizeof(ncclComm_t)*nGPUs);
    ncclCommInitAll(comms, nGPUs,{0, 1, 2, 3});

I use nvcc to complier this code 
return to error on line 5 ;

> error: expected an expression

I am sure I get the nGPUs is 4.

How to use nccl?

**Comment by sjeaugey** [comment]
I think the compiler is complaining that the syntax {0, 1, 2, 3} is not allowed in C as an argument to a function.

**Comment by FaceOP** [comment]
I solved it!
It just add -lnccl when complier.
like
`nvcc XX.cu -lnccl`
