### ISSUE TITLE
applyLoadMultimem api confused usage

### ISSUE THREAD

**Issue by heguixiang** [NVIDIA/nccl#881]
Hi NCCL contributors! I noticed a relatively large NCCL change recently @sjeaugey , and there is one place that I don’t understand very well, so I would like to ask for advice.

Mainly about the differences in the following screenshots:
![image](https://github.com/NVIDIA/nccl/assets/16131498/aaac7009-78a7-4659-9413-9d776ff6931c)

According to my understanding, the applyLoadMultimem API called on the right side of the screenshot should be used to apply the Hopper series chip multimem instruction. The purpose is to reduce the user's amount of load instructions to aggregate the buffers address which the multimem pointed to. But after looking at the usage here, it seems that we still need to load the data one by one like ordinary ld_volatile_global API, and then call applyReduce to calculate the results. I didn’t see the benefits brought by multimem, and I look forward to your reply, thanks.

**Comment by sjeaugey** [comment]
Loading from a multicast address requires specific instructions, hence the specific code. 
In all cases today, we'll have a single multimem source, i.e. we'll perform a single load to get the sum for all GPUs on the node.
But we may still need to add that to other sources, like data coming from the network in a multi-node case, hence we need to check for other sources and reduce the values.

**Comment by heguixiang** [comment]
Thank you for your prompt reply.
Ok, I got it, so I can understand that when the current NCCL code uses multimem instructions and does not need to cross the network, then must MinSrcs=MaxSrcs=1, because Resv=1 is no longer required, right? No need to perform additional applyReduce operations at this time?
There is another question. As far as I know, the latest driver of cuda release does not support NVLink SHArP. When will this be released? Thanks.

**Comment by sjeaugey** [comment]
> when the current NCCL code uses multimem instructions and does not need to cross the network, then must MinSrcs=MaxSrcs=1, because Resv=1 is no longer required, right? No need to perform additional applyReduce operations at this time?

Yes, correct.

> As far as I know, the latest driver of cuda release does not support NVLink SHArP. When will this be released?

I think this is platform specific, as some platforms already support NVLink SHARP on CUDA 12.1. But the schedule of CUDA drivers and toolkits is outside of our scope.

**Comment by heguixiang** [comment]
Got it, thanks for your reply and great contribution . ：）
