### ISSUE TITLE
Questions about NCCL_TOPO_MAX_NODES

### ISSUE THREAD

**Issue by MonroeD** [NVIDIA/nccl#885]
I noticed that NCCL_TOPO_MAX_NODES is set to 256. Does this mean that the entire system supports a maximum of 256 nodes within a specific node type using nccl? and NCCL_TOPO_MAX_LINKS is 32, why these numbers

**Comment by sjeaugey** [comment]
This define is only in the context of the intra-node topology graph. "Node" here means node in a graph. Likewise, "Link" is how we connect nodes in The graph together.

So our topology graph supports up to 256 CPUs, 256 GPUs, 256 PCI switches and 256 NICs, where each of those nodes can connect to up to 32 other nodes.
