### ISSUE TITLE
Does current NCCL released version support cross node NVLink SHArP feature？And will it be supported in the future?

### ISSUE THREAD

**Issue by heguixiang** [NVIDIA/nccl#888]
Dear @sjeaugey,
A.T.T. 
e.g. For super DGX 256 cards，and per node 8 cards，NVLink SHArP feature can be used as a single multimem instruction to get the sums of all 256 cards result, a.k.a. does NVLink SHArP feature can cross nodes by multi layer NVSwitch3.0 connected? 
If it is not supported now, will it be supported in the future?
Look forward to your replay，thanks！

**Comment by sjeaugey** [comment]
NCCL will support features when products are released, and after CUDA supports it. At the moment none of that is released, so NCCL cannot support it.

**Comment by heguixiang** [comment]
So I can understand that it can be supported in the future, right? Currently, just because of the lack of some cross-node related driver api support?
