### ISSUE TITLE
Does NCCL support command level NVLink SHArP feature?

### ISSUE THREAD

**Issue by heguixiang** [NVIDIA/nccl#895]
Dear NCCL contributors,

I am doing network training on a large number of H800 clusters, and I am very concerned about end-to-end reliability control. So we prefer to use command level NVLink SHArP feature, does NCCL support command level NVLink SHArP feature? If yes, How can I enable it, and if no, have any plan to support it in the feature?

Looking forward to your replay, thanks!

**Comment by heguixiang** [comment]
> 

The “command level” NVLink SHAtP here actually refers to trigger SHArP feature through DMA command copy.

**Comment by sjeaugey** [comment]
I see. There is no DMA. NVLink SHARP operation relies on simple load/store operations on virtual memory regions which alias to a set of buffers on multiple GPUs. When you perform a store to an MC address, data gets written to each of the buffers; when you perform a load_reduce on that address, you get the sum of all the values from all GPUs.

**Comment by heguixiang** [comment]
OK，got it，thanks for your reply！
