### ISSUE TITLE
Why x86 intel CPU can't use p2p in topo PHB?

### ISSUE THREAD

**Issue by jiangxiaobin96** [NVIDIA/nccl#896]
https://github.com/NVIDIA/nccl/blob/ea38312273e5b9a19a224c9ff4c10b7fcf441eaf/src/graph/paths.cc#L291
From code, we can see x86 intel CPU can't use p2p transport when gpu topology is PHB. If not seting userP2pLevel like `NCCL_P2P_LEVEL`, two gpus will communicate through net even though seting `NCCL_P2P_USE_CUDA_MEMCPY`.
However I test `cudaDeviceCanAccessPeer` function in PHB, it can use memcpyDeviceToDevice. So why here can not use p2p?

**Comment by sjeaugey** [comment]
It's not that we cannot use P2P, more that it is faster to use shared memory. Now, I'm not sure why you're saying it would use NET instead of P2P. I can see how using NET could be faster in some situations but in most cases, NCCL should use SHM instead of P2P.

**Comment by jiangxiaobin96** [comment]
OK, I understand. So if two GPUs can connect by p2p,  do they use Unified Virtual Addressing or `cudaMemcpyDeviceToDevice` to transfer data? If using  `cudaMemcpyDeviceToDevice`, I find it works in `p2pSendProxyProgress` function, but  this only works when enable `NCCL_P2P_USE_CUDA_MEMCPY`.

**Comment by sjeaugey** [comment]
>  if two GPUs can connect by p2p, do they use Unified Virtual Addressing or cudaMemcpyDeviceToDevice to transfer data?

No, unless you set `NCCL_P2P_USE_CUDA_MEMCPY` but that can lead to hangs unless we create a different context, and even in that case, it's not 100% safe. So by default, NCCL will only use direct memory access between GPUs, which has a much better latency.
