### ISSUE TITLE
how to add a path to LD_LIBRARY_PATH

### ISSUE THREAD

**Issue by Alex1991hua** [NVIDIA/nccl#90]
when I into torch and run require 'nccl，then have this problem
th> require 'nccl'
Tried loading libnccl.so.1 but got error /usr/local/share/lua/5.1/nccl/ffi.lua:192: libnccl.so.1: cannot open shared object file: No such file or directory	
Tried loading libnccl.1.dylib but got error /usr/local/share/lua/5.1/nccl/ffi.lua:192: libnccl.1.dylib: cannot open shared object file: No such file or directory	
/usr/local/share/lua/5.1/trepl/init.lua:389: /usr/local/share/lua/5.1/trepl/init.lua:389: /usr/local/share/lua/5.1/nccl/ffi.lua:201: 'libnccl.so could not be loaded, please refer to error messages above. If libnccl.so was not found, 
please install nccl, then make sure all the files named as libnccl.so* are placed in your library load path 
    (for example /usr/local/lib , or manually add a path to LD_LIBRARY_PATH)

stack traceback:
	[C]: in function 'error'
	/usr/local/share/lua/5.1/trepl/init.lua:389: in function 'require'
	[string "_RESULT={require 'nccl'}"]:1: in main chunk
	[C]: in function 'xpcall'
	/usr/local/share/lua/5.1/trepl/init.lua:661: in function 'repl'
	/usr/local/lib/luarocks/rocks/trepl/scm-1/bin/th:204: in main chunk
	[C]: at 0x00406020	
                                                                      [0.2437s]
th>

**Comment by sjeaugey** [comment]
Usually that's done with the following shell command :
```
export LD_LIBRARY_PATH=<directory-where-libnccl.so.1-is>:$LD_LIBRARY_PATH
```
So if you compiled NCCL in your home directory, in a "nccl" subdirectory, which would be something like  /home/user/nccl, you would set :
```
export LD_LIBRARY_PATH=/home/user/nccl/build/lib:$LD_LIBRARY_PATH
```

**Comment by Alex1991hua** [comment]
Thanks for your reply, and still encountered the following problem.

   In CentOS 7, I install nccl under root user. However, other users can’t load it directly whilst have to add path every time

    (export LD_LIBRARY_PATH=/home/root/nccl/build/lib:$LD_LIBRARY_PATH).

   Otherwise, when executing <require 'nccl' > in torch, there occur errors. Can I install nccl in a no user-specific path, and load it without set the PATH?

**Comment by cliffwoolley** [comment]
You should install into a system path rather than into the root user's home directory.  Then you won't need the LD_LIBRARY_PATH variable, either.

Exact instructions on where the best place to install is will vary from distro to distro.

**Comment by elliotekoch** [comment]
Strange I too am having issues with libnccl.so.1, but after installing nccl severla times, redoing Cuda, Cudnn, and torch I have this issue, and even after deliberate search throughout my /root and /usr/* directories I cannot find ANY libncll.so* anywhere.  Is it possible something is missing in the nccl package?

Tried loading libnccl.so.1 but got error /root/torch/install/share/lua/5.1/nccl/ffi.lua:192: libnccl.so.1: cannot open shared object file: No such file or directory
Tried loading libnccl.1.dylib but got error /root/torch/install/share/lua/5.1/nccl/ffi.lua:192: libnccl.1.dylib: cannot open shared object file: No such file or directory
warning: could not load nccl, falling back to default communication
