### ISSUE TITLE
dependency inside NCCL group

### ISSUE THREAD

**Issue by anchenchai** [NVIDIA/nccl#900]
Hi there,
  NCCLCHECK(ncclGroupStart());
  NCCLCHECK(ncclBroadcast(..., stream0));
  CUDACHECK(cudaEventRecord(notify, stream0));
  CUDACHECK(cudaStreamWaitEvent(stream1, notify, 0));
  NCCLCHECK(ncclAllReduce(..., stream1));
  NCCLCHECK(ncclGroupEnd());

As the example shown above, I try to add dependency between stream0 and stream1 using cuda event. Does ncclGroup guarantee this kind of stream dependency, i.e., allreduce will be executed after broadcast? Or we lose this kind of dependency inside NcclGroup.

Thanks.

**Comment by sjeaugey** [comment]
We should not include stream operations inside the group. All NCCL stream operations will happen during ncclGroupEnd. NCCL can fuse all operations within a group as a single operation, so there is no way to add dependencies between operations of the same group as they're supposed to happen concurrently. If you want one to happen after the other, they need to be in different groups.

**Comment by anchenchai** [comment]
OK，thanks for your reply.
