### ISSUE TITLE
NCCL only use RDMA_WRITE/READ why it still got opcode 0 error 12 err

### ISSUE THREAD

**Issue by zrss** [NVIDIA/nccl#902]
> https://www.rdmamojo.com/2013/02/15/ibv_poll_cq/

opcode 0 in wc, means that is a `IBV_WC_SEND`, but i can't find any `WR_SEND` in nccl ib codes

```
NCCL WARN NET/IB : Got completion with error 12, opcode 0, len 0, vendor err 129
```

can anyone give some hints

**Comment by zrss** [comment]
> Indeed we only use RDMA_WRITE and RDMA_WRITE_WITH_IMM (with length 0). Not sure why we have `opcode 0` but maybe that's bad reporting.
> 
> In any case, error 12 is a communication timeout and a very common error, which either means two NICs can't talk to each other (missing link, routing for RoCEv2, ...), or the network connection is very bad so we hit the timeout. In the latter case, increasing NCCL_IB_TIMEOUT can help, but if NICs can't talk to each other, it will not solve anything.

Many thanks for your quick reply. @sjeaugey , by the way, currently, we try to reproduce this error 12 problem in RoCE V2 network, as lower down the `NCCL_IB_TIMEOUT=1` and `NCCL_IB_RETRY_CNT=0`, with the `ib_write_bw` large network flow between RoCE NIC, this problem can quickly occur

so is there other option, such as we can increase the `NCCL_IB_RETRY_CNT` rather then `NCCL_IB_TIMEOUT`

https://docs.nvidia.com/deeplearning/nccl/user-guide/docs/env.html#nccl-ib-retry-cnt

* NCCL_IB_RETRY_CNT: default value 7

**Comment by sjeaugey** [comment]
You can get a timeout with `NCCL_IB_TIMEOUT=1`, `NCCL_IB_RETRY_CNT=0` on any system, so it's doesn't really teach us anything.

Does the error always happen at the same point, or is it more random?

**Comment by zrss** [comment]
thanks for your reply @sjeaugey , about this err, any advice would be great help

> You can get a timeout with NCCL_IB_TIMEOUT=1, NCCL_IB_RETRY_CNT=0 on any system, so it's doesn't really teach us anything.

yes, we confirm the `NCCL_IB_RETRY_CNT` and `NCCL_IB_TIMEOUT` can help *real* network timeout problem by previous experiments (`NCCL_IB_TIMEOUT=1`, `NCCL_IB_RETRY_CNT=0`).

but, recently, my training job, torch 1.13.1, nccl 2.14.3-1, even when it set `NCCL_IB_TIMEOUT=25` (about 2min), randomly running 48 - 96h (2 ~ 4 days) will still (suddenly) throw out the `NCCL WARN NET/IB : Got completion with error 12` error. and the training speed is normal before the problem occur.

from the monitor metrics of switch and nic, there are no dropped/error packets record. and there has stable 5Gbits/s flow rate in switch port (which connected to the training server nic), before the problem occur, and the rate fall down to ~0Gbit/s rate after the problem occur. generally, that says the network seems work well during the problem occur :)

so we doubt maybe the mlnx cx5 (RoCE) or mlnx ofed (4.9 LTS) bug ? but lack of log and proof :disappointed_relieved:

---

besides, by reading nccl codes (2.14.3-1), it seems the ib qp are pre created, and print out by following code

```
      INFO(NCCL_NET,"NET/IB: Dev %d Port %d qpn %d mtu %d GID %ld (%lX/%lX)", dev, ib_port, qpInfo.qpn[q], qpInfo.mtu, ncclParamIbGidIndex(), qpInfo.spn, qpInfo.iid);
```

but the remote side (accept side), nccl lack of the log out like the connect side (above-mentioned code). and ib communication in roce network flow can exact locate by the server rdma nic ip (roce), qp num and client rdma nic ip (roce), qp num. that is reason why i post the propose https://github.com/NVIDIA/nccl/pull/880, :satisfied:, certainly, there still has a lot of code work to do ...

**Comment by sjeaugey** [comment]
Do you believe that when the hangs occurs, your application is trying to connect to a new peer it never talked to before? `NCCL_DEBUG=INFO` would indeed show that.

In that case, could it be come peers are simply inaccessible, for example if you are on a system with multiple NICs but NIC 0 on one node cannot communicate with NIC 1 on another node? That's a classic issue on RoCE systems where each NIC is in a separate subnet with no routing between subnets.

**Comment by sjeaugey** [comment]
Could be a flapping link, causing random timeouts. These usually disappear as systems get more stable, cables are re-plugged, and less people walk near the machines.

Feel free to close if you believe that's resolved.
