### ISSUE TITLE
Memory consistency across GPUs

### ISSUE THREAD

**Issue by Zha0q1** [NVIDIA/nccl#903]
I have been working on understanding NCCL code recently.

A general question is, when we exchange data via NVLink (IPC or multicast) between two local GPUs, how does NCCL make sure the reader sees the writes?

I was looking at the release/acquire model but could not fully understand the steps https://docs.nvidia.com/cuda/parallel-thread-execution/#memory-consistency-model

@sjeaugey would you share some insights? Thanks!

**Comment by Zha0q1** [comment]
Did more research:

1. https://github.com/NVIDIA/nccl/issues/572 this thread suggests there is an extra warp dedicated to call threadfence_system() to avoid bubbling of the main warps
2. https://github.com/NVIDIA/nccl/issues/765 this thread suggests per 128 bits write, 8 bits are used as controller bits so that threadfence_system() is not needed altogether

Which solution is used in the main branch today? Or, do both solution exist and serve different collectives (in that case which solution does all_gather use)? 

@sjeaugey @jbachan  would appreciate your help!

**Comment by sjeaugey** [comment]
1. That's indeed a correct description of how the `Simple` protocol works.
2. That's the `LL128` protocol, where 8 Bytes (not bits) are used out of 128 Bytes (not bits) to indicate data has been written. That implies a maximum bandwidth of 6% less peak bandwidth but the latency is better. LL128 doesn't work everywhere though as we need to make sure 128B stores are not cut and reordered.
3. In addition to that there is the `LL` protocol which has an even better latency and a worse bandwidth.

All 3 protocols can be used with the `Tree` and `Ring` algorithms, used by all collectives. Some algorithms (Collnet, NVLS, or send/recv) only support the `Simple` protocol at the moment.

**Comment by Zha0q1** [comment]
Thanks @sjeaugey  that's very clear!

Follow up questions on `LL128`
```
inline __device__ void store128(uint64_t* ptr, uint64_t v0, uint64_t v1) {
  asm volatile("st.volatile.global.v2.u64 [%2], {%0,%1};"
      :: "l"(v0), "l"(v1), "l"(ptr));
}
```
1. My understanding is that `store128` or `st.volatile.global.v2.u64` is the largest store instruction, and it's 128 bits. I can understand how 8 bits out of 128 bits could be used as controlling bits. But you mentioned that in reality NCCL `LL128` uses 8 bytes out of 128 bytes. What is the instruction used to guarantee that those 128 bytes appear atomically? 
2. I did not find any open reference as to which platforms can safely use `LL128`. I am mainly using A100 and H100 GPUs. Are those safer?

**Comment by Zha0q1** [comment]
More specifically on question 1 --
```
    if (SEND) {
      for (int i=1; i<MaxSend && i<fan.nsend(); i++) {
        uint64_t flag = sendFlag(i);
        uint64_t* ptr = sendPtr(i)+ll128Offset;
        #pragma unroll
        for (int u=0; u<ELEMS_PER_THREAD; u+=2) {
          store128(ptr+u*WARP_SIZE, v[u], flagThread ? flag : v[u+1]);
        }
      }
      uint64_t flag = sendFlag(0);
      uint64_t* ptr = sendPtr(0)+ll128Offset;
      #pragma unroll
      for (int u=0; u<ELEMS_PER_THREAD; u+=2) {
        store128(ptr+u*WARP_SIZE, v[u], flagThread ? flag : v[u+1]);
      }
    }
```
So out of every 8 threads, 1 of them is `flagThread`. When we send, thread 0-6 stores 16 bytes of data and thread 7 stores 8 bytes of data and 8 bytes of flag. How do we guarantee that those 128 bytes appear atomically to the receiver? Again my setup is 8 H100 GPUs connected with NVLink, no network involved

**Comment by sjeaugey** [comment]
> What is the instruction/algorithm/trick used to guarantee that those 128 bytes appear atomically?

CUDA does not guarantee LL128 operation (not today and therefore not moving forward), and users should not try to replicate this. We rely on the compiler not breaking ordering, then on the HW aggregating load/stores at the warp level into 128B load/stores, then transmitting those 128B load/stores through NVLink or PCI switches without breaking them. This is something we have to qualify for each new compiler version, new HW architecture and also NVSwitch/PCI switches; and we may need to adapt the code ffrom time to time (or disable LL128 when it may not work). So if you copy and paste the code today it may work for you, but long term you may end up with silent data corruption which is not good.

**Comment by Zha0q1** [comment]
Understood! Thank you Sylvain! Closing the issue now
