### ISSUE TITLE
When will p2pTransport be used ?

### ISSUE THREAD

**Issue by ziannchen** [NVIDIA/nccl#907]
Hi nccl's developers. I am learning about nccl source code. 

I think nccl will use kernel for intra-node data transfer between GPUs, and use net (ib or socket) in proxy threads for inter-node data transfer. But I notice that there is a 'p2pTransport' in src/transport/p2p.cc, so when will this 'p2pTransport' be used? Is there a case that nccl will use cudaMemcpy of p2pTransport to do intra-node data transfer between GPUs,  instead of using kernel?

**Comment by ziannchen** [comment]
I see nccl introduces NCCL_P2P_USE_CUDA_MEMCPY env var in 2.13.4-1.

When we set NCCL_P2P_USE_CUDA_MEMCPY=1, p2pTransport.send.proxyProgress will point to p2pSendProxyProgress, and p2pSendProxyProgress is implemented by cudaMemcpyAsync.

**Comment by sjeaugey** [comment]
The p2p transport is the code that uses NVLink. In general, it just maps buffers between GPUs for direct access.

We added an option to use CUDA memcpy indeed, which can give better performance on specific architectures, but can also cause hangs. Creating a separate subcontext for the progress proxy helps avoiding hangs, although without guarantees.

**Comment by vvmex** [comment]
@ziannchen hi, did you get the solution that sendrecv operation is used by the cudaMemcpy instead of gpu kernel? If true,could you tell me the way, thanks very much

**Comment by sjeaugey** [comment]
At this time, NCCL does not provide the option to use cudaMemcpy for send/recv operations instead of GPU kernels.
