### ISSUE TITLE
what is the latest release version of NCCL?

### ISSUE THREAD

**Issue by mortada** [NVIDIA/nccl#91]
According to this page http://docs.nvidia.com/deeplearning/dgx/tensorflow-release-notes/rel_17.04.html#rel_17.04 it looks like there is already a 1.6.1 version of NVIDIA NCCL 

However on this github repo the latest version is 1.3.4 https://github.com/NVIDIA/nccl/releases 

Which one is correct?

**Comment by cliffwoolley** [comment]
Version 1.3.4 is the latest open-source release; it is focused on PCIe
communication.  NCCL 1.6-series releases add support for NVLink
communication and are available in binary form as part of the DL frameworks
images released monthly to DGX-1 customers as described in the release
notes you cited.


NCCL 2, which was announced last week at GTC 2017, will unify the two
versions.  Look for NCCL 2 to be released through the NVIDIA Developer Zone
in July.

Thanks,

Cliff

**Comment by mortada** [comment]
thanks @cliffwoolley , close this issue
