### ISSUE TITLE
Questions about adding paths

### ISSUE THREAD

**Issue by Alex1991hua** [NVIDIA/nccl#92]
In CentOS 7, I install nccl under root user. However, other users can’t load it directly whilst have to add path every time

(export LD_LIBRARY_PATH=/home/root/nccl/build/lib:$LD_LIBRARY_PATH).
Otherwise, when executing <require 'nccl' > in torch, there occur errors. Can I install nccl in a no user-specific path, and load it without set the PATH?

**Comment by cliffwoolley** [comment]
This is a dupe of #90.
