### ISSUE TITLE
NCCL error and  trigger S3 error

### ISSUE THREAD

**Issue by ForFishes** [NVIDIA/nccl#920]
When NCCL is running, the program exits abnormally and the following error occurs:

`arrow\cpp\src\arrow\filesystem\s3fs.cc:2598: arrow::fs::FinalizeS3 was not called even though S3 was initialized. This could lead to a segmentation fault at exit`

<img width="1132" alt="0054dc8bf6a9dffacc8b068fafe4eee3" src="https://github.com/NVIDIA/nccl/assets/19485646/1f6140e9-6b3d-4097-b134-e18c98af8e4d">

**Comment by KaimingOuyang** [comment]
Can you set `NCCL_DEBUG=INFO` and provide the log?

**Comment by Zhanghahah** [comment]
any updates? or solutions. I also meet this bug , Thx
