### ISSUE TITLE
NCCL_SHM_USE_CUDA_MEMCPY causes performance degradation

### ISSUE THREAD

**Issue by tangrc99** [NVIDIA/nccl#922]
I'm testing nccl's performance using nccl-tests on 8 - A10 machine. When using env  NCCL_SHM_USE_CUDA_MEMCPY, the performance is much lower in some cases. 
I'm using nccl 2.18.1 and cuda 11.4

Here are the command and outputs:
`-x NCCL_SOCKET_IFNAME=eth0 -x NCCL_DEBUG=INFO -x PATH -x NCCL_IB_GID_INDEX=1 -x LD_LIBRARY_PATH -x NCCL_SHM_USE_CUDA_MEMCPY=1 -x NCCL_P2P_USE_CUDA_MEMCPY=1 -x NCCL_CREATE_THREAD_CONTEXT=1 ./build/all_reduce_perf -b 2 -e 1024M -f 2 -g 1 
` 

the ring:
![image](https://github.com/NVIDIA/nccl/assets/65721989/55d30bb0-c437-47b4-92a0-5ce3faf8d1da)

test result without NCCL_SHM_USE_CUDA_MEMCPY and NCCL_SHM_USE_CUDA_MEMCPY
       size         count      type   redop    root     time   algbw   busbw #wrong     time   algbw   busbw #wrong
        (B)    (elements)                               (us)  (GB/s)  (GB/s)            (us)  (GB/s)  (GB/s)     
       32768          8192     float     sum      -1    36.83    0.89    1.56      0    35.83    0.91    1.60      0
       65536         16384     float     sum      -1    38.50    1.70    2.98      0    37.71    1.74    3.04      0
      131072         32768     float     sum      -1    118.1    1.11    1.94      0    117.9    1.11    1.95      0
      262144         65536     float     sum      -1    127.0    2.06    3.61      0    127.1    2.06    3.61      0
      524288        131072     float     sum      -1    153.0    3.43    6.00      0    153.2    3.42    5.99      0
     1048576        262144     float     sum      -1    199.6    5.25    9.19      0    200.4    5.23    9.16      0

test result with NCCL_SHM_USE_CUDA_MEMCPY=1 and NCCL_SHM_USE_CUDA_MEMCPY=1
       size         count      type   redop    root     time   algbw   busbw #wrong     time   algbw   busbw #wrong
        (B)    (elements)                               (us)  (GB/s)  (GB/s)            (us)  (GB/s)  (GB/s)     
       32768          8192     float     sum      -1    36.46    0.90    1.57      0    35.86    0.91    1.60      0
       65536         16384     float     sum      -1    38.25    1.71    3.00      0    37.61    1.74    3.05      0
      131072         32768     float     sum      -1    282.5    0.46    0.81      0    278.1    0.47    0.82      0
      262144         65536     float     sum      -1    289.4    0.91    1.59      0    287.3    0.91    1.60      0
      524288        131072     float     sum      -1    307.9    1.70    2.98      0    308.6    1.70    2.97      0
     1048576        262144     float     sum      -1    414.4    2.53    4.43      0    415.5    2.52    4.42      0

Why the performance is much lower when size is between 131072 and 1048576 ?

**Comment by KaimingOuyang** [comment]
Because CE engine imposes a higher launch overhead.

**Comment by tangrc99** [comment]
Thanks for your kind reply!

In issue [#907](https://github.com/NVIDIA/nccl/issues/907) and [#803](https://github.com/NVIDIA/nccl/issues/803) , the env NCCL_SHM_USE_CUDA_MEMCPY and NCCL_P2P_USE_CUDA_MEMCPY can give better performance on specific architectures.

In which case can these ENVs give a better performance? Is specific package size or specific GPU architectures required?

**Comment by KaimingOuyang** [comment]
Generally, CUDA_MEMCPY is designed for medium and large message sizes (e.g. tens of MB to GB). However, if you are using AMD CPU which is a bad switch can cause a lot of overhead if CUDA_MEMCPY is not turned on. However, if you are using PCIe switches or NVLink, I would expect CUDA_MEMCPY only provides slightly better perf when message size is large enough.

**Comment by tangrc99** [comment]
Thanks, I tested performance when message sizes are 16MB ~ 1GB. As expected, CUDA_MEMCPY provides a better performance.
