### ISSUE TITLE
nvvp fails with nccl's reduce_test or any code with reduce or other nccl calls.

### ISSUE THREAD

**Issue by pseudotensor** [NVIDIA/nccl#93]
First run in nvvp works fine, but  "Examine GPU Usage" or any "Examine Individual Kernels"  locks the screen and eventually (after about 10 seconds) fail to run and just reports:

Error: CUDA device error.
==2368== Error: Application encountered error: the launch timed out and was terminated (702).

This also occurs with my own use of a single nccl reduce call in a separate program, so it's not the numerous tests in reduce_test that cause problems.  I could test other nccl test programs, but this should be sufficient.  This makes it difficult to profile nccl  codes.

Running as root makes no difference.  For an otherwise identical code but one has a nccl Reduce or an equivalent like user code, the failure only occurs with the Reduce call itself in place.  So it's not the other nccl calls causing problems.

This is with:
Ubuntu 16.04 with 3 Titan-X Maxwells
NVIDIA-SMI 367.48                 Driver Version: 367.48
Cuda compilation tools, release 8.0, V8.0.44
latest nccl (ccfc4567dc3e2a37fb42cfbc64d10eb526e7da7b)

Exactly the same also occurs on different system with Ubuntu 16.04 with 4 Titan-X Pascals
NVIDIA-SMI 378.13                 Driver Version: 378.13
Cuda compilation tools, release 8.0, V8.0.61
latest nccl (as above)

**Comment by cliffwoolley** [comment]
Kernel replay, which is the is the default method of collecting multiple
metrics and/or events in nvprof (and nvvp, by extension) is incompatible
with NCCL.  You have to use application replay rather than kernel replay
mode when profiling a NCCL application.

--Cliff

**Comment by cliffwoolley** [comment]
Kernel replay, which is the is the default method of collecting multiple
metrics and/or events in nvprof (and nvvp, by extension) is incompatible
with NCCL.  You have to use application replay rather than kernel replay
mode when profiling a NCCL application.
