### ISSUE TITLE
nvvp does not show nccl calls

### ISSUE THREAD

**Issue by pseudotensor** [NVIDIA/nccl#94]
In nvvp, nccl calls don't appear.  I see only host-side cudaMalloc or cudaHostmalloc, but not he kernels. This makes it hard to identify what is going on.  For example, even with 1 GPU, nccl calls like out-of-place AllGather take alot of time even though they should take only on-device memcpy time.  However, one can't really see this easily in nvvp.  This includes when trying application replay.

**Comment by sjeaugey** [comment]
Closing old issue, please re-open if still a problem.
