### ISSUE TITLE
Slow (~56%) inter-node all_reduce_perf performance on A100 Virtual Machine

### ISSUE THREAD

**Issue by potaytoh** [NVIDIA/nccl#949]
Hi,

I am creating an issue to get help with a performance degradation when measuring NCCL All Reduce performance.

## Issue Details
I have two of A100 SXM4*8 nodes with 2 * HDR Infiniband cards each.

I configured a virtual machine on each server with 8 GPUs, NVSwitch, and Infiniband SR-IOV VF pass-through.
The VM reflects the host's NUMA structure and PCIe topology as close as possible, and hugepage and vCPU pinning are also applied.

PCI Topology of the VM via lspci -tvv is as follows:
```
-+-[0000:d0]---00.0-[d1]--+-01.0  NVIDIA Corporation GA100 [A100 SXM4 80GB]
 |                        +-02.0  NVIDIA Corporation GA100 [A100 SXM4 80GB]
 |                        +-04.0  NVIDIA Corporation GA100 [A100 NVSwitch]
 |                        +-05.0  NVIDIA Corporation GA100 [A100 NVSwitch]
 |                        +-06.0  NVIDIA Corporation GA100 [A100 NVSwitch]
 |                        +-07.0  NVIDIA Corporation GA100 [A100 NVSwitch]
 |                        +-08.0  NVIDIA Corporation GA100 [A100 NVSwitch]
 |                        \-09.0  NVIDIA Corporation GA100 [A100 NVSwitch]
 +-[0000:c0]---00.0-[c1]--+-01.0  NVIDIA Corporation GA100 [A100 SXM4 80GB]
 |                        \-02.0  NVIDIA Corporation GA100 [A100 SXM4 80GB]
 +-[0000:b0]-+-00.0-[b1]--+-01.0  NVIDIA Corporation GA100 [A100 SXM4 80GB]
 |           |            \-02.0  NVIDIA Corporation GA100 [A100 SXM4 80GB]
 |           \-01.0-[b2]----00.0  Mellanox Technologies MT28908 Family [ConnectX-6 Virtual Function]
 +-[0000:a0]-+-00.0-[a1]--+-01.0  NVIDIA Corporation GA100 [A100 SXM4 80GB]
 |           |            \-02.0  NVIDIA Corporation GA100 [A100 SXM4 80GB]
 |           \-01.0-[a2]----00.0  Mellanox Technologies MT28908 Family [ConnectX-6 Virtual Function]
```

To tell NCCL the topology of the VM, I created a topology xml file and injected it with the `NCCL_TOPO_FILE` option as follows.
```
<system version="1">
  <cpu numaid="0" affinity="000000,0fffffff" arch="x86_64" vendor="AuthenticAMD" familyid="175" modelid="1">
    <pci busid="0000:a0:00.0" class="0x060400" vendor="0x1b36" device="0x000e" subsystem_vendor="0x0000" subsystem_device="0x0000" link_speed="16 GT/s" link_width="16">
        <pci busid="0000:a1:01.0" class="0x030200" vendor="0x10de" device="0x20b2" subsystem_vendor="0x10de" subsystem_device="0x1463" link_speed="16.0 GT/s PCIe" link_width="16"/>
        <pci busid="0000:a1:02.0" class="0x030200" vendor="0x10de" device="0x20b2" subsystem_vendor="0x10de" subsystem_device="0x1463" link_speed="16.0 GT/s PCIe" link_width="16"/>
        <pci busid="0000:a2:00.0" class="0x020700" vendor="0x15b3" device="0x101c" subsystem_vendor="0x15b3" subsystem_device="0x0007" link_speed="16.0 GT/s PCIe" link_width="16"/>
    </pci>
    <pci busid="0000:b0:00.0" class="0x060400" vendor="0x1b36" device="0x000e" subsystem_vendor="0x0000" subsystem_device="0x0000" link_speed="16 GT/s" link_width="16">
        <pci busid="0000:b1:01.0" class="0x030200" vendor="0x10de" device="0x20b2" subsystem_vendor="0x10de" subsystem_device="0x1463" link_speed="16.0 GT/s PCIe" link_width="16"/>
        <pci busid="0000:b1:02.0" class="0x030200" vendor="0x10de" device="0x20b2" subsystem_vendor="0x10de" subsystem_device="0x1463" link_speed="16.0 GT/s PCIe" link_width="16"/>
        <pci busid="0000:b2:00.0" class="0x020700" vendor="0x15b3" device="0x101c" subsystem_vendor="0x15b3" subsystem_device="0x0007" link_speed="16.0 GT/s PCIe" link_width="16"/>
    </pci>
  </cpu>
  <cpu numaid="1" affinity="ffffff,f0000000" arch="x86_64" vendor="AuthenticAMD" familyid="175" modelid="1">
    <pci busid="0000:c0:00.0" class="0x060400" vendor="0x1b36" device="0x000e" subsystem_vendor="0x0000" subsystem_device="0x0000" link_speed="16 GT/s" link_width="16">
        <pci busid="0000:c1:01.0" class="0x030200" vendor="0x10de" device="0x20b2" subsystem_vendor="0x10de" subsystem_device="0x1463" link_speed="16.0 GT/s PCIe" link_width="16"/>
        <pci busid="0000:c1:02.0" class="0x030200" vendor="0x10de" device="0x20b2" subsystem_vendor="0x10de" subsystem_device="0x1463" link_speed="16.0 GT/s PCIe" link_width="16"/>
    </pci>
    <pci busid="0000:d0:00.0" class="0x060400" vendor="0x1b36" device="0x000e" subsystem_vendor="0x0000" subsystem_device="0x0000" link_speed="16 GT/s" link_width="16">
        <pci busid="0000:d1:01.0" class="0x030200" vendor="0x10de" device="0x20b2" subsystem_vendor="0x10de" subsystem_device="0x1463" link_speed="16.0 GT/s PCIe" link_width="16"/>
        <pci busid="0000:d1:02.0" class="0x030200" vendor="0x10de" device="0x20b2" subsystem_vendor="0x10de" subsystem_device="0x1463" link_speed="16.0 GT/s PCIe" link_width="16"/>
    </pci>
  </cpu>
</system>
```

After setting it up as above, I ran the all_reduce_perf benchmark to measure performance.

After reading many issues, I understood that we should use the Ring algorithm to measure the network bandwidth, so I added the `NCCL_ALGO=RING` option to the all_reduce_perf measurement.

The commands performed are as follows:
```
mpirun --allow-run-as-root -H 192.168.0.11:8,192.168.0.13:8 -np 16 -x LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH -x NCCL_IB_PCI_RELAXED_ORDERING=1 -x NCCL_DEBUG=INFO -x NCCL_NET_GDR_LEVEL=SYS -x NCCL_DEBUG_SUBSYS=GRAPH,INIT -x NCCL_ALGO=RING -x NCCL_TOPO_FILE=tune0711-3.xml --mca btl ^openib --bind-to none /root/nccl-tests/build/all_reduce_perf  -b 8 -e 1G -f 2 -g 1 -c 1 -n 10
```

The expected performance is `200Gb/s * 2 =~ 50GB/s`, but the measured performance is about `27GB/s (=~ 216Gb/s)`.
Because of virtualization, I expected some performance degradation but this is way worse.... :(
```
#                                                              out-of-place                       in-place
#       size         count      type   redop    root     time   algbw   busbw #wrong     time   algbw   busbw #wrong
#        (B)    (elements)                               (us)  (GB/s)  (GB/s)            (us)  (GB/s)  (GB/s)

           8             2     float     sum      -1    43.04    0.00    0.00      0    41.82    0.00    0.00      0
          16             4     float     sum      -1    43.47    0.00    0.00      0    41.58    0.00    0.00      0
          32             8     float     sum      -1    42.85    0.00    0.00      0    42.84    0.00    0.00      0
          64            16     float     sum      -1    42.53    0.00    0.00      0    41.09    0.00    0.00      0
         128            32     float     sum      -1    42.80    0.00    0.01      0    42.25    0.00    0.01      0
         256            64     float     sum      -1    43.17    0.01    0.01      0    42.82    0.01    0.01      0
         512           128     float     sum      -1    44.28    0.01    0.02      0    42.53    0.01    0.02      0
        1024           256     float     sum      -1    46.39    0.02    0.04      0    45.31    0.02    0.04      0
        2048           512     float     sum      -1    50.56    0.04    0.08      0    50.70    0.04    0.08      0
        4096          1024     float     sum      -1    55.32    0.07    0.14      0    55.42    0.07    0.14      0
        8192          2048     float     sum      -1    63.50    0.13    0.24      0    64.81    0.13    0.24      0
       16384          4096     float     sum      -1    78.23    0.21    0.39      0    78.67    0.21    0.39      0
       32768          8192     float     sum      -1    162.3    0.20    0.38      0    161.2    0.20    0.38      0
       65536         16384     float     sum      -1    392.6    0.17    0.31      0    391.2    0.17    0.31      0
      131072         32768     float     sum      -1    98.71    1.33    2.49      0    98.76    1.33    2.49      0
      262144         65536     float     sum      -1    106.8    2.45    4.60      0    105.3    2.49    4.67      0
      524288        131072     float     sum      -1    125.5    4.18    7.83      0    130.3    4.02    7.55      0
     1048576        262144     float     sum      -1    166.6    6.29   11.80      0    162.6    6.45   12.09      0
     2097152        524288     float     sum      -1    209.5   10.01   18.77      0    210.1    9.98   18.72      0
     4194304       1048576     float     sum      -1    355.3   11.80   22.13      0    354.9   11.82   22.16      0
     8388608       2097152     float     sum      -1    648.0   12.95   24.27      0    647.7   12.95   24.28      0
    16777216       4194304     float     sum      -1   1252.5   13.39   25.11      0   1252.5   13.40   25.12      0
    33554432       8388608     float     sum      -1   2332.2   14.39   26.98      0   2334.0   14.38   26.96      0
    67108864      16777216     float     sum      -1   4645.0   14.45   27.09      0   4640.9   14.46   27.11      0
   134217728      33554432     float     sum      -1   9263.3   14.49   27.17      0   9259.7   14.49   27.18      0
   268435456      67108864     float     sum      -1    18795   14.28   26.78      0    18510   14.50   27.19      0
   536870912     134217728     float     sum      -1    37002   14.51   27.20      0    37127   14.46   27.11      0
  1073741824     268435456     float     sum      -1    74072   14.50   27.18      0    74113   14.49   27.16      0

# Out of bounds values : 0 OK
# Avg bus bandwidth    : 10.0437
```

Here is nccl output log : 
[nccl_allreduce_result_230808.txt](https://github.com/NVIDIA/nccl/files/12281671/nccl_allreduce_result_230808.txt)

and graph dump is : 
[nccl_graph_dump_230808.txt](https://github.com/NVIDIA/nccl/files/12281732/nccl_graph_dump_230808.txt)

I checked each HCA bandwidth using ib_write_bw and it shows ~198Gbps in all cases.
so it seems to be no problem with the IB network. 

The driver, CUDA, OFED, NCCL, and nv_peer_mem versions currently in use are as follows.
```
Driver : 525.105.17
CUDA : 11.2
OFED : 5.9-0.5.5
NCCL : 2.18.3-1
nv_peer_mem : 1.1-0
```

Could you please help me on this?
Please let me know if you need any additional information.

Thanks & Best regards,
- Min

**Comment by sjeaugey** [comment]
Inside a VM, all GPU-NIC traffic needs to go through ACS, i.e. the CPU root complex, which is probably the reason why you see poor performance inside the VM (provided on baremetal you see >=48 GB/s).

To get back to peak BW, you need to enable ATS, so that the address translation is cached and doesn't need to go the the CPU root complex upon every translation. Unfortunately, I don't have good pointers to provide as to how to make that work.

**Comment by potaytoh** [comment]
@sjeaugey Thank you for your response.

I understood it to be an overhead impact due to address translation.
For ATS, it looks like it's only a supported option for virtio devices...

I would like to try assigning a vIOMMU device to a VM, but with amd-iommu devices, it seems that the address space notifier feature is not yet implemented, so I can't assign a vfio-pci device to a VM...

Can I assume that there is nothing unusual about the graph path determined by NCCL?

**Comment by sjeaugey** [comment]
> Can I assume that there is nothing unusual about the graph path determined by NCCL?

Indeed, we're finding 2 paths @24 GB/s so that should give 48 GB/s total BW on ring.

**Comment by potaytoh** [comment]
@sjeaugey 
Thank you very much for your confirmation.

I found the settings I was missing regarding ACS.
After applying it, I observe a bandwidth of 48GB/s (=~ 384Gbps) using the RING algorithm on 2 nodes.

I believe this is line rate of 2*HDR Links.

```
#
#                                                              out-of-place                       in-place
#       size         count      type   redop    root     time   algbw   busbw #wrong     time   algbw   busbw #wrong
#        (B)    (elements)                               (us)  (GB/s)  (GB/s)            (us)  (GB/s)  (GB/s)
           8             2     float     sum      -1    40.56    0.00    0.00      0    39.06    0.00    0.00      0
          16             4     float     sum      -1    38.93    0.00    0.00      0    38.25    0.00    0.00      0
          32             8     float     sum      -1    38.16    0.00    0.00      0    37.90    0.00    0.00      0
          64            16     float     sum      -1    37.87    0.00    0.00      0    38.11    0.00    0.00      0
         128            32     float     sum      -1    38.47    0.00    0.01      0    40.06    0.00    0.01      0
         256            64     float     sum      -1    38.26    0.01    0.01      0    38.26    0.01    0.01      0
         512           128     float     sum      -1    45.53    0.01    0.02      0    38.43    0.01    0.02      0
        1024           256     float     sum      -1    40.85    0.03    0.05      0    40.39    0.03    0.05      0
        2048           512     float     sum      -1    43.38    0.05    0.09      0    42.68    0.05    0.09      0
        4096          1024     float     sum      -1    45.58    0.09    0.17      0    45.95    0.09    0.17      0
        8192          2048     float     sum      -1    50.81    0.16    0.30      0    50.68    0.16    0.30      0
       16384          4096     float     sum      -1    55.15    0.30    0.56      0    53.56    0.31    0.57      0
       32768          8192     float     sum      -1    60.05    0.55    1.02      0    58.40    0.56    1.05      0
       65536         16384     float     sum      -1    67.60    0.97    1.82      0    65.22    1.00    1.88      0
      131072         32768     float     sum      -1    89.90    1.46    2.73      0    89.16    1.47    2.76      0
      262144         65536     float     sum      -1    99.52    2.63    4.94      0    98.50    2.66    4.99      0
      524288        131072     float     sum      -1    116.2    4.51    8.46      0    115.8    4.53    8.49      0
     1048576        262144     float     sum      -1    145.9    7.19   13.47      0    145.1    7.23   13.55      0
     2097152        524288     float     sum      -1    189.9   11.04   20.71      0    200.2   10.47   19.64      0
     4194304       1048576     float     sum      -1    278.8   15.05   28.21      0    277.4   15.12   28.35      0
     8388608       2097152     float     sum      -1    506.0   16.58   31.09      0    496.7   16.89   31.67      0
    16777216       4194304     float     sum      -1    730.0   22.98   43.09      0    736.8   22.77   42.70      0
    33554432       8388608     float     sum      -1   1404.6   23.89   44.79      0   1416.7   23.68   44.41      0
    67108864      16777216     float     sum      -1   2670.7   25.13   47.12      0   2621.5   25.60   48.00      0
   134217728      33554432     float     sum      -1   5220.9   25.71   48.20      0   5209.3   25.76   48.31      0
   268435456      67108864     float     sum      -1    10410   25.79   48.35      0    10389   25.84   48.45      0
   536870912     134217728     float     sum      -1    20672   25.97   48.70      0    20683   25.96   48.67      0
  1073741824     268435456     float     sum      -1    41352   25.97   48.69      0    41318   25.99   48.73      0
# Out of bounds values : 0 OK
# Avg bus bandwidth    : 15.8117
#
```

Once again, thank you very much for the clue to the solution :-)

**Comment by sjeaugey** [comment]
That's indeed perfect performance. Happy to see that :-)

Closing -- please reopen if needed.

**Comment by joydchh** [comment]
> @sjeaugey Thank you very much for your confirmation.
> 
> I found the settings I was missing regarding ACS. After applying it, I observe a bandwidth of 48GB/s (=~ 384Gbps) using the RING algorithm on 2 nodes.
> 
> I believe this is line rate of 2*HDR Links.
> 
> ```
> #
> #                                                              out-of-place                       in-place
> #       size         count      type   redop    root     time   algbw   busbw #wrong     time   algbw   busbw #wrong
> #        (B)    (elements)                               (us)  (GB/s)  (GB/s)            (us)  (GB/s)  (GB/s)
>            8             2     float     sum      -1    40.56    0.00    0.00      0    39.06    0.00    0.00      0
>           16             4     float     sum      -1    38.93    0.00    0.00      0    38.25    0.00    0.00      0
>           32             8     float     sum      -1    38.16    0.00    0.00      0    37.90    0.00    0.00      0
>           64            16     float     sum      -1    37.87    0.00    0.00      0    38.11    0.00    0.00      0
>          128            32     float     sum      -1    38.47    0.00    0.01      0    40.06    0.00    0.01      0
>          256            64     float     sum      -1    38.26    0.01    0.01      0    38.26    0.01    0.01      0
>          512           128     float     sum      -1    45.53    0.01    0.02      0    38.43    0.01    0.02      0
>         1024           256     float     sum      -1    40.85    0.03    0.05      0    40.39    0.03    0.05      0
>         2048           512     float     sum      -1    43.38    0.05    0.09      0    42.68    0.05    0.09      0
>         4096          1024     float     sum      -1    45.58    0.09    0.17      0    45.95    0.09    0.17      0
>         8192          2048     float     sum      -1    50.81    0.16    0.30      0    50.68    0.16    0.30      0
>        16384          4096     float     sum      -1    55.15    0.30    0.56      0    53.56    0.31    0.57      0
>        32768          8192     float     sum      -1    60.05    0.55    1.02      0    58.40    0.56    1.05      0
>        65536         16384     float     sum      -1    67.60    0.97    1.82      0    65.22    1.00    1.88      0
>       131072         32768     float     sum      -1    89.90    1.46    2.73      0    89.16    1.47    2.76      0
>       262144         65536     float     sum      -1    99.52    2.63    4.94      0    98.50    2.66    4.99      0
>       524288        131072     float     sum      -1    116.2    4.51    8.46      0    115.8    4.53    8.49      0
>      1048576        262144     float     sum      -1    145.9    7.19   13.47      0    145.1    7.23   13.55      0
>      2097152        524288     float     sum      -1    189.9   11.04   20.71      0    200.2   10.47   19.64      0
>      4194304       1048576     float     sum      -1    278.8   15.05   28.21      0    277.4   15.12   28.35      0
>      8388608       2097152     float     sum      -1    506.0   16.58   31.09      0    496.7   16.89   31.67      0
>     16777216       4194304     float     sum      -1    730.0   22.98   43.09      0    736.8   22.77   42.70      0
>     33554432       8388608     float     sum      -1   1404.6   23.89   44.79      0   1416.7   23.68   44.41      0
>     67108864      16777216     float     sum      -1   2670.7   25.13   47.12      0   2621.5   25.60   48.00      0
>    134217728      33554432     float     sum      -1   5220.9   25.71   48.20      0   5209.3   25.76   48.31      0
>    268435456      67108864     float     sum      -1    10410   25.79   48.35      0    10389   25.84   48.45      0
>    536870912     134217728     float     sum      -1    20672   25.97   48.70      0    20683   25.96   48.67      0
>   1073741824     268435456     float     sum      -1    41352   25.97   48.69      0    41318   25.99   48.73      0
> # Out of bounds values : 0 OK
> # Avg bus bandwidth    : 15.8117
> #
> ```
> 
> Once again, thank you very much for the clue to the solution :-)

Hi, we've met a similar situation here, and tried to enable and disable pcie switch ACS, but no change in bw. What settings you adjusted in ACS to achieve full bw?

**Comment by dhruvik7** [comment]
@joydchh @potaytoh could you share what settings you needed to change to achieve the full bandwidth?

**Comment by wangjiafu0310** [comment]
> [@sjeaugey](https://github.com/sjeaugey) Thank you very much for your confirmation.
> 
> I found the settings I was missing regarding ACS. After applying it, I observe a bandwidth of 48GB/s (=~ 384Gbps) using the RING algorithm on 2 nodes.
> 
> I believe this is line rate of 2*HDR Links.
> 
> ```
> #
> #                                                              out-of-place                       in-place
> #       size         count      type   redop    root     time   algbw   busbw #wrong     time   algbw   busbw #wrong
> #        (B)    (elements)                               (us)  (GB/s)  (GB/s)            (us)  (GB/s)  (GB/s)
>            8             2     float     sum      -1    40.56    0.00    0.00      0    39.06    0.00    0.00      0
>           16             4     float     sum      -1    38.93    0.00    0.00      0    38.25    0.00    0.00      0
>           32             8     float     sum      -1    38.16    0.00    0.00      0    37.90    0.00    0.00      0
>           64            16     float     sum      -1    37.87    0.00    0.00      0    38.11    0.00    0.00      0
>          128            32     float     sum      -1    38.47    0.00    0.01      0    40.06    0.00    0.01      0
>          256            64     float     sum      -1    38.26    0.01    0.01      0    38.26    0.01    0.01      0
>          512           128     float     sum      -1    45.53    0.01    0.02      0    38.43    0.01    0.02      0
>         1024           256     float     sum      -1    40.85    0.03    0.05      0    40.39    0.03    0.05      0
>         2048           512     float     sum      -1    43.38    0.05    0.09      0    42.68    0.05    0.09      0
>         4096          1024     float     sum      -1    45.58    0.09    0.17      0    45.95    0.09    0.17      0
>         8192          2048     float     sum      -1    50.81    0.16    0.30      0    50.68    0.16    0.30      0
>        16384          4096     float     sum      -1    55.15    0.30    0.56      0    53.56    0.31    0.57      0
>        32768          8192     float     sum      -1    60.05    0.55    1.02      0    58.40    0.56    1.05      0
>        65536         16384     float     sum      -1    67.60    0.97    1.82      0    65.22    1.00    1.88      0
>       131072         32768     float     sum      -1    89.90    1.46    2.73      0    89.16    1.47    2.76      0
>       262144         65536     float     sum      -1    99.52    2.63    4.94      0    98.50    2.66    4.99      0
>       524288        131072     float     sum      -1    116.2    4.51    8.46      0    115.8    4.53    8.49      0
>      1048576        262144     float     sum      -1    145.9    7.19   13.47      0    145.1    7.23   13.55      0
>      2097152        524288     float     sum      -1    189.9   11.04   20.71      0    200.2   10.47   19.64      0
>      4194304       1048576     float     sum      -1    278.8   15.05   28.21      0    277.4   15.12   28.35      0
>      8388608       2097152     float     sum      -1    506.0   16.58   31.09      0    496.7   16.89   31.67      0
>     16777216       4194304     float     sum      -1    730.0   22.98   43.09      0    736.8   22.77   42.70      0
>     33554432       8388608     float     sum      -1   1404.6   23.89   44.79      0   1416.7   23.68   44.41      0
>     67108864      16777216     float     sum      -1   2670.7   25.13   47.12      0   2621.5   25.60   48.00      0
>    134217728      33554432     float     sum      -1   5220.9   25.71   48.20      0   5209.3   25.76   48.31      0
>    268435456      67108864     float     sum      -1    10410   25.79   48.35      0    10389   25.84   48.45      0
>    536870912     134217728     float     sum      -1    20672   25.97   48.70      0    20683   25.96   48.67      0
>   1073741824     268435456     float     sum      -1    41352   25.97   48.69      0    41318   25.99   48.73      0
> # Out of bounds values : 0 OK
> # Avg bus bandwidth    : 15.8117
> #
> ```
> 
> Once again, thank you very much for the clue to the solution :-)



Woud you please kindly share how to enable ACS+ATS inside the VM? I have the familiar issue. Thanks a lot.
