### ISSUE TITLE
How to use the ROCE net card ?

### ISSUE THREAD

**Issue by pengshuang** [NVIDIA/nccl#958]
My NCCL version 2.17.1+cuda12.1
I would like to use RoCE network cards by setting the Environment Variables of NCCL. However, my attempts have been unsuccessful, and I would like to understand whether this is due to an installation error with the RoCE network cards or if there might be an issue with the Environment Variables settings I've configured.

My environment variable settings suggest the following:
`os.environ["NCCL_NET"]="Socket"`
`os.environ['NCCL_SOCKET_IFNAME']="enp88s0np0,enp114s0np0"`

Is this correct?

If I set environment variable settings as:
`os.environ["NCCL_NET"]="IB"`
The logs from NCCL will show an error: NET/IB: No device found.

Thank you very much!

**Comment by sjeaugey** [comment]
You need to use the IB network backend to use RoCE, so the best is to not set `NCCL_NET`. NCCL will automatically use any RoCE NIC if available.

If you get a `NET/IB: No device found.` error, then it simply means the OS could not find a usable RoCE NIC.

Please run `ibv_devinfo` and see if your RoCE NIC is there. If it is, check that its state is active. If it is not, check that the NIC is visible in `lspci`, then in `/sys/class/infiniband`.
If `ibv_devinfo` is not present, you need to install the RDMA networking stack.

**Comment by pengshuang** [comment]
Thanks for your reply.

**Comment by aldopareja** [comment]
@pengshuang , where did you find information on how to setup nccl to allow for RoCE enabled cards?
