### ISSUE TITLE
How to use NCCL operations in CUDA graph with dynamic params?

### ISSUE THREAD

**Issue by ziannchen** [NVIDIA/nccl#961]
I want to capture NCCL operations and some cudaMemcpyAsync/cuda kernel into a CUDA graph, just as this sample code in nccl's user guide. Now I want to change ncclAllreduce's sendbuff without re-capturing a graph, what should I do. Can I think that ncclAllreduce is a cuda kernel, and then use cudaGraphExecKernelNodeSetParams directly?

cudaGraph_t graph;
cudaStreamBeginCapture(stream);
kernel_A<<< ..., stream >>>(...);
kernel_B<<< ..., stream >>>(...);
ncclAllreduce(..., stream);
kernel_C<<< ..., stream >>>(...);
cudaStreamEndCapture(stream, &graph);

cudaGraphExec_t instance;
cudaGraphInstantiate(&instance, graph, NULL, NULL, 0);
cudaGraphLaunch(instance, stream);
cudaStreamSynchronize(stream);

**Comment by KaimingOuyang** [comment]
I don't think you can do it right now. NCCL does not support node update, which would require exporting NCCL details to users and we don't want to do it.

**Comment by ziannchen** [comment]
thanks
