### ISSUE TITLE
Nccl all reduce expose port

### ISSUE THREAD

**Issue by wangxiangming01** [NVIDIA/nccl#965]
![image](https://github.com/NVIDIA/nccl/assets/142417162/6f2a2fa0-64a2-4121-bd2b-c7426d450762)
 When I start the program, I find that NCCL's all reduce launches two ports, which are exposed and can be connected via TCP.
How could I specify these ports as localhost mode?

**Comment by wangxiangming01** [comment]
> If you want to see 127.0.0.1 instead of 10.176.81.28, you can set `NCCL_SOCKET_IFNAME=lo`. That will not work if you launch on multiple machines, though.

thanks，it works～ but

**Comment by sjeaugey** [comment]
I'm not sure this is from NCCL. Can you run NCCL perf tests and see whether you see the same port open?

**Comment by wangxiangming01** [comment]
> I'm not sure this is from NCCL. Can you run NCCL perf tests and see whether you see the same port open?

Thanks. I found that the port was exposed by PyTorch
