### ISSUE TITLE
How to use NCCL_P2P_LEVEL environment variable

### ISSUE THREAD

**Issue by Renoshen** [NVIDIA/nccl#967]
How can I use NCCL_P2P_LEVEL to compare performance under different parameters?I got the same result with all the parameters。

**Comment by sjeaugey** [comment]
My guess is that CUDA is disabling P2P between your GPUs and therefore NCCL cannot use P2P, regardless of its internal settings.

**Comment by Renoshen** [comment]
Thanks for your replay.
