### ISSUE TITLE
How to detect which node causes a NCCL hang?

### ISSUE THREAD

**Issue by void-main** [NVIDIA/nccl#968]
Hi community,

We're running a large-scale training job which leverages NCCL for inter-GPU communications. 
The job uses model parallel along with data parallel, so it has several parallel nccl communication groups. The major operations the jobs needs are `AllReduce`, `ReduceScatter` and `AllGather`.

During the training process, a single GPU may run into faulty states, and since NCCL operations have sync semantics, the whole job may get hang. When the hang happens, the GPU util is 100% but the power consumption is pretty low (~70W). Based on our understanding, our bet is that the jobs now hangs in NCCL operations.

We know that NCCL kernel is not the root cause for the hang, but it's really hard to find which GPU is the culprit, because the sync semantic of the NCCL operations. 

So my questions are:
1. if it is possible to check which kernels are currently executing on each GPU? So that we could verify our guess that "the jobs now hangs in NCCL operations"
2. is it possible that we find which GPU node causes the hang? In my understanding, the culprit GPU must be in different state from the other GPUs, how could we add some monitoring metrics to detect that case? Maybe exporting `opCount`?
3. how to tell which NCCL comm group is causing the hang?

Thanks!

**Comment by sjeaugey** [comment]
You should ensure your code is waiting on CUDA operation not with `cudaStreamSynchronize` but with a mix of `cudaStreamQuery` and `ncclCommGetAsyncError`. Most hangs are caused by a networking operation failing, and that will be reported through `ncclCommGetAsyncError` (and also print a `NCCL WARN`, so setting `NCCL_DEBUG=WARN` can also tell you what happened).

**Comment by void-main** [comment]
Some of our hangs are caused by GPU errors, but not network errors. 

For example, in some case, we found that there's a `xid` error, but the framework doesn't report error (don't know why), how could we solve cases like this?

**Comment by sjeaugey** [comment]
IF there is a xid error then there should be a CUDA error; in that case, the failing rank should be detected by the process launcher, which would initiate a global abort.

**Comment by void-main** [comment]
> If there is a xid error then there should be a CUDA error; in that case, the failing rank should be detected by the process launcher, which would initiate a global abort.

Got it, we should check why the process didn't initiate a global abort.

Thanks @sjeaugey

**Comment by void-main** [comment]
Hi @sjeaugey , would GPU report error on XID 109, which is a reserved error?

**Comment by sjeaugey** [comment]
I don't know about all XIDs, but I would think all XIDs would cause CUDA to stop (potentially not calling NCCL if the NCCL call was after), hence report an error to CUDA, which can be handled by the application.
