### ISSUE TITLE
hello,I want to know why just 2 nic is used in VM?

### ISSUE THREAD

**Issue by zzhint** [NVIDIA/nccl#977]
I have a VM (guest) which has 8 cx6 nics and 8 gpu, this is the run shell:

NCCL_IB_GID_INDEX=3 \
NCCL_MAX_NCHANNELS=8 \
NCCL_P2P_PXN_LEVEL=0 \
NCCL_NET_GDR_LEVEL=SYS \
NCCL_DEBUG=INFO \
NCCL_DEBUG_SUBSYS=ALL \
NCCL_DEBUG_FILE=debug.log \
NCCL_IB_DISABLE=0 \
NCCL_SOCKET_IFNAME=eth0 \
OMP_NUM_THREADS=1 \
NCCL_IB_HCA=mlx5_1:1,mlx5_2:1,mlx5_3:1,mlx5_4:1,mlx5_5:1,mlx5_6:1,mlx5_7:1,mlx5_8:1 \
torchrun \
--nproc_per_node 8 --nnodes 2 --node_rank 0\
 --master_addr='192.168.16.40' \
 --master_port='6101' example.py

it works but just two nics work, and I see there is just two channels,  this is the debug.log in guest

[debug.log](https://github.com/NVIDIA/nccl/files/12465059/debug.log)

in host, there is 8 channels, this is the debug.log

[debug_8.log](https://github.com/NVIDIA/nccl/files/12465095/debug_8.log)

how nccl get the channels?

**Comment by sjeaugey** [comment]
Can you explain what is the difference between the two logs? Each log seems to be initializing NCCL on 16 ranks (2 nodes) and one log gets 8 channels as expected while the other one gets only 2 channels.

The log with only 2 channels is very truncated; we don't have the output for each rank. Some ranks (2 and 3) seem to have trouble with topology detection:
```
hpc-10:52318:52480 [2] NCCL INFO Could not find real path of /sys/class/pci_bus/0000:6f/../../0000:6f:00.0
```
then they are computing only 2 channels:
```
pc-10:52318:52480 [2] NCCL INFO Pattern 4, crossNic 0, nChannels 2, bw 12.000000/12.000000, type NVL/PXB, sameChannels 1
hpc-10:52318:52480 [2] NCCL INFO  0 : NET/0 GPU/0 GPU/1 GPU/2 GPU/3 GPU/4 GPU/5 GPU/6 GPU/7 NET/6
hpc-10:52318:52480 [2] NCCL INFO  1 : NET/1 GPU/0 GPU/1 GPU/2 GPU/3 GPU/4 GPU/5 GPU/6 GPU/7 NET/7
```
But I can't see what topology they have detected; I can only see what rank 1 has detected and the topology looks ok on that rank:
```
hpc-10:52317:52479 [1] NCCL INFO === System : maxBw 12.5 totalBw 264.0 ===
hpc-10:52317:52479 [1] NCCL INFO CPU/0 (1/1/2)
hpc-10:52317:52479 [1] NCCL INFO + PCI[24.0] - PCI/4B000 (1000c01010000000)
hpc-10:52317:52479 [1] NCCL INFO               + PCI[24.0] - PCI/4F000 (1000c01010de13b8)
hpc-10:52317:52479 [1] NCCL INFO                             + PCI[24.0] - GPU/80 (0)
hpc-10:52317:52479 [1] NCCL INFO                                           + NVL[264.0] - NVS/0
hpc-10:52317:52479 [1] NCCL INFO               + PCI[24.0] - PCI/54000 (1000c01010de13b8)
hpc-10:52317:52479 [1] NCCL INFO                             + PCI[24.0] - GPU/90 (1)
hpc-10:52317:52479 [1] NCCL INFO                                           + NVL[264.0] - NVS/0
hpc-10:52317:52479 [1] NCCL INFO               + PCI[24.0] - NIC/18000
hpc-10:52317:52479 [1] NCCL INFO                             + NET[12.5] - NET/0 (1e9c6c0003d3ebe8/1/12.500000)
hpc-10:52317:52479 [1] NCCL INFO                             + NET[12.5] - NET/1 (1e9c6c0003d3ebe8/2/12.500000)
hpc-10:52317:52479 [1] NCCL INFO + PCI[24.0] - PCI/65000 (1000c01010000000)
hpc-10:52317:52479 [1] NCCL INFO               + PCI[24.0] - PCI/69000 (1000c01010de13b8)
hpc-10:52317:52479 [1] NCCL INFO                             + PCI[24.0] - GPU/A0 (2)
hpc-10:52317:52479 [1] NCCL INFO                                           + NVL[264.0] - NVS/0
hpc-10:52317:52479 [1] NCCL INFO               + PCI[24.0] - PCI/6F000 (1000c01010de13b8)
hpc-10:52317:52479 [1] NCCL INFO                             + PCI[24.0] - GPU/B0 (3)
hpc-10:52317:52479 [1] NCCL INFO                                           + NVL[264.0] - NVS/0
hpc-10:52317:52479 [1] NCCL INFO               + PCI[24.0] - NIC/19000
hpc-10:52317:52479 [1] NCCL INFO                             + NET[12.5] - NET/2 (1e9c6c0003d3ebe8/1/12.500000)
hpc-10:52317:52479 [1] NCCL INFO                             + NET[12.5] - NET/3 (1e9c6c0003d3ebe8/2/12.500000)
hpc-10:52317:52479 [1] NCCL INFO + SYS[9.0] - CPU/1
hpc-10:52317:52479 [1] NCCL INFO CPU/1 (1/1/2)
hpc-10:52317:52479 [1] NCCL INFO + PCI[24.0] - PCI/84000 (1000c01010000000)
hpc-10:52317:52479 [1] NCCL INFO               + PCI[24.0] - PCI/88000 (1000c01010de13b8)
hpc-10:52317:52479 [1] NCCL INFO                             + PCI[24.0] - GPU/C0 (4)
hpc-10:52317:52479 [1] NCCL INFO                                           + NVL[264.0] - NVS/0
hpc-10:52317:52479 [1] NCCL INFO               + PCI[24.0] - PCI/8C000 (1000c01010de13b8)
hpc-10:52317:52479 [1] NCCL INFO                             + PCI[24.0] - GPU/D0 (5)
hpc-10:52317:52479 [1] NCCL INFO                                           + NVL[264.0] - NVS/0
hpc-10:52317:52479 [1] NCCL INFO               + PCI[24.0] - NIC/1A000
hpc-10:52317:52479 [1] NCCL INFO                             + NET[12.5] - NET/4 (1e9c6c0003d3ebe8/1/12.500000)
hpc-10:52317:52479 [1] NCCL INFO                             + NET[12.5] - NET/5 (1e9c6c0003d3ebe8/2/12.500000)
hpc-10:52317:52479 [1] NCCL INFO + PCI[24.0] - PCI/E3000 (1000c01010000000)
hpc-10:52317:52479 [1] NCCL INFO               + PCI[24.0] - PCI/E7000 (1000c01010de13b8)
hpc-10:52317:52479 [1] NCCL INFO                             + PCI[24.0] - GPU/E0 (6)
hpc-10:52317:52479 [1] NCCL INFO                                           + NVL[264.0] - NVS/0
hpc-10:52317:52479 [1] NCCL INFO               + PCI[24.0] - PCI/EA000 (1000c01010de13b8)
hpc-10:52317:52479 [1] NCCL INFO                             + PCI[24.0] - GPU/F0 (7)
hpc-10:52317:52479 [1] NCCL INFO                                           + NVL[264.0] - NVS/0
hpc-10:52317:52479 [1] NCCL INFO               + PCI[24.0] - NIC/1B000
hpc-10:52317:52479 [1] NCCL INFO                             + NET[12.5] - NET/6 (1e9c6c0003d3ebe8/1/12.500000)
hpc-10:52317:52479 [1] NCCL INFO                             + NET[12.5] - NET/7 (1e9c6c0003d3ebe8/2/12.500000)
hpc-10:52317:52479 [1] NCCL INFO + SYS[9.0] - CPU/0
hpc-10:52317:52479 [1] NCCL INFO ==========================================
```
So overall, I could not follow the entire log of rank 2.

**Comment by zzhint** [comment]
Thanks for your recovery! I want NCCL to run on the virtual machine (named guest), debug_8. log is generated on the host (real machine), while debug.log is generated on the guest machine. In order to maintain consistency between the topology of the host and guest, I have dumped a topology file (NCCL_TOPO_DUMP_FILE=xxx) on the host as follows. （please change the format to xml, I can't upload xml format file）

[system8-nic.log](https://github.com/NVIDIA/nccl/files/12470978/system8-nic.log)

At the same time, I have made some modifications to use it for the virtual machine as follows.

[system-vm-nogpu.log](https://github.com/NVIDIA/nccl/files/12470986/system-vm-nogpu.log)

I used NCCL_TOPO_FILE=./gpurdmaxml/system-vm-gpu-nic.xml , in this xml, I delete the <gpu> and keep the <nic>, because this is the only way no error.

Among them, errors like these:
hpc-10:52319:52461 [3] NCCL INFO Could not find real path of /sys/class/pci_bus/0000:4f/../../0000:4f:00.0
hpc-10:52319:52461 [3] NCCL INFO Could not find real path of /sys/class/pci_bus/0000:4d/../../0000:4d:00.0
hpc-10:52319:52461 [3] NCCL INFO Could not find real path of /sys/class/pci_bus/0000:4b/../../0000:4b:00.0
hpc-10:52318:52480 [2] NCCL INFO Could not find real path of /sys/class/pci_bus/0000:54/../../0000:54:00.0
hpc-10:52318:52480 [2] NCCL INFO Could not find real path of /sys/class/pci_bus/0000:52/../../0000:52:00.0

are caused by the fact that these devices are not actually present in the guest. These devices are PCI bridges, and I am not sure if these will affect the number of channels

In the end, I would like to ask how the number of channels is calculated. I think the topology of the two machines is consistent, but different channels they have

**Comment by sjeaugey** [comment]
That's great. Feel free to close the issue if your problem is resolved.
