### ISSUE TITLE
How to control AllReduce GPU workload

### ISSUE THREAD

**Issue by fmana** [NVIDIA/nccl#98]
I have an implementation single-process multi-threads using Nickel AllReduce. 
In order to improve concurrency between Nickel and my kernels, I'm running Nickel on a parallel stream.
I'm experiencing with an unexpected way of working.

Looking at the profiling timelines, allreduce and my own kernels are overlapped, but they take twice time to be executed.
In practice, I have vanished all the potential speed up coming from the overlapping.
I tried to run with a simple copy from Device to Host instead of allreduce, 
and in this way my own kernels seem to be fine as speed (even if the copy is twice allreduce).

How can I handle that? any comments are welcomed.

I tried to set priority to streams but I failed since cudaDeviceGetStreamPriorityRange() returns 
0,-1 for min and max priority values. That's surprising me.
Do I need to have some special setting on the server in order to modify streams priorities?

Is it possible to configure Nickel to use "less" gpu resourses?
In my case I have room to execute in parallel even longer allreduce.

Thanks,
Franco

**Comment by sjeaugey** [comment]
Could you try decreasing the number of threads to see if it improves overall performance ? (for all reduce : https://github.com/NVIDIA/nccl/blob/master/src/all_reduce.cu#L200)

512 threads are needed to get 10GB/s on Kepler, but if you are running on Maxwell or Pascal architecture, 256 should be enough. You can even go down to 128. It would likely increase the total time, but it may work better with concurrent kernels.

**Comment by fmana** [comment]
Yes, I'm running on P6000/P100 boards.
Let me try ... Thanks. I'll keep you posted.

**Comment by sjeaugey** [comment]
Closing. Please re-open if needed.
