### ISSUE TITLE
 what's different between nv_peer_mem and nvidia_peermem?

### ISSUE THREAD

**Issue by ReyRen** [NVIDIA/nccl#988]
Hello, 

Recently, I used A100 to do the GPU DirectRDMA test. The version of cuda is 11.6, NCCL is 2.12.9. 
The wired thing is, I didn't load the "nv_peer_mem" and "nvidia_peermem" kernel module, however, I notice the NCCL using the IB net to do the tranning.
```
(pytorch) [root@gpu3 ~]# lsmod | grep nvidia_peermem
(pytorch) [root@gpu3 ~]# lsmod | grep nv_peer_mem
(pytorch) [root@gpu3 ~]#
```
the log is blow:
```
ad5b8ae33076:28331:28331 [0] NCCL INFO Bootstrap : Using eth0:10.0.1.2<0>
ad5b8ae33076:28331:28331 [0] NCCL INFO NET/Plugin: Failed to find ncclNetPlugin_v5 symbol.
ad5b8ae33076:28331:28331 [0] NCCL INFO NET/Plugin: Failed to find ncclCollNetPlugin_v5 symbol.
ad5b8ae33076:28331:28331 [0] NCCL INFO Plugin Path : /opt/hpcx/nccl_rdma_sharp_plugin/lib/libnccl-net.so
ad5b8ae33076:28331:28331 [0] NCCL INFO P2P plugin IBext
ad5b8ae33076:28331:28331 [0] NCCL INFO NET/IB : Using [0]mlx5_0:1/IB/SHARP [1]mlx5_1:1/IB/SHARP [2]mlx5_2:1/IB/SHARP [3]mlx5_3:1/IB/SHARP [4]mlx5_4:1/IB/SHARP [5]mlx5_5:1/IB/SHARP [6]mlx5_6:1/IB/SHARP [7]mlx5_7:1/IB/SHARP ; OOB eth0:10.0.1.2<0>
ad5b8ae33076:28331:28331 [0] NCCL INFO Using network IBext
NCCL version 2.12.9+cuda11.6
ad5b8ae33076:28332:28332 [1] NCCL INFO Bootstrap : Using eth0:10.0.1.2<0>
ad5b8ae33076:28332:28332 [1] NCCL INFO NET/Plugin: Failed to find ncclNetPlugin_v5 symbol.
ad5b8ae33076:28332:28332 [1] NCCL INFO NET/Plugin: Failed to find ncclCollNetPlugin_v5 symbol.
ad5b8ae33076:28332:28332 [1] NCCL INFO Plugin Path : /opt/hpcx/nccl_rdma_sharp_plugin/lib/libnccl-net.so
ad5b8ae33076:28332:28332 [1] NCCL INFO P2P plugin IBext
ad5b8ae33076:28334:28334 [3] NCCL INFO Bootstrap : Using eth0:10.0.1.2<0>
381077730cf7:52623:52623 [1] NCCL INFO Bootstrap : Using eth0:10.0.1.3<0>
ad5b8ae33076:28334:28334 [3] NCCL INFO NET/Plugin: Failed to find ncclNetPlugin_v5 symbol.
ad5b8ae33076:28334:28334 [3] NCCL INFO NET/Plugin: Failed to find ncclCollNetPlugin_v5 symbol.
ad5b8ae33076:28334:28334 [3] NCCL INFO Plugin Path : /opt/hpcx/nccl_rdma_sharp_plugin/lib/libnccl-net.so
ad5b8ae33076:28334:28334 [3] NCCL INFO P2P plugin IBext
ad5b8ae33076:28337:28337 [6] NCCL INFO Bootstrap : Using eth0:10.0.1.2<0>
381077730cf7:52622:52622 [0] NCCL INFO Bootstrap : Using eth0:10.0.1.3<0>
ad5b8ae33076:28333:28333 [2] NCCL INFO Bootstrap : Using eth0:10.0.1.2<0>
ad5b8ae33076:28336:28336 [5] NCCL INFO Bootstrap : Using eth0:10.0.1.2<0>
381077730cf7:52623:52623 [1] NCCL INFO NET/Plugin: Failed t
```

My confused are:
1. GPUDirect RDMA used or not?
2. What is IB/SHARP?
3. How can I get real-time Infiniband usage log?

Looking forward to your reply!

**Comment by sjeaugey** [comment]
You don't need GPU Direct RDMA to use IB/RoCE NICs. It is important to load it however if the NIC is connected to a PCI switch which is also connected to one or more GPUs: that way, NCCL will try to communicate directly between the NIC and GPUs through the PCI switch and not loading GPU Direct RDMA will make all traffic go back and forth to the CPU, halving the performance.

IB SHARP is a mechanism in recent Quantum switches which performs allreduce operations in the switch between nodes. NCCL can leverage that to improve performance and scalability of allreduce operations.

Infiniband NICs and Switches have counters which can be queried by fabric management tools like UFM. Since network communication is not handled by the kernel (like for TCP/IP), the linux kernel cannot keep track of what was sent/received, so don't expect to see that in classic linux IP tools.

**Comment by ReyRen** [comment]
Thannks @sjeaugey , I really appreciate your help and answering them. 

> You don't need GPU Direct RDMA to use IB/RoCE NICs. It is important to load it however if the NIC is connected to a PCI switch which is also connected to one or more GPUs: that way, NCCL will try to communicate directly between the NIC and GPUs through the PCI switch and not loading GPU Direct RDMA will make all traffic go back and forth to the CPU, halving the performance.

I use SXM-A800 (NV-Switch opened) and Quantum switches. Do I need to load the kernel module "nv_peermem" in my scenario? Or is it the case that if I don't load the "nv_peermem" module, it will simply use IB for communication without utilizing GPUDirect RDMA? Additionally, as mentioned in this issue, in my previous usage of cuda11.2, I used "nv_peer_mem" to load GPUDirect RDMA. I'm not sure if "nv_peermem" is a replacement for "nv_peer_mem."

**Comment by ReyRen** [comment]
I noticed that in my experimental scenario, whether or not I load the "nv_peermem" module, it is mentioned in the NCCL output logs：
<img width="814" alt="图片" src="https://github.com/NVIDIA/nccl/assets/26827250/1638c655-0a02-4bc5-af11-b64a53b377e1">

**Comment by sjeaugey** [comment]
I believe depending on your networking stack, the module will be called `nv_peer_mem` or `nvidia-peermem`. If you see NCCL report GDRDMA, you probably have one of the two loaded.

**Comment by ReyRen** [comment]
However, in fact, it was not loaded unless I was viewing it incorrectly. 
<img width="310" alt="图片" src="https://github.com/NVIDIA/nccl/assets/26827250/e143923c-cf8a-4b70-a9f9-767302bd836b">

**Comment by sjeaugey** [comment]
Can you check `nvidia-peermem` instead of `nvidia_peermem`?

**Comment by ReyRen** [comment]
Sovled. The name is `nvidia_peermem`。
> I believe depending on your networking stack, the module will be called `nv_peer_mem` or `nvidia-peermem`. If you see NCCL report GDRDMA, you probably have one of the two loaded.

You're correct. Thanks again, this can be closed.

**Comment by David9998** [comment]
> GDRDMA

I encouter the same issue with you , so how do you resolve it ? thanks a lot.

**Comment by ReyRen** [comment]
> > GDRDMA
> 
> I encouter the same issue with you , so how do you resolve it ? thanks a lot.

The module name is "nvidia_peermem" rather than the "nv_peer_mem" described in NCCL doc. And nvidia_peermem is assembled in new driver.

**Comment by alokprasad** [comment]
@sjeaugey though its closed ticket , what is output in nccl-tests logs if we use dmabuf 
i understand GDRDMA is for nv-peermem ? is it same ?

**Comment by alokprasad** [comment]
Got the answer here 
https://github.com/NVIDIA/nccl/issues/908
