### ISSUE TITLE
Just wondering how you do data copy among GPUs

### ISSUE THREAD

**Issue by GuanhuaWang** [NVIDIA/nccl#99]
Hi, I am just curious about how you do memcpy for data transfer among GPUs.

I looked through your source codes. And I am not sure whether the GPU p2p data transfer uses 
(1) cuda library like cudamemcpyasync(); 
(2) or you did it by yourself using something like "Prims::Copy"

If it is the (2) case, can you explain more about the prims::copy. Cuz I have found any implementation code of this function

**Comment by sjeaugey** [comment]
We are doing the copies with the CUDA kernels. The Copy function actually maps to the ReduceOrCopy function which does everything : load data from one or two sources (reduce them if there are two) then stores the result to one or two destinations.

Except for special cases, we don't have separate memcpy functions. Inter-GPU communication is performed as a last store operation in the processing of each chunk of data.

**Comment by GuanhuaWang** [comment]
Cool, thanks @sjeaugey
